<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl NMPCatSuc xsd soapenc12 ns2 soapenc11 wsdlsoap wsdl soap11 ns1 soap12 tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns2="http://exception.midas.nmp.com.mx" xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:NMPCatSuc="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCatSucSvc" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://dto.model.midas.nmp.com.mx" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:tns="urn:mx.com.nmp.midas" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPCatSucursalSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getSucursalesRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCatSucSvc"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/MIDASSucursalesSvcWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="getSucursales" namespace="urn:mx.com.nmp.midas"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON JAN 09 10:43:24 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:getSucursales>
      <tns:sucursalRequest>
        <ns1:ramo>
          <xsl:value-of select="/NMPCatSuc:getSucursalesRequest/NMPCatSuc:ramo"/>
        </ns1:ramo>
        <xsl:if test="/NMPCatSuc:getSucursalesRequest/NMPCatSuc:subramo">
          <ns1:subramo>
            <xsl:if test="/NMPCatSuc:getSucursalesRequest/NMPCatSuc:subramo/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/NMPCatSuc:getSucursalesRequest/NMPCatSuc:subramo/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/NMPCatSuc:getSucursalesRequest/NMPCatSuc:subramo"/>
          </ns1:subramo>
        </xsl:if>
        <ns1:sucursales>
          <xsl:for-each select="/NMPCatSuc:getSucursalesRequest/NMPCatSuc:Sucursal">
            <tns:int>
              <xsl:value-of select="NMPCatSuc:idSucursal"/>
            </tns:int>
          </xsl:for-each>
        </ns1:sucursales>
      </tns:sucursalRequest>
    </tns:getSucursales>
  </xsl:template>
</xsl:stylesheet>