<wsdl:definitions name="consultarDetalleSolicitudBPEL" targetNamespace="http://qualitas.com.mx/Solicitud/ConsultarDetalleSolicitud/" xmlns:client="http://qualitas.com.mx/Solicitud/ConsultarDetalleSolicitud/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.20:7007/soa-infra/services/GPADomain/ConsultarDetalleSolicitudBPEL!1.0/WSDLs/consultarDetalleSolicitud.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="consultarDetalleSolicitudBPEL">
        <plnk:role name="consultarDetalleSolicitudBPELProvider" portType="client:consultarDetalleSolicitudBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/" schemaLocation="consultarDetalleSolicitud.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="consultarDetalleSolicitudBPELRequestMessage">
        <wsdl:part name="consultarDetalleSolicitudRequest" element="ns1:consultarDetalleSolicitudRequest"/>
    </wsdl:message>
    <wsdl:message name="consultarDetalleSolicitudBPELResponseMessage">
        <wsdl:part name="consultarDetalleSolicitudResponse" element="ns1:consultarDetalleSolicitudResponse"/>
    </wsdl:message>
    <wsdl:portType name="consultarDetalleSolicitudBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:consultarDetalleSolicitudBPELRequestMessage"/>
            <wsdl:output message="client:consultarDetalleSolicitudBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="consultarDetalleSolicitudBPELBindingSOAP" type="client:consultarDetalleSolicitudBPEL">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/consultarDetalleSolicitudApp/consultarDetalleSolicitudPrj/consultarDetalleSolicitudBPEL/process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="consultardetallesolicitudbpel_client_ep">
        <wsdl:port name="consultarDetalleSolicitudBPEL_pt" binding="client:consultarDetalleSolicitudBPELBindingSOAP">
            <soap:address location="http://11.50.0.20:7007/soa-infra/services/GPADomain/ConsultarDetalleSolicitudBPEL/consultardetallesolicitudbpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>