<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl soapenc12 ns2 soapenc11 wsdlsoap wsdl soap11 ns1 xsd soap12 tns NMPPart xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:NMPPart="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPartidas" xmlns:ns2="http://exception.midas.nmp.com.mx" xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://dto.model.midas.nmp.com.mx" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:tns="urn:mx.com.nmp.midas" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/NMPConsultaPartidasSvcWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="getPartidasPorClienteResponse" namespace="urn:mx.com.nmp.midas"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPPartidasSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getPartidasClienteResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPartidas"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON JAN 09 11:47:41 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <NMPPart:getPartidasClienteResponse>
      <xsl:for-each select="/tns:getPartidasPorClienteResponse/tns:return/ns1:DatosPartidaHelpDesk">
        <NMPPart:Partida>
          <NMPPart:folioPartida>
            <xsl:value-of select="ns1:folio"/>
          </NMPPart:folioPartida>
          <NMPPart:ramo>
            <xsl:value-of select="ns1:ramo"/>
          </NMPPart:ramo>
          <NMPPart:subramo>
            <xsl:value-of select="ns1:subRamo"/>
          </NMPPart:subramo>
          <NMPPart:estadoPrenda>
            <xsl:value-of select="ns1:estadoPrenda"/>
          </NMPPart:estadoPrenda>
          <NMPPart:descripcion>
            <xsl:value-of select="ns1:descripcion"/>
          </NMPPart:descripcion>
          <NMPPart:montoPrestamo>
            <xsl:value-of select="ns1:montoPrestamo"/>
          </NMPPart:montoPrestamo>
          <NMPPart:idSucursalPartida>
            <xsl:value-of select="ns1:idSucursalPartida"/>
          </NMPPart:idSucursalPartida>
          <NMPPart:fechaVencimiento>
            <xsl:value-of select="ns1:fechaVencimiento"/>
          </NMPPart:fechaVencimiento>
          <NMPPart:Beneficiarios>
            <xsl:for-each select="ns1:beneficiarios/ns1:BeneficiarioPartida">
              <NMPPart:Beneficiario>
                <NMPPart:nombre>
                  <xsl:value-of select="ns1:nombre"/>
                </NMPPart:nombre>
                <NMPPart:apellidoPaterno>
                  <xsl:value-of select="ns1:apellidoPaterno"/>
                </NMPPart:apellidoPaterno>
                <NMPPart:apellidoMaterno>
                  <xsl:value-of select="ns1:apellidoMaterno"/>
                </NMPPart:apellidoMaterno>
              </NMPPart:Beneficiario>
            </xsl:for-each>
          </NMPPart:Beneficiarios>
        </NMPPart:Partida>
      </xsl:for-each>
    </NMPPart:getPartidasClienteResponse>
  </xsl:template>
</xsl:stylesheet>