<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl soapenc12 ns2 soapenc11 wsdlsoap wsdl soap11 ns1 xsd soap12 tns NMPPart xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:NMPPart="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPartidas" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns2="http://exception.midas.nmp.com.mx" xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://dto.model.midas.nmp.com.mx" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope" xmlns:tns="urn:mx.com.nmp.midas" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/MIDASDetallePartidaSvcWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="getDetallePartidaResponse" namespace="urn:mx.com.nmp.midas"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPPartidasSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getPartidaDetalleResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPartidas"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON JAN 09 11:47:24 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <NMPPart:getPartidaDetalleResponse>
      <NMPPart:Avaluo>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:folio">
          <NMPPart:folio>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:folio"/>
          </NMPPart:folio>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:ramo">
          <NMPPart:ramo>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:ramo"/>
          </NMPPart:ramo>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:subramo">
          <NMPPart:subramo>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:subramo"/>
          </NMPPart:subramo>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:descripcion">
          <NMPPart:descripcion>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:descripcion"/>
          </NMPPart:descripcion>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:montoAvaluo">
          <NMPPart:montoAvaluo>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:montoAvaluo"/>
          </NMPPart:montoAvaluo>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:montoPrestamo">
          <NMPPart:montoPrestamo>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:montoPrestamo"/>
          </NMPPart:montoPrestamo>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:titular">
          <NMPPart:titular>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:titular"/>
          </NMPPart:titular>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:valuador">
          <NMPPart:valuador>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:valuador"/>
          </NMPPart:valuador>
        </xsl:if>
        <NMPPart:Beneficiarios>
          <xsl:for-each select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:beneficiarios/ns1:BeneficiarioPartida">
            <NMPPart:Beneficiario>
              <xsl:if test="ns1:nombre">
                <NMPPart:nombre>
                  <xsl:value-of select="ns1:nombre"/>
                </NMPPart:nombre>
              </xsl:if>
              <xsl:if test="ns1:apellidoPaterno">
                <NMPPart:apellidoPaterno>
                  <xsl:value-of select="ns1:apellidoPaterno"/>
                </NMPPart:apellidoPaterno>
              </xsl:if>
              <xsl:if test="ns1:apellidoMaterno">
                <NMPPart:apellidoMaterno>
                  <xsl:value-of select="ns1:apellidoMaterno"/>
                </NMPPart:apellidoMaterno>
              </xsl:if>
            </NMPPart:Beneficiario>
          </xsl:for-each>
        </NMPPart:Beneficiarios>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:tipoContrato">
          <NMPPart:tipoContrato>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluo/ns1:tipoContrato"/>
          </NMPPart:tipoContrato>
        </xsl:if>
      </NMPPart:Avaluo>
      <NMPPart:AvaluoAlhajas>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:incremento">
          <NMPPart:incremento>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:incremento"/>
          </NMPPart:incremento>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:desplazamiento">
          <NMPPart:desplazamiento>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:desplazamiento"/>
          </NMPPart:desplazamiento>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:valorComercial">
          <NMPPart:valorComercial>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:valorComercial"/>
          </NMPPart:valorComercial>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:valorMonte">
          <NMPPart:valorMonte>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:valorMonte"/>
          </NMPPart:valorMonte>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:costoMetal">
          <NMPPart:costoMetal>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:costoMetal"/>
          </NMPPart:costoMetal>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:kilataje">
          <NMPPart:kilataje>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:kilataje"/>
          </NMPPart:kilataje>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:avaluoComplementario">
          <NMPPart:avaluoComplementario>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:avaluoComplementario"/>
          </NMPPart:avaluoComplementario>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:rango">
          <NMPPart:rango>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleAvaluoAlhajas/ns1:rango"/>
          </NMPPart:rango>
        </xsl:if>
      </NMPPart:AvaluoAlhajas>
      <NMPPart:UbicacionDeposito>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:sucursal">
          <NMPPart:sucursal>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:sucursal"/>
          </NMPPart:sucursal>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:deposito">
          <NMPPart:deposito>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:deposito"/>
          </NMPPart:deposito>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:cajon">
          <NMPPart:cajon>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:cajon"/>
          </NMPPart:cajon>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:consecutivo">
          <NMPPart:consecutivo>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionDeposito/ns1:consecutivo"/>
          </NMPPart:consecutivo>
        </xsl:if>
      </NMPPart:UbicacionDeposito>
      <NMPPart:UbicacionAlmoneda>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:sucursal">
          <NMPPart:sucursal>
            <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:sucursal/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:sucursal/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:sucursal"/>
          </NMPPart:sucursal>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:numeroExpendio">
          <NMPPart:numeroExpendio>
            <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:numeroExpendio/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:numeroExpendio/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:numeroExpendio"/>
          </NMPPart:numeroExpendio>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:expendedor">
          <NMPPart:expendedor>
            <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:expendedor/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:expendedor/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleUbicacionAlmoneda/ns1:expendedor"/>
          </NMPPart:expendedor>
        </xsl:if>
      </NMPPart:UbicacionAlmoneda>
      <NMPPart:Estado>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:estadoPrenda">
          <NMPPart:estadoPrenda>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:estadoPrenda"/>
          </NMPPart:estadoPrenda>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:estadoCaja">
          <NMPPart:estadoCaja>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:estadoCaja"/>
          </NMPPart:estadoCaja>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:fechaIngreso">
          <NMPPart:fechaIngreso>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:fechaIngreso"/>
          </NMPPart:fechaIngreso>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:fechaComercializacion">
          <NMPPart:fechaComercializacion>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:fechaComercializacion"/>
          </NMPPart:fechaComercializacion>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:fechaIngresoDeposito">
          <NMPPart:fechaIngresoDeposito>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:fechaIngresoDeposito"/>
          </NMPPart:fechaIngresoDeposito>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:numRefrendosRealizados">
          <NMPPart:numRefrendosRealizados>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:numRefrendosRealizados"/>
          </NMPPart:numRefrendosRealizados>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:interes">
          <NMPPart:interes>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:interes"/>
          </NMPPart:interes>
        </xsl:if>
        <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:custodia">
          <NMPPart:custodia>
            <xsl:value-of select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleEstado/ns1:custodia"/>
          </NMPPart:custodia>
        </xsl:if>
      </NMPPart:Estado>
      <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleProyeccion">
        <NMPPart:Proyecciones>
          <xsl:for-each select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleProyeccion/ns1:DetalleProyeccion">
            <NMPPart:Proyeccion>
              <xsl:if test="ns1:operacion">
                <NMPPart:operacion>
                  <xsl:value-of select="ns1:operacion"/>
                </NMPPart:operacion>
              </xsl:if>
              <xsl:if test="ns1:monto">
                <NMPPart:monto>
                  <xsl:value-of select="ns1:monto"/>
                </NMPPart:monto>
              </xsl:if>
            </NMPPart:Proyeccion>
          </xsl:for-each>
        </NMPPart:Proyecciones>
      </xsl:if>
      <xsl:if test="/tns:getDetallePartidaResponse/tns:return/ns1:detalleMovimiento">
        <NMPPart:HistorialesMovimientos>
          <xsl:for-each select="/tns:getDetallePartidaResponse/tns:return/ns1:detalleMovimiento/ns1:DetalleMovimiento">
            <NMPPart:HistorialMovimientos>
              <xsl:if test="ns1:timestampOperacion">
                <NMPPart:timestampOperacion>
                  <xsl:value-of select="ns1:timestampOperacion"/>
                </NMPPart:timestampOperacion>
              </xsl:if>
              <xsl:if test="ns1:usuario">
                <NMPPart:usuario>
                  <xsl:value-of select="ns1:usuario"/>
                </NMPPart:usuario>
              </xsl:if>
              <xsl:if test="ns1:operacion">
                <NMPPart:operacion>
                  <xsl:value-of select="ns1:operacion"/>
                </NMPPart:operacion>
              </xsl:if>
              <xsl:if test="ns1:sucursal">
                <NMPPart:sucursal>
                  <xsl:value-of select="ns1:sucursal"/>
                </NMPPart:sucursal>
              </xsl:if>
            </NMPPart:HistorialMovimientos>
          </xsl:for-each>
        </NMPPart:HistorialesMovimientos>
      </xsl:if>
    </NMPPart:getPartidaDetalleResponse>
  </xsl:template>
</xsl:stylesheet>