<wsdl:definitions
     name="ConsultaNumeroEmpleado"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_Desarrollo/GenerarSolicitud/ConsultaNumeroEmpleado"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_Desarrollo/GenerarSolicitud/ConsultaNumeroEmpleado"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultaNumeroEmpleado"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultaNumeroEmpleado_plt" >
    <plt:role name="ConsultaNumeroEmpleado_role" >
      <plt:portType name="tns:ConsultaNumeroEmpleado_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ConsultaNumeroEmpleado" schemaLocation="../Schemas/ConsultaNumeroEmpleado_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaNumeroEmpleadoSelect_inputParameters">
        <wsdl:part name="ConsultaNumeroEmpleadoSelect_inputParameters" element="top:ConsultaNumeroEmpleadoSelect_loginUsuarioInputParameters"/>
    </wsdl:message>
    <wsdl:message name="GpaMapeoUsuariosCollection_msg">
        <wsdl:part name="GpaMapeoUsuariosCollection" element="top:GpaMapeoUsuariosCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaNumeroEmpleado_ptt">
        <wsdl:operation name="ConsultaNumeroEmpleadoSelect">
            <wsdl:input message="tns:ConsultaNumeroEmpleadoSelect_inputParameters"/>
            <wsdl:output message="tns:GpaMapeoUsuariosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
