<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://TargetNamespace.com/ServiceName" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/AutosSinResguardoPrc" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:tns6="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPAutosSinResguardo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../Schemas/nxsd_DatosCliente.xsd"/>
        <oracle-xsl-mapper:rootElement name="DatosClienteRequest" namespace="http://TargetNamespace.com/ServiceName"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../WSDLs/AutosSinResguardoPrc.wsdl"/>
        <oracle-xsl-mapper:rootElement name="inicioGestionBPM" namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/AutosSinResguardoPrc"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUL 28 18:58:29 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="urls"/>
  <xsl:param name="noFolio"/>
  <xsl:template match="/">
    <tns:inicioGestionBPM>
      <tns6:Cliente>
        <tns6:idCliente>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:IdCliente"/>
        </tns6:idCliente>
        <tns6:numeroDeCredencial>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:NumeroCredencial"/>
        </tns6:numeroDeCredencial>
        <tns6:folioTramite>
          <xsl:value-of select="$noFolio"/>
        </tns6:folioTramite>
        <tns6:nombre>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:PrimerNombre"/>
        </tns6:nombre>
        <tns6:apellidoPaterno>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:ApellidoPaterno"/>
        </tns6:apellidoPaterno>
        <tns6:apellidoMaterno>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:ApellidoMaterno"/>
        </tns6:apellidoMaterno>
        <tns6:fechaNacimiento>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:FechaNacimiento"/>
        </tns6:fechaNacimiento>
        <tns6:email>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:Email"/>
        </tns6:email>
        <tns6:telefono>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:Telefono"/>
        </tns6:telefono>
        <tns6:edad>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:Edad"/>
        </tns6:edad>
        <tns6:ocupacion>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:Ocupacion"/>
        </tns6:ocupacion>
        <tns6:direccion>
          <tns6:DireccionList>
            <tns6:calle>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:Calle"/>
            </tns6:calle>
            <tns6:numeroExterior>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:NumExt"/>
            </tns6:numeroExterior>
            <tns6:numeroInterior>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:NumInt"/>
            </tns6:numeroInterior>
            <tns6:colonia>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:Colonia"/>
            </tns6:colonia>
            <tns6:municipio>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:Municipio"/>
            </tns6:municipio>
            <tns6:delegacion>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:Municipio"/>
            </tns6:delegacion>
            <tns6:estado>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:Estado"/>
            </tns6:estado>
            <tns6:tipoDomicilio>
              <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Domicilio/ns0:TipoDomicilio"/>
            </tns6:tipoDomicilio>
          </tns6:DireccionList>
        </tns6:direccion>
        <tns6:rfc>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:Rfc"/>
        </tns6:rfc>
        <tns6:monto>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:MontoPrestamo"/>
        </tns6:monto>
      </tns6:Cliente>
      <tns6:Auto>
        <tns6:marca>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Marca"/>
        </tns6:marca>
        <tns6:submarca>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Submarca"/>
        </tns6:submarca>
        <tns6:modelo>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Modelo"/>
        </tns6:modelo>
        <tns6:version>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Version"/>
        </tns6:version>
        <tns6:kilometraje>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Kilometraje"/>
        </tns6:kilometraje>
        <tns6:color>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Color"/>
        </tns6:color>
        <tns6:placas>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Placa"/>
        </tns6:placas>
        <tns6:serieMotor>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:SerieMotor"/>
        </tns6:serieMotor>
        <tns6:serieChasis>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:SerieChasis"/>
        </tns6:serieChasis>
        <tns6:equipoAdicional>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:EquipoAdicional"/>
        </tns6:equipoAdicional>
        <tns6:comentarios>
          <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosAuto/ns0:Comentarios"/>
        </tns6:comentarios>
      </tns6:Auto>
      <tns6:Url>
        <xsl:for-each select="$urls/archivo">
          <xsl:if test="nombre/text()!=''">
            <tns6:URLsList>
              <tns6:nombreDoc>
                <xsl:value-of select="nombre/text()"/>
              </tns6:nombreDoc>
              <tns6:url>
                <xsl:value-of select="url/text()"/>
              </tns6:url>
            </tns6:URLsList>
          </xsl:if>
        </xsl:for-each>
      </tns6:Url>
    </tns:inicioGestionBPM>
  </xsl:template>
</xsl:stylesheet>