<xsl:stylesheet version="1.0" exclude-result-prefixes="fn xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://TargetNamespace.com/ServiceName" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../../Schemas/nxsd_DatosCliente.xsd"/>
                <oracle-xsl-mapper:rootElement name="DatosClienteRequest" namespace="http://TargetNamespace.com/ServiceName"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../../Schemas/OpenTextXSD.xsd"/>
                <oracle-xsl-mapper:rootElement name="almacenaDocumentosRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUL 28 17:33:33 CDT 2016].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:param name="contenido"/>
    <xsl:param name="tamano"/>
    <xsl:param name="indice"/>
    <xsl:param name="noFolio"/>
    <xsl:param name="nombreArchivo"/>
    <xsl:template match="/">
        <tns:almacenaDocumentosRequest>
            <tns:ruta>
                <tns:directorio tipo="Periodo">
                    <tns:nombre>2016</tns:nombre>
                </tns:directorio>
                <tns:subdirectorios tipo="NumCliente" nivelDependencia="1">
                    <tns:nombre>
                        <xsl:value-of select="/ns0:DatosClienteRequest/ns0:DatosCliente/ns0:Cliente/ns0:NumeroCredencial"/>
                    </tns:nombre>
                </tns:subdirectorios>
                <tns:subdirectorios tipo="NumFolio" nivelDependencia="2">
                    <tns:nombre>
                        <xsl:value-of select="$noFolio"/>
                    </tns:nombre>
                </tns:subdirectorios>
            </tns:ruta>
            <tns:documentos>
                <tns:documento>
                    <tns:nombre>
                        <xsl:value-of select="substring-before(substring-after(substring-after ($nombreArchivo, 'filename='),'&quot;'),'&quot;')"/>
                    </tns:nombre>
                    <tns:contenido>
                        <xsl:value-of select="$contenido"/>
                    </tns:contenido>
                    <tns:size>
                        <xsl:value-of select="$tamano"/>
                    </tns:size>
                </tns:documento>
            </tns:documentos>
        </tns:almacenaDocumentosRequest>
    </xsl:template>
</xsl:stylesheet>