<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CatalogosServiceImplService" targetNamespace="http://webservicesImpl.wscatalogos.qualitas.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://webservices.wscatalogos.qualitas.com/" xmlns:ns2="http://webservicesImpl.wscatalogos.qualitas.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="catalogosService">
      <plnk:role name="CatalogosService" portType="ns1:CatalogosService"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://webservicesImpl.wscatalogos.qualitas.com/" location="catalogosService.wsdl"/>
</wsdl:definitions>
