<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ObtenerPretadorProcess" targetNamespace="http://xmlns.oracle.com/BORRAR/ObtenerPrestador/ObtenerPretadorProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/BORRAR/ObtenerPrestador/ObtenerPretadorProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/BORRAR/ObtenerPrestador/ObtenerPretadorProcess" schemaLocation="../Schemas/ObtenerPretadorProcess.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ObtenerPretadorProcessRequestMessage">
      <wsdl:part name="payload" element="client:process"/>
   </wsdl:message>
   <wsdl:message name="ObtenerPretadorProcessResponseMessage">
      <wsdl:part name="payload" element="client:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="ObtenerPretadorProcess">
      <wsdl:operation name="process">
         <wsdl:input message="client:ObtenerPretadorProcessRequestMessage"/>
         <wsdl:output message="client:ObtenerPretadorProcessResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ObtenerPretadorProcess">
      <plnk:role name="ObtenerPretadorProcessProvider" portType="client:ObtenerPretadorProcess"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
