<definitions targetNamespace="http://service.ucm.soaint.com/" name="ContentSvc" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="http://service.ucm.soaint.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://service.ucm.soaint.com/" schemaLocation="ContentSvc_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="delete">
    <part name="parameters" element="tns:delete"/>
  </message>
  <message name="deleteResponse">
    <part name="parameters" element="tns:deleteResponse"/>
  </message>
  <message name="findDocuments">
    <part name="parameters" element="tns:findDocuments"/>
  </message>
  <message name="findDocumentsResponse">
    <part name="parameters" element="tns:findDocumentsResponse"/>
  </message>
  <portType name="ContentService">
    <operation name="delete">
      <input wsam:Action="http://service.ucm.soaint.com/ContentService/deleteRequest" message="tns:delete"/>
      <output wsam:Action="http://service.ucm.soaint.com/ContentService/deleteResponse" message="tns:deleteResponse"/>
    </operation>
    <operation name="findDocuments">
      <input wsam:Action="http://service.ucm.soaint.com/ContentService/findDocumentsRequest" message="tns:findDocuments"/>
      <output wsam:Action="http://service.ucm.soaint.com/ContentService/findDocumentsResponse" message="tns:findDocumentsResponse"/>
    </operation>
  </portType>
  <binding name="ContentSvcPortBinding" type="tns:ContentService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="delete">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="findDocuments">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ContentSvc">
    <port name="ContentSvcPort" binding="tns:ContentSvcPortBinding">
      <soap:address location="http://localhost:7101/QualitasContent-OracleUCM-context-root/ContentSvcPort"/>
    </port>
  </service>
</definitions>