<wsdl:definitions name="InscribirBPELProcess" targetNamespace="http://xmlns.oracle.com/nmpApp/WSInscribir/InscribirBPELProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/nmpApp/WSInscribir/InscribirBPELProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://nmpsoaserver:8001/soa-infra/services/cenmp/WSInscribir!1.0.0/InscribirBPELProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="InscribirBPELProcess">
        <plnk:role name="InscribirBPELProcessProvider" portType="client:InscribirBPELProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/nmpApp/WSInscribir/InscribirBPELProcess" schemaLocation="../xsd/InscribirBPELProcess.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="InscribirBPELProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="InscribirBPELProcessResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="InscribirBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:InscribirBPELProcessRequestMessage"/>
            <wsdl:output message="client:InscribirBPELProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="InscribirBPELProcessBinding" type="client:InscribirBPELProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="inscribirbpelprocess_client_ep">
        <wsdl:port name="InscribirBPELProcess_pt" binding="client:InscribirBPELProcessBinding">
            <soap:address location="http://nmpsoaserver:8001/soa-infra/services/cenmp/WSInscribir/inscribirbpelprocess_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>