<wsdl:definitions name="ObtenerOfertaTECBPELProcess" targetNamespace="http://xmlns.oracle.com/nmpApp/WSObtenerOfertaTEC/ObtenerOfertaTECBPELProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/nmpApp/WSObtenerOfertaTEC/ObtenerOfertaTECBPELProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://nmpsoaserver:8001/soa-infra/services/cenmp/WSObtenerOfertaTEC!1.0/ObtenerOfertaTECBPELProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ObtenerOfertaTECBPELProcess">
        <plnk:role name="ObtenerOfertaTECBPELProcessProvider" portType="client:ObtenerOfertaTECBPELProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/nmpApp/WSObtenerOfertaTEC/ObtenerOfertaTECBPELProcess" schemaLocation="../xsd/XMLSchema_510219435.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerOfertaTECBPELProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="ObtenerOfertaTECBPELProcessResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerOfertaTECBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:ObtenerOfertaTECBPELProcessRequestMessage"/>
            <wsdl:output message="client:ObtenerOfertaTECBPELProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ObtenerOfertaTECBPELProcessBinding" type="client:ObtenerOfertaTECBPELProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="obtenerofertatecbpelprocess_client_ep">
        <wsdl:port name="ObtenerOfertaTECBPELProcess_pt" binding="client:ObtenerOfertaTECBPELProcessBinding">
            <soap:address location="http://nmpsoaserver:8001/soa-infra/services/cenmp/WSObtenerOfertaTEC/obtenerofertatecbpelprocess_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>