<wsdl:definitions name="bpelRegisterAppointment" targetNamespace="http://xmlns.oracle.com/NMPApplication/RegisterProcesses/bpelRegisterAppointment" xmlns:ns1="http://nmp.com/CommonDataModel/1.0/Common" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/NMPApplication/RegisterProcesses/bpelRegisterAppointment" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://localhost:12001/soa-infra/services/cenmp/RegisterProcesses!1.0/bpelRegisterAppointment.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="bpelRegisterAppointment">
        <plnk:role name="bpelRegisterAppointmentProvider" portType="client:bpelRegisterAppointment"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://nmp.com/CommonDataModel/1.0/Common" schemaLocation="../xsd/Messages.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="bpelRegisterAppointmentRequestMessage">
        <wsdl:part name="payload" element="ns1:RegisterAppointmentIM"/>
    </wsdl:message>
    <wsdl:message name="bpelRegisterAppointmentResponseMessage">
        <wsdl:part name="payload" element="ns1:GeneralResponseIM"/>
    </wsdl:message>
    <wsdl:portType name="bpelRegisterAppointment">
        <wsdl:operation name="process">
            <wsdl:input message="client:bpelRegisterAppointmentRequestMessage"/>
            <wsdl:output message="client:bpelRegisterAppointmentResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="bpelRegisterAppointmentBinding" type="client:bpelRegisterAppointment">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="wsRegisterAppointment_ep">
        <wsdl:port name="bpelRegisterAppointment_pt" binding="client:bpelRegisterAppointmentBinding">
            <soap:address location="http://localhost:12001/soa-infra/services/cenmp/RegisterProcesses/wsRegisterAppointment"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>