<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultaEstatusOrden" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPAQualitasApp/EmailRecordatorioPrj/ConsultaEstatusOrden" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GPAQualitasApp/EmailRecordatorioPrj/ConsultaEstatusOrden" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaEstatusOrden" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="ConsultaEstatusOrden_plt">
      <plt:role name="ConsultaEstatusOrden_role">
         <plt:portType name="tns:ConsultaEstatusOrden_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaEstatusOrden" schemaLocation="../Schemas/ConsultaEstatusOrden.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ConsultaEstatusOrdenInput_msg">
      <wsdl:part name="ConsultaEstatusOrdenInput_msg" element="db:ConsultaEstatusOrdenInput"/>
   </wsdl:message>
   <wsdl:message name="ConsultaEstatusOrdenOutputCollection_msg">
      <wsdl:part name="ConsultaEstatusOrdenOutputCollection" element="db:ConsultaEstatusOrdenOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="ConsultaEstatusOrden_ptt">
      <wsdl:operation name="ConsultaEstatusOrden">
         <wsdl:input message="tns:ConsultaEstatusOrdenInput_msg"/>
         <wsdl:output message="tns:ConsultaEstatusOrdenOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
