<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ActualizaEstadoSolicitudBPEL" targetNamespace="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" schemaLocation="../Schemas/ActualizaEstadoSolicitudBPEL.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ActualizaEstadoSolicitudBPELRequestMessage">
      <wsdl:part name="payload" element="client:estadoSolicitudRequest"/>
   </wsdl:message>
   <wsdl:message name="ActualizaEstadoSolicitudBPELResponseMessage">
      <wsdl:part name="payload" element="client:estadoSolicitudResponse"/>
   </wsdl:message>
   <wsdl:portType name="ActualizaEstadoSolicitudBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ActualizaEstadoSolicitudBPELRequestMessage"/>
         <wsdl:output message="client:ActualizaEstadoSolicitudBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ActualizaEstadoSolicitudBPEL">
      <plnk:role name="ActualizaEstadoSolicitudBPELProvider" portType="client:ActualizaEstadoSolicitudBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
