<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SolicitudViaticosSvc" targetNamespace="http://service.gpa.mx.com.qualitas/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N1="http://service.gpa.mx.com.qualitas/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="SolicitudViaticosSvcPxy">
      <plnk:role name="SolicitudViaticosSvc" portType="WL5G3N1:SolicitudViaticosSvc"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://service.gpa.mx.com.qualitas/" location="http://11.50.0.20:7006/Finance/AP/GPA/Entity/ProxySvc/SolicitudViaticosSvcPxy?wsdl"/>
</wsdl:definitions>
