<wsdl:definitions
     name="ProyectosPrestadorDataSvc"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/ProyectosPrestador/ProyectosPrestadorDataSvc"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/ProyectosPrestador/ProyectosPrestadorDataSvc"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectosPrestadorDataSvc"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ProyectosPrestadorDataSvc_plt" >
    <plt:role name="ProyectosPrestadorDataSvc_role" >
      <plt:portType name="tns:ProyectosPrestadorDataSvc_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectosPrestadorDataSvc" schemaLocation="ProyectosPrestadorDataSvc.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ProyectosPrestadorDataSvcInput_msg">
        <wsdl:part name="ProyectosPrestadorDataSvcInput_msg" element="db:ProyectosPrestadorDataSvcInput"/>
    </wsdl:message>
    <wsdl:message name="ProyectosPrestadorDataSvcOutputCollection_msg">
        <wsdl:part name="ProyectosPrestadorDataSvcOutputCollection" element="db:ProyectosPrestadorDataSvcOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ProyectosPrestadorDataSvc_ptt">
        <wsdl:operation name="ProyectosPrestadorDataSvc">
            <wsdl:input message="tns:ProyectosPrestadorDataSvcInput_msg"/>
            <wsdl:output message="tns:ProyectosPrestadorDataSvcOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
