<wsdl:definitions
     name="ConsultaServiciosPrestadorDataSvc"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/SolicitudesBDQry/ConsultaServiciosPrestadorDataSvc"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/SolicitudesBDQry/ConsultaServiciosPrestadorDataSvc"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaServiciosPrestadorDataSvc"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ConsultaServiciosPrestadorDataSvc_plt" >
    <plt:role name="ConsultaServiciosPrestadorDataSvc_role" >
      <plt:portType name="tns:ConsultaServiciosPrestadorDataSvc_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaServiciosPrestadorDataSvc"
                schemaLocation="ConsultaServiciosPrestadorDataSvc.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaServiciosPrestadorDataSvcInput_msg">
        <wsdl:part name="ConsultaServiciosPrestadorDataSvcInput_msg" element="db:ConsultaServiciosPrestadorDataSvcInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaServiciosPrestadorDataSvcOutputCollection_msg">
        <wsdl:part name="ConsultaServiciosPrestadorDataSvcOutputCollection" element="db:ConsultaServiciosPrestadorDataSvcOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaServiciosPrestadorDataSvc_ptt">
        <wsdl:operation name="ConsultaServiciosPrestadorDataSvc">
            <wsdl:input message="tns:ConsultaServiciosPrestadorDataSvcInput_msg"/>
            <wsdl:output message="tns:ConsultaServiciosPrestadorDataSvcOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
