<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PagosService" targetNamespace="http://service.pagos.qualitas.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://service.pagos.qualitas.com.mx/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="PagosService">
      <plnk:role name="PagosService" portType="ns1:PagosService"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://service.pagos.qualitas.com.mx/" location="http://11.50.0.73:9010/pagos-web/servicios/pagosService?wsdl"/>
</wsdl:definitions>
