<wsdl:definitions name="ConsultaInformacionWsImplService" targetNamespace="http://impl.service.centroscosto.qualitas.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl.service.centroscosto.qualitas.com.mx/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://service.centroscosto.qualitas.com.mx/">
    <wsdl:import location="ConsultaInformacionPortWSDL.wsdl" namespace="http://service.centroscosto.qualitas.com.mx/"/>
    <wsdl:binding name="ConsultaInformacionWsImplServiceSoapBinding" type="ns1:ConsultaInformacionWs">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="validaEntradas">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="validaEntradas">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="validaEntradasResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ConsultaInformacionWsImplService">
        <wsdl:port binding="tns:ConsultaInformacionWsImplServiceSoapBinding" name="ConsultaInformacionWsImplPort">
            <soap:address location="http://11.50.0.73:9010/consultainformacion-ws/servicios/ConsultaInformacion"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>