<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SelImportesCCDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleSolicitudApp/ConsultarDetalleSolicitudPrj/SelImportesCCDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleSolicitudApp/ConsultarDetalleSolicitudPrj/SelImportesCCDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelImportesCCDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="SelImportesCCDB_plt">
      <plt:role name="SelImportesCCDB_role">
         <plt:portType name="tns:SelImportesCCDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelImportesCCDB" schemaLocation="../Schemas/SelImportesCCDB.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="SelImportesCCDBInput_msg">
      <wsdl:part name="SelImportesCCDBInput_msg" element="db:SelImportesCCDBInput"/>
   </wsdl:message>
   <wsdl:message name="SelImportesCCDBOutputCollection_msg">
      <wsdl:part name="SelImportesCCDBOutputCollection" element="db:SelImportesCCDBOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="SelImportesCCDB_ptt">
      <wsdl:operation name="SelImportesCCDB">
         <wsdl:input message="tns:SelImportesCCDBInput_msg"/>
         <wsdl:output message="tns:SelImportesCCDBOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
