<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EmpleadoMapping/UsuarioEmpleadoMapppingDataSvc" name="UsuarioEmpleadoMapppingDataSvc-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="UsuarioEmpleadoMapppingDataSvc.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EmpleadoMapping/UsuarioEmpleadoMapppingDataSvc"/>
    <wsdl:binding name="UsuarioEmpleadoMapppingDataSvc_ptt-binding" type="usu:UsuarioEmpleadoMapppingDataSvc_ptt" xmlns:usu="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EmpleadoMapping/UsuarioEmpleadoMapppingDataSvc">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="UsuarioEmpleadoMapppingDataSvcSelect">
            <soap:operation soapAction="UsuarioEmpleadoMapppingDataSvcSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>