<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tns="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/" xmlns:nsd2="http://ws.gpa.qualitas.mx/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/ImporteDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 nsd2 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://oracle.com/sca/soapservice/GestionOrdenPagoApp/OrdenesPagoPrj/OrdenesPagoService" xmlns:ns3="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:inp1="http://qualitas.com.mx/Comunes/OrdenesPago/v1/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/ImporteDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/OrdenesPagoService.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="ordenPagProrrateoRequest" namespace="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_7">
            <oracle-xsl-mapper:schema location="http://11.50.0.20:7006/Finance/AP/GPA/Entity/ProxySvc/db/ImporteDBPxy?WSDL%2FFinance%2FAP%2FGPA%2FEntity%2FResources%2FImporteDB" xml:id="id_8"/>
            <oracle-xsl-mapper:rootElement name="Gpa002ImportesCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ImporteDB" xml:id="id_9"/>
            <oracle-xsl-mapper:param name="Inv_Importes_OutVar.Gpa002ImportesCollection" xml:id="id_10"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_11">
            <oracle-xsl-mapper:schema location="../WSDLs/ProrrateoParsingPxy_2.wsdl" xml:id="id_12"/>
            <oracle-xsl-mapper:rootElement name="Prorrateo" namespace="" xml:id="id_13"/>
            <oracle-xsl-mapper:rootElementDatatype name="prorrateoResponse" namespace="http://ws.gpa.qualitas.mx/" xml:id="id_14"/>
            <oracle-xsl-mapper:param name="Inv_Parsing_parse_OutputVariable.Prorrateo" xml:id="id_15"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_16">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_17">
            <oracle-xsl-mapper:schema location="http://11.50.0.20:7007/soa-infra/services/GPADomain/GestionOrdenPago!1.0/WSDLs/GestionOrdenPagoBPEL.wsdl" xml:id="id_18"/>
            <oracle-xsl-mapper:rootElement name="guardarOrdenPagoRequest" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xml:id="id_19"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [SUN MAR 19 17:02:50 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Inv_Importes_OutVar.Gpa002ImportesCollection" xml:id="id_20"/>
   <xsl:param name="Inv_Parsing_parse_OutputVariable.Prorrateo" xml:id="id_21"/>
   <xsl:template match="/" xml:id="id_22">
      <tns:guardarOrdenPagoRequest xml:id="id_23">
         <tns:Input xml:id="id_24">
         <!-- SUBTOTAL -->
            <xsl:if xml:id="id_27" test="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/listaProrrateoRow/importe > 0">
               <xsl:for-each xml:id="id_25" select="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/listaProrrateoRow">
                  <tns:ctaPagos xml:id="id_26">
                     <tns:ctaPago xml:id="id_40">
                        <xsl:value-of select="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/cuentaContable" xml:id="id_41"/>
                     </tns:ctaPago>
                     <tns:cveOficinaMov xml:id="id_42">
                        <xsl:value-of select="numeroOficina" xml:id="id_43"/>
                     </tns:cveOficinaMov>
                     <tns:descMov xml:id="id_65">
                        <xsl:value-of select="concat (&quot;F-&quot;, folio, &quot; &quot;, $Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/concepto, &quot; OF-&quot;, numeroOficina)" xml:id="id_66"/>
                     </tns:descMov>
                     <tns:importe xml:id="id_44">
                        <xsl:value-of select="importe" xml:id="id_45"/>
                     </tns:importe>
                     <tns:tipMov xml:id="id_46">D</tns:tipMov>
                     <tns:varCta xml:id="id_47">
                        <xsl:value-of select="numeroCentroCosto" xml:id="id_48"/>
                     </tns:varCta>
                  </tns:ctaPagos>
               </xsl:for-each>
            </xsl:if>
            <!-- MONTO IVA -->
             <tns:ctaPagos xml:id="id_49">
                     <tns:ctaPago xml:id="id_50">
                        <xsl:value-of select="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/cuentaContableIVA" xml:id="id_59"/>
                     </tns:ctaPago>
                     <tns:cveOficinaMov xml:id="id_52">
                        <xsl:value-of select="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/oficinaIVA" xml:id="id_60"/>
                     </tns:cveOficinaMov>
                     <tns:descMov xml:id="id_61">
                        <xsl:value-of select="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/descripcionIVA" xml:id="id_62"/>
                     </tns:descMov>
                     <tns:importe xml:id="id_54">
                        <xsl:value-of xml:id="id_64" select="sum($Inv_Importes_OutVar.Gpa002ImportesCollection//*:Gpa002Importes/*:montoIva)"/>
                     </tns:importe>
                     <tns:tipMov xml:id="id_56">D</tns:tipMov>
                     <tns:varCta xml:id="id_57">
                        <xsl:value-of select="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/centroCostosIVA" xml:id="id_63"/>
                     </tns:varCta>
                  </tns:ctaPagos>
            <tns:cveBen xml:id="id_28">
               <xsl:value-of xml:id="id_69" select="oraext:query-database (concat (&quot;SELECT ID_PRESTADOR FROM GPA015_SERVICIOS WHERE ID_SOLICITUD = '&quot;, $Inv_Importes_OutVar.Gpa002ImportesCollection/ns1:Gpa002ImportesCollection/ns1:Gpa002Importes/ns1:idSolicitud, &quot;'&quot; ), false(), false(), &quot;jdbc/GPAConnDB&quot; )"/>
            </tns:cveBen>
            <tns:monePag xml:id="id_30">
               <xsl:value-of xml:id="id_31" select="concat (0,0)"/>
            </tns:monePag>
            <tns:observ xml:id="id_32">
               <xsl:value-of select="$Inv_Parsing_parse_OutputVariable.Prorrateo/Prorrateo/data/concepto" xml:id="id_67"/>
            </tns:observ>
            <tns:ofnaPag xml:id="id_34">
               <xsl:value-of xml:id="id_35" select="oraext:query-database (concat (&quot;SELECT OFICINA_DESTINO FROM GPA001_SOLICITUD WHERE ID_SOLICITUD = '&quot;, $Inv_Importes_OutVar.Gpa002ImportesCollection/ns1:Gpa002ImportesCollection/ns1:Gpa002Importes/ns1:idSolicitud, &quot;'&quot; ), false(), false(), &quot;jdbc/GPAConnDB&quot; )"/>
            </tns:ofnaPag>
            <tns:tipBen xml:id="id_36">T</tns:tipBen>
            <tns:usuario xml:id="id_37">LZARCO</tns:usuario>
            <tns:id_solicitud xml:id="id_38">
               <xsl:value-of select="$Inv_Importes_OutVar.Gpa002ImportesCollection/ns1:Gpa002ImportesCollection/ns1:Gpa002Importes/ns1:idSolicitud" xml:id="id_68"/>
            </tns:id_solicitud>
         </tns:Input>
      </tns:guardarOrdenPagoRequest>
   </xsl:template>
</xsl:stylesheet>