<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tns="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/" xmlns:nsd1="http://ws.gpa.qualitas.mx/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 nsd1 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://oracle.com/sca/soapservice/GestionOrdenPagoApp/OrdenesPagoPrj/OrdenesPagoService" xmlns:ns2="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:inp1="http://qualitas.com.mx/Comunes/OrdenesPago/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/OrdenesPagoService.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="ordenPagProrrateoRequest" namespace="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_7">
            <oracle-xsl-mapper:schema location="http://11.50.0.21:8001/GPACommonsBasic/ProrrateoSvcPort?WSDL" xml:id="id_8"/>
            <oracle-xsl-mapper:rootElement name="Prorrateo" namespace="" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElementDatatype name="prorrateoResponse" namespace="http://ws.gpa.qualitas.mx/" xml:id="id_10"/>
            <oracle-xsl-mapper:param name="InvParseoDoc_OutputVariable.Prorrateo" xml:id="id_11"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_12">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/GPADomain/GestionOrdenPago!1.0/WSDLs/GestionOrdenPagoBPEL.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="guardarOrdenPagoRequest" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xml:id="id_15"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI MAR 03 12:05:04 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InvParseoDoc_OutputVariable.Prorrateo" xml:id="id_16"/>
   <xsl:template match="/" xml:id="id_17">
      <tns:guardarOrdenPagoRequest xml:id="id_18">
         <tns:Input xml:id="id_19">
            <xsl:for-each xml:id="id_22" select="$InvParseoDoc_OutputVariable.Prorrateo/Prorrateo/data/listaProrrateoRow">
               <tns:ctaPagos xml:id="id_23">
                  <tns:ctaPago xml:id="id_32">
                     <xsl:value-of select="$InvParseoDoc_OutputVariable.Prorrateo/Prorrateo/data/cuentaContable" xml:id="id_33"/>
                  </tns:ctaPago>
                  <tns:cveOficinaMov xml:id="id_26">
                     <xsl:value-of select="numeroOficina" xml:id="id_27"/>
                  </tns:cveOficinaMov>
                  <tns:descMov xml:id="id_41">
                     <xsl:value-of select="$InvParseoDoc_OutputVariable.Prorrateo/Prorrateo/data/descripcion" xml:id="id_42"/>
                  </tns:descMov>
                  <tns:importe xml:id="id_24">
                     <xsl:value-of select="importe" xml:id="id_25"/>
                  </tns:importe>
                  <tns:tipMov xml:id="id_36">D</tns:tipMov>
                  <tns:varCta xml:id="id_28">
                     <xsl:value-of select="numeroCentroCosto" xml:id="id_29"/>
                  </tns:varCta>
               </tns:ctaPagos>
            </xsl:for-each>
            <tns:cveBen xml:id="id_37">26110</tns:cveBen>
            <tns:monePag xml:id="id_34">
               <xsl:value-of xml:id="id_35" select="concat (0, 0 )"/>
            </tns:monePag>
            <tns:observ xml:id="id_30">
               <xsl:value-of select="$InvParseoDoc_OutputVariable.Prorrateo/Prorrateo/data/descripcion" xml:id="id_31"/>
            </tns:observ>
            <tns:ofnaPag xml:id="id_38">010</tns:ofnaPag>
            <tns:tipBen xml:id="id_39">T</tns:tipBen>
            <tns:usuario xml:id="id_40">LZARCO</tns:usuario>
            <tns:id_solicitud xml:id="id_20">
               <xsl:value-of select="/ns0:ordenPagProrrateoRequest/ns0:Input/ns0:id_solicitud" xml:id="id_21"/>
            </tns:id_solicitud>
         </tns:Input>
      </tns:guardarOrdenPagoRequest>
   </xsl:template>
</xsl:stylesheet>