<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ObtenerEmpleadoBPEL" targetNamespace="http://xmlns.oracle.com/ObtenerEmpleadoApp/ObtenerEmpleadoPrj/ObtenerEmpleadoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ObtenerEmpleadoApp/ObtenerEmpleadoPrj/ObtenerEmpleadoBPEL" xmlns:ns1="http://qualitas.com.mx/Personas/Empleado/obtenerEmpleadoPorNumero/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Personas/Empleado/obtenerEmpleadoPorNumero/v1/" schemaLocation="../Schemas/obtenerEmpleadoPorNumero.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ObtenerEmpleadoBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:ObtenerEmpleadoRequest"/>
   </wsdl:message>
   <wsdl:message name="ObtenerEmpleadoBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:ObtenerEmpleadoResponse"/>
   </wsdl:message>
   <wsdl:portType name="ObtenerEmpleadoBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ObtenerEmpleadoBPELRequestMessage"/>
         <wsdl:output message="client:ObtenerEmpleadoBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ObtenerEmpleadoBPEL">
      <plnk:role name="ObtenerEmpleadoBPELProvider" portType="client:ObtenerEmpleadoBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
