<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="VwEmpleadoRHDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPA_App/ObtenerEmpleadoPrj/VwEmpleadoRHDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GPA_App/ObtenerEmpleadoPrj/VwEmpleadoRHDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/VwEmpleadoRHDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="VwEmpleadoRHDB_plt">
      <plt:role name="VwEmpleadoRHDB_role">
         <plt:portType name="tns:VwEmpleadoRHDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/VwEmpleadoRHDB" schemaLocation="../Schemas/VwEmpleadoRHDB.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="VwEmpleadoRHDBInput_msg">
      <wsdl:part name="VwEmpleadoRHDBInput_msg" element="db:VwEmpleadoRHDBInput"/>
   </wsdl:message>
   <wsdl:message name="VwEmpleadoRHDBOutputCollection_msg">
      <wsdl:part name="VwEmpleadoRHDBOutputCollection" element="db:VwEmpleadoRHDBOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="VwEmpleadoRHDB_ptt">
      <wsdl:operation name="VwEmpleadoRHDB">
         <wsdl:input message="tns:VwEmpleadoRHDBInput_msg"/>
         <wsdl:output message="tns:VwEmpleadoRHDBOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
