<wsdl:definitions name="CrearServicioBPEL" targetNamespace="http://qualitas.com.mx/CrearServicioApp/CrearServicioPrj/CrearServicioBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/CrearServicioApp/CrearServicioPrj/CrearServicioBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Servicio/CrearServicioPorTipo/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.22:7007/soa-infra/services/GPADomain/CrearServicioPrj!1.0/WSDLs/CrearServicioBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="CrearServicioBPEL">
        <plnk:role name="CrearServicioBPELProvider" portType="client:CrearServicioBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/Comun/Servicio/CrearServicioPorTipo/v1/" schemaLocation="XMLSchema_-1825572657.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CrearServicioBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:CrearServicioRequest"/>
    </wsdl:message>
    <wsdl:message name="CrearServicioBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:CrearServicioResponse"/>
    </wsdl:message>
    <wsdl:portType name="CrearServicioBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:CrearServicioBPELRequestMessage"/>
            <wsdl:output message="client:CrearServicioBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CrearServicioBPELBinding" type="client:CrearServicioBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="crearserviciobpel_client_ep">
        <wsdl:port name="CrearServicioBPEL_pt" binding="client:CrearServicioBPELBinding">
            <soap:address location="http://11.50.0.22:7007/soa-infra/services/GPADomain/CrearServicioPrj/crearserviciobpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>