<wsdl:definitions name="BatchScoreSvc" targetNamespace="http://servicios.montedepiedad.com.mx/NMP/Services/BatchScore" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Services/BatchScore" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:top="http://servicios.montedepiedad.com.mx/NMP/Services/BatchScore">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://servicios.montedepiedad.com.mx/NMP/Services/BatchScore" schemaLocation="../Schemas/OSBBatchPrendarioSvcXSD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="TaDetalleOperacionCollection_msg">
    <wsdl:part name="TaDetalleOperacionCollection" element="top:TaDetalleOperacionCollection"/>
  </wsdl:message>
  <wsdl:portType name="BatchScore_ptt">
    <wsdl:operation name="receive">
      <wsdl:input message="tns:TaDetalleOperacionCollection_msg"/>
      <wsdl:output message="tns:responseAck_msg"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BatchScore_ptt-binding" type="tns:BatchScore_ptt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="receive">
      <soap:operation soapAction="receive" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BatchScore-service">
    <wsdl:port name="BatchScore-port" binding="tns:BatchScore_ptt-binding">
      <soap:address location=""/>
    </wsdl:port>
  </wsdl:service>
  <wsdl:message name="responseAck_msg">
    <wsdl:part name="response" element="tns:response"/>
  </wsdl:message>
</wsdl:definitions>