<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasDataServices/SolicitudesCursoDataSvc/SolicitudesCursoDataBS" name="SolicitudesCursoDataBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SolicitudesCursoDataBS.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasDataServices/SolicitudesCursoDataSvc/SolicitudesCursoDataBS"/>
    <wsdl:binding name="SolicitudesCursoDataBS_ptt-binding" type="sol:SolicitudesCursoDataBS_ptt" xmlns:sol="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasDataServices/SolicitudesCursoDataSvc/SolicitudesCursoDataBS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SolicitudesCursoDataBSSelect">
            <soap:operation soapAction="SolicitudesCursoDataBSSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>