<wsdl:definitions name="BitacoraPrestamoDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AutomatizacionContable/BitacoraMidas/BitacoraPrestamoDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AutomatizacionContable/BitacoraMidas/BitacoraPrestamoDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/BitacoraPrestamoDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="BitacoraPrestamoDB_plt">
    <plt:role name="BitacoraPrestamoDB_role">
      <plt:portType name="tns:BitacoraPrestamoDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/BitacoraPrestamoDB" schemaLocation="../Schemas/OSBBitacoraPrestamoSvcXSD.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="BitOsbPrestamoCollection_msg">
        <wsdl:part name="BitOsbPrestamoCollection" element="top:BitOsbPrestamoCollection"/>
    </wsdl:message>
    <wsdl:portType name="BitacoraPrestamoDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:BitOsbPrestamoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>