<wsdl:definitions name="CountServiciosSolicitudDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountServiciosSolicitudDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountServiciosSolicitudDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CountServiciosSolicitud" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CountServiciosSolicitudDB_plt">
    <plt:role name="CountServiciosSolicitudDB_role">
      <plt:portType name="tns:CountServiciosSolicitudDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CountServiciosSolicitud" schemaLocation="CountServiciosSolicitudDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="CountServiciosSolicitudInput_msg">
        <wsdl:part name="CountServiciosSolicitudInput_msg" element="db:CountServiciosSolicitudInput"/>
    </wsdl:message>
    <wsdl:message name="CountServiciosSolicitudOutput_msg">
        <wsdl:part name="CountServiciosSolicitudOutput" element="db:CountServiciosSolicitudOutput"/>
    </wsdl:message>
    <wsdl:portType name="CountServiciosSolicitudDB_ptt">
        <wsdl:operation name="CountServiciosSolicitudDB">
            <wsdl:input message="tns:CountServiciosSolicitudInput_msg"/>
            <wsdl:output message="tns:CountServiciosSolicitudOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>