<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountServiciosSolicitudDB" name="CountServiciosSolicitudDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CountServiciosSolicitudDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountServiciosSolicitudDB"/>
    <wsdl:binding name="CountServiciosSolicitudDB_ptt-binding" type="coun:CountServiciosSolicitudDB_ptt" xmlns:coun="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountServiciosSolicitudDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CountServiciosSolicitudDB">
            <soap:operation soapAction="CountServiciosSolicitudDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>