<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo" xmlns:tns="urn:mx.com.nmp.midas" xmlns:ve="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:ns3="http://nmpcotizadorautomovil.services.nmp.servicios.montedepiedad.com.mx" xmlns:ns1="http://nmpcotizadorautomovil.schema.nmp.servicios.montedepiedad.com.mx" xmlns:ns2="http://nmpstandardmessage.schema.nmp.servicios.montedepiedad.com.mx">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPAvaluoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="obtenerAvaluoAuto" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/MIDASCotizadorAutomovilResponseTypeXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="obtenerAvaluoAutomovil" namespace="urn:mx.com.nmp.midas"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU FEB 23 20:34:09 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:obtenerAvaluoAutomovil>
         <tns:idMarca>
            <xsl:if test="/ns0:obtenerAvaluoAuto/ve:marca/ve:idMarca/@xsi:nil">
               <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:marca/ve:idMarca/@xsi:nil"/>
               </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:marca/ve:idMarca"/>
         </tns:idMarca>
         <tns:idSubMarca>
            <xsl:if test="/ns0:obtenerAvaluoAuto/ve:submarca/ve:idSubMarca/@xsi:nil">
               <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:submarca/ve:idSubMarca/@xsi:nil"/>
               </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:submarca/ve:idSubMarca"/>
         </tns:idSubMarca>
         <tns:idModelo>
            <xsl:if test="/ns0:obtenerAvaluoAuto/ve:modelo/ve:idModelo/@xsi:nil">
               <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:modelo/ve:idModelo/@xsi:nil"/>
               </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:modelo/ve:idModelo"/>
         </tns:idModelo>
         <tns:idVersion>
            <xsl:if test="/ns0:obtenerAvaluoAuto/ve:version/ve:idVersion/@xsi:nil">
               <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:version/ve:idVersion/@xsi:nil"/>
               </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:version/ve:idVersion"/>
         </tns:idVersion>
         <tns:idKilometraje>
            <xsl:if test="/ns0:obtenerAvaluoAuto/ve:kilometraje/ve:idKilometraje/@xsi:nil">
               <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:kilometraje/ve:idKilometraje/@xsi:nil"/>
               </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:kilometraje/ve:idKilometraje"/>
         </tns:idKilometraje>
         <tns:complementos>
            <xsl:if test="/ns0:obtenerAvaluoAuto/ve:complementos/ve:complemento/@xsi:nil">
               <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:complementos/ve:complemento/@xsi:nil"/>
               </xsl:attribute>
            </xsl:if>
            <xsl:for-each select="/ns0:obtenerAvaluoAuto/ve:complementos/ve:complemento">
               <tns:long>
                  <xsl:value-of select="ve:idComplemento"/>
               </tns:long>
            </xsl:for-each>
         </tns:complementos>
      </tns:obtenerAvaluoAutomovil>
   </xsl:template>
</xsl:stylesheet>