<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SPObtenerProrrateo" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GestionArchivoProrrateo/GestionArchivoProrrateoPrj/SPObtenerProrrateo" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GestionArchivoProrrateo/GestionArchivoProrrateoPrj/SPObtenerProrrateo" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerProrrateo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="SPObtenerProrrateo_plt">
      <plt:role name="SPObtenerProrrateo_role">
         <plt:portType name="tns:SPObtenerProrrateo_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerProrrateo" schemaLocation="../Schemas/SPObtenerProrrateo_sp.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="args_in_msg">
      <wsdl:part name="InputParameters" element="db:InputParameters"/>
   </wsdl:message>
   <wsdl:message name="args_out_msg">
      <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
   </wsdl:message>
   <wsdl:portType name="SPObtenerProrrateo_ptt">
      <wsdl:operation name="SPObtenerProrrateo">
         <wsdl:input message="tns:args_in_msg"/>
         <wsdl:output message="tns:args_out_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
