package model.capturacriterios.ent;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 08 10:11:57 CDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ControlEtapasImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdSolicitud,
        IdProyecto,
        IdEtapa,
        FechaCreacionEtapa,
        IdSubetapa,
        FechaCreacionSubetapa;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IDSOLICITUD = AttributesEnum.IdSolicitud.index();
    public static final int IDPROYECTO = AttributesEnum.IdProyecto.index();
    public static final int IDETAPA = AttributesEnum.IdEtapa.index();
    public static final int FECHACREACIONETAPA = AttributesEnum.FechaCreacionEtapa.index();
    public static final int IDSUBETAPA = AttributesEnum.IdSubetapa.index();
    public static final int FECHACREACIONSUBETAPA = AttributesEnum.FechaCreacionSubetapa.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ControlEtapasImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.capturacriterios.ent.ControlEtapas");
    }


    /**
     * Gets the attribute value for IdSolicitud, using the alias name IdSolicitud.
     * @return the value of IdSolicitud
     */
    public Number getIdSolicitud() {
        return (Number) getAttributeInternal(IDSOLICITUD);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdSolicitud.
     * @param value value to set the IdSolicitud
     */
    public void setIdSolicitud(Number value) {
        setAttributeInternal(IDSOLICITUD, value);
    }

    /**
     * Gets the attribute value for IdProyecto, using the alias name IdProyecto.
     * @return the value of IdProyecto
     */
    public Number getIdProyecto() {
        return (Number) getAttributeInternal(IDPROYECTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdProyecto.
     * @param value value to set the IdProyecto
     */
    public void setIdProyecto(Number value) {
        setAttributeInternal(IDPROYECTO, value);
    }

    /**
     * Gets the attribute value for IdEtapa, using the alias name IdEtapa.
     * @return the value of IdEtapa
     */
    public Number getIdEtapa() {
        return (Number) getAttributeInternal(IDETAPA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdEtapa.
     * @param value value to set the IdEtapa
     */
    public void setIdEtapa(Number value) {
        setAttributeInternal(IDETAPA, value);
    }

    /**
     * Gets the attribute value for FechaCreacionEtapa, using the alias name FechaCreacionEtapa.
     * @return the value of FechaCreacionEtapa
     */
    public String getFechaCreacionEtapa() {
        return (String) getAttributeInternal(FECHACREACIONETAPA);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaCreacionEtapa.
     * @param value value to set the FechaCreacionEtapa
     */
    public void setFechaCreacionEtapa(String value) {
        setAttributeInternal(FECHACREACIONETAPA, value);
    }

    /**
     * Gets the attribute value for IdSubetapa, using the alias name IdSubetapa.
     * @return the value of IdSubetapa
     */
    public Number getIdSubetapa() {
        return (Number) getAttributeInternal(IDSUBETAPA);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdSubetapa.
     * @param value value to set the IdSubetapa
     */
    public void setIdSubetapa(Number value) {
        setAttributeInternal(IDSUBETAPA, value);
    }

    /**
     * Gets the attribute value for FechaCreacionSubetapa, using the alias name FechaCreacionSubetapa.
     * @return the value of FechaCreacionSubetapa
     */
    public String getFechaCreacionSubetapa() {
        return (String) getAttributeInternal(FECHACREACIONSUBETAPA);
    }

    /**
     * Sets <code>value</code> as the attribute value for FechaCreacionSubetapa.
     * @param value value to set the FechaCreacionSubetapa
     */
    public void setFechaCreacionSubetapa(String value) {
        setAttributeInternal(FECHACREACIONSUBETAPA, value);
    }

    /**
     * @param idSolicitud key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number idSolicitud) {
        return new Key(new Object[] { idSolicitud });
    }


}

