<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPGenerarSeguDB" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPGenerarObservacionesDB" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/Seguimiento/GenerarSeguimiento/v1/" xmlns:ns3="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/SPGenerarSeguDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/SPGenerarObservacionesDB">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/ActualizaEstadoSolicitudBPEL.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="estadoSolicitudRequest" namespace="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_7">
            <oracle-xsl-mapper:schema location="../WSDLs/SPGenerarSeguDB.wsdl" xml:id="id_8"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPGenerarSeguDB" xml:id="id_9"/>
            <oracle-xsl-mapper:param name="GenerarSeguimientoPL_OutputVariable.OutputParameters" xml:id="id_10"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_11">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_12">
            <oracle-xsl-mapper:schema location="../WSDLs/SPGenerarObservacionesDB.wsdl" xml:id="id_13"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPGenerarObservacionesDB" xml:id="id_14"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON FEB 13 13:33:25 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="GenerarSeguimientoPL_OutputVariable.OutputParameters" xml:id="id_15"/>
   <xsl:template match="/" xml:id="id_16">
      <tns:InputParameters xml:id="id_17">
         <tns:P_IDSEG xml:id="id_18">
            <xsl:value-of select="$GenerarSeguimientoPL_OutputVariable.OutputParameters/ns1:OutputParameters/ns1:P_IDSEG" xml:id="id_19"/>
         </tns:P_IDSEG>
         <tns:P_TXOBS xml:id="id_20">
            <xsl:value-of select="/ns0:estadoSolicitudRequest/ns0:motivoRechazo/ns2:txObservaciones" xml:id="id_21"/>
         </tns:P_TXOBS>
         <xsl:choose xml:id="id_22">
            <xsl:when xml:id="id_23" test="/ns0:estadoSolicitudRequest/ns0:motivoRechazo/ns2:idTpObservacion > 0">
               <tns:P_IDTPOBS xml:id="id_24">
                  <xsl:value-of select="/ns0:estadoSolicitudRequest/ns0:motivoRechazo/ns2:idTpObservacion" xml:id="id_25"/>
               </tns:P_IDTPOBS>
            </xsl:when>
            <xsl:otherwise>
                <tns:P_IDTPOBS xml:id="id_26">
                  <xsl:value-of xml:id="id_27" select="0"/>
               </tns:P_IDTPOBS>
            </xsl:otherwise>
         </xsl:choose>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>