<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CrearServicioBPEL" targetNamespace="http://qualitas.com.mx/CrearServicioApp/CrearServicioPrj/CrearServicioBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/CrearServicioApp/CrearServicioPrj/CrearServicioBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Servicio/CrearServicioPorTipo/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comun/Servicio/CrearServicioPorTipo/v1/" schemaLocation="../Schemas/crearServicioPorTipo.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CrearServicioBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:CrearServicioRequest"/>
   </wsdl:message>
   <wsdl:message name="CrearServicioBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:CrearServicioResponse"/>
   </wsdl:message>
   <wsdl:portType name="CrearServicioBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:CrearServicioBPELRequestMessage"/>
         <wsdl:output message="client:CrearServicioBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="CrearServicioBPEL">
      <plnk:role name="CrearServicioBPELProvider" portType="client:CrearServicioBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
