<definitions targetNamespace="http://service.gpa.mx.com.qualitas/" name="CuentaDeudoraSvc" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="http://service.gpa.mx.com.qualitas/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://service.gpa.mx.com.qualitas/" schemaLocation="CuentaDeudoraSvcXSD.xsd"/>
    </xsd:schema>
  </types>
  <message name="consultarAutorizadores">
    <part name="parameters" element="tns:consultarAutorizadores"/>
  </message>
  <message name="consultarAutorizadoresResponse">
    <part name="parameters" element="tns:consultarAutorizadoresResponse"/>
  </message>
  <portType name="CuentaDeudoraSvc">
    <operation name="consultarAutorizadores">
      <input wsam:Action="http://service.gpa.mx.com.qualitas/CuentaDeudoraSvc/consultarAutorizadoresRequest" message="tns:consultarAutorizadores"/>
      <output wsam:Action="http://service.gpa.mx.com.qualitas/CuentaDeudoraSvc/consultarAutorizadoresResponse" message="tns:consultarAutorizadoresResponse"/>
    </operation>
  </portType>
  <binding name="CuentaDeudoraSvcPortBinding" type="tns:CuentaDeudoraSvc">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="consultarAutorizadores">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CuentaDeudoraSvc">
    <port name="CuentaDeudoraSvcPort" binding="tns:CuentaDeudoraSvcPortBinding">
      <soap:address location=""/>
    </port>
  </service>
</definitions>