<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerSolicitudDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleSolicitudApp/ConsultarDetalleSolicitudPrj/SPObtenerSolicitudDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/Importes/v1/" xmlns:ns3="http://qualitas.com.mx/comunes/" xmlns:ns4="http://qualitas.com.mx/Comun/Servicio/v1/" xmlns:client="http://qualitas.com.mx/Solicitud/ConsultarDetalleSolicitud/" xmlns:ns5="http://qualitas.com.mx/Comun/Servicio/ProyectoData/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SPObtenerSolicitudDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerSolicitudDB"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/consultarDetalleSolicitud.wsdl"/>
            <oracle-xsl-mapper:rootElement name="consultarDetalleSolicitudResponse" namespace="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI JAN 06 18:45:30 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:consultarDetalleSolicitudResponse>
         <pagoServicios>
            <xsl:choose>
               <xsl:when test="/ns0:OutputParameters/ns0:P_TIPOSERVICIO = 1">
                  <servicio>
                     <ns4:idTpServicio>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDTPSERVICIO"/>
                     </ns4:idTpServicio>
                     <ns4:idPrestador>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDPRESTADOR"/>
                     </ns4:idPrestador>
                     <ns4:CentroDeCosto>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_CENTROCOSTO"/>
                     </ns4:CentroDeCosto>
                     <ns4:cveOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_CVEOFIC"/>
                     </ns4:cveOficina>
                     <ns4:descOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESOFIC"/>
                     </ns4:descOficina>
                     <ns4:descArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESAREA"/>
                     </ns4:descArea>
                     <ns4:respArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_RESPAREA"/>
                     </ns4:respArea>
                     <ns4:servicioData>
                        <ns4:idServicio>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDSERVICIO"/>
                        </ns4:idServicio>
                        <ns4:descripcion>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESSERVICIO"/>
                        </ns4:descripcion>
                        <ns4:tipoMoneda>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:TP_MONEDA"/>
                        </ns4:tipoMoneda>
                     </ns4:servicioData>
                  </servicio>
               </xsl:when>
               <xsl:when test="/ns0:OutputParameters/ns0:P_TIPOSERVICIO = 3">
                  <servicio>
                     <ns4:idTpServicio>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_TIPOSERVICIO"/>
                     </ns4:idTpServicio>
                     <ns4:idPrestador>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:C_IDESTADOPROY"/>
                     </ns4:idPrestador>
                     <ns4:CentroDeCosto>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_CENTROCOSTO"/>
                     </ns4:CentroDeCosto>
                     <ns4:cveOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_CVEOFIC"/>
                     </ns4:cveOficina>
                     <ns4:descOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESOFIC"/>
                     </ns4:descOficina>
                     <ns4:descArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESCAREA"/>
                     </ns4:descArea>
                     <ns4:respArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_RESPAREA"/>
                     </ns4:respArea>
                     <ns4:servicioData>
                        <ns4:idServicio/>
                        <ns4:descripcion/>
                        <ns4:tipoMoneda/>
                     </ns4:servicioData>
                     <ns4:proyecto>
                        <ns5:idProyecto>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDPROYECTO"/>
                        </ns5:idProyecto>
                        <ns5:descripcion>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESPROY"/>
                        </ns5:descripcion>
                        <ns5:nombre>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_NOMPROY"/>
                        </ns5:nombre>
                        <ns5:presupuestoAprob>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_PRESAPROB"/>
                        </ns5:presupuestoAprob>
                        <ns5:numParcialidades>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:C_NUPARC"/>
                        </ns5:numParcialidades>
                        <ns5:idcondicionPago>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDCONDPAGO"/>
                        </ns5:idcondicionPago>
                        <xsl:if test="/ns0:OutputParameters/ns0:B_IDCONDPAGO = 1">
                           <ns5:condicionPago>PAGO EN UNA SOLA EXHIBICION</ns5:condicionPago>
                        </xsl:if>
                        <xsl:if test="/ns0:OutputParameters/ns0:B_IDCONDPAGO = 2">
                           <ns5:condicionPago>PARCIALIDADES</ns5:condicionPago>
                        </xsl:if>
                        <ns5:tipoMoneda>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:TP_MONEDA"/>
                        </ns5:tipoMoneda>
                        <ns5:complemento>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:C_COMPLEMENTO"/>
                        </ns5:complemento>
                     </ns4:proyecto>
                  </servicio>
               </xsl:when>
            </xsl:choose>
            <xsl:for-each select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row">
               <Importes>
                  <ns2:idImportes>
                     <xsl:value-of select="ns0:ID_IMPORTES"/>
                  </ns2:idImportes>
                  <ns2:nombreDocumento>
                     <xsl:value-of select="ns0:NOMBRE_DOCUMENTO"/>
                  </ns2:nombreDocumento>
                  <ns2:subtotal>
                     <xsl:value-of select="ns0:SUBTOTAL"/>
                  </ns2:subtotal>
                  <ns2:montoIva>
                     <xsl:value-of select="ns0:MONTO_IVA"/>
                  </ns2:montoIva>
                  <ns2:tasaIva>
                     <xsl:value-of select="ns0:TASA_IVA"/>
                  </ns2:tasaIva>
                  <ns2:retencionIsr>
                     <xsl:value-of select="ns0:MONTO_RETENCION_ISR"/>
                  </ns2:retencionIsr>
                  <ns2:retencionIva>
                     <xsl:value-of select="ns0:MONTO_RETENCION_IVA"/>
                  </ns2:retencionIva>
                  <ns2:otrosImpuestos>
                     <xsl:value-of select="ns0:OTROS_IMPUESTOS"/>
                  </ns2:otrosImpuestos>
                  <ns2:observaciones>
                     <xsl:value-of select="ns0:OBSERVACIONES"/>
                  </ns2:observaciones>
                  <ns2:xmlFactura>
                     <xsl:value-of select="ns0:XML_FACTURA"/>
                  </ns2:xmlFactura>
                  <ns2:tipoMoneda>
                     <xsl:value-of select="ns0:TP_MONEDA"/>
                  </ns2:tipoMoneda>
                  <ns2:folioFiscal>
                     <xsl:value-of select="ns0:FOLIO_FISCAL"/>
                  </ns2:folioFiscal>
               </Importes>
            </xsl:for-each>
            <Solicitud>
               <idSolicitud>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_IDSOL"/>
               </idSolicitud>
               <totalPagar>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_TOTALPAGAR"/>
               </totalPagar>
               <idUsuario>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_IDUSUARIO"/>
               </idUsuario>
               <numEmpleado>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_NUMPLEADO"/>
               </numEmpleado>
               <nomEmpleado>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_NOMEMPLEADO"/>
               </nomEmpleado>
               <cveOfiDestino>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_OFICDEST"/>
               </cveOfiDestino>
            </Solicitud>
         </pagoServicios>
      </tns:consultarDetalleSolicitudResponse>
   </xsl:template>
</xsl:stylesheet>