<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://tempuri.org/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPNotificacionesSMS" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns2="http://schemas.datacontract.org/2004/07/EntityLayer.Respuesta" xmlns:ns1="http://schemas.datacontract.org/2004/07/EntityLayer">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPNotificacionesSMSXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="validarCodigoSMSRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPNotificacionesSMS"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/CRMCodigosSms0XSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="ValidaCodigo" namespace="http://tempuri.org/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU FEB 23 13:42:15 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ValidaCodigo>
      <tns:Request>
        <xsl:if test="/ns0:validarCodigoSMSRequest/ns0:codigo">
          <ns1:Codigo>
            <xsl:value-of select="/ns0:validarCodigoSMSRequest/ns0:codigo"/>
          </ns1:Codigo>
        </xsl:if>
        <xsl:if test="/ns0:validarCodigoSMSRequest/ns0:credencialNmp">
          <ns1:CredencialNmp>
            <xsl:value-of select="/ns0:validarCodigoSMSRequest/ns0:credencialNmp"/>
          </ns1:CredencialNmp>
        </xsl:if>
        <xsl:if test="/ns0:validarCodigoSMSRequest/ns0:Fuente">
          <ns1:Fuente>
            <xsl:value-of select="/ns0:validarCodigoSMSRequest/ns0:Fuente"/>
          </ns1:Fuente>
        </xsl:if>
        <xsl:if test="/ns0:validarCodigoSMSRequest/ns0:idCliente">
          <ns1:IdCliente>
            <xsl:value-of select="/ns0:validarCodigoSMSRequest/ns0:idCliente"/>
          </ns1:IdCliente>
        </xsl:if>
        <xsl:if test="/ns0:validarCodigoSMSRequest/ns0:NumTelefono">
          <ns1:NumTelefono>
            <xsl:value-of select="/ns0:validarCodigoSMSRequest/ns0:NumTelefono"/>
          </ns1:NumTelefono>
        </xsl:if>
      </tns:Request>
    </tns:ValidaCodigo>
  </xsl:template>
</xsl:stylesheet>