<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AutomatizacionContable/SIGOTiempoReal/BitacoraContabilidadDB" name="BitacoraContabilidadDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="OSBBitacoraContabilidadDbWSDL.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AutomatizacionContable/SIGOTiempoReal/BitacoraContabilidadDB"/>
    <wsdl:binding name="BitacoraContabilidadDB_ptt-binding" type="bit:BitacoraContabilidadDB_ptt" xmlns:bit="http://xmlns.oracle.com/pcbpel/adapter/db/AutomatizacionContable/SIGOTiempoReal/BitacoraContabilidadDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>