<wsdl:definitions name="BPELIncapacidadesPermisos" targetNamespace="http://xmlns.oracle.com/Vitamedica/VitamedicaLayout/BPELIncapacidadesPermisos" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/IncYPer/Schema" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/Vitamedica/VitamedicaLayout/BPELIncapacidadesPermisos" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
        <abstractWSDL>http://dcpsoadev1n1.nmp.com.mx:8001/soa-infra/services/nmp/VitamedicaLayout!1.0/BPELIncapacidadesPermisos.wsdl</abstractWSDL>
    </wsdl:documentation>
  <plnk:partnerLinkType name="BPELIncapacidadesPermisos">
    <plnk:role name="BPELIncapacidadesPermisosProvider">
      <plnk:portType name="client:BPELIncapacidadesPermisos"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://servicios.montedepiedad.com.mx/NMP/IncYPer/Schema" schemaLocation="../Schemas/BPELIncYPerElementosXSD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="BPELIncapacidadesPermisosRequestMessage">
    <wsdl:part name="payload" element="ns1:process"/>
  </wsdl:message>
  <wsdl:portType name="BPELIncapacidadesPermisos">
    <wsdl:operation name="process">
      <wsdl:input message="client:BPELIncapacidadesPermisosRequestMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BPELIncapacidadesPermisosBinding" type="client:BPELIncapacidadesPermisos">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <soap:operation style="document" soapAction="process"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="bpelincapacidadespermisos_client_ep">
    <wsdl:port name="BPELIncapacidadesPermisos_pt" binding="client:BPELIncapacidadesPermisosBinding">
      <soap:address location="http://dcpsoadev1n1.nmp.com.mx:8001/soa-infra/services/nmp/VitamedicaLayout/bpelincapacidadespermisos_client_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>