<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/TotalesPadronDBAdapter" name="TotalesPadronDBAdapter-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/TotalesPadronDBAdapter" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/TotalesPadronDBAdapter" location="DBTotalesBeneficiariosDbWSDL.wsdl"/>
  <binding name="TotalesPadronDBAdapter_ptt-binding" type="tns:TotalesPadronDBAdapter_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="TotalesPadronDBAdapter">
      <soap:operation soapAction="TotalesPadronDBAdapter"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="TotalesPadronDBAdapter-service">
    <port name="TotalesPadronDBAdapter-port" binding="tns:TotalesPadronDBAdapter_ptt-binding">
      <soap:address location="jca://eis/DB/PeopleSoftAdapter"/>
    </port>
  </service>
</definitions>