<?binding.jca DetallePadronDBAdapter_db.jca?><wsdl:definitions name="DetallePadronDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/DetallePadronDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DetallePadronDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/DetallePadronDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <plt:partnerLinkType name="DetallePadronDBAdapter_plt">
    <plt:role name="DetallePadronDBAdapter_role">
      <plt:portType name="tns:DetallePadronDBAdapter_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DetallePadronDBAdapter" schemaLocation="../Schemas/DBBeneficiariosDetalleElementosXSD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="DetallePadronDBAdapterInput_msg">
    <wsdl:part name="DetallePadronDBAdapterInput_msg" element="db:DetallePadronDBAdapterInput"/>
  </wsdl:message>
  <wsdl:message name="DetallePadronDBAdapterOutputCollection_msg">
    <wsdl:part name="DetallePadronDBAdapterOutputCollection" element="db:DetallePadronDBAdapterOutputCollection"/>
  </wsdl:message>
  <wsdl:portType name="DetallePadronDBAdapter_ptt">
    <wsdl:operation name="DetallePadronDBAdapter">
      <wsdl:input message="tns:DetallePadronDBAdapterInput_msg"/>
      <wsdl:output message="tns:DetallePadronDBAdapterOutputCollection_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>