<definitions targetNamespace="http://service.gpa.mx.com.qualitas/" name="SolicitudViaticosSvc" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="http://service.gpa.mx.com.qualitas/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://service.gpa.mx.com.qualitas/" schemaLocation="SolicitudViaticosSvcXSD.xsd"/>
    </xsd:schema>
  </types>
  <message name="consultarActivas">
    <part name="parameters" element="tns:consultarActivas"/>
  </message>
  <message name="consultarActivasResponse">
    <part name="parameters" element="tns:consultarActivasResponse"/>
  </message>
  <message name="GPAException">
    <part name="fault" element="tns:GPAException"/>
  </message>
  <portType name="SolicitudViaticosSvc">
    <operation name="consultarActivas">
      <input wsam:Action="http://service.gpa.mx.com.qualitas/SolicitudViaticosSvc/consultarActivasRequest" message="tns:consultarActivas"/>
      <output wsam:Action="http://service.gpa.mx.com.qualitas/SolicitudViaticosSvc/consultarActivasResponse" message="tns:consultarActivasResponse"/>
      <fault message="tns:GPAException" name="GPAException" wsam:Action="http://service.gpa.mx.com.qualitas/SolicitudViaticosSvc/consultarActivas/Fault/GPAException"/>
    </operation>
  </portType>
  <binding name="SolicitudViaticosSvcPortBinding" type="tns:SolicitudViaticosSvc">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="consultarActivas">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="GPAException">
        <soap:fault name="GPAException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="SolicitudViaticosSvc">
    <port name="SolicitudViaticosSvcPort" binding="tns:SolicitudViaticosSvcPortBinding">
      <soap:address location=""/>
    </port>
  </service>
</definitions>