<definitions targetNamespace="http://servicios.montedepiedad.com.mx/NMP/Service/RiesgoTransaccional" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Service/RiesgoTransaccional" xmlns:ns1="http://servicios.montepiedad.com.mx/NMP/Schema/RiesgoTransaccional" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://servicios.montepiedad.com.mx/NMP/Schema/RiesgoTransaccional" schemaLocation="../Schemas/NMPRiesgoTransaccionalMsgXSD.xsd"/>
    </xsd:schema>
  </types>
  <message name="orquestadorAnalisisRequest">
    <part name="orquestadorAnalisisRequest" element="ns1:orquestadorAnalisisRequest"/>
  </message>
  <portType name="orquestadorAnalisisPortType">
    <operation name="orquestadorAnalisis">
      <input message="tns:orquestadorAnalisisRequest"/>
    </operation>
  </portType>
  <binding name="orquestadorAnalisisPortTypeSOAP11Binding" type="tns:orquestadorAnalisisPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="orquestadorAnalisis">
      <soap:operation style="document" soapAction="http://servicios.montedepiedad.com.mx/NMP/Service/RiesgoTransaccional/orquestadorAnalisis"/>
      <input>
        <soap:body use="literal" parts="orquestadorAnalisisRequest"/>
      </input>
    </operation>
  </binding>
</definitions>