<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/CatalogosBase/EntidadDataSvc" name="EntidadDataSvc-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EntidadDataSvc.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/CatalogosBase/EntidadDataSvc"/>
    <wsdl:binding name="EntidadDataSvc_ptt-binding" type="ent:EntidadDataSvc_ptt" xmlns:ent="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/CatalogosBase/EntidadDataSvc">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="selectByPrimaryKey">
            <soap:operation soapAction="selectByPrimaryKey"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>