<wsdl:definitions name="TxHistoricasCliente" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RT_DB_OSB/RT_DB/TxHistoricasCliente" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RT_DB_OSB/RT_DB/TxHistoricasCliente" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TxHistoricasCliente" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="TxHistoricasCliente_plt">
    <plt:role name="TxHistoricasCliente_role">
      <plt:portType name="tns:TxHistoricasCliente_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/TxHistoricasCliente" schemaLocation="../Schemas/BITxHistoricasClienteSPXSD.xsd"/>
     </schema>
    </wsdl:types>
    
    
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    
    <wsdl:portType name="TxHistoricasCliente_ptt">
        <wsdl:operation name="TxHistoricasCliente">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
        </wsdl:portType>
        
        
        <wsdl:binding name="TxHistoricasCliente_ptt-binding" type="txh:TxHistoricasCliente_ptt" xmlns:txh="http://xmlns.oracle.com/pcbpel/adapter/db/RT_DB_OSB/RT_DB/TxHistoricasCliente">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="TxHistoricasCliente">
            <soap:operation soapAction="TxHistoricasCliente"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    
</wsdl:definitions>