<wsdl:definitions name="ObtenerOficinaBPEL" targetNamespace="http://qualitas.com.mx/ObtenerOficinaApp/ObtenerOficinaPrj/ObtenerOficinaBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ObtenerOficinaApp/ObtenerOficinaPrj/ObtenerOficinaBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Oficina/obtenerOficinaPorClave/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.20:7007/soa-infra/services/GPADomain/ObtenerOficinaPrj!1.0/WSDLs/ObtenerOficinaBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ObtenerOficinaBPEL">
        <plnk:role name="ObtenerOficinaBPELProvider" portType="client:ObtenerOficinaBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/Comun/Oficina/obtenerOficinaPorClave/v1/" schemaLocation="XMLSchema_-2111547787.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerOficinaBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:obtenerOficinaPorClaveRequest"/>
    </wsdl:message>
    <wsdl:message name="ObtenerOficinaBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:obtenerOficinaPorClaveResponse"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerOficinaBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ObtenerOficinaBPELRequestMessage"/>
            <wsdl:output message="client:ObtenerOficinaBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ObtenerOficinaBPELBinding" type="client:ObtenerOficinaBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="obteneroficinabpel_client_ep">
        <wsdl:port name="ObtenerOficinaBPEL_pt" binding="client:ObtenerOficinaBPELBinding">
            <soap:address location="http://11.50.0.20:7007/soa-infra/services/GPADomain/ObtenerOficinaPrj/obteneroficinabpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>