<wsdl:definitions name="ValuadorDiamantesEndpointService" targetNamespace="http://ws.api.valuacion.sivad.ms.nmp.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.api.valuacion.sivad.ms.nmp.com.mx/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://nmp.com.mx/ms/sivad/valuacion/ws/diamantes/">
<wsdl:import location="SIVAValuadorDiamantesServiceWSDL.wsdl" namespace="http://nmp.com.mx/ms/sivad/valuacion/ws/diamantes/"/>
<wsdl:binding name="ValuadorDiamantesEndpointServiceSoapBinding" type="ns1:ValuadorDiamantesService">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="valuarPrendaBasico">
<soap:operation soapAction="http://nmp.com.mx/ms/valuacion/ws/diamantes/valuarPrendaBasico" style="document"/>
<wsdl:input name="valuarPrendaBasico">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="valuarPrendaBasicoResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="valuarPrendaNMP">
<soap:operation soapAction="http://nmp.com.mx/ms/valuacion/ws/diamantes/valuarPrendaNMP" style="document"/>
<wsdl:input name="valuarPrendaNMP">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="valuarPrendaNMPResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="ValuadorDiamantesEndpointService">
<wsdl:port binding="tns:ValuadorDiamantesEndpointServiceSoapBinding" name="ValuadorDiamantesEndpointPort">
<soap:address location="https://dev1775-sivad-motor-valuacion.mybluemix.net/soap-api/ValuadorDiamantes"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>