<wsdl:definitions name="ConsultaEntidadDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaEntidadAPP/ConsultaEntidad/ConsultaEntidadDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaEntidadAPP/ConsultaEntidad/ConsultaEntidadDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaEntidadDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="ConsultaEntidadDB_plt">
    <plt:role name="ConsultaEntidadDB_role">
      <plt:portType name="tns:ConsultaEntidadDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaEntidadDB" schemaLocation="ConsultaEntidadSchema.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="ConsultaEntidadDBInput_msg">
        <wsdl:part name="ConsultaEntidadDBInput_msg" element="db:ConsultaEntidadDBInput"/>
    </wsdl:message>
    <wsdl:message name="ConsultaEntidadDBOutputCollection_msg">
        <wsdl:part name="ConsultaEntidadDBOutputCollection" element="db:ConsultaEntidadDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="ConsultaEntidadDB_ptt">
        <wsdl:operation name="ConsultaEntidadDB">
            <wsdl:input message="tns:ConsultaEntidadDBInput_msg"/>
            <wsdl:output message="tns:ConsultaEntidadDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="ConsultaEntidadDB_ptt-binding" type="con:ConsultaEntidadDB_ptt" xmlns:con="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaEntidadAPP/ConsultaEntidad/ConsultaEntidadDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="ConsultaEntidadDB">
            <soap:operation soapAction="ConsultaEntidadDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
</wsdl:definitions>