<wsdl:definitions name="ValidarOficinasBPEL" targetNamespace="http://xmlns.oracle.com/ValidarCentroDeCostosApp/ValidarOficinasPrj/ValidarOficinasBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ValidarCentroDeCostosApp/ValidarOficinasPrj/ValidarOficinasBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Oficina/validarOficinas/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.22:7007/soa-infra/services/GPADomain/ValidarOficinasPrj!1.0/WSDLs/ValidarOficinasBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ValidarOficinasBPEL">
        <plnk:role name="ValidarOficinasBPELProvider" portType="client:ValidarOficinasBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/Comun/Oficina/validarOficinas/v1/" schemaLocation="XMLSchema_1252131864.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ValidarOficinasBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:validarOficinasRequest"/>
    </wsdl:message>
    <wsdl:message name="ValidarOficinasBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:validarOficinasResponse"/>
    </wsdl:message>
    <wsdl:portType name="ValidarOficinasBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ValidarOficinasBPELRequestMessage"/>
            <wsdl:output message="client:ValidarOficinasBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarOficinasBPELBinding" type="client:ValidarOficinasBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="validaroficinasbpel_ep">
        <wsdl:port name="ValidarOficinasBPEL_pt" binding="client:ValidarOficinasBPELBinding">
            <soap:address location="http://11.50.0.22:7007/soa-infra/services/GPADomain/ValidarOficinasPrj/validaroficinasbpel_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>