<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPlataformacomercial" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.oracle.com/xdb/CMPLATAFORMACOMERCIAL" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Servicios/NMPPublicarArticulosQueue" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:NMPsh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CMPLATAFORMACOMERCIAL_NMP_AJUSTE_PRECIOS_TYPE.xsd"/>
            <oracle-xsl-mapper:rootElement name="NMP_AJUSTE_PRECIOS_TYPE" namespace="http://xmlns.oracle.com/xdb/CMPLATAFORMACOMERCIAL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/NMPAgilirionProductoQueueSvcWSDL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="obteneArticuloAgilirionResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPlataformacomercial"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON AUG 21 16:38:55 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:obteneArticuloAgilirionResponse>
         <tns:articulos>
            <tns:articulo>
               <tns:articuloQueue>
                  <tns:ProductName>
                     <xsl:value-of select="/ns0:NMP_AJUSTE_PRECIOS_TYPE/DESCRIPCION"/>
                  </tns:ProductName>
                  <tns:ProductCode>
                     <xsl:value-of select="/ns0:NMP_AJUSTE_PRECIOS_TYPE/FOLIO"/>
                  </tns:ProductCode>
                  <tns:Barcode>
                     <xsl:value-of select="/ns0:NMP_AJUSTE_PRECIOS_TYPE/FOLIO"/>
                  </tns:Barcode>
                  <tns:ProductCategory>
                     <xsl:value-of select="/ns0:NMP_AJUSTE_PRECIOS_TYPE/RAMO"/>
                  </tns:ProductCategory>
                  <tns:SeoDescription>
                     <xsl:value-of select="/ns0:NMP_AJUSTE_PRECIOS_TYPE/DESCRIPCION"/>
                  </tns:SeoDescription>
                  <tns:Description>
                     <xsl:value-of select="/ns0:NMP_AJUSTE_PRECIOS_TYPE/DESCRIPCION"/>
                  </tns:Description>
                  <tns:ProductStockManager>admin</tns:ProductStockManager>
                  <tns:IncomeAccount>Uncategorized Income</tns:IncomeAccount>
                  <tns:CogsAccount>Cost of Goods Sold</tns:CogsAccount>
                  <tns:AssetAccount>Inventory Asset</tns:AssetAccount>
                  <tns:TaxCategory>Taxable</tns:TaxCategory>
               </tns:articuloQueue>
            </tns:articulo>
         </tns:articulos>
      </tns:obteneArticuloAgilirionResponse>
   </xsl:template>
</xsl:stylesheet>