<wsdl:definitions name="ObtenerServiciosPorPrestadorBPEL" targetNamespace="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.20:7007/soa-infra/services/GPADomain/ObtenerServicioPorPretstadorPrj!1.0/WSDLs/ObtenerServiciosPorPrestadorBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ObtenerServiciosPorPrestadorBPEL">
        <plnk:role name="ObtenerServiciosPorPrestadorBPELProvider" portType="client:ObtenerServiciosPorPrestadorBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" schemaLocation="XMLSchema_114001964.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerServiciosPorPrestadorBPELRequestMessage">
        <wsdl:part name="payload" element="client:serviciosPrestadorRequest"/>
    </wsdl:message>
    <wsdl:message name="ObtenerServiciosPorPrestadorBPELResponseMessage">
        <wsdl:part name="payload" element="client:serviciosPrestadorResponse"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerServiciosPorPrestadorBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ObtenerServiciosPorPrestadorBPELRequestMessage"/>
            <wsdl:output message="client:ObtenerServiciosPorPrestadorBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ObtenerServiciosPorPrestadorBPELBinding" type="client:ObtenerServiciosPorPrestadorBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="obtenerserviciosporprestadorbpel_client_ep">
        <wsdl:port name="ObtenerServiciosPorPrestadorBPEL_pt" binding="client:ObtenerServiciosPorPrestadorBPELBinding">
            <soap:address location="http://11.50.0.20:7007/soa-infra/services/GPADomain/ObtenerServicioPorPretstadorPrj/obtenerserviciosporprestadorbpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>