<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:ns0="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsEstatusSolicitudWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmRfcEstatusSolicitudResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPCreditoSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getEstatusSolicitudResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.2(XSLT Build 150402.0900.0103) AT [WED DEC 09 17:39:45 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:getEstatusSolicitudResponse>
      <tns:EstatusSolicitudes>
        <xsl:for-each select="/ns0:ZlmRfcEstatusSolicitudResponse/EstatusSolicitud/item">
          <tns:EstatusSolicitudes>
            <tns:nombreCliente>
              <xsl:value-of select="NombreCliente"/>
            </tns:nombreCliente>
            <tns:solicitud>
              <xsl:value-of select="Solicitud"/>
            </tns:solicitud>
            <tns:estatusGestion>
              <xsl:value-of select="EstatusGestion"/>
            </tns:estatusGestion>
            <tns:estatusSolicitud>
              <xsl:value-of select="EstatusSolicitud"/>
            </tns:estatusSolicitud>
            <tns:motivoPen>
              <xsl:value-of select="MotivoPen"/>
            </tns:motivoPen>
            <tns:fechaFirma>
              <xsl:value-of select="FechaFirma"/>
            </tns:fechaFirma>
            <tns:montoDesembolso>
              <xsl:value-of select="MontoDesembolso"/>
            </tns:montoDesembolso>
            <tns:saldoFecha>
              <xsl:value-of select="SaldoFecha"/>
            </tns:saldoFecha>
          </tns:EstatusSolicitudes>
        </xsl:for-each>
      </tns:EstatusSolicitudes>
    </tns:getEstatusSolicitudResponse>
  </xsl:template>
</xsl:stylesheet>