<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ValidarCentroDeCostosBPEL" targetNamespace="http://qualitas.com.mx/ValidarCentroDeCostosApp/ValidarCentrosDeCostosPrj/ValidarCentroDeCostosBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ValidarCentroDeCostosApp/ValidarCentrosDeCostosPrj/ValidarCentroDeCostosBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/CentroCostos/validarCentroCostos/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comun/CentroCostos/validarCentroCostos/v1/" schemaLocation="../Schemas/validarCentroCostos.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ValidarCentroDeCostosBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:ValidarCentroCostosRequest"/>
   </wsdl:message>
   <wsdl:message name="ValidarCentroDeCostosBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:ValidarCentroCostosResponse"/>
   </wsdl:message>
   <wsdl:portType name="ValidarCentroDeCostosBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ValidarCentroDeCostosBPELRequestMessage"/>
         <wsdl:output message="client:ValidarCentroDeCostosBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ValidarCentroDeCostosBPEL">
      <plnk:role name="ValidarCentroDeCostosBPELProvider" portType="client:ValidarCentroDeCostosBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
