<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://qualitas.com.mx/Solicitud/GuardarSolicitud/v1/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPGuardarImportesDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/Importes/v1/" xmlns:ns3="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:ns4="http://qualitas.com.mx/Comun/Servicio/TipoServicioData/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://qualitas.com.mx/Comun/Servicio/TipoServicio/v1/" xmlns:client="http://qualitas.com.mx/GuardarSolicitudApp/GuardarSolicitudPrj/GuardarSolicitudBPEL" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/GuardarSolicitudApp/GuardarSolicitudPrj/SPGuardarImportesDB">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/GuardarSolicitudBPEL.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="GuardarSolicitudRequest" namespace="http://qualitas.com.mx/Solicitud/GuardarSolicitud/v1/" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../WSDLs/SPGuardarImportesDB.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="InputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPGuardarImportesDB" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON DEC 26 21:52:16 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <tns:InputParameters xml:id="id_12">
         <tns:P_IDSOLICITUD xml:id="id_13">
            <xsl:value-of select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:idSolicitud" xml:id="id_14"/>
         </tns:P_IDSOLICITUD>
         <xsl:for-each xml:id="id_15" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:subtotal">
            <tns:P_SUBTOTAL xml:id="id_16">
               <xsl:value-of select="." xml:id="id_17"/>
            </tns:P_SUBTOTAL>
         </xsl:for-each>
         <xsl:for-each xml:id="id_18" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:montoIva">
            <tns:P_MONTOIVA xml:id="id_19">
               <xsl:value-of select="." xml:id="id_36"/>
            </tns:P_MONTOIVA>
         </xsl:for-each>
         <xsl:for-each xml:id="id_20" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:tasaIva">
            <tns:P_TASAIVA xml:id="id_21">
               <xsl:value-of select="." xml:id="id_37"/>
            </tns:P_TASAIVA>
         </xsl:for-each>
         <xsl:for-each xml:id="id_22" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:retencionIsr">
            <tns:P_RETISR xml:id="id_23">
               <xsl:value-of select="." xml:id="id_38"/>
            </tns:P_RETISR>
         </xsl:for-each>
         <xsl:for-each xml:id="id_24" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:retencionIva">
            <tns:P_RETIVA xml:id="id_25">
               <xsl:value-of select="." xml:id="id_39"/>
            </tns:P_RETIVA>
         </xsl:for-each>
         <xsl:for-each xml:id="id_26" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:otrosImpuestos">
            <tns:P_OTROSIMP xml:id="id_27">
               <xsl:value-of select="." xml:id="id_40"/>
            </tns:P_OTROSIMP>
         </xsl:for-each>
         <xsl:for-each xml:id="id_28" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:folioFiscal">
            <tns:P_FOLIOFISCAL xml:id="id_29">
               <xsl:value-of select="." xml:id="id_41"/>
            </tns:P_FOLIOFISCAL>
         </xsl:for-each>
         <xsl:for-each xml:id="id_30" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:nombreDocumento">
            <tns:P_NOMDOCUMENTO xml:id="id_31">
               <xsl:value-of select="." xml:id="id_42"/>
            </tns:P_NOMDOCUMENTO>
         </xsl:for-each>
         <xsl:for-each xml:id="id_32" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:xmlFactura">
            <tns:P_XMLFACTURA xml:id="id_33">
               <xsl:value-of select="." xml:id="id_43"/>
            </tns:P_XMLFACTURA>
         </xsl:for-each>
         <xsl:for-each xml:id="id_34" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN/ns2:idTipoMoneda">
            <tns:P_TPMONEDA xml:id="id_35">
               <xsl:value-of select="." xml:id="id_44"/>
            </tns:P_TPMONEDA>
         </xsl:for-each>
      </tns:InputParameters>
   </xsl:template>
</xsl:stylesheet>