<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://qualitas.com.mx/Solicitud/GuardarSolicitud/v1/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/GuardarImportesSolicitud" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/Importes/v1/" xmlns:ns3="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:ns4="http://qualitas.com.mx/Comun/Servicio/TipoServicioData/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://qualitas.com.mx/Comun/Servicio/TipoServicio/v1/" xmlns:client="http://qualitas.com.mx/GuardarSolicitudApp/GuardarSolicitudPrj/GuardarSolicitudBPEL" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/GuardarSolicitud/GuardarSolicitudPrj/GuardarImportesSolicitud">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/GuardarSolicitudBPEL.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="GuardarSolicitudRequest" namespace="http://qualitas.com.mx/Solicitud/GuardarSolicitud/v1/" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../WSDLs/GuardarImportesSolicitud.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="Gpa002ImportesCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GuardarImportesSolicitud" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON JAN 23 14:55:20 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <tns:Gpa002ImportesCollection xml:id="id_12">
         <xsl:for-each xml:id="id_39" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:importesOEN">
            <tns:Gpa002Importes xml:id="id_13">
               <tns:idSolicitud xml:id="id_17">
                  <xsl:value-of xml:id="id_18" select="/ns0:GuardarSolicitudRequest/ns0:Input/ns0:idSolicitud"/>
               </tns:idSolicitud>
               <tns:montoIva xml:id="id_19">
                  <xsl:value-of xml:id="id_20" select="ns2:montoIva"/>
               </tns:montoIva>
               <tns:tasaIva xml:id="id_25">
                  <xsl:value-of xml:id="id_26" select="ns2:tasaIva"/>
               </tns:tasaIva>
               <xsl:if test="ns2:observaciones" xml:id="id_40">
                  <tns:observaciones xml:id="id_41">
                     <xsl:value-of select="ns2:observaciones" xml:id="id_42"/>
                  </tns:observaciones>
               </xsl:if>
               <tns:folioFiscal xml:id="id_37">
                  <xsl:value-of xml:id="id_38" select="ns2:folioFiscal"/>
               </tns:folioFiscal>
               <tns:nombreDocumento xml:id="id_23">
                  <xsl:value-of xml:id="id_24" select="ns2:nombreDocumento"/>
               </tns:nombreDocumento>
               <tns:xmlFactura xml:id="id_33">
                  <xsl:value-of xml:id="id_34" select="ns2:xmlFactura"/>
               </tns:xmlFactura>
               <tns:tpMoneda xml:id="id_35">
                  <xsl:value-of xml:id="id_36" select="ns2:idTipoMoneda"/>
               </tns:tpMoneda>
               <tns:montoRetencionIsr xml:id="id_27">
                  <xsl:value-of xml:id="id_28" select="ns2:retencionIsr"/>
               </tns:montoRetencionIsr>
               <tns:montoRetencionIva xml:id="id_29">
                  <xsl:value-of xml:id="id_30" select="ns2:retencionIva"/>
               </tns:montoRetencionIva>
               <tns:otrosImpuestos xml:id="id_31">
                  <xsl:value-of xml:id="id_32" select="ns2:otrosImpuestos"/>
               </tns:otrosImpuestos>
               <tns:subtotal xml:id="id_21">
                  <xsl:value-of xml:id="id_22" select="ns2:subtotal"/>
               </tns:subtotal>
               <tns:total xml:id="id_43">
                  <xsl:value-of select="ns2:total" xml:id="id_44"/>
               </tns:total>
            </tns:Gpa002Importes>
         </xsl:for-each>
      </tns:Gpa002ImportesCollection>
   </xsl:template>
</xsl:stylesheet>