<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/MotordePrecios/Elementos" xmlns:tns="http://nmp.com.mx/ms/sivad/valuacion/ws/diamantes/datatypes/" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:t="http://servicios.montedepiedad.com.mx/NMP/Schema/MotordePrecios/Tipos" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://nmp.com.mx/ms/sivad/valuacion/ws/diamantes/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPMotordePreciosElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="valuarPrendaNMPRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/MotordePrecios/Elementos"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SIVAValuadorDiamantesServiceWSDL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="valuarPrendaNMPRequest" namespace="http://nmp.com.mx/ms/sivad/valuacion/ws/diamantes/datatypes/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI JAN 20 17:01:47 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:valuarPrendaNMPRequest>
         <tns:prenda>
            <tns:id>
               <xsl:if test="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:id/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:id/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:id"/>
            </tns:id>
            <tns:ramo>
               <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:ramo"/>
            </tns:ramo>
            <tns:subramo>
               <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:subramo"/>
            </tns:subramo>
            <tns:tipo>
               <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:tipo"/>
            </tns:tipo>
            <tns:avaluo>
               <xsl:if test="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:avaluo/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:avaluo/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <tns:valorMinimo>
                  <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:avaluo/t:valorMinimo"/>
               </tns:valorMinimo>
               <tns:valorPromedio>
                  <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:avaluo/t:valorPromedio"/>
               </tns:valorPromedio>
               <tns:valorMaximo>
                  <xsl:value-of select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:avaluo/t:valorMaximo"/>
               </tns:valorMaximo>
            </tns:avaluo>
            <xsl:for-each select="/ns0:valuarPrendaNMPRequest/ns0:prenda/t:pieza">
               <tns:pieza>
                  <tns:id>
                     <xsl:value-of select="t:id"/>
                  </tns:id>
                  <tns:cantidad>
                     <xsl:value-of select="t:cantidad"/>
                  </tns:cantidad>
                  <tns:avaluo>
                     <tns:valorMinimo>
                        <xsl:value-of select="t:avaluo/t:valorMinimo"/>
                     </tns:valorMinimo>
                     <tns:valorPromedio>
                        <xsl:value-of select="t:avaluo/t:valorPromedio"/>
                     </tns:valorPromedio>
                     <tns:valorMaximo>
                        <xsl:value-of select="t:avaluo/t:valorMaximo"/>
                     </tns:valorMaximo>
                  </tns:avaluo>
                  <xsl:if test="t:diamante">
                     <tns:diamante>
                        <tns:corte>
                           <xsl:value-of select="t:diamante/t:corte"/>
                        </tns:corte>
                        <tns:forma>
                           <xsl:value-of select="t:diamante/t:forma"/>
                        </tns:forma>
                        <tns:color>
                           <xsl:value-of select="t:diamante/t:color"/>
                        </tns:color>
                        <tns:claridad>
                           <xsl:value-of select="t:diamante/t:claridad"/>
                        </tns:claridad>
                        <tns:quilataje>
                           <xsl:value-of select="t:diamante/t:quilataje"/>
                        </tns:quilataje>
                        <tns:certificado>
                           <xsl:if test="t:diamante/t:certificado/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="t:diamante/t:certificado/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="t:diamante/t:certificado"/>
                        </tns:certificado>
                        <tns:valorExperto>
                           <xsl:if test="t:diamante/t:valorExperto/t:unitario">
                              <tns:unitario>
                                 <xsl:value-of select="t:diamante/t:valorExperto/t:unitario"/>
                              </tns:unitario>
                           </xsl:if>
                           <xsl:if test="t:diamante/t:valorExperto/t:total">
                              <tns:total>
                                 <xsl:value-of select="t:diamante/t:valorExperto/t:total"/>
                              </tns:total>
                           </xsl:if>
                        </tns:valorExperto>
                     </tns:diamante>
                  </xsl:if>
                  <xsl:if test="t:alhaja">
                     <tns:alhaja>
                        <tns:tipo>
                           <xsl:value-of select="t:alhaja/t:tipo"/>
                        </tns:tipo>
                        <tns:forma>
                           <xsl:value-of select="t:alhaja/t:forma"/>
                        </tns:forma>
                        <tns:metal>
                           <xsl:value-of select="t:alhaja/t:metal"/>
                        </tns:metal>
                        <tns:color>
                           <xsl:if test="t:alhaja/t:color/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="t:alhaja/t:color/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="t:alhaja/t:color"/>
                        </tns:color>
                        <tns:rango>
                           <xsl:if test="t:alhaja/t:rango/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="t:alhaja/t:rango/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="t:alhaja/t:rango"/>
                        </tns:rango>
                        <tns:calidad>
                           <xsl:if test="t:alhaja/t:calidad/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="t:alhaja/t:calidad/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="t:alhaja/t:calidad"/>
                        </tns:calidad>
                        <tns:peso>
                           <xsl:value-of select="t:alhaja/t:peso"/>
                        </tns:peso>
                        <tns:condicion>
                           <xsl:value-of select="t:alhaja/t:condicion"/>
                        </tns:condicion>
                        <tns:valorExperto>
                           <xsl:if test="t:alhaja/t:valorExperto/t:unitario">
                              <tns:unitario>
                                 <xsl:value-of select="t:alhaja/t:valorExperto/t:unitario"/>
                              </tns:unitario>
                           </xsl:if>
                           <xsl:if test="t:alhaja/t:valorExperto/t:total">
                              <tns:total>
                                 <xsl:value-of select="t:alhaja/t:valorExperto/t:total"/>
                              </tns:total>
                           </xsl:if>
                        </tns:valorExperto>
                        <tns:incremento>
                           <xsl:value-of select="t:alhaja/t:incremento"/>
                        </tns:incremento>
                        <tns:desplazamiento>
                           <xsl:value-of select="t:alhaja/t:desplazamiento"/>
                        </tns:desplazamiento>
                     </tns:alhaja>
                  </xsl:if>
                  <xsl:if test="t:complemento">
                     <tns:complemento>
                        <tns:tipo>
                           <xsl:value-of select="t:complemento/t:tipo"/>
                        </tns:tipo>
                        <tns:peso>
                           <xsl:value-of select="t:complemento/t:peso"/>
                        </tns:peso>
                        <tns:valorExperto>
                           <xsl:if test="t:complemento/t:valorExperto/t:unitario">
                              <tns:unitario>
                                 <xsl:value-of select="t:complemento/t:valorExperto/t:unitario"/>
                              </tns:unitario>
                           </xsl:if>
                           <xsl:if test="t:complemento/t:valorExperto/t:total">
                              <tns:total>
                                 <xsl:value-of select="t:complemento/t:valorExperto/t:total"/>
                              </tns:total>
                           </xsl:if>
                        </tns:valorExperto>
                     </tns:complemento>
                  </xsl:if>
               </tns:pieza>
            </xsl:for-each>
         </tns:prenda>
      </tns:valuarPrendaNMPRequest>
   </xsl:template>
</xsl:stylesheet>