<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://tempuri.org/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCampaniasPrendario" xmlns:ns1="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity.Modelos" xmlns:ns2="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity.DataContract" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCommonTypes" xmlns:type="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCampaniasPrendarioT" xmlns:ns4="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity" xmlns:ns5="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns6="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Campania">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../../GestionCatalogos/Sepomex/Resources/Schemas/CRMCatalogosEntityXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="ConsultaCanalesResponse" namespace="http://tempuri.org/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPCampaniasPrendarioSvcElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="getCanalesOrigenResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCampaniasPrendario"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU FEB 11 18:42:03 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:getCanalesOrigenResponse>
         <xsl:for-each select="/ns0:ConsultaCanalesResponse/ns0:ConsultaCanalesResult/ns2:DetalleRespuesta/ns1:CanalNMP">
            <type:listaCanales>
               <ns3:guidCanalOrigen>
                  <xsl:value-of select="ns1:GuidCanal"/>
               </ns3:guidCanalOrigen>
               <ns3:canalOrigen>
                  <xsl:value-of select="ns1:Nombre"/>
               </ns3:canalOrigen>
               <ns3:idCanalOrigen>
                  <xsl:value-of select="ns1:IdCanal"/>
               </ns3:idCanalOrigen>
            </type:listaCanales>
         </xsl:for-each>
      </tns:getCanalesOrigenResponse>
   </xsl:template>
</xsl:stylesheet>