<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://tempuri.org/" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://schemas.datacontract.org/2004/07/EntityLayer.Respuesta" xmlns:ns2="http://schemas.datacontract.org/2004/07/EntityLayer.Modelos" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPCampania="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Campania">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CRMMiMonteServiceElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetClienteResponse" namespace="http://tempuri.org/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPClientesSvcElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="obtenerClientePorUsuarioResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUN 15 16:34:31 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:obtenerClientePorUsuarioResponse>
         <tns:Cliente>
            <tns:idCliente>
               <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosPersonales/ns2:IdCliente"/>
            </tns:idCliente>
            <tns:nombre>
               <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosPersonales/ns2:Nombre"/>
            </tns:nombre>
            <tns:apellidoPaterno>
               <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosPersonales/ns2:ApellidoPaterno"/>
            </tns:apellidoPaterno>
            <tns:apellidoMaterno>
               <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosPersonales/ns2:ApellidoMaterno"/>
            </tns:apellidoMaterno>
            <tns:fechaDeNacimiento>
               <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosPersonales/ns2:FechaNacimiento"/>
            </tns:fechaDeNacimiento>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:FechaIngreso">
               <tns:fechaIngreso>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:FechaIngreso"/>
               </tns:fechaIngreso>
            </xsl:if>
            <tns:numeroDeCredencial>
               <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosPersonales/ns2:CredencialNMP"/>
            </tns:numeroDeCredencial>
            <xsl:for-each select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosContacto/ns2:Email/ns2:Email">
               <tns:CorreosElectronicos>
                  <tns:CorreoElectronico>
                     <xsl:if test="ns2:Correo">
                        <tns:email>
                           <xsl:value-of select="ns2:Correo"/>
                        </tns:email>
                     </xsl:if>
                     <xsl:if test="ns2:Tipo">
                        <tns:tipoEmail>
                           <xsl:value-of select="ns2:Tipo"/>
                        </tns:tipoEmail>
                     </xsl:if>
                     <xsl:if test="ns2:FuenteDato">
                        <tns:fuenteDato>
                           <xsl:value-of select="ns2:FuenteDato"/>
                        </tns:fuenteDato>
                     </xsl:if>
                  </tns:CorreoElectronico>
               </tns:CorreosElectronicos>
            </xsl:for-each>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:SobreAforo">
               <tns:sobreAforo>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:SobreAforo"/>
               </tns:sobreAforo>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionAjustada">
               <tns:calificacionAjustada>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionAjustada"/>
               </tns:calificacionAjustada>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionSIVA2">
               <tns:calificacionSIVA2>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionSIVA2"/>
               </tns:calificacionSIVA2>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:SobreAforoAjustado">
               <tns:sobreaforoAjustado>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:SobreAforoAjustado"/>
               </tns:sobreaforoAjustado>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:SobreAforoSIVA2">
               <tns:sobreaforoSIVA2>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:SobreAforoSIVA2"/>
               </tns:sobreaforoSIVA2>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionReal">
               <tns:calificacionReal>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionReal"/>
               </tns:calificacionReal>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionMidas">
               <tns:calificacionMidas>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:CalificacionMidas"/>
               </tns:calificacionMidas>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:ProbabilidadIncumplimiento">
               <tns:probabilidadIncumplimiento>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:ProbabilidadIncumplimiento"/>
               </tns:probabilidadIncumplimiento>
            </xsl:if>
            <xsl:if test="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:IndiceRecuperacion">
               <tns:indiceRecuperacion>
                  <xsl:value-of select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosCalifiacionPrendaria/ns2:IndiceRecuperacion"/>
               </tns:indiceRecuperacion>
            </xsl:if>
            <tns:Contacto>
               <tns:ListaTelefonos>
                  <xsl:for-each select="/ns0:GetClienteResponse/ns0:GetClienteResult/ns1:DetalleRespuesta/ns2:DatosContacto/ns2:Telefonos/ns2:Telefono">
                     <tns:Telefono>
                        <xsl:if test="ns2:Numero">
                           <tns:numeroTelefonico>
                              <xsl:value-of select="ns2:Numero"/>
                           </tns:numeroTelefonico>
                        </xsl:if>
                        <xsl:if test="ns2:Extension">
                           <tns:extension>
                              <xsl:value-of select="ns2:Extension"/>
                           </tns:extension>
                        </xsl:if>
                        <xsl:if test="ns2:Tipo">
                           <tns:tipoTelefono>
                              <xsl:value-of select="ns2:Tipo"/>
                           </tns:tipoTelefono>
                        </xsl:if>
                     </tns:Telefono>
                  </xsl:for-each>
               </tns:ListaTelefonos>
            </tns:Contacto>
         </tns:Cliente>
      </tns:obtenerClientePorUsuarioResponse>
   </xsl:template>
</xsl:stylesheet>