<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://tempuri.org/" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://schemas.datacontract.org/2004/07/EntityLayer.Respuesta" xmlns:ns2="http://schemas.datacontract.org/2004/07/EntityLayer.Modelos" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPCampania="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Campania">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CRMMiMonteServiceElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultaEstatusProcesoResponse" namespace="http://tempuri.org/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPClientesSvcElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarEstadoRegistroResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE JUN 13 15:13:24 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:consultarEstadoRegistroResponse>
         <tns:codigo>
            <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:Codigo"/>
         </tns:codigo>
         <tns:mensaje>
            <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:Mensaje"/>
         </tns:mensaje>
         <tns:cliente>
            <tns:idCliente>
               <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:IdCliente"/>
            </tns:idCliente>
            <tns:numCredencial>
               <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:CredencialNMP"/>
            </tns:numCredencial>
            <xsl:choose>
               <xsl:when test="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta">
                  <tns:estadosFlujo>
                     <tns:estadoFlujo>
                        <tns:idFlujo>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:Registro/ns2:IdFlujo"/>
                        </tns:idFlujo>
                        <tns:idEstado>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:Registro/ns2:IdStatus"/>
                        </tns:idEstado>
                        <tns:fechaEstado>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:Registro/ns2:FechaStatus"/>
                        </tns:fechaEstado>
                     </tns:estadoFlujo>
                     <tns:estadoFlujo>
                        <tns:idFlujo>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:Actualizacion/ns2:IdFlujo"/>
                        </tns:idFlujo>
                        <tns:idEstado>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:Actualizacion/ns2:IdStatus"/>
                        </tns:idEstado>
                        <tns:fechaEstado>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:Actualizacion/ns2:FechaStatus"/>
                        </tns:fechaEstado>
                     </tns:estadoFlujo>
                     <tns:estadoFlujo>
                        <tns:idFlujo>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:CambioContrasena/ns2:IdFlujo"/>
                        </tns:idFlujo>
                        <tns:idEstado>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:CambioContrasena/ns2:IdStatus"/>
                        </tns:idEstado>
                        <tns:fechaEstado>
                           <xsl:value-of select="/ns0:consultaEstatusProcesoResponse/ns0:consultaEstatusProcesoResult/ns1:DetalleRespuesta/ns2:CambioContrasena/ns2:FechaStatus"/>
                        </tns:fechaEstado>
                     </tns:estadoFlujo>
                  </tns:estadosFlujo>
               </xsl:when>
            </xsl:choose>
         </tns:cliente>
      </tns:consultarEstadoRegistroResponse>
   </xsl:template>
</xsl:stylesheet>