<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCampaniasPrendario" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPCampania="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Campania" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCommonTypes" xmlns:type="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCampaniasPrendarioT" xmlns:NMPConsultaC="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPClientesSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getClienteCampaniasByIdRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../FuerzaDeVentas/Campanias/Prendario/Resources/Schemas/NMPCampaniasPrendarioSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getCampaniasClienteRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCampaniasPrendario"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU AUG 04 17:02:02 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:getCampaniasClienteRequest>
      <xsl:if test="/NMPConsultaC:getClienteCampaniasByIdRequest/NMPConsultaC:idCliente">
        <type:idCliente>
          <xsl:value-of select="/NMPConsultaC:getClienteCampaniasByIdRequest/NMPConsultaC:idCliente"/>
        </type:idCliente>
      </xsl:if>
      <xsl:if test="/NMPConsultaC:getClienteCampaniasByIdRequest/NMPConsultaC:numCredencial">
        <type:numCredencial>
          <xsl:value-of select="/NMPConsultaC:getClienteCampaniasByIdRequest/NMPConsultaC:numCredencial"/>
        </type:numCredencial>
      </xsl:if>
    </ns0:getCampaniasClienteRequest>
  </xsl:template>
 
</xsl:stylesheet>