<wsdl:definitions
     name="CatBeneficiariosPagosDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Aplicacion_SOA_Qualitas/ObtenerGenerico/CatBeneficiariosPagosDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Aplicacion_SOA_Qualitas/ObtenerGenerico/CatBeneficiariosPagosDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CatBeneficiariosPagosDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CatBeneficiariosPagosDB_plt" >
    <plt:role name="CatBeneficiariosPagosDB_role" >
      <plt:portType name="tns:CatBeneficiariosPagosDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CatBeneficiariosPagosDB" schemaLocation="../Schemas/CatBeneficiariosPagosDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CatBeneficiariosPagosDBSelect_inputParameters">
        <wsdl:part name="CatBeneficiariosPagosDBSelect_inputParameters" element="top:CatBeneficiariosPagosDBSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="Gpa026BeneficiariosPagosCollection_msg">
        <wsdl:part name="Gpa026BeneficiariosPagosCollection" element="top:Gpa026BeneficiariosPagosCollection"/>
    </wsdl:message>
    <wsdl:portType name="CatBeneficiariosPagosDB_ptt">
        <wsdl:operation name="CatBeneficiariosPagosDBSelect">
            <wsdl:input message="tns:CatBeneficiariosPagosDBSelect_inputParameters"/>
            <wsdl:output message="tns:Gpa026BeneficiariosPagosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
