<wsdl:definitions
     name="CatFormasPagoDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Aplicacion_SOA_Qualitas/ObtenerGenerico/CatFormasPagoDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Aplicacion_SOA_Qualitas/ObtenerGenerico/CatFormasPagoDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CatFormasPagoDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CatFormasPagoDB_plt" >
    <plt:role name="CatFormasPagoDB_role" >
      <plt:portType name="tns:CatFormasPagoDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CatFormasPagoDB" schemaLocation="../Schemas/CatFormasPagoDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CatFormasPagoDBSelect_inputParameters">
        <wsdl:part name="CatFormasPagoDBSelect_inputParameters" element="top:CatFormasPagoDBSelectInputParameters"/>
    </wsdl:message>
    <wsdl:message name="Gpa025FormasPagoCollection_msg">
        <wsdl:part name="Gpa025FormasPagoCollection" element="top:Gpa025FormasPagoCollection"/>
    </wsdl:message>
    <wsdl:portType name="CatFormasPagoDB_ptt">
        <wsdl:operation name="CatFormasPagoDBSelect">
            <wsdl:input message="tns:CatFormasPagoDBSelect_inputParameters"/>
            <wsdl:output message="tns:Gpa025FormasPagoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
