<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CatTipoServicioDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/CatTipoServicioDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/CatTipoServicioDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CatTipoServicioDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="CatTipoServicioDB_plt">
      <plt:role name="CatTipoServicioDB_role">
         <plt:portType name="tns:CatTipoServicioDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CatTipoServicioDB" schemaLocation="../Schemas/CatTipoServicioDB.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CatTipoServicioDBInput_msg">
      <wsdl:part name="CatTipoServicioDBInput_msg" element="db:CatTipoServicioDBInput"/>
   </wsdl:message>
   <wsdl:message name="CatTipoServicioDBOutputCollection_msg">
      <wsdl:part name="CatTipoServicioDBOutputCollection" element="db:CatTipoServicioDBOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="CatTipoServicioDB_ptt">
      <wsdl:operation name="CatTipoServicioDB">
         <wsdl:input message="tns:CatTipoServicioDBInput_msg"/>
         <wsdl:output message="tns:CatTipoServicioDBOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
