<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:web="http://webservices.wscatalogos.qualitas.com/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/BORRAR/ObtenerPrestador/ObtenerPretadorProcess" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/ObtenerPretadorProcess.wsdl"/>
                <oracle-xsl-mapper:rootElement name="process" namespace="http://xmlns.oracle.com/BORRAR/ObtenerPrestador/ObtenerPretadorProcess"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="WSDL">
                <oracle-xsl-mapper:schema location="../WSDLs/catalogosService_wsdl_CatalogosService.wsdl"/>
                <oracle-xsl-mapper:rootElement name="getRegistros" namespace="http://webservices.wscatalogos.qualitas.com/"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI AUG 11 17:45:52 CDT 2017].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <web:getRegistros>
            <web:tabla>MPRES</web:tabla>
            <web:columnas>claveProveedor</web:columnas>
            <web:columnas>Status</web:columnas>
            <web:columnas>descProveedor</web:columnas>
            <web:columnas>rfc</web:columnas>
            <web:columnas>claveEstado</web:columnas>
            <web:columnas>descTipoPersona</web:columnas>
            <web:columnas>tipoPersona</web:columnas>
            <web:parametros>
                <web:campo>claveProveedor</web:campo>
                <web:operador>=</web:operador>
                <web:valores>
                    <xsl:value-of select="/ns0:process/ns0:numeroPrestador"/>
                </web:valores>
            </web:parametros>
        </web:getRegistros>
    </xsl:template>
</xsl:stylesheet>