<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="OrdenPagoProrrateo" targetNamespace="http://xmlns.oracle.com/GestionOrdenPagoApp/OrdenPagoProrrateoPrj/OrdenPagoProrrateo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/GestionOrdenPagoApp/OrdenPagoProrrateoPrj/OrdenPagoProrrateo" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/GestionOrdenPagoApp/OrdenPagoProrrateoPrj/OrdenPagoProrrateo" schemaLocation="../Schemas/OrdenPagoProrrateo.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="OrdenPagoProrrateoRequestMessage">
      <wsdl:part name="payload" element="client:process"/>
   </wsdl:message>
   <wsdl:message name="OrdenPagoProrrateoResponseMessage">
      <wsdl:part name="payload" element="client:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="OrdenPagoProrrateo">
      <wsdl:operation name="process">
         <wsdl:input message="client:OrdenPagoProrrateoRequestMessage"/>
         <wsdl:output message="client:OrdenPagoProrrateoResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="OrdenPagoProrrateo">
      <plnk:role name="OrdenPagoProrrateoProvider" portType="client:OrdenPagoProrrateo"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
