<wsdl:definitions name="ValidarCentroDeCostosBPEL" targetNamespace="http://qualitas.com.mx/ValidarCentroDeCostosApp/ValidarCentrosDeCostosPrj/ValidarCentroDeCostosBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ValidarCentroDeCostosApp/ValidarCentrosDeCostosPrj/ValidarCentroDeCostosBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/CentroCostos/validarCentroCostos/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.22:7007/soa-infra/services/GPADomain/ValidarCentroDeCostoPrj!1.0/WSDLs/ValidarCentroDeCostosBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ValidarCentroDeCostosBPEL">
        <plnk:role name="ValidarCentroDeCostosBPELProvider" portType="client:ValidarCentroDeCostosBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/Comun/CentroCostos/validarCentroCostos/v1/" schemaLocation="XMLSchema_-2132380513.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ValidarCentroDeCostosBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:ValidarCentroCostosRequest"/>
    </wsdl:message>
    <wsdl:message name="ValidarCentroDeCostosBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:ValidarCentroCostosResponse"/>
    </wsdl:message>
    <wsdl:portType name="ValidarCentroDeCostosBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ValidarCentroDeCostosBPELRequestMessage"/>
            <wsdl:output message="client:ValidarCentroDeCostosBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ValidarCentroDeCostosBPELBinding" type="client:ValidarCentroDeCostosBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="validarcentrodecostosbpel_client_ep">
        <wsdl:port name="ValidarCentroDeCostosBPEL_pt" binding="client:ValidarCentroDeCostosBPELBinding">
            <soap:address location="http://11.50.0.22:7007/soa-infra/services/GPADomain/ValidarCentroDeCostoPrj/validarcentrodecostosbpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>