<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="TestConcat" targetNamespace="http://xmlns.oracle.com/QualitasGPA/TestConcat/TestConcat" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/QualitasGPA/TestConcat/TestConcat" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/QualitasGPA/TestConcat/TestConcat" schemaLocation="../Schemas/TestConcat.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="TestConcatRequestMessage">
      <wsdl:part name="payload" element="client:process"/>
   </wsdl:message>
   <wsdl:message name="TestConcatResponseMessage">
      <wsdl:part name="payload" element="client:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="TestConcat">
      <wsdl:operation name="process">
         <wsdl:input message="client:TestConcatRequestMessage"/>
         <wsdl:output message="client:TestConcatResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="TestConcat">
      <plnk:role name="TestConcatProvider" portType="client:TestConcat"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
