<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="DBDocumento" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_INT/ordenPagoProrrateoBPEL/DBDocumento" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA_INT/ordenPagoProrrateoBPEL/DBDocumento" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DBDocumento" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="DBDocumento_plt">
      <plt:role name="DBDocumento_role">
         <plt:portType name="tns:DBDocumento_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBDocumento" schemaLocation="../Schemas/DBDocumento.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="DBDocumentoInput_msg">
      <wsdl:part name="DBDocumentoInput_msg" element="db:DBDocumentoInput"/>
   </wsdl:message>
   <wsdl:message name="DBDocumentoOutputCollection_msg">
      <wsdl:part name="DBDocumentoOutputCollection" element="db:DBDocumentoOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="DBDocumento_ptt">
      <wsdl:operation name="DBDocumento">
         <wsdl:input message="tns:DBDocumentoInput_msg"/>
         <wsdl:output message="tns:DBDocumentoOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
