<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ProrrateoSvc" targetNamespace="http://ws.gpa.qualitas.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://ws.gpa.qualitas.mx/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ParseoDocService">
      <plnk:role name="ProrrateoSvc" portType="tns:ProrrateoSvc"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://ws.gpa.qualitas.mx/" location="http://11.50.0.21:8001/GPACommonsBasic/ProrrateoSvcPort?WSDL"/>
</wsdl:definitions>
