<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tempuri.org/" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:ns1="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity.DataContract" xmlns:ns2="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity" xmlns:ns3="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity.Modelos" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:ns5="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Persona" xmlns:ns4="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/OrdenesTrabajo" xmlns:ns6="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns7="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Cliente">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
         <oracle-xsl-mapper:schema location="../Schemas/NMPSvcOrdenesTrabajoElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="realizarPreregistroOrdenRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/CRMGestionesElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="CapturaPreRegistro" namespace="http://tempuri.org/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU NOV 26 15:44:23 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:CapturaPreRegistro>
      <tns:request>
      <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:apellidoMaterno">
        <ns1:ApellidoMaterno>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:apellidoMaterno"/>
        </ns1:ApellidoMaterno>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:apellidoPaterno">
        <ns1:ApellidoPaterno>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:apellidoPaterno"/>
        </ns1:ApellidoPaterno>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:nombreDeLaCalle">
        <ns1:Calle>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:nombreDeLaCalle"/>
        </ns1:Calle>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:codigoPostal">
        <ns1:CodigoPostal>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:codigoPostal"/>
        </ns1:CodigoPostal>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:colonia">
        <ns1:Colonia>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:colonia"/>
        </ns1:Colonia>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:email">
        <ns1:Correo>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:email"/>
        </ns1:Correo>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:delegacionMunicipio">
        <ns1:DelegacionMunicipio>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:delegacionMunicipio"/>
        </ns1:DelegacionMunicipio>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:descripcion">
        <ns1:Descripcion>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:descripcion"/>
        </ns1:Descripcion>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:estado">
        <ns1:Estado>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:estado"/>
        </ns1:Estado>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:evento">
        <ns1:Evento>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:evento"/>
        </ns1:Evento>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:fechaDeNacimiento">
        <ns1:FechaNacimiento>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:fechaDeNacimiento"/>
        </ns1:FechaNacimiento>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:genero">
        <ns1:Genero>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:genero"/>
        </ns1:Genero>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Telefonos/ns4:Telefono/ns4:codigoArea">
        <ns1:Lada>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Telefonos/ns4:Telefono/ns4:codigoArea"/>
        </ns1:Lada>
        </xsl:if>
        <ns1:Latitud>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:DatosTransaccion/ns4:DatosGeoespaciales/ns4:latitudFinal"/>
        </ns1:Latitud>
        <ns1:Longitud>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:DatosTransaccion/ns4:DatosGeoespaciales/ns4:longitudFinal"/>
        </ns1:Longitud>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:primerNombre">
        <ns1:Nombre>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:primerNombre"/>
        </ns1:Nombre>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:numeroExterior">
        <ns1:NumeroExterior>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:numeroExterior"/>
        </ns1:NumeroExterior>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:numeroInterior">
        <ns1:NumeroInterior>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Direccion/ns4:numeroInterior"/>
        </ns1:NumeroInterior>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:idOrigen">
          <ns1:Origen>
            <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:idOrigen"/>
          </ns1:Origen>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Telefonos/ns4:Telefono/ns4:numeroTelefonico">
        <ns1:Telefono>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Telefonos/ns4:Telefono/ns4:numeroTelefonico"/>
        </ns1:Telefono>
        </xsl:if>
        <xsl:if test="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Telefonos/ns4:Telefono/ns4:tipoTelefono">
        <ns1:TipoTelefono>
          <xsl:value-of select="/ns0:realizarPreregistroOrdenRequest/ns4:Preregistro/ns4:ContactoDomicilio/ns4:Telefonos/ns4:Telefono/ns4:tipoTelefono"/>
        </ns1:TipoTelefono>
        </xsl:if>
        <ns1:UserName>
          <xsl:value-of select="concat('nmp/',/ns0:realizarPreregistroOrdenRequest/ns4:DatosTransaccion/ns4:promotorAsignado)"/>
        </ns1:UserName>
      </tns:request>
    </tns:CapturaPreRegistro>
  </xsl:template>
</xsl:stylesheet>