<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsCotizacionWSDL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ZlmRfcCotizacionResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPCreditoSvcElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="obtenerTablaAmortizacionResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI MAR 03 17:16:33 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:obtenerTablaAmortizacionResponse>
         <xsl:for-each select="/ns0:ZlmRfcCotizacionResponse/TablaAmort/item">
            <tns:pago>
               <tns:numeroPago>
                  <xsl:value-of select="Nopago"/>
               </tns:numeroPago>
               <tns:fecha>
                  <xsl:value-of select="Fecha"/>
               </tns:fecha>
               <tns:capitalInicial>
                  <xsl:value-of select="Capitalinit"/>
               </tns:capitalInicial>
               <tns:interes>
                  <xsl:value-of select="Interes"/>
               </tns:interes>
               <tns:iva>
                  <xsl:value-of select="Iva"/>
               </tns:iva>
               <tns:abonoCapital>
                  <xsl:value-of select="Abonocapital"/>
               </tns:abonoCapital>
               <tns:abonoTotal>
                  <xsl:value-of select="Abonototal"/>
               </tns:abonoTotal>
               <tns:capitalFinal>
                  <xsl:value-of select="Capitalfinal"/>
               </tns:capitalFinal>
               <tns:saldoPagare>
                  <xsl:value-of select="Saldopagare"/>
               </tns:saldoPagare>
            </tns:pago>
         </xsl:for-each>
      </tns:obtenerTablaAmortizacionResponse>
   </xsl:template>
</xsl:stylesheet>