<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl soap wsdl mime n1 wsp http xsd wsu tns NMPCred xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:NMPCred="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsSimulaPagoWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmRfcSimulaPagoResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPCreditoSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="simularPagosResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON AUG 01 12:20:45 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <NMPCred:simularPagosResponse>
      <NMPCred:SaldosSimulado>
        <NMPCred:producto>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/Producto"/>
        </NMPCred:producto>
        <NMPCred:moneda>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/Moneda"/>
        </NMPCred:moneda>
        <NMPCred:desembolso>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/Desembolso"/>
        </NMPCred:desembolso>
        <NMPCred:capitalVigente>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/CapVig"/>
        </NMPCred:capitalVigente>
        <NMPCred:capitalVencido>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/CapVen"/>
        </NMPCred:capitalVencido>
        <NMPCred:saldoVigente>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/SaldoVig"/>
        </NMPCred:saldoVigente>
        <NMPCred:saldoVencido>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/SaldoVen"/>
        </NMPCred:saldoVencido>
        <NMPCred:saldoCapital>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/SaldoCap"/>
        </NMPCred:saldoCapital>
        <NMPCred:interesVigente>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/IntVig"/>
        </NMPCred:interesVigente>
        <NMPCred:interesVencido>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/IntVen"/>
        </NMPCred:interesVencido>
        <NMPCred:saldoInteres>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/SaldoInt"/>
        </NMPCred:saldoInteres>
        <NMPCred:saldoComision>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/SaldoCom"/>
        </NMPCred:saldoComision>
        <NMPCred:pagosNoAplicados>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/PagosNoAplicados"/>
        </NMPCred:pagosNoAplicados>
        <NMPCred:saldoLiquida>
          <xsl:value-of select="/tns:ZlmRfcSimulaPagoResponse/SaldosSimulados/SaldoLiquida"/>
        </NMPCred:saldoLiquida>
      </NMPCred:SaldosSimulado>
      <NMPCred:TablaAmortizacion>
        <xsl:for-each select="/tns:ZlmRfcSimulaPagoResponse/Amortizacion/item">
          <NMPCred:Amortizacion>
            <NMPCred:numeroPago>
              <xsl:value-of select="NumPago"/>
            </NMPCred:numeroPago>
            <NMPCred:fechaPago>
              <xsl:value-of select="FechaPago"/>
            </NMPCred:fechaPago>
            <NMPCred:pagoTotal>
              <xsl:value-of select="PagoTotal"/>
            </NMPCred:pagoTotal>
            <NMPCred:capital>
              <xsl:value-of select="Capital"/>
            </NMPCred:capital>
            <NMPCred:interes>
              <xsl:value-of select="Interes"/>
            </NMPCred:interes>
            <NMPCred:IVAInteres>
              <xsl:value-of select="IvaInteres"/>
            </NMPCred:IVAInteres>
            <NMPCred:saldoCapital>
              <xsl:value-of select="SaldoCapital"/>
            </NMPCred:saldoCapital>
            <NMPCred:saldoInteres>
              <xsl:value-of select="SaldoInteres"/>
            </NMPCred:saldoInteres>
          </NMPCred:Amortizacion>
        </xsl:for-each>
      </NMPCred:TablaAmortizacion>
    </NMPCred:simularPagosResponse>
  </xsl:template>
</xsl:stylesheet>