<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl soap mime wsdl n1 wsp http xsd wsu tns NMPCred xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:NMPCred="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsInfoCredBpWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmRfcInfoCredBpResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPCreditoSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getInfoCreditoResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI NOV 20 19:44:51 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <NMPCred:getInfoCreditoResponse>
      <NMPCred:Cliente>
        <NMPCred:idCliente>
          <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/NumCliente"/>
        </NMPCred:idCliente>
        <NMPCred:nombre>
          <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/NombreCliente"/>
        </NMPCred:nombre>
      </NMPCred:Cliente>
      <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos">
        <NMPCred:Saldo>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/Producto">
            <NMPCred:producto>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/Producto"/>
            </NMPCred:producto>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/Moneda">
            <NMPCred:moneda>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/Moneda"/>
            </NMPCred:moneda>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/Desembolso">
            <NMPCred:desembolso>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/Desembolso"/>
            </NMPCred:desembolso>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/CapVig">
            <NMPCred:capitalVigente>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/CapVig"/>
            </NMPCred:capitalVigente>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/CapVen">
            <NMPCred:capitalVencido>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/CapVen"/>
            </NMPCred:capitalVencido>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoVig">
            <NMPCred:saldoVigente>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoVig"/>
            </NMPCred:saldoVigente>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoVen">
            <NMPCred:saldoVencido>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoVen"/>
            </NMPCred:saldoVencido>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoCap">
            <NMPCred:saldoCapital>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoCap"/>
            </NMPCred:saldoCapital>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/IntVig">
            <NMPCred:interesVigente>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/IntVig"/>
            </NMPCred:interesVigente>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/IntVen">
            <NMPCred:interesVencido>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/IntVen"/>
            </NMPCred:interesVencido>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoInt">
            <NMPCred:saldoInteres>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoInt"/>
            </NMPCred:saldoInteres>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoCom">
            <NMPCred:saldoComision>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/SaldoCom"/>
            </NMPCred:saldoComision>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/PagosNoAplicados">
            <NMPCred:pagosNoAplicados>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Saldos/item/PagosNoAplicados"/>
            </NMPCred:pagosNoAplicados>
          </xsl:if>
        </NMPCred:Saldo>
      </xsl:if>
      <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes">
        <NMPCred:Solicitud>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/ClaveProducto">
            <NMPCred:cveProducto>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/ClaveProducto"/>
            </NMPCred:cveProducto>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/DescripcionEstatus">
            <NMPCred:estatus>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/DescripcionEstatus"/>
            </NMPCred:estatus>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Subestatus">
            <NMPCred:subEstatus>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Subestatus"/>
            </NMPCred:subEstatus>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Pendiente">
            <NMPCred:pendiente>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Pendiente"/>
            </NMPCred:pendiente>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/MotivoPendiente">
            <NMPCred:motivoPendiente>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/MotivoPendiente"/>
            </NMPCred:motivoPendiente>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/EstatusPago">
            <NMPCred:estatusPago>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/EstatusPago"/>
            </NMPCred:estatusPago>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/EstatusAnterior">
            <NMPCred:estatusAnterior>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/EstatusAnterior"/>
            </NMPCred:estatusAnterior>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaSolicitud">
            <NMPCred:fechaSolicitud>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaSolicitud"/>
            </NMPCred:fechaSolicitud>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaSuscripcion">
            <NMPCred:fechaSuscripcion>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaSuscripcion"/>
            </NMPCred:fechaSuscripcion>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/TiempoAprob">
            <NMPCred:tiempoAprobacion>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/TiempoAprob"/>
            </NMPCred:tiempoAprobacion>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaAutorizacion">
            <NMPCred:fechaAutorizacion>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaAutorizacion"/>
            </NMPCred:fechaAutorizacion>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaDesembolso">
            <NMPCred:fechaDesembolso>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/FechaDesembolso"/>
            </NMPCred:fechaDesembolso>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Fecha1erPago">
            <NMPCred:fechaPrimerPago>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Fecha1erPago"/>
            </NMPCred:fechaPrimerPago>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Destino">
            <NMPCred:destino>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Destino"/>
            </NMPCred:destino>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/HoraCita">
            <NMPCred:horaCita>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/HoraCita"/>
            </NMPCred:horaCita>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/GerenteSucursal">
            <NMPCred:gerenteSucursal>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/GerenteSucursal"/>
            </NMPCred:gerenteSucursal>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Desembolso">
            <NMPCred:desembolso>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Desembolso"/>
            </NMPCred:desembolso>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Moneda">
            <NMPCred:moneda>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Moneda"/>
            </NMPCred:moneda>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Frecuencia">
            <NMPCred:frecuencia>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/Frecuencia"/>
            </NMPCred:frecuencia>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/NumeroDePagos">
            <NMPCred:numPagos>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Solicitudes/item/NumeroDePagos"/>
            </NMPCred:numPagos>
          </xsl:if>
        </NMPCred:Solicitud>
      </xsl:if>
      <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta">
        <NMPCred:GestionVenta>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/Estatus">
            <NMPCred:estatus>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/Estatus"/>
            </NMPCred:estatus>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/FechaCreacion">
            <NMPCred:fechaCreacion>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/FechaCreacion"/>
            </NMPCred:fechaCreacion>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/Promotor">
            <NMPCred:promotor>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/Promotor"/>
            </NMPCred:promotor>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/VisitaVentas">
            <NMPCred:resultadoVisitaVentas>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/VisitaVentas"/>
            </NMPCred:resultadoVisitaVentas>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/GestionVentas">
            <NMPCred:gestionVentas>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/GestionVentas"/>
            </NMPCred:gestionVentas>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/VisitaVentas2">
            <NMPCred:resultadoVisitaVentas2>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/VisitaVentas2"/>
            </NMPCred:resultadoVisitaVentas2>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/GestionTransmision">
            <NMPCred:gestionTransmision>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/GestionVenta/item/GestionTransmision"/>
            </NMPCred:gestionTransmision>
          </xsl:if>
        </NMPCred:GestionVenta>
      </xsl:if>
      <NMPCred:TablaAmortizacion>
        <xsl:for-each select="/tns:ZlmRfcInfoCredBpResponse/Amortizaciones/item">
          <NMPCred:Amortizacion>
            <NMPCred:numeroPago>
              <xsl:value-of select="NumPago"/>
            </NMPCred:numeroPago>
            <NMPCred:fechaPago>
              <xsl:value-of select="FechaPago"/>
            </NMPCred:fechaPago>
            <NMPCred:pagoTotal>
              <xsl:value-of select="PagoTotal"/>
            </NMPCred:pagoTotal>
            <NMPCred:capital>
              <xsl:value-of select="Capital"/>
            </NMPCred:capital>
            <NMPCred:interes>
              <xsl:value-of select="Interes"/>
            </NMPCred:interes>
            <NMPCred:IVAInteres>
              <xsl:value-of select="IvaInteres"/>
            </NMPCred:IVAInteres>
            <NMPCred:saldoCapital>
              <xsl:value-of select="SaldoCapital"/>
            </NMPCred:saldoCapital>
            <NMPCred:saldoInteres>
              <xsl:value-of select="SaldoInteres"/>
            </NMPCred:saldoInteres>
          </NMPCred:Amortizacion>
        </xsl:for-each>
      </NMPCred:TablaAmortizacion>
      <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion">
        <NMPCred:ProyeccionPago>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/Santwhr">
            <NMPCred:moneda>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/Santwhr"/>
            </NMPCred:moneda>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SActual">
            <NMPCred:saldoActual>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SActual"/>
            </NMPCred:saldoActual>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/FCorte">
            <NMPCred:fechaCorte1>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/FCorte"/>
            </NMPCred:fechaCorte1>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SCorte">
            <NMPCred:saldoCorte1>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SCorte"/>
            </NMPCred:saldoCorte1>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/FCorte2">
            <NMPCred:fechaCorte2>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/FCorte2"/>
            </NMPCred:fechaCorte2>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SCorte2">
            <NMPCred:saldoCorte2>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SCorte2"/>
            </NMPCred:saldoCorte2>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SCorte3">
            <NMPCred:fechaCorte3>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/FCorte3"/>
            </NMPCred:fechaCorte3>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/FCorte3">
            <NMPCred:saldoCorte3>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Proyeccion/item/SCorte3"/>
            </NMPCred:saldoCorte3>
          </xsl:if>
        </NMPCred:ProyeccionPago>
      </xsl:if>
      <NMPCred:PartidasAbiertas>
        <xsl:for-each select="/tns:ZlmRfcInfoCredBpResponse/PartidasAbiertas/item">
          <NMPCred:PartidaAbierta>
            <NMPCred:fechaValor>
              <xsl:value-of select="FechaValor"/>
            </NMPCred:fechaValor>
            <NMPCred:fechaContable>
              <xsl:value-of select="FechaContable"/>
            </NMPCred:fechaContable>
            <NMPCred:moneda>
              <xsl:value-of select="Moneda"/>
            </NMPCred:moneda>
            <NMPCred:monto>
              <xsl:value-of select="Monto"/>
            </NMPCred:monto>
            <NMPCred:descripcion>
              <xsl:value-of select="Descripcion"/>
            </NMPCred:descripcion>
          </NMPCred:PartidaAbierta>
        </xsl:for-each>
      </NMPCred:PartidasAbiertas>
      <NMPCred:Vencimientos>
        <xsl:for-each select="/tns:ZlmRfcInfoCredBpResponse/Vencimientos/item">
          <NMPCred:Vencimiento>
            <NMPCred:fechaVencimiento>
              <xsl:value-of select="FechaVencimiento"/>
            </NMPCred:fechaVencimiento>
            <NMPCred:planeado-real>
              <xsl:value-of select="PlaneadoReal"/>
            </NMPCred:planeado-real>
            <NMPCred:interes>
              <xsl:value-of select="Interes"/>
            </NMPCred:interes>
            <NMPCred:otros>
              <xsl:value-of select="Otros"/>
            </NMPCred:otros>
            <NMPCred:IVAInteres>
              <xsl:value-of select="IvaInteres"/>
            </NMPCred:IVAInteres>
            <NMPCred:importe>
              <xsl:value-of select="Importe"/>
            </NMPCred:importe>
            <NMPCred:moneda>
              <xsl:value-of select="Moneda"/>
            </NMPCred:moneda>
            <NMPCred:concepto>
              <xsl:value-of select="Concepto"/>
            </NMPCred:concepto>
          </NMPCred:Vencimiento>
        </xsl:for-each>
      </NMPCred:Vencimientos>
      <NMPCred:Pagos>
        <xsl:for-each select="/tns:ZlmRfcInfoCredBpResponse/Pagos/item">
          <NMPCred:Pago>
            <NMPCred:fechaPago>
              <xsl:value-of select="FechaPago"/>
            </NMPCred:fechaPago>
            <NMPCred:capital>
              <xsl:value-of select="Capital"/>
            </NMPCred:capital>
            <NMPCred:interes>
              <xsl:value-of select="Interes"/>
            </NMPCred:interes>
            <NMPCred:otros>
              <xsl:value-of select="Otros"/>
            </NMPCred:otros>
            <NMPCred:iva>
              <xsl:value-of select="Iva"/>
            </NMPCred:iva>
            <NMPCred:importe>
              <xsl:value-of select="Importe"/>
            </NMPCred:importe>
            <NMPCred:moneda>
              <xsl:value-of select="Moneda"/>
            </NMPCred:moneda>
            <NMPCred:concepto>
              <xsl:value-of select="Concepto"/>
            </NMPCred:concepto>
          </NMPCred:Pago>
        </xsl:for-each>
      </NMPCred:Pagos>
      <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Moratorios">
        <NMPCred:ProyeccionMoratorios>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Monto">
            <NMPCred:monto>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Monto"/>
            </NMPCred:monto>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Tasa">
            <NMPCred:tasa>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Tasa"/>
            </NMPCred:tasa>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Dias">
            <NMPCred:dias>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Dias"/>
            </NMPCred:dias>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/ImporteBase">
            <NMPCred:importeBase>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/ImporteBase"/>
            </NMPCred:importeBase>
          </xsl:if>
          <xsl:if test="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Texto">
            <NMPCred:texto>
              <xsl:value-of select="/tns:ZlmRfcInfoCredBpResponse/Moratorios/item/Texto"/>
            </NMPCred:texto>
          </xsl:if>
        </NMPCred:ProyeccionMoratorios>
      </xsl:if>
    </NMPCred:getInfoCreditoResponse>
  </xsl:template>
</xsl:stylesheet>