<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl soap mime wsdl n1 wsp http xsd wsu tns NMPCred xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:NMPCred="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsConsultaSaldosWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmRfcConsultaSaldosResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPCreditoSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getSaldosResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI NOV 20 19:46:38 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <NMPCred:getSaldosResponse>
      <xsl:for-each select="/tns:ZlmRfcConsultaSaldosResponse/Saldos/item">
        <NMPCred:Saldo>
          <NMPCred:contrato>
            <xsl:value-of select="Contrato"/>
          </NMPCred:contrato>
          <NMPCred:producto>
            <xsl:value-of select="Producto"/>
          </NMPCred:producto>
          <NMPCred:moneda>
            <xsl:value-of select="Moneda"/>
          </NMPCred:moneda>
          <NMPCred:desembolso>
            <xsl:value-of select="Desembolso"/>
          </NMPCred:desembolso>
          <NMPCred:capitalVigente>
            <xsl:value-of select="CapVig"/>
          </NMPCred:capitalVigente>
          <NMPCred:capitalVencido>
            <xsl:value-of select="CapVen"/>
          </NMPCred:capitalVencido>
          <NMPCred:saldoVigente>
            <xsl:value-of select="SaldoVig"/>
          </NMPCred:saldoVigente>
          <NMPCred:saldoVencido>
            <xsl:value-of select="SaldoVen"/>
          </NMPCred:saldoVencido>
          <NMPCred:saldoCapital>
            <xsl:value-of select="SaldoCap"/>
          </NMPCred:saldoCapital>
          <NMPCred:interesVigente>
            <xsl:value-of select="IntVig"/>
          </NMPCred:interesVigente>
          <NMPCred:interesVencido>
            <xsl:value-of select="IntVen"/>
          </NMPCred:interesVencido>
          <NMPCred:saldoInteres>
            <xsl:value-of select="SaldoInt"/>
          </NMPCred:saldoInteres>
          <NMPCred:saldoComision>
            <xsl:value-of select="SaldoCom"/>
          </NMPCred:saldoComision>
          <NMPCred:pagosNoAplicados>
            <xsl:value-of select="PagosNoAplicados"/>
          </NMPCred:pagosNoAplicados>
          <NMPCred:saldoLiquidar>
            <xsl:value-of select="SaldoLiquidar"/>
          </NMPCred:saldoLiquidar>
        </NMPCred:Saldo>
      </xsl:for-each>
    </NMPCred:getSaldosResponse>
  </xsl:template>
</xsl:stylesheet>