<wsdl:definitions name="CatalogosServiceImplService" targetNamespace="http://webservicesImpl.wscatalogos.qualitas.com/" xmlns:ns1="http://webservices.wscatalogos.qualitas.com/" xmlns:ns2="http://cxf.apache.org/bindings/xformat" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservicesImpl.wscatalogos.qualitas.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="WSDL_2108267467.wsdl" namespace="http://webservices.wscatalogos.qualitas.com/">
    </wsdl:import>
  <wsdl:binding name="CatalogosServiceImplServiceSoapBinding" type="ns1:CatalogosService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getRegistros">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getRegistros">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getRegistrosResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CatalogosServiceImplService">
    <wsdl:port binding="tns:CatalogosServiceImplServiceSoapBinding" name="CatalogosServiceImplPort">
      <soap:address location="http://110.10.0.57:8070/wsCatalogos/catalogosService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>