<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPIdentidades" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/NSchema/NMPIdentidades" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/OAMPerfilesRestNXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="PerfilResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/NSchema/NMPIdentidades"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPGestionIdentidades.xsd"/>
            <oracle-xsl-mapper:rootElement name="ObtenerRolesAutorizadosResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPIdentidades"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SUN MAY 28 13:35:29 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ObtenerRolesAutorizadosResponse>
         <tns:roles>
            <xsl:for-each select="/ns0:PerfilResponse/ns0:memberof">
              
               <tns:rol>
                  <tns:nombre>
                     <xsl:value-of select="."/>
                  </tns:nombre>
               </tns:rol>
            </xsl:for-each>
         </tns:roles>
      </tns:ObtenerRolesAutorizadosResponse>
   </xsl:template>
   <!-- manipular cadena memerOf Ejmplo: "CN=Gerente Credito Autoavanza,OU=Auto Sin Resguardo,OU=Grupos Control Acceso,OU=Infraestructura,DC=1775ad,DC=com,DC=mx"-->
    <xsl:template name="memberOf">
        <xsl:param name="memberOf"/>
        <ns0:memberofComplex>
          <xsl:for-each select="xsl:tokenize(.,',')">
            <xsl:element name="CN">
                <xsl:value-of select="."/>
            </xsl:element>
        </xsl:for-each>
        </ns0:memberofComplex>
        </xsl:template>
        
</xsl:stylesheet>