<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Common/XSD/NMPStandardHeader.xsd"/>
        <oracle-xsl-mapper:rootElement name="headerMessage" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Common/XSD/NMPStandardHeader.xsd"/>
        <oracle-xsl-mapper:rootElement name="headerMessageResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI DEC 02 14:40:50 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="codigoRespuesta"/>
  <xsl:template match="/">
    <ns0:headerMessageResponse>
      <ns0:usuario>
        <xsl:value-of select="/ns0:headerMessage/ns0:usuario"/>
      </ns0:usuario>
      <ns0:idConsumidor>
        <xsl:value-of select="/ns0:headerMessage/ns0:idConsumidor"/>
      </ns0:idConsumidor>
      <ns0:idDestino>
        <xsl:value-of select="/ns0:headerMessage/ns0:idDestino"/>
      </ns0:idDestino>
      <ns0:codigoRespuesta>
        <xsl:value-of select="$codigoRespuesta"/>
      </ns0:codigoRespuesta>
      <ns0:descripcionRespuesta>
        <xsl:call-template name="descripcionRespuesta">
          <xsl:with-param name="codigo" select="$codigoRespuesta"/>
        </xsl:call-template>
      </ns0:descripcionRespuesta>
    </ns0:headerMessageResponse>
  </xsl:template>
    <xsl:template name="descripcionRespuesta">
    <xsl:param name="codigo"/>
    <xsl:choose>
      <xsl:when test="$codigo=0">Registro del cliente exitoso</xsl:when>
      <xsl:when test="$codigo=800">Ocurrió un problema en la validacion del schema</xsl:when>
      <xsl:when test="$codigo=801">El usuario ya se encuentra registrado en la BD</xsl:when>
      <xsl:when test="$codigo=802">El sms no fue enviado</xsl:when>
      <xsl:otherwise>Generic Server Fault</xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>