<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ObtenerArchivoProrrateoBPEL" targetNamespace="http://xmlns.oracle.com/ObtenerArchivoProrrateo/ObtenerArchivoProrrateoPrj/ObtenerArchivoProrrateoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ObtenerArchivoProrrateo/ObtenerArchivoProrrateoPrj/ObtenerArchivoProrrateoBPEL" xmlns:ns1="http://qualitas.com.mx/Comunes/Prorrateo/obtenerArchivoProrrateo/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comunes/Prorrateo/obtenerArchivoProrrateo/v1/" schemaLocation="../Schemas/ObtenerArchivoProrrateo.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ObtenerArchivoProrrateoBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:processRequest"/>
   </wsdl:message>
   <wsdl:message name="ObtenerArchivoProrrateoBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="ObtenerArchivoProrrateoBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ObtenerArchivoProrrateoBPELRequestMessage"/>
         <wsdl:output message="client:ObtenerArchivoProrrateoBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ObtenerArchivoProrrateoBPEL">
      <plnk:role name="ObtenerArchivoProrrateoBPELProvider" portType="client:ObtenerArchivoProrrateoBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
