<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/GestorTransacciones/GestorTransacciones" name="GestorTransacciones-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="GestorTransacciones.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/GestorTransacciones/GestorTransacciones"/>
    <wsdl:binding name="GestorTransacciones_ptt-binding" type="ges:GestorTransacciones_ptt" xmlns:ges="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/GestorTransacciones/GestorTransacciones">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="delete">
            <soap:operation soapAction="delete"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="GestorTransaccionesSelect">
            <soap:operation soapAction="GestorTransaccionesSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>