<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="OrdenPagoProrrateoBPEL" targetNamespace="http://xmlns.oracle.com/SOA_INT/ordenPagoProrrateoBPEL/OrdenPagoProrrateoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/SOA_INT/ordenPagoProrrateoBPEL/OrdenPagoProrrateoBPEL" xmlns:ns1="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/" schemaLocation="../Schemas/ordenPagoProrrateo.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="OrdenPagoProrrateoBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:ordenPagProrrateoRequest"/>
   </wsdl:message>
   <wsdl:message name="OrdenPagoProrrateoBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:ordenPagProrrateoResponse"/>
   </wsdl:message>
   <wsdl:portType name="OrdenPagoProrrateoBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:OrdenPagoProrrateoBPELRequestMessage"/>
         <wsdl:output message="client:OrdenPagoProrrateoBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="OrdenPagoProrrateoBPEL">
      <plnk:role name="OrdenPagoProrrateoBPELProvider" portType="client:OrdenPagoProrrateoBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
