<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultaMotivoRech" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPM-QUALITAS-PAGOS_ADMINISTRATIVOS/BpmPagosAdministrativos/ConsultaMotivoRech" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BPM-QUALITAS-PAGOS_ADMINISTRATIVOS/BpmPagosAdministrativos/ConsultaMotivoRech" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaMotivoRech" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="ConsultaMotivoRech_plt">
      <plt:role name="ConsultaMotivoRech_role">
         <plt:portType name="tns:ConsultaMotivoRech_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaMotivoRech" schemaLocation="../Schemas/ConsultaMotivoRech.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ConsultaMotivoRechInput_msg">
      <wsdl:part name="ConsultaMotivoRechInput_msg" element="db:ConsultaMotivoRechInput"/>
   </wsdl:message>
   <wsdl:message name="ConsultaMotivoRechOutputCollection_msg">
      <wsdl:part name="ConsultaMotivoRechOutputCollection" element="db:ConsultaMotivoRechOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="ConsultaMotivoRech_ptt">
      <wsdl:operation name="ConsultaMotivoRech">
         <wsdl:input message="tns:ConsultaMotivoRechInput_msg"/>
         <wsdl:output message="tns:ConsultaMotivoRechOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
