<wsdl:definitions targetNamespace="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:n1="urn:sap-com:document:sap:rfc:functions">
  <wsdl:documentation>
<sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>
</wsdl:documentation>
  <wsp:UsingPolicy wsdl:required="true"/>
  <wsp:Policy wsu:Id="BN_ZLM_WS_INFO_CONTACTO_BP">
    <wsaw:UsingAddressing xmlns:wsaw="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
    <saptrnbnd:OptimizedXMLTransfer uri="http://xml.sap.com/2006/11/esi/esp/binxml" wsp:Optional="true" xmlns:saptrnbnd="http://www.sap.com/webas/710/soap/features/transportbinding/"/>
    <sapattahnd:Enabled xmlns:sapattahnd="http://www.sap.com/710/features/attachment/">false</sapattahnd:Enabled>
    <wsp:ExactlyOne xmlns:sapsp="http://www.sap.com/webas/630/soap/features/security/policy" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsu="http://schemas.xmlsoap.org/ws/2002/07/utility"/>
  </wsp:Policy>
  <wsp:Policy wsu:Id="IF_ZLM_WS_INFO_CONTACTO_BP">
    <sapsession:Session xmlns:sapsession="http://www.sap.com/webas/630/soap/features/session/">
      <sapsession:enableSession>false</sapsession:enableSession>
    </sapsession:Session>
    <sapcentraladmin:CentralAdministration wsp:Optional="true" xmlns:sapcentraladmin="http://www.sap.com/webas/700/soap/features/CentralAdministration/">
      <sapcentraladmin:BusinessApplicationID>E3DA1948DDE97EF1BD4DF8DB880509E3</sapcentraladmin:BusinessApplicationID>
    </sapcentraladmin:CentralAdministration>
  </wsp:Policy>
  <wsp:Policy wsu:Id="OP_ZlmRfcInfoContactoBp">
    <sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
    <sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
    <saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
    <saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
  </wsp:Policy>
  <wsdl:types>
     <xsd:schema>
      <xsd:import namespace="urn:sap-com:document:sap:soap:functions:mc-style" schemaLocation="../Schemas/SAPClientesXSD.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="urn:sap-com:document:sap:rfc:functions" schemaLocation="../Schemas/SAPClientesTypesXSD.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ZlmRfcInfoContactoBp">
    <wsdl:part name="parameters" element="tns:ZlmRfcInfoContactoBp"/>
  </wsdl:message>
  <wsdl:message name="ZlmRfcInfoContactoBpResponse">
    <wsdl:part name="parameter" element="tns:ZlmRfcInfoContactoBpResponse"/>
  </wsdl:message>
  <wsdl:message name="ZlmRfcInfoContactoBp.Exception">
    <wsdl:part name="ZlmRfcInfoContactoBp.Exception" element="tns:ZlmRfcInfoContactoBp.Exception"/>
  </wsdl:message>
  <wsdl:portType name="ZLM_WS_INFO_CONTACTO_BP">
    <wsp:Policy>
      <wsp:PolicyReference URI="#IF_ZLM_WS_INFO_CONTACTO_BP"/>
    </wsp:Policy>
    <wsdl:operation name="ZlmRfcInfoContactoBp">
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_ZlmRfcInfoContactoBp"/>
      </wsp:Policy>
      <wsdl:input message="tns:ZlmRfcInfoContactoBp"/>
      <wsdl:output message="tns:ZlmRfcInfoContactoBpResponse"/>
      <wsdl:fault name="ZlmRfcInfoContactoBp.Exception" message="tns:ZlmRfcInfoContactoBp.Exception"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ZLM_WS_INFO_CONTACTO_BP" type="tns:ZLM_WS_INFO_CONTACTO_BP">
    <wsp:Policy>
      <wsp:PolicyReference URI="#BN_ZLM_WS_INFO_CONTACTO_BP"/>
    </wsp:Policy>
    <wsa:EndpointReference xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
      <wsa:ReferenceParameters/>
    </wsa:EndpointReference>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="ZlmRfcInfoContactoBp">
      <soap:operation soapAction="ZlmRfcInfoContactoBp" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ZlmRfcInfoContactoBp.Exception">
        <soap:fault name="ZlmRfcInfoContactoBp.Exception" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ZLM_WS_INFO_CONTACTO_BP">
    <wsdl:port name="ZLM_WS_INFO_CONTACTO_BP" binding="tns:ZLM_WS_INFO_CONTACTO_BP">
      <soap:address location="http://dcpimsdsap01.nmp.com.mx:8000/sap/bc/srt/rfc/sap/zlm_ws_info_contacto_bp/300/zlm_ws_info_contacto_bp/zlm_ws_info_contacto_bp"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>