<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPGarantias" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsLeeGarantiaWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmfmRfcLeeGarantiaResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPGarantiasSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="consultarGarantiaResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPGarantias"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE AUG 08 13:27:18 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:consultarGarantiaResponse>
      <tns:InformacionGarantia>
        <tns:numeroGarantia>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Rsicher"/>
        </tns:numeroGarantia>
        <tns:descripcionVehiculo>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Descripcion"/>
        </tns:descripcionVehiculo>
        <xsl:choose>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Valor != ''">
            <tns:montoFactura>
              <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Valor"/>
            </tns:montoFactura>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <tns:serieChasis>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Noserie"/>
        </tns:serieChasis>
        <tns:numeroFactura>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/NoFactura"/>
        </tns:numeroFactura>
        <tns:serieMotor>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/NoMotor"/>
        </tns:serieMotor>
        <tns:aNombreDe>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/ANombreDe"/>
        </tns:aNombreDe>
        <tns:descripcionMarca>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Marca"/>
        </tns:descripcionMarca>
        <xsl:choose>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Anio != ''">
            <tns:anio>
              <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Anio"/>
            </tns:anio>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <tns:color>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Color"/>
        </tns:color>
        <xsl:choose>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Capacidad != ''">
            <tns:capacidad>
              <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Capacidad"/>
            </tns:capacidad>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Puertas != ''">
            <tns:numPuertas>
              <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Puertas"/>
            </tns:numPuertas>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <tns:uso>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Uso"/>
        </tns:uso>
        <tns:complemento>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/EquipoEspecial"/>
        </tns:complemento>
        <tns:placas>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/ClaveVehicular"/>
        </tns:placas>
        <tns:agenciaOrigen>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Proveedor"/>
        </tns:agenciaOrigen>
        <tns:descripcionModelo>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Modelo"/>
        </tns:descripcionModelo>
        <tns:transmision>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Transmision"/>
        </tns:transmision>
        <tns:combustible>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Combustible"/>
        </tns:combustible>
        <tns:lugarEmisionFactura>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/TextoAux"/>
        </tns:lugarEmisionFactura>
        <xsl:choose>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Usado = &quot;U&quot;">
            <tns:esUsado>
              <xsl:value-of select="true()"/>
            </tns:esUsado>
          </xsl:when>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Usado = &quot;N&quot;">
            <tns:esUsado>
              <xsl:value-of select="false()"/>
            </tns:esUsado>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <tns:vin>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Vin"/>
        </tns:vin>
        <xsl:choose>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/PrelacionCobro != ''">
            <tns:prelacionCobro>
              <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/PrelacionCobro"/>
            </tns:prelacionCobro>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <tns:descripcionSubmarca>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Submarca"/>
        </tns:descripcionSubmarca>
        <tns:descripcionVersion>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/Version"/>
        </tns:descripcionVersion>
        <tns:rfcEmisor>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/EmisorFactura"/>
        </tns:rfcEmisor>
        <xsl:choose>
          <xsl:when test="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/FechaFactura != '' and /ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/FechaFactura != '0000-00-00'">
            <tns:fechaEmisionFactura>
              <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/FechaFactura"/>
            </tns:fechaEmisionFactura>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <tns:ubicacionAgencia>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/DirProveedor"/>
        </tns:ubicacionAgencia>
        <tns:numeroTarjetaCirculacion>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/TarjetaCirculacion"/>
        </tns:numeroTarjetaCirculacion>
        <tns:engomado>
          <xsl:value-of select="/ns0:ZlmfmRfcLeeGarantiaResponse/InfoGarantia/ColorCalcomania"/>
        </tns:engomado>
      </tns:InformacionGarantia>
      <tns:ValoresGarantia>
        <xsl:choose>
          <xsl:when test="count(/ns0:ZlmfmRfcLeeGarantiaResponse/ValorGarantia/item) > 0">
            <xsl:for-each select="/ns0:ZlmfmRfcLeeGarantiaResponse/ValorGarantia/item">
              <tns:valorGarantia>
                <xsl:choose>
                  <xsl:when test="Rsicher != ''">
                    <tns:numeroGarantia>
                      <xsl:value-of select="Rsicher"/>
                    </tns:numeroGarantia>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
                <xsl:choose>
                  <xsl:when test="FechaValuacion != '' and FechaValuacion != '0000-00-00'">
                    <tns:fechaActualizacion>
                      <xsl:value-of select="concat(FechaValuacion, 'T00:00:00')"/>
                    </tns:fechaActualizacion>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
                <xsl:choose>
                  <xsl:when test="ValorReal = ''">
                    <tns:montoPrestamo>
                      <xsl:value-of select="ValorReal"/>
                    </tns:montoPrestamo>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
                <xsl:choose>
                  <xsl:when test="Garantizado != ''">
                    <tns:montoGarantizado>
                      <xsl:value-of select="Garantizado"/>
                    </tns:montoGarantizado>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
                <xsl:choose>
                  <xsl:when test="Castigo != ''">
                    <tns:montoAvaluoDictaminador>
                      <xsl:value-of select="Castigo"/>
                    </tns:montoAvaluoDictaminador>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
                <xsl:choose>
                  <xsl:when test="Kilometraje != ''">
                    <tns:descripcionKilometraje>
                      <xsl:value-of select="Kilometraje"/>
                    </tns:descripcionKilometraje>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
                <xsl:choose>
                  <xsl:when test="Dictaminador != ''">
                    <tns:nombreDictaminador>
                      <xsl:value-of select="Dictaminador"/>
                    </tns:nombreDictaminador>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
                <xsl:choose>
                  <xsl:when test="FolioBpm != ''">
                    <tns:folioTramite>
                      <xsl:value-of select="FolioBpm"/>
                    </tns:folioTramite>
                  </xsl:when>
                  <xsl:otherwise/>
                </xsl:choose>
              </tns:valorGarantia>
            </xsl:for-each>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
      </tns:ValoresGarantia>
    </tns:consultarGarantiaResponse>
  </xsl:template>
</xsl:stylesheet>