<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPGarantias" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPGarantiasSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="crearGarantiaRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPGarantias"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsCreaGarantiaWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmfmRfcCreaGarantia" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE AUG 08 13:20:34 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ZlmfmRfcCreaGarantia>
      <Garantia>
        <Rsicher>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:numeroGarantia"/>
        </Rsicher>
        <Descripcion>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:descripcionVehiculo"/>
        </Descripcion>
        <xsl:choose>
          <xsl:when test="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:montoFactura != &quot;&quot;">
            <Valor>
              <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:montoFactura"/>
            </Valor>
          </xsl:when>
          <xsl:otherwise>
            <Valor>0.00</Valor>
          </xsl:otherwise>
        </xsl:choose>
        <Noserie>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:serieChasis"/>
        </Noserie>
        <NoFactura>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:numeroFactura"/>
        </NoFactura>
        <NoMotor>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:serieMotor"/>
        </NoMotor>
        <ANombreDe>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:aNombreDe"/>
        </ANombreDe>
        <Marca>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:descripcionMarca"/>
        </Marca>
        <Anio>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:anio"/>
        </Anio>
        <Color>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:color"/>
        </Color>
        <Capacidad>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:capacidad"/>
        </Capacidad>
        <Puertas>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:numPuertas"/>
        </Puertas>
        <Uso>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:uso"/>
        </Uso>
        <EquipoEspecial>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:complemento"/>
        </EquipoEspecial>
        <ClaveVehicular>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:placas"/>
        </ClaveVehicular>
        <Proveedor>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:agenciaOrigen"/>
        </Proveedor>
        <Modelo>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:descripcionModelo"/>
        </Modelo>
        <Transmision>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:transmision"/>
        </Transmision>
        <Combustible>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:combustible"/>
        </Combustible>
        <TextoAux>
          <xsl:value-of select="substring (/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:lugarEmisionFactura, 0, 100 )"/>
        </TextoAux>
        <xsl:choose>
          <xsl:when test="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:esUsado">
            <Usado>
              <xsl:choose>
                <xsl:when test="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:esUsado = true()">
                  <xsl:text>U</xsl:text>
                </xsl:when>
                <xsl:otherwise>
                  <xsl:text>N</xsl:text>
                </xsl:otherwise>
              </xsl:choose>
            </Usado>
          </xsl:when>
          <xsl:otherwise/>
        </xsl:choose>
        <Vin>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:vin"/>
        </Vin>
        <xsl:choose>
          <xsl:when test="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:prelacionCobro != &quot;&quot;">
            <PrelacionCobro>
              <xsl:value-of select="substring(/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:prelacionCobro, 0, 3)"/>
            </PrelacionCobro>
          </xsl:when>
          <xsl:otherwise>
            <PrelacionCobro>0</PrelacionCobro>
          </xsl:otherwise>
        </xsl:choose>
        <Submarca>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:descripcionSubmarca"/>
        </Submarca>
        <Version>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:descripcionVersion"/>
        </Version>
        <EmisorFactura>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:rfcEmisor"/>
        </EmisorFactura>
        <FechaFactura>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:fechaEmisionFactura"/>
        </FechaFactura>
        <DirProveedor>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:ubicacionAgencia"/>
        </DirProveedor>
        <TarjetaCirculacion>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:numeroTarjetaCirculacion"/>
        </TarjetaCirculacion>
        <ColorCalcomania>
          <xsl:value-of select="substring(/ns0:crearGarantiaRequest/ns0:InformacionGarantia/ns0:engomado, 0, 20)"/>
        </ColorCalcomania>
      </Garantia>
      <ValorGarantia>
        <Rsicher>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:numeroGarantia"/>
        </Rsicher>
        <FechaValuacion>
          <xsl:value-of select="substring-before(/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:fechaActualizacion, 'T')"/>
        </FechaValuacion>
        <ValorReal>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:montoPrestamo"/>
        </ValorReal>
        <Garantizado>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:montoGarantizado"/>
        </Garantizado>
        <Castigo>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:montoAvaluoDictaminador"/>
        </Castigo>
        <Kilometraje>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:descripcionKilometraje"/>
        </Kilometraje>
        <Dictaminador>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:nombreDictaminador"/>
        </Dictaminador>
        <FolioBpm>
          <xsl:value-of select="/ns0:crearGarantiaRequest/ns0:ValorGarantia/ns0:folioTramite"/>
        </FolioBpm>
      </ValorGarantia>
    </tns:ZlmfmRfcCreaGarantia>
  </xsl:template>
</xsl:stylesheet>