<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://tempuri.org/" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Persona" xmlns:OrdT="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/OrdenesTrabajo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Cliente" xmlns:ns4="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity.Modelos" xmlns:ns5="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity" xmlns:ns6="http://schemas.datacontract.org/2004/07/Nmp.Crm.BusinessEntity.DataContract">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPSvcOrdenesTrabajoElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="actualizarGestionOrdenRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/CRMGestionesElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="RecepcionGestiones" namespace="http://tempuri.org/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUL 28 17:09:39 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:RecepcionGestiones>
         <tns:request>
            <ns6:CartaId>
               <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:idExterno"/>
            </ns6:CartaId>
            <ns6:CategoriaInteraccion>
               <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GestionVisita/OrdT:resultadoVisita"/>
            </ns6:CategoriaInteraccion>
            <ns6:FechaReinserccion>
               <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:fechaInicial"/>
            </ns6:FechaReinserccion>
            <ns6:Notas>
               <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GestionVisita/OrdT:gestion"/>
            </ns6:Notas>
            <ns6:ResultadoInteraccion>
               <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GestionVisita/OrdT:gestion"/>
            </ns6:ResultadoInteraccion>
         </tns:request>
      </tns:RecepcionGestiones>
   </xsl:template>
</xsl:stylesheet>