<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/CobranzaConsultas" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:GestionT="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilRESTTipos" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/CobranzaConsultas" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilTipos" xmlns:NMPGestion="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovil">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/GestionMovilFormiikRestElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="FlexibleUpdateWorkOrderRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../OperacionCreditos/Cobranza/Resources/Schemas/NMPSvcCobranzaConsultasElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="consultarCobranzaClienteRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/CobranzaConsultas"/>
        
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU DEC 10 23:32:59 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:consultarCobranzaClienteRequest>
      <ns1:contrato>
        <xsl:value-of select="/ns0:FlexibleUpdateWorkOrderRequest/GestionT:InputFields/GestionT:Num_Contrato"/>
      </ns1:contrato>
      <ns1:idCliente>
        <xsl:value-of select="/ns0:FlexibleUpdateWorkOrderRequest/GestionT:InputFields/GestionT:Num_Cliente"/>
      </ns1:idCliente>
      <ns1:promotor>
        <xsl:value-of select="/ns0:FlexibleUpdateWorkOrderRequest/GestionT:Username"/>
      </ns1:promotor>
    </tns:consultarCobranzaClienteRequest>
  </xsl:template>
</xsl:stylesheet>