<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST" xmlns:GestionT="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilRESTTipos" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Persona" xmlns:OrdT="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/OrdenesTrabajo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Cliente">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/GestionMovilFormiikRestElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="Response" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPSvcOrdenesTrabajoElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="actualizarPendientesOrdenRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SUN JUL 31 12:20:54 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:actualizarPendientesOrdenRequest>
      <OrdT:Pendiente>
        <OrdT:ContactoDomicilio>
          <xsl:if test="/ns0:Response//GestionT:DatosGenerales">
            <OrdT:Direccion>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:CalleCB">
                <OrdT:nombreDeLaCalle>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:CalleCB"/>
                </OrdT:nombreDeLaCalle>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:NoExtCB">
                <OrdT:numeroExterior>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:NoExtCB"/>
                </OrdT:numeroExterior>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:NoIntCB">
                <OrdT:numeroInterior>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:NoIntCB"/>
                </OrdT:numeroInterior>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:EntreCalle1CB">
                <OrdT:entreCalle1>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:EntreCalle1CB"/>
                </OrdT:entreCalle1>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:EntreCalle2CB">
                <OrdT:entreCalle2>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:EntreCalle2CB"/>
                </OrdT:entreCalle2>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:EstadoDCD">
                <OrdT:estado>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:EstadoDCD"/>
                </OrdT:estado>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:DelegacionCB">
                <OrdT:delegacionMunicipio>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:DelegacionCB"/>
                </OrdT:delegacionMunicipio>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:ColoniaCB">
                <OrdT:colonia>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:ColoniaCB"/>
                </OrdT:colonia>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:CPCB">
                <OrdT:codigoPostal>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:CPCB"/>
                </OrdT:codigoPostal>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:ManzanaCB">
                <OrdT:manzana>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:ManzanaCB"/>
                </OrdT:manzana>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:LoteCB">
                <OrdT:lote>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:LoteCB"/>
                </OrdT:lote>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:DatosGenerales/GestionT:LocalidadCB">
                <OrdT:localidad>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosGenerales/GestionT:LocalidadCB"/>
                </OrdT:localidad>
              </xsl:if>
            </OrdT:Direccion>
          </xsl:if>
          <OrdT:Telefonos>
            <xsl:if test="/ns0:Response//GestionT:DatosDeContacto/GestionT:Telefono">
              <OrdT:Telefono>
                <OrdT:numeroTelefonico>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDeContacto/GestionT:Telefono"/>
                </OrdT:numeroTelefonico>
                <OrdT:tipoTelefono>1</OrdT:tipoTelefono>
              </OrdT:Telefono>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:DatosDeContacto/GestionT:Lada_Celular">
              <OrdT:Telefono>
                <OrdT:codigoArea>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDeContacto/GestionT:Lada_Celular"/>
                </OrdT:codigoArea>
                <OrdT:numeroTelefonico>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDeContacto/GestionT:Telefono_Celular"/>
                </OrdT:numeroTelefonico>
                <OrdT:tipoTelefono>2</OrdT:tipoTelefono>
              </OrdT:Telefono>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:DatosDeContacto/GestionT:Lada_Recados">
              <OrdT:Telefono>
                <OrdT:codigoArea>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDeContacto/GestionT:Lada_Recados"/>
                </OrdT:codigoArea>
                <OrdT:numeroTelefonico>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDeContacto/GestionT:Telefono_Recados"/>
                </OrdT:numeroTelefonico>
                <OrdT:tipoTelefono>3</OrdT:tipoTelefono>
              </OrdT:Telefono>
            </xsl:if>
          </OrdT:Telefonos>
        </OrdT:ContactoDomicilio>
        <OrdT:DocumentacionCliente>
          <xsl:if test="/ns0:Response//GestionT:Comprobante_Dom">
            <OrdT:FotosCompDom>
              <xsl:for-each select="/ns0:Response//GestionT:Comprobante_Dom/*[contains(local-name(), 'FotoCompDom')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
              <xsl:if test="/ns0:Response//GestionT:Identificacion_Of/GestionT:TipoIdentificacionOficial">
                <OrdT:tipoComprobanteDom>
                  <xsl:value-of select="/ns0:Response//GestionT:Comprobante_Dom/GestionT:TipoComprobanteDomicilio"/>
                </OrdT:tipoComprobanteDom>
              </xsl:if>
            </OrdT:FotosCompDom>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Identificacion_Of">
            <OrdT:FotosIdOficial>
              <xsl:for-each select="/ns0:Response//GestionT:Identificacion_Of/*[contains(local-name(), 'FotoID')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
              <xsl:if test="/ns0:Response//GestionT:Identificacion_Of/GestionT:TipoIdentificacionOficial">
                <OrdT:tipoIdOficial>
                  <xsl:value-of select="/ns0:Response//GestionT:Identificacion_Of/GestionT:TipoIdentificacionOficial"/>
                </OrdT:tipoIdOficial>
              </xsl:if>
            </OrdT:FotosIdOficial>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Comprobante_Vivienda">
            <OrdT:FotosCompViv>
              <xsl:for-each select="/ns0:Response//GestionT:Comprobante_Vivienda/*[contains(local-name(), 'FotoCompViv')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
              <xsl:if test="/ns0:Response//GestionT:Comprobante_Vivienda/GestionT:TipoComprobanteVivienda">
                <OrdT:tipoComprobanteViv>
                  <xsl:value-of select="/ns0:Response//GestionT:Comprobante_Vivienda/GestionT:TipoComprobanteVivienda"/>
                </OrdT:tipoComprobanteViv>
              </xsl:if>
            </OrdT:FotosCompViv>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Comprobante_Ingresos">
            <OrdT:FotosCompIngEmp>
              <xsl:for-each select="/ns0:Response//GestionT:Comprobante_Ingresos/*[contains(local-name(), 'FotoCompIngEmp')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
              <xsl:if test="/ns0:Response//GestionT:Comprobante_Ingresos/GestionT:ComprobanteIngresosActividad">
                <OrdT:comprobanteIngresosAct>
                  <xsl:value-of select="/ns0:Response//GestionT:Comprobante_Ingresos/GestionT:ComprobanteIngresosActividad"/>
                </OrdT:comprobanteIngresosAct>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:Comprobante_Ingresos/GestionT:TipoComprobanteIngresosEmpleado">
                <OrdT:tipoComprobanteIngEmp>
                  <xsl:value-of select="/ns0:Response//GestionT:Comprobante_Ingresos/GestionT:TipoComprobanteIngresosEmpleado"/>
                </OrdT:tipoComprobanteIngEmp>
              </xsl:if>
            </OrdT:FotosCompIngEmp>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Comprobante_Ingresos">
            <OrdT:FotosCompIngNeg>
              <xsl:for-each select="/ns0:Response//GestionT:Comprobante_Ingresos/*[contains(local-name(), 'FotoCompIngNeg')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
              <xsl:if test="/ns0:Response//GestionT:Comprobante_Ingresos/GestionT:TipoComprobanteIngresosNegocio">
                <OrdT:comprobanteIngresosAct>
                  <xsl:value-of select="/ns0:Response//GestionT:Comprobante_Ingresos/GestionT:TipoComprobanteIngresosNegocio"/>
                </OrdT:comprobanteIngresosAct>
              </xsl:if>
            </OrdT:FotosCompIngNeg>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Comprobante_OtrosIng">
            <OrdT:FotosCompIngOtro>
              <xsl:for-each select="/ns0:Response//GestionT:Comprobante_OtrosIng/*[contains(local-name(), 'FotoCompOtrosIng')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
            </OrdT:FotosCompIngOtro>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Fotografias_cte">
            <OrdT:FotosCliente>
              <xsl:for-each select="/ns0:Response//GestionT:Fotografias_cte/*[contains(local-name(), 'FotoCliente')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
            </OrdT:FotosCliente>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Solicitud_cte">
            <OrdT:FotosSC>
              <xsl:for-each select="/ns0:Response//GestionT:Solicitud_cte/*[starts-with(local-name(), 'Foto') and ends-with(local-name(),'SC')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
            </OrdT:FotosSC>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:Formato_BC">
            <OrdT:FotosCB>
              <xsl:for-each select="/ns0:Response//GestionT:Formato_BC/*[starts-with(local-name(), 'Foto') and ends-with(local-name(),'CB')]">
                <OrdT:Fotos>
                  <OrdT:foto>
                    <xsl:value-of select="."/>
                  </OrdT:foto>
                </OrdT:Fotos>
              </xsl:for-each>
            </OrdT:FotosCB>
          </xsl:if>
        </OrdT:DocumentacionCliente>
        <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera">
          <OrdT:InformacionFinanciera>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ActividadIF">
              <OrdT:actividadEconomica>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ActividadIF"/>
              </OrdT:actividadEconomica>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VentasMensuales">
              <OrdT:ventasMensuales>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VentasMensuales"/>
              </OrdT:ventasMensuales>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Compras">
              <OrdT:compras>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Compras"/>
              </OrdT:compras>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Inventario">
              <OrdT:inventario>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Inventario"/>
              </OrdT:inventario>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:UtilidadBruta">
              <OrdT:utilidadBruta>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:UtilidadBruta"/>
              </OrdT:utilidadBruta>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosOperativos">
              <OrdT:gastosOperativos>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosOperativos"/>
              </OrdT:gastosOperativos>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Sueldos">
              <OrdT:sueldos>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Sueldos"/>
              </OrdT:sueldos>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasNegocio">
              <OrdT:deudasNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasNegocio"/>
              </OrdT:deudasNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosNegocio">
              <OrdT:serviciosPublicosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosNegocio"/>
              </OrdT:serviciosPublicosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteNegocio">
              <OrdT:transporteNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteNegocio"/>
              </OrdT:transporteNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaNegocio">
              <OrdT:rentaNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaNegocio"/>
              </OrdT:rentaNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionNegocio">
              <OrdT:alimentacionNeg>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionNegocio"/>
              </OrdT:alimentacionNeg>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosNegocio">
              <OrdT:otrosgastosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosNegocio"/>
              </OrdT:otrosgastosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliares">
              <OrdT:gastosFamiliares>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliares"/>
              </OrdT:gastosFamiliares>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroNegocio">
              <OrdT:deudasBuroNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroNegocio"/>
              </OrdT:deudasBuroNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosNegocio">
              <OrdT:pagosRealNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosNegocio"/>
              </OrdT:pagosRealNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosNegocio">
              <OrdT:totalGastosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosNegocio"/>
              </OrdT:totalGastosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosNegocio">
              <OrdT:otrosIngresosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosNegocio"/>
              </OrdT:otrosIngresosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosNegocio">
              <OrdT:tipoOtrosIngresosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosNegocio"/>
              </OrdT:tipoOtrosIngresosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Excedente">
              <OrdT:excedente>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Excedente"/>
              </OrdT:excedente>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:IngresosMensuales">
              <OrdT:ingresoMensual>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:IngresosMensuales"/>
              </OrdT:ingresoMensual>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ImpuestosRetenciones">
              <OrdT:impuestosRetenidos>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ImpuestosRetenciones"/>
              </OrdT:impuestosRetenidos>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosDifNegocio">
              <OrdT:otrosIngresosDiferidosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosDifNegocio"/>
              </OrdT:otrosIngresosDiferidosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosDifNegocio">
              <OrdT:tipoOtrosIngesosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosDifNegocio"/>
              </OrdT:tipoOtrosIngesosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalIngresosDifNegocio">
              <OrdT:totalIngresosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalIngresosDifNegocio"/>
              </OrdT:totalIngresosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliaresDifNegocio">
              <OrdT:gastosFamDiferidosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliaresDifNegocio"/>
              </OrdT:gastosFamDiferidosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionDifNegocio">
              <OrdT:alimentacionDiferidoNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionDifNegocio"/>
              </OrdT:alimentacionDiferidoNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:EducacionDifNegocio">
              <OrdT:educacionDiferidaNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:EducacionDifNegocio"/>
              </OrdT:educacionDiferidaNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosDifNegocio">
              <OrdT:serviciosPublicosDiferidosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosDifNegocio"/>
              </OrdT:serviciosPublicosDiferidosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteDifNegocio">
              <OrdT:transporteDiferidoNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteDifNegocio"/>
              </OrdT:transporteDiferidoNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaDifNegocio">
              <OrdT:rentaDiferidoNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaDifNegocio"/>
              </OrdT:rentaDiferidoNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VestidoDifNegocio">
              <OrdT:vestidoDiferidoNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VestidoDifNegocio"/>
              </OrdT:vestidoDiferidoNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosDifNegocio">
              <OrdT:otrosGastosDiferidosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosDifNegocio"/>
              </OrdT:otrosGastosDiferidosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroDifNegocio">
              <OrdT:deudasBuroDiferidoNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroDifNegocio"/>
              </OrdT:deudasBuroDiferidoNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosDifNegocio">
              <OrdT:pagosRealDiferidoNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosDifNegocio"/>
              </OrdT:pagosRealDiferidoNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosDifNegocio">
              <OrdT:totalGastosDiferidosNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosDifNegocio"/>
              </OrdT:totalGastosDiferidosNegocio>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ExcedenteDifNegocio">
              <OrdT:excedenteDiferidoNegocio>
                <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ExcedenteDifNegocio"/>
              </OrdT:excedenteDiferidoNegocio>
            </xsl:if>
          </OrdT:InformacionFinanciera>
        </xsl:if>
        <xsl:if test="/ns0:Response//GestionT:Ref1">
          <OrdT:Referencias>
            <xsl:for-each select="/ns0:Response//*[contains(local-name(), 'Ref')]">
              <OrdT:Referencia>
                <OrdT:primerNombre>
                  <xsl:value-of select="./*[contains(local-name(), concat('PrimerNombreRef',position()))]"/>
                </OrdT:primerNombre>
                <OrdT:segundoNombre>
                  <xsl:value-of select="./*[contains(local-name(), concat('SegundoNombreRef',position()))]"/>
                </OrdT:segundoNombre>
                <OrdT:apellidoPaterno>
                  <xsl:value-of select="./*[contains(local-name(), concat('ApPaternoRef',position()))]"/>
                </OrdT:apellidoPaterno>
                <OrdT:apellidoMaterno>
                  <xsl:value-of select="./*[contains(local-name(), concat('ApMaternoRef',position()))]"/>
                </OrdT:apellidoMaterno>
                <OrdT:parentesco>
                  <xsl:value-of select="./*[contains(local-name(), concat('ParentescoRef',position()))]"/>
                </OrdT:parentesco>
                <OrdT:ContactoDomicilioReferencia>
                  <OrdT:Direccion>
                    <OrdT:nombreDeLaCalle>
                      <xsl:value-of select="./*[contains(local-name(), concat('CalleRef',position()))]"/>
                    </OrdT:nombreDeLaCalle>
                    <OrdT:numeroExterior>
                      <xsl:value-of select="./*[contains(local-name(), concat('NoExtRef',position()))]"/>
                    </OrdT:numeroExterior>
                    <OrdT:numeroInterior>
                      <xsl:value-of select="./*[contains(local-name(), concat('NoIntRef',position()))]"/>
                    </OrdT:numeroInterior>
                    <OrdT:estado>
                      <xsl:value-of select="./*[contains(local-name(), concat('EstadoRef',position()))]"/>
                    </OrdT:estado>
                    <OrdT:delegacionMunicipio>
                      <xsl:value-of select="./*[contains(local-name(), concat('DelegacionRef',position()))]"/>
                    </OrdT:delegacionMunicipio>
                    <OrdT:colonia>
                      <xsl:value-of select="./*[contains(local-name(), concat('ColoniaRef',position()))]"/>
                    </OrdT:colonia>
                    <OrdT:codigoPostal>
                      <xsl:value-of select="./*[contains(local-name(), concat('CPRef',position()))]"/>
                    </OrdT:codigoPostal>
                    <OrdT:manzana>
                      <xsl:value-of select="./*[contains(local-name(), concat('ManzanaRef',position()))]"/>
                    </OrdT:manzana>
                    <OrdT:lote>
                      <xsl:value-of select="./*[contains(local-name(), concat('LoteRef',position()))]"/>
                    </OrdT:lote>
                    <OrdT:localidad>
                      <xsl:value-of select="./*[contains(local-name(), concat('LocalidadRef',position()))]"/>
                    </OrdT:localidad>
                  </OrdT:Direccion>
                  <OrdT:Telefonos>
                    <OrdT:Telefono>
                      <OrdT:numeroTelefonico>
                        <xsl:value-of select="./*[contains(local-name(), concat('TelCelularRef',position()))]"/>
                      </OrdT:numeroTelefonico>
                      <OrdT:tipoTelefono>2</OrdT:tipoTelefono>
                    </OrdT:Telefono>
                    <OrdT:Telefono>
                      <OrdT:numeroTelefonico>
                        <xsl:value-of select="./*[contains(local-name(), concat('TelDomicilioRef',position()))]"/>
                      </OrdT:numeroTelefonico>
                      <OrdT:tipoTelefono>1</OrdT:tipoTelefono>
                    </OrdT:Telefono>
                  </OrdT:Telefonos>
                </OrdT:ContactoDomicilioReferencia>
              </OrdT:Referencia>
            </xsl:for-each>
          </OrdT:Referencias>
        </xsl:if>
        <xsl:if test="/ns0:Response//GestionT:DatosGenerales/*[contains(local-name(), 'Num_ClienteRef')]">
        <OrdT:ListaReferenciasPreSolicitud>
          <xsl:for-each select="/ns0:Response//GestionT:DatosGenerales/*[contains(local-name(), 'Num_ClienteRef')]">
            <OrdT:Referencia>
              <OrdT:referencia>
                <xsl:value-of select="."/>
              </OrdT:referencia>
            </OrdT:Referencia>
          </xsl:for-each>
        </OrdT:ListaReferenciasPreSolicitud>
        </xsl:if>
      </OrdT:Pendiente>
      <OrdT:DatosTransaccion>
        <OrdT:idProducto>
          <xsl:value-of select="/ns0:Response/@ProductId"/>
        </OrdT:idProducto>
        <OrdT:idExterno>
          <xsl:value-of select="/ns0:Response/@ExternalId"/>
        </OrdT:idExterno>
        <OrdT:tipoOrdenTrabajo>
          <xsl:value-of select="/ns0:Response/@ExternalType"/>
        </OrdT:tipoOrdenTrabajo>
        <OrdT:promotorAsignado>
          <xsl:value-of select="/ns0:Response/@AssignedTo"/>
        </OrdT:promotorAsignado>
        <OrdT:fechaInicial>
          <!--Ejemplo Entrada: 20160715 17:10:19-->
          <!--Ejemplo Salida: 1991-09-28T20:49:45-->
          <xsl:value-of select="concat(substring(/ns0:Response/@InitialDate,1,4),'-',substring(/ns0:Response/@InitialDate,5,2),'-',substring(/ns0:Response/@InitialDate,7,2),'T',substring(/ns0:Response/@InitialDate,10))"/>
        </OrdT:fechaInicial>
        <OrdT:fechaFinal>
          <!--Ejemplo Entrada: 20160715 17:10:19-->
          <!--Ejemplo Salida: 1991-09-28T20:49:45-->
          <xsl:value-of select="concat(substring(/ns0:Response/@FinalDate,1,4),'-',substring(/ns0:Response/@FinalDate,5,2),'-',substring(/ns0:Response/@FinalDate,7,2),'T',substring(/ns0:Response/@FinalDate,10))"/>
        </OrdT:fechaFinal>
        <OrdT:fechaRespuesta>
         <!--Ejemplo Entrada: 20160715 17:10:19-->
          <!--Ejemplo Salida: 1991-09-28T20:49:45-->
          <xsl:value-of select="concat(substring(/ns0:Response/@ResponseDate,1,4),'-',substring(/ns0:Response/@ResponseDate,5,2),'-',substring(/ns0:Response/@ResponseDate,7,2),'T',substring(/ns0:Response/@ResponseDate,10))"/>
        </OrdT:fechaRespuesta>
        <OrdT:DatosGeoespaciales>
          <OrdT:latitudInicial>
            <xsl:value-of select="/ns0:Response/@InitialLatitude"/>
          </OrdT:latitudInicial>
          <OrdT:longitudInicial>
            <xsl:value-of select="/ns0:Response/@InitialLongitude"/>
          </OrdT:longitudInicial>
          <OrdT:latitudFinal>
            <xsl:value-of select="/ns0:Response/@FinalLatitude"/>
          </OrdT:latitudFinal>
          <OrdT:longitudFinal>
            <xsl:value-of select="/ns0:Response/@FinalLongitude"/>
          </OrdT:longitudFinal>
        </OrdT:DatosGeoespaciales>
        <OrdT:origenRespuesta>
          <xsl:value-of select="/ns0:Response/@FormiikResponseSource"/>
        </OrdT:origenRespuesta>
      </OrdT:DatosTransaccion>
    </tns:actualizarPendientesOrdenRequest>
  </xsl:template>
</xsl:stylesheet>