<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CatConceptoIVA" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenerico/ObtenerGenericoPrj/CatConceptoIVA" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenerico/ObtenerGenericoPrj/CatConceptoIVA" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CatConceptoIVA" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="CatConceptoIVA_plt">
      <plt:role name="CatConceptoIVA_role">
         <plt:portType name="tns:CatConceptoIVA_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CatConceptoIVA" schemaLocation="../Schemas/CatConceptoIVA.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CatConceptoIVAInput_msg">
      <wsdl:part name="CatConceptoIVAInput_msg" element="db:CatConceptoIVAInput"/>
   </wsdl:message>
   <wsdl:message name="CatConceptoIVAOutputCollection_msg">
      <wsdl:part name="CatConceptoIVAOutputCollection" element="db:CatConceptoIVAOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="CatConceptoIVA_ptt">
      <wsdl:operation name="CatConceptoIVA">
         <wsdl:input message="tns:CatConceptoIVAInput_msg"/>
         <wsdl:output message="tns:CatConceptoIVAOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
