<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CatCDeudoras" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenerico/ObtenerGenericoPrj/CatCDeudoras" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenerico/ObtenerGenericoPrj/CatCDeudoras" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CatCDeudoras" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="CatCDeudoras_plt">
      <plt:role name="CatCDeudoras_role">
         <plt:portType name="tns:CatCDeudoras_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CatCDeudoras" schemaLocation="../Schemas/CatCDeudoras.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CatCDeudorasInput_msg">
      <wsdl:part name="CatCDeudorasInput_msg" element="db:CatCDeudorasInput"/>
   </wsdl:message>
   <wsdl:message name="CatCDeudorasOutputCollection_msg">
      <wsdl:part name="CatCDeudorasOutputCollection" element="db:CatCDeudorasOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="CatCDeudoras_ptt">
      <wsdl:operation name="CatCDeudoras">
         <wsdl:input message="tns:CatCDeudorasInput_msg"/>
         <wsdl:output message="tns:CatCDeudorasOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
