<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="catRespSolicitud" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenerico/ObtenerGenericoPrj/catRespSolicitud" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenerico/ObtenerGenericoPrj/catRespSolicitud" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/catRespSolicitud" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="catRespSolicitud_plt">
      <plt:role name="catRespSolicitud_role">
         <plt:portType name="tns:catRespSolicitud_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/catRespSolicitud" schemaLocation="../Schemas/catRespSolicitud.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="catRespSolicitudInput_msg">
      <wsdl:part name="catRespSolicitudInput_msg" element="db:catRespSolicitudInput"/>
   </wsdl:message>
   <wsdl:message name="catRespSolicitudOutputCollection_msg">
      <wsdl:part name="catRespSolicitudOutputCollection" element="db:catRespSolicitudOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="catRespSolicitud_ptt">
      <wsdl:operation name="catRespSolicitud">
         <wsdl:input message="tns:catRespSolicitudInput_msg"/>
         <wsdl:output message="tns:catRespSolicitudOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
