<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CatSubtipoServicioDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/CatSubtipoServicioDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/CatSubtipoServicioDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CatSubtipoServicioDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="CatSubtipoServicioDB_plt">
      <plt:role name="CatSubtipoServicioDB_role">
         <plt:portType name="tns:CatSubtipoServicioDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CatSubtipoServicioDB" schemaLocation="../Schemas/CatSubtipoServicioDB.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CatSubtipoServicioDBInput_msg">
      <wsdl:part name="CatSubtipoServicioDBInput_msg" element="db:CatSubtipoServicioDBInput"/>
   </wsdl:message>
   <wsdl:message name="CatSubtipoServicioDBOutputCollection_msg">
      <wsdl:part name="CatSubtipoServicioDBOutputCollection" element="db:CatSubtipoServicioDBOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="CatSubtipoServicioDB_ptt">
      <wsdl:operation name="CatSubtipoServicioDB">
         <wsdl:input message="tns:CatSubtipoServicioDBInput_msg"/>
         <wsdl:output message="tns:CatSubtipoServicioDBOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
