<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CatTipoSolicitudDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/CatTipoSolicitudDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/CatTipoSolicitudDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CatTipoSolicitudDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="CatTipoSolicitudDB_plt">
      <plt:role name="CatTipoSolicitudDB_role">
         <plt:portType name="tns:CatTipoSolicitudDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CatTipoSolicitudDB" schemaLocation="../Schemas/CatTipoSolicitudDB.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CatTipoSolicitudDBInput_msg">
      <wsdl:part name="CatTipoSolicitudDBInput_msg" element="db:CatTipoSolicitudDBInput"/>
   </wsdl:message>
   <wsdl:message name="CatTipoSolicitudDBOutputCollection_msg">
      <wsdl:part name="CatTipoSolicitudDBOutputCollection" element="db:CatTipoSolicitudDBOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="CatTipoSolicitudDB_ptt">
      <wsdl:operation name="CatTipoSolicitudDB">
         <wsdl:input message="tns:CatTipoSolicitudDBInput_msg"/>
         <wsdl:output message="tns:CatTipoSolicitudDBOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
