<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ObtenerGenericoBPEL" targetNamespace="http://qualitas.com.mx/ObtenerGenericoApp/ObtenerGenericoPrj/ObtenerGenericoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ObtenerGenericoApp/ObtenerGenericoPrj/ObtenerGenericoBPEL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/ObtenerGenericoApp/ObtenerGenericoPrj/ObtenerGenericoBPEL" schemaLocation="../Schemas/ObtenerGenericoBPEL.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ObtenerGenericoBPELRequestMessage">
      <wsdl:part name="payload" element="client:process"/>
   </wsdl:message>
   <wsdl:message name="ObtenerGenericoBPELResponseMessage">
      <wsdl:part name="payload" element="client:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="ObtenerGenericoBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ObtenerGenericoBPELRequestMessage"/>
         <wsdl:output message="client:ObtenerGenericoBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ObtenerGenericoBPEL">
      <plnk:role name="ObtenerGenericoBPELProvider" portType="client:ObtenerGenericoBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
