<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SelCatTipoCContables" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/SelCatTipoCContables" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerGenericoApp/ObtenerGenericoPrj/SelCatTipoCContables" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelCatTipoCContables" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="SelCatTipoCContables_plt">
      <plt:role name="SelCatTipoCContables_role">
         <plt:portType name="tns:SelCatTipoCContables_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelCatTipoCContables" schemaLocation="../Schemas/SelCatTipoCContables.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="SelCatTipoCContablesInput_msg">
      <wsdl:part name="SelCatTipoCContablesInput_msg" element="db:SelCatTipoCContablesInput"/>
   </wsdl:message>
   <wsdl:message name="SelCatTipoCContablesOutputCollection_msg">
      <wsdl:part name="SelCatTipoCContablesOutputCollection" element="db:SelCatTipoCContablesOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="SelCatTipoCContables_ptt">
      <wsdl:operation name="SelCatTipoCContables">
         <wsdl:input message="tns:SelCatTipoCContablesInput_msg"/>
         <wsdl:output message="tns:SelCatTipoCContablesOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
