<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ObtenerServiciosPorPrestadorBPEL" targetNamespace="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" schemaLocation="../Schemas/ObtenerServiciosPorPrestadorBPEL.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ObtenerServiciosPorPrestadorBPELRequestMessage">
      <wsdl:part name="payload" element="client:serviciosPrestadorRequest"/>
   </wsdl:message>
   <wsdl:message name="ObtenerServiciosPorPrestadorBPELResponseMessage">
      <wsdl:part name="payload" element="client:serviciosPrestadorResponse"/>
   </wsdl:message>
   <wsdl:portType name="ObtenerServiciosPorPrestadorBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ObtenerServiciosPorPrestadorBPELRequestMessage"/>
         <wsdl:output message="client:ObtenerServiciosPorPrestadorBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ObtenerServiciosPorPrestadorBPEL">
      <plnk:role name="ObtenerServiciosPorPrestadorBPELProvider" portType="client:ObtenerServiciosPorPrestadorBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
