<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/Contrato" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:NMPsh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader" xmlns:NPMsm="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:Asrcot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizacion" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/commons/AutoSinResguardo" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:NMPAsr="http://servicios.montedepiedad.com.mx/NMP/Services/AutoSinResguardo">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDL/ZLM_WS_CREA_CONTRATO_DEV.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmRfcCreaContratoResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDL/GetCotizacionContratoWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ContratoResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Contrato"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED JUL 13 13:06:55 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="folio"/>
  <xsl:param name="proceso"/>
  <xsl:template match="/">
    <tns:ContratoResponse>
      <tns:IdContrato>
        <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/Contrato"/>
      </tns:IdContrato>
      <tns:DatosCliente>
        <tns:IdCliente>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/IdCliente"/>
        </tns:IdCliente>
        <tns:Folio>
          <xsl:value-of select="$folio"/>
        </tns:Folio>
        <tns:Proceso>
          <xsl:value-of select="$proceso"/>
        </tns:Proceso>
        <tns:Cliente>
          <tns:PrimerNombre>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Cliente/PrimerNombre"/>
          </tns:PrimerNombre>
          <tns:SegundoNombre>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Cliente/SegundoNombre"/>
          </tns:SegundoNombre>
          <tns:ApellidoPaterno>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/EsDatosCliente/Cliente/ApellidoPaterno"/>
          </tns:ApellidoPaterno>
          <tns:ApellidoMaterno>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Cliente/ApellidoMaterno"/>
          </tns:ApellidoMaterno>
          <tns:FechaNacimiento>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Cliente/FechaNacimiento"/>
          </tns:FechaNacimiento>
          <tns:Rfc>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Cliente/Rfc"/>
          </tns:Rfc>
        </tns:Cliente>
        <tns:Domicilio>
          <tns:Calle>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Domicilio/Calle"/>
          </tns:Calle>
          <tns:NumExt>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Domicilio/NumExt"/>
          </tns:NumExt>
          <tns:NumInt>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Domicilio/NumInt"/>
          </tns:NumInt>
          <tns:IdColonia>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Domicilio/IdColonia"/>
          </tns:IdColonia>
          <tns:Cp>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Domicilio/Cp"/>
          </tns:Cp>
          <tns:IdMunicipio>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Domicilio/IdMunicipio"/>
          </tns:IdMunicipio>
          <tns:IdEstado>
            <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosCliente/Domicilio/IdEstado"/>
          </tns:IdEstado>
        </tns:Domicilio>
      </tns:DatosCliente>
      <tns:DatosContrato>
        <tns:Sociedad>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/Sociedad"/>
        </tns:Sociedad>
        <tns:Producto>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/Producto"/>
        </tns:Producto>
        <tns:MontoSolicitado>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/MontoSolicitado"/>
        </tns:MontoSolicitado>
        <tns:Frecuencia>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/Frecuencia"/>
        </tns:Frecuencia>
        <tns:Plazo>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/Plazo"/>
        </tns:Plazo>
        <tns:TasaInteres>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/TasaInteres"/>
        </tns:TasaInteres>
        <tns:FechaDesembolso>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/FechaDesembolso"/>
        </tns:FechaDesembolso>
        <tns:FechaPrimerCobro>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/FechaPrimerCobro"/>
        </tns:FechaPrimerCobro>
        <tns:MultMoratorio>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/MultMoratorio"/>
        </tns:MultMoratorio>
        <tns:Origen>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/Origen"/>
        </tns:Origen>
        <tns:Destino>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/Destino"/>
        </tns:Destino>
        <tns:TipoDePago>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/TipoDePago"/>
        </tns:TipoDePago>
        <tns:DiasGracia>
          <xsl:value-of select="/ns0:ZlmRfcCreaContratoResponse/DatosContrato/DiasGracia"/>
        </tns:DiasGracia>
      </tns:DatosContrato>
    </tns:ContratoResponse>
  </xsl:template>
</xsl:stylesheet>