<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/UsuariosMonte" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPCampania="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Campania">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPUsuariosMonteXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="actualizarDatosRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/UsuariosMonte"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Clientes/Resources/Schemas/NMPClientesSvcElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateClienteRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI JUN 23 11:10:36 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="idCliente"/>
   <xsl:template match="/">
      <tns:updateClienteRequest>
         <tns:idCliente>
            <xsl:value-of select="$idCliente"/>
         </tns:idCliente>
         <tns:numeroDeCredencial>
            <xsl:value-of select="/ns0:actualizarDatosRequest/ns0:cliente/ns0:numCredencial"/>
         </tns:numeroDeCredencial>
         <tns:Contacto>
            <tns:ListaTelefonos>
               <tns:Telefono>
                  <xsl:if test="/ns0:actualizarDatosRequest/ns0:usuario/ns0:datoActualizar/ns0:telefono/ns0:codigoPais">
                     <tns:codigoPais>
                        <xsl:value-of select="/ns0:actualizarDatosRequest/ns0:usuario/ns0:datoActualizar/ns0:telefono/ns0:codigoPais"/>
                     </tns:codigoPais>
                  </xsl:if>
                  <xsl:if test="/ns0:actualizarDatosRequest/ns0:usuario/ns0:datoActualizar/ns0:telefono/ns0:codigoArea">
                     <tns:codigoArea>
                        <xsl:value-of select="/ns0:actualizarDatosRequest/ns0:usuario/ns0:datoActualizar/ns0:telefono/ns0:codigoArea"/>
                     </tns:codigoArea>
                  </xsl:if>
                  <xsl:if test="/ns0:actualizarDatosRequest/ns0:usuario/ns0:datoActualizar/ns0:telefono/ns0:numeroTelefono">
                     <tns:numeroTelefonico>
                        <xsl:value-of select="/ns0:actualizarDatosRequest/ns0:usuario/ns0:datoActualizar/ns0:telefono/ns0:numeroTelefono"/>
                     </tns:numeroTelefonico>
                  </xsl:if>
                  <xsl:if test="/ns0:actualizarDatosRequest/ns0:usuario/ns0:datoActualizar/ns0:telefono/ns0:numeroTelefono">
                     <tns:tipoTelefono>celular</tns:tipoTelefono>
                  </xsl:if>
               </tns:Telefono>
            </tns:ListaTelefonos>
         </tns:Contacto>
      </tns:updateClienteRequest>
   </xsl:template>
</xsl:stylesheet>