<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns2 ns1 ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:NMPCred="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:ava="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:NMPIniciaASR="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:NMPDoc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ns4="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ct="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCommonTypes" xmlns:NMPPers="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPersona">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPVehiculosSinResguardoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="actualizarSolicitudRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Common/XSD/NMPStandardHeader.xsd"/>
            <oracle-xsl-mapper:rootElement name="headerMessage" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader"/>
            <oracle-xsl-mapper:param name="header"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../SolicitudesVSR/Resources/Schemas/NMPSolicitudesVSRXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="validarVehiculoResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR"/>
            <oracle-xsl-mapper:param name="solicitud"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../SolicitudesVSR/Resources/Schemas/NMPSolicitudesVSRXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="actualizarSolicitudRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON APR 17 16:13:20 EDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="header"/>
   <xsl:param name="solicitud"/>
   <xsl:template match="/">
      <ns2:actualizarSolicitudRequest>
         <ns2:NmpSolicitudesClientesInfo>
            <xsl:if test="/ns0:actualizarSolicitudRequest/NMPIniciaASR:cliente/NMPIniciaASR:numeroCliente">
               <ns2:numCliente>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/NMPIniciaASR:cliente/NMPIniciaASR:numeroCliente"/>
               </ns2:numCliente>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/NMPIniciaASR:folio">
               <ns2:folioTramite>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/NMPIniciaASR:folio"/>
               </ns2:folioTramite>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoMaximoPrestamo">
               <ns2:montoPrestamo>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoMaximoPrestamo"/>
               </ns2:montoPrestamo>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoAvaluo">
               <ns2:montoAvaluo>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoAvaluo"/>
               </ns2:montoAvaluo>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoCastigo">
               <ns2:montoAvaluoDictaminador>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoCastigo"/>
               </ns2:montoAvaluoDictaminador>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoPrestamoSolicitado">
               <ns2:prestamoSolicitado>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoPrestamoSolicitado"/>
               </ns2:prestamoSolicitado>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:listaOfertas/ns0:oferta/cot:plazo">
               <ns2:plazo>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:listaOfertas/ns0:oferta/cot:plazo"/>
               </ns2:plazo>
            </xsl:if>
            <xsl:if test="$solicitud/ns2:validarVehiculoResponse/ns2:solicitud/ns2:estadoSolicitud">
               <ns2:estadoSolicitud>
                  <xsl:value-of select="$solicitud/ns2:validarVehiculoResponse/ns2:solicitud/ns2:estadoSolicitud"/>
               </ns2:estadoSolicitud>
            </xsl:if>
            <xsl:if test="$solicitud/ns2:validarVehiculoResponse/ns2:solicitud/ns2:idContrato">
               <ns2:idContrato>
                  <xsl:value-of select="$solicitud/ns2:validarVehiculoResponse/ns2:solicitud/ns2:idContrato"/>
               </ns2:idContrato>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoMinimoPrestamo">
               <ns2:montoMinimo>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:cotizacion/cot:montoMinimoPrestamo"/>
               </ns2:montoMinimo>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:nombreDictaminador">
               <ns2:nombreDictaminador>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:nombreDictaminador"/>
               </ns2:nombreDictaminador>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:prelacionCobro">
               <ns2:prelacionCobro>
                  <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:prelacionCobro"/>
               </ns2:prelacionCobro>
            </xsl:if>
            <ns2:actualizadoPor>
                  <xsl:value-of select="$header//ns1:usuario"/>
               </ns2:actualizadoPor>
            <ns2:fechaActualizacion>
               <xsl:value-of select="xp20:current-dateTime ( )"/>
            </ns2:fechaActualizacion>
            <!--ns2:nmpDocumentosSolicitudInfoCollection>
               <xsl:for-each select="/ns0:actualizarSolicitudRequest/ns0:listaDocumentos/NMPDoc:documentos">
                  <ns2:NmpDocumentosSolicitudInfo>
                     <xsl:if test="NMPDoc:nombreDocumento">
                        <NMPDoc:nombreDocumento>
                           <xsl:value-of select="NMPDoc:nombreDocumento"/>
                        </NMPDoc:nombreDocumento>
                     </xsl:if>
                     <xsl:if test="NMPDoc:tipoDocumento">
                        <NMPDoc:tipoDocumento>
                           <xsl:value-of select="NMPDoc:tipoDocumento"/>
                        </NMPDoc:tipoDocumento>
                     </xsl:if>
                     <xsl:if test="NMPDoc:documentoURL">
                        <NMPDoc:url>
                           <xsl:value-of select="NMPDoc:documentoURL"/>
                        </NMPDoc:url>
                     </xsl:if>
                     <xsl:if test="NMPDoc:fechaCreacion">
                        <NMPDoc:fechaCreacion>
                           <xsl:value-of select="NMPDoc:fechaCreacion"/>
                        </NMPDoc:fechaCreacion>
                     </xsl:if>
                  </ns2:NmpDocumentosSolicitudInfo>
               </xsl:for-each>
            </ns2:nmpDocumentosSolicitudInfoCollection-->
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:listaOfertas">
               <ns2:nmpFormasPagoCollection>
                  <xsl:for-each select="/ns0:actualizarSolicitudRequest/ns0:listaOfertas/ns0:oferta">
                     <ns2:NmpFormasPago>
                        <xsl:if test="cot:plazo">
                           <cot:plazo>
                              <xsl:value-of select="cot:plazo"/>
                           </cot:plazo>
                        </xsl:if>
                        <xsl:if test="cot:montoCredito">
                           <cot:montoCredito>
                              <xsl:value-of select="cot:montoCredito"/>
                           </cot:montoCredito>
                        </xsl:if>
                        <xsl:if test="cot:pagoMensual">
                           <cot:pagoMensual>
                              <xsl:value-of select="cot:pagoMensual"/>
                           </cot:pagoMensual>
                        </xsl:if>
                        <xsl:if test="cot:tasa">
                           <cot:tasa>
                              <xsl:value-of select="cot:tasa"/>
                           </cot:tasa>
                        </xsl:if>
                        <cot:actualizadoPor>
                           <xsl:value-of select="$header//ns1:usuario"/>
                        </cot:actualizadoPor>
                        <cot:fechaActualizacion>
                           <xsl:value-of select="xp20:current-dateTime ( )"/>
                        </cot:fechaActualizacion>
                        <xsl:if test="cot:idFormaPago">
                           <cot:idFormaPago>
                              <xsl:value-of select="cot:idFormaPago"/>
                           </cot:idFormaPago>
                        </xsl:if>
                        <xsl:if test="cot:estadoFormaPago">
                           <cot:estadoFormaPago>
                              <xsl:value-of select="cot:estadoFormaPago"/>
                           </cot:estadoFormaPago>
                        </xsl:if>
                     </ns2:NmpFormasPago>
                  </xsl:for-each>
               </ns2:nmpFormasPagoCollection>
            </xsl:if>
            <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo">
               <ns2:nmpVehiculoInfoCollection>
                  <ns2:NmpVehiculoInfo>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:vin">
                        <veh:vin>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:vin"/>
                        </veh:vin>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:serieMotor">
                        <veh:serieMotor>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:serieMotor"/>
                        </veh:serieMotor>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:tipoVehiculo">
                        <veh:tipoVehiculo>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:tipoVehiculo"/>
                        </veh:tipoVehiculo>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:placas">
                        <veh:placas>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:placas"/>
                        </veh:placas>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:marca/veh:descripcion">
                        <veh:descripcionMarca>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:marca/veh:descripcion"/>
                        </veh:descripcionMarca>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca">
                        <veh:idMarca>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca"/>
                        </veh:idMarca>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:descripcion">
                        <veh:descripcionSubMarca>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:descripcion"/>
                        </veh:descripcionSubMarca>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca">
                        <veh:idSubMarca>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca"/>
                        </veh:idSubMarca>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:descripcion">
                        <veh:descripcionModelo>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:descripcion"/>
                        </veh:descripcionModelo>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo">
                        <veh:idModelo>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo"/>
                        </veh:idModelo>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:version/veh:descripcion">
                        <veh:descripcionVersion>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:version/veh:descripcion"/>
                        </veh:descripcionVersion>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion">
                        <veh:idVersion>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion"/>
                        </veh:idVersion>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:descripcion">
                        <veh:descripcionKilometraje>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:descripcion"/>
                        </veh:descripcionKilometraje>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje">
                        <veh:idKilometraje>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje"/>
                        </veh:idKilometraje>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:color">
                        <veh:color>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:color"/>
                        </veh:color>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:serieChasis">
                        <veh:serieChasis>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:serieChasis"/>
                        </veh:serieChasis>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:numeroTarjetaCirculacion">
                        <veh:numeroTarjetaCirculacion>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:numeroTarjetaCirculacion"/>
                        </veh:numeroTarjetaCirculacion>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:numeroFactura">
                        <veh:numeroFactura>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:numeroFactura"/>
                        </veh:numeroFactura>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:rfcEmisor">
                        <veh:rfcEmisor>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:rfcEmisor"/>
                        </veh:rfcEmisor>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:agenciaOrigen">
                        <veh:agenciaOrigen>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:agenciaOrigen"/>
                        </veh:agenciaOrigen>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:comentarios">
                        <veh:comentarios>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:comentarios"/>
                        </veh:comentarios>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:engomado">
                        <veh:engomado>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:engomado"/>
                        </veh:engomado>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:anio">
                        <veh:anio>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:anio"/>
                        </veh:anio>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:fechaEmisionFactura">
                        <veh:fechaEmisionFactura>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:fechaEmisionFactura"/>
                        </veh:fechaEmisionFactura>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:montoFactura">
                        <veh:montoFactura>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:montoFactura"/>
                        </veh:montoFactura>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:lugarEmisionFactura">
                        <veh:lugarEmisionFactura>
                           <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:lugarEmisionFactura"/>
                        </veh:lugarEmisionFactura>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:uso">
                     <veh:uso>
                        <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:uso"/>
                     </veh:uso>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:transmision">
                     <veh:transmision>
                        <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:transmision"/>
                     </veh:transmision>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:combustible">
                     <veh:combustible>
                        <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:combustible"/>
                     </veh:combustible>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:usado">
                     <veh:usado>
                        <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:usado"/>
                     </veh:usado>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:capacidad">
                     <veh:capacidad>
                        <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:capacidad"/>
                     </veh:capacidad>
                     </xsl:if>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:numPuertas">
                     <veh:numPuertas>
                        <xsl:value-of select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:numPuertas"/>
                     </veh:numPuertas>
                     </xsl:if>
                     <veh:actualizadoPor>
                        <xsl:value-of select="$header//ns1:usuario"/>
                     </veh:actualizadoPor>
                     <veh:fechaActualizacion>
                        <xsl:value-of select="xp20:current-dateTime ( )"/>
                     </veh:fechaActualizacion>
                     <xsl:if test="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:complementos">
                        <veh:nmpGrupoComplementosCollection>
                           <xsl:for-each select="/ns0:actualizarSolicitudRequest/ns0:vehiculo/veh:complementos/veh:complemento">
                              <veh:NmpGrupoComplementos>
                                 <xsl:if test="veh:idComplemento">
                                    <veh:idComplemento>
                                       <xsl:value-of select="veh:idComplemento"/>
                                    </veh:idComplemento>
                                 </xsl:if>
                                 <xsl:if test="veh:descripcion">
                                    <veh:descripcion>
                                       <xsl:value-of select="veh:descripcion"/>
                                    </veh:descripcion>
                                 </xsl:if>
                              </veh:NmpGrupoComplementos>
                           </xsl:for-each>
                        </veh:nmpGrupoComplementosCollection>
                     </xsl:if>
                  </ns2:NmpVehiculoInfo>
               </ns2:nmpVehiculoInfoCollection>
            </xsl:if>
         </ns2:NmpSolicitudesClientesInfo>
      </ns2:actualizarSolicitudRequest>
   </xsl:template>
</xsl:stylesheet>