<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:doc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ct="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCommonTypes" xmlns:ava="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:NMPIniciaASR="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPPers="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPersona" xmlns:NMPCred="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../SolicitudesVSR/Resources/Schemas/NMPSolicitudesVSRXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarSolicitudResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPVehiculosSinResguardoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarSolicitudResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON MAR 06 20:31:22 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:consultarSolicitudResponse>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:folioTramite != ''">
            <NMPIniciaASR:folio>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:folioTramite"/>
            </NMPIniciaASR:folio>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:estadoSolicitud != ''">
            <NMPIniciaASR:estadoSolicitud>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:estadoSolicitud"/>
            </NMPIniciaASR:estadoSolicitud>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:estadoFlujo != ''">
            <NMPIniciaASR:estadoFlujoBpm>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:estadoFlujo"/>
            </NMPIniciaASR:estadoFlujoBpm>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idContrato != ''">
            <tns:idContrato>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idContrato"/>
            </tns:idContrato>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idProducto != ''">
            <NMPIniciaASR:idProducto>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idProducto"/>
            </NMPIniciaASR:idProducto>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nombreProducto != ''">
            <NMPIniciaASR:nombreProducto>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nombreProducto"/>
            </NMPIniciaASR:nombreProducto>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idSubproducto != ''">
            <NMPIniciaASR:idSubProducto>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idSubproducto"/>
         </NMPIniciaASR:idSubProducto>
         </xsl:if>
         <NMPIniciaASR:cliente>
               <NMPIniciaASR:numeroCliente>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:numCliente"/>
               </NMPIniciaASR:numeroCliente>
            </NMPIniciaASR:cliente>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo != ''">
            <tns:vehiculo>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:tipoVehiculo != ''">
                  <veh:tipoVehiculo>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:tipoVehiculo"/>
                  </veh:tipoVehiculo>
               </xsl:if>
               <veh:vin>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:vin"/>
               </veh:vin>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieMotor != ''">
                  <veh:serieMotor>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieMotor"/>
                  </veh:serieMotor>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:placas != ''">
                  <veh:placas>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:placas"/>
                  </veh:placas>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:engomado != ''">
                  <veh:engomado>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:engomado"/>
                  </veh:engomado>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idMarca != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionMarca != ''">
                  <veh:marca>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idMarca != ''">
                        <veh:idMarca>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idMarca"/>
                        </veh:idMarca>
                     </xsl:if>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionMarca != ''">
                        <veh:descripcion>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionMarca"/>
                        </veh:descripcion>
                     </xsl:if>
                  </veh:marca>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idSubMarca != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionSubMarca != ''">
                  <veh:submarca>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idSubMarca != ''">
                        <veh:idSubMarca>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idSubMarca"/>
                        </veh:idSubMarca>
                     </xsl:if>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionSubMarca != ''">
                        <veh:descripcion>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionSubMarca"/>
                        </veh:descripcion>
                     </xsl:if>
                  </veh:submarca>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idModelo != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionModelo != ''">
                  <veh:modelo>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idModelo != ''">
                        <veh:idModelo>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idModelo"/>
                        </veh:idModelo>
                     </xsl:if>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionModelo != ''">
                        <veh:descripcion>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionModelo"/>
                        </veh:descripcion>
                     </xsl:if>
                  </veh:modelo>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idVersion != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionVersion != ''">
                  <veh:version>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idVersion != ''">
                        <veh:idVersion>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idVersion"/>
                        </veh:idVersion>
                     </xsl:if>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionVersion != ''">
                        <veh:descripcion>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionVersion"/>
                        </veh:descripcion>
                     </xsl:if>
                  </veh:version>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idKilometraje != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionKilometraje != ''">
                  <veh:kilometraje>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idKilometraje != ''">
                        <veh:idKilometraje>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idKilometraje"/>
                        </veh:idKilometraje>
                     </xsl:if>
                     <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionKilometraje != ''">
                        <veh:descripcion>
                           <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionKilometraje"/>
                        </veh:descripcion>
                     </xsl:if>
                  </veh:kilometraje>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:nmpGrupoComplementosCollection != ''">
                  <veh:complementos>
                     <xsl:for-each select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:nmpGrupoComplementosCollection/veh:NmpGrupoComplementos">
                        <veh:complemento>
                           <veh:idComplemento>
                              <xsl:value-of select="veh:idComplemento"/>
                           </veh:idComplemento>
                           <xsl:if test="veh:descripcion != ''">
                              <veh:descripcion>
                                 <xsl:value-of select="veh:descripcion"/>
                              </veh:descripcion>
                           </xsl:if>
                        </veh:complemento>
                     </xsl:for-each>
                  </veh:complementos>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:color != ''">
                  <veh:color>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:color"/>
                  </veh:color>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieChasis != ''">
                  <veh:serieChasis>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieChasis"/>
                  </veh:serieChasis>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroTarjetaCirculacion != ''">
                  <veh:numeroTarjetaCirculacion>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroTarjetaCirculacion"/>
                  </veh:numeroTarjetaCirculacion>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroFactura != ''">
                  <veh:numeroFactura>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroFactura"/>
                  </veh:numeroFactura>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:rfcEmisor != ''">
                  <veh:rfcEmisor>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:rfcEmisor"/>
                  </veh:rfcEmisor>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:agenciaOrigen != ''">
                  <veh:agenciaOrigen>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:agenciaOrigen"/>
                  </veh:agenciaOrigen>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:comentarios != ''">
                  <veh:comentarios>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:comentarios"/>
                  </veh:comentarios>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:anio != ''">
               <veh:anio>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:anio"/>
               </veh:anio>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:fechaEmisionFactura != ''">
               <veh:fechaEmisionFactura>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:fechaEmisionFactura"/>
               </veh:fechaEmisionFactura>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:montoFactura != ''">
               <veh:montoFactura>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:montoFactura"/>
               </veh:montoFactura>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:lugarEmisionFactura != ''">
               <veh:lugarEmisionFactura>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:lugarEmisionFactura"/>
               </veh:lugarEmisionFactura>
               </xsl:if>
            </tns:vehiculo>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluo != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoMinimo != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoPrestamo != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:prestamoSolicitado != '' or /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador != ''">
            <tns:cotizacion>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluo != ''">
                  <cot:montoAvaluo>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluo"/>
                  </cot:montoAvaluo>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoMinimo != ''">
                  <cot:montoMinimoPrestamo>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoMinimo"/>
                  </cot:montoMinimoPrestamo>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoPrestamo != ''">
                  <cot:montoMaximoPrestamo>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoPrestamo"/>
                  </cot:montoMaximoPrestamo>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:prestamoSolicitado != ''">
                  <cot:montoPrestamoSolicitado>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:prestamoSolicitado"/>
                  </cot:montoPrestamoSolicitado>
               </xsl:if>
               <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador != ''">
                  <cot:montoCastigo>
                     <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador"/>
                  </cot:montoCastigo>
               </xsl:if>
            </tns:cotizacion>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpFormasPagoCollection != ''">
            <tns:listaOfertas>
               <xsl:for-each select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpFormasPagoCollection/ns0:NmpFormasPago">
                  <tns:oferta>
                     <cot:plazo>
                        <xsl:value-of select="cot:plazo"/>
                     </cot:plazo>
                     <xsl:if test="cot:montoCredito != ''">
                        <cot:montoCredito>
                           <xsl:value-of select="cot:montoCredito"/>
                        </cot:montoCredito>
                     </xsl:if>
                     <xsl:if test="cot:pagoMensual != ''">
                        <cot:pagoMensual>
                           <xsl:value-of select="cot:pagoMensual"/>
                        </cot:pagoMensual>
                     </xsl:if>
                     <xsl:if test="cot:tasa != ''">
                        <cot:tasa>
                           <xsl:value-of select="cot:tasa"/>
                        </cot:tasa>
                     </xsl:if>
                     <xsl:if test="cot:creadoPor != ''">
                        <cot:creadoPor>
                           <xsl:value-of select="cot:creadoPor"/>
                        </cot:creadoPor>
                     </xsl:if>
                     <xsl:if test="cot:fechaCreacion != ''">
                        <cot:fechaCreacion>
                           <xsl:value-of select="cot:fechaCreacion"/>
                        </cot:fechaCreacion>
                     </xsl:if>
                     <xsl:if test="cot:actualizadoPor != ''">
                        <cot:actualizadoPor>
                           <xsl:value-of select="cot:actualizadoPor"/>
                        </cot:actualizadoPor>
                     </xsl:if>
                     <xsl:if test="cot:fechaActualizacion != ''">
                        <cot:fechaActualizacion>
                           <xsl:value-of select="cot:fechaActualizacion"/>
                        </cot:fechaActualizacion>
                     </xsl:if>
                     <xsl:if test="cot:estadoFormaPago != ''">
                        <cot:estadoFormaPago>
                           <xsl:value-of select="cot:estadoFormaPago"/>
                        </cot:estadoFormaPago>
                     </xsl:if>
                  </tns:oferta>
               </xsl:for-each>
            </tns:listaOfertas>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpDocumentosSolicitudInfoCollection != ''">
            <tns:listaDocumentos>
               <xsl:for-each select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpDocumentosSolicitudInfoCollection/ns0:NmpDocumentosSolicitudInfo">
                  <doc:documentos>
                     <doc:nombreDocumento>
                        <xsl:value-of select="doc:nombreDocumento"/>
                     </doc:nombreDocumento>
                     <xsl:if test="doc:url != ''">
                        <doc:documentoURL>
                           <xsl:value-of select="doc:url"/>
                        </doc:documentoURL>
                     </xsl:if>
                     <xsl:if test="doc:fechaCreacion != ''">
                        <doc:fechaCreacion>
                           <xsl:value-of select="doc:fechaCreacion"/>
                        </doc:fechaCreacion>
                     </xsl:if>
                     <xsl:if test="doc:tipoDocumento != ''">
                        <doc:tipoDocumento>
                           <xsl:value-of select="doc:tipoDocumento"/>
                        </doc:tipoDocumento>
                     </xsl:if>
                  </doc:documentos>
               </xsl:for-each>
            </tns:listaDocumentos>
         </xsl:if>
         <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idMotivoRechazo != ''">
            <tns:motivoRechazo>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:idMotivoRechazo"/>
            </tns:motivoRechazo>
         </xsl:if>
      </tns:consultarSolicitudResponse>
   </xsl:template>
</xsl:stylesheet>