<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:NMPIniciaASR="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:NMPDoc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:NMPPers="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPersona">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPVehiculosSinResguardoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="generarContratoRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../Creditos/Resources/Schemas/NMPCreditoSvcElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="generarContratoRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE APR 25 19:06:58 EDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:generarContratoRequest>
         <tns:idCliente>
            <xsl:value-of select="/ns0:generarContratoRequest/tns:idCliente"/>
         </tns:idCliente>
         <tns:folio>
            <xsl:value-of select="/ns0:generarContratoRequest/tns:folio"/>
         </tns:folio>
         <tns:datosContrato>
            <tns:sociedad>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:sociedad"/>
            </tns:sociedad>
            <tns:producto>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:producto"/>
            </tns:producto>
            <tns:subproducto>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:subproducto"/>
            </tns:subproducto>
            <tns:montoSolicitado>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:montoSolicitado"/>
            </tns:montoSolicitado>
            <tns:frecuencia>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:frecuencia"/>
            </tns:frecuencia>
            <tns:plazo>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:plazo"/>
            </tns:plazo>
            <tns:tasaInteres>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:tasaInteres"/>
            </tns:tasaInteres>
            <tns:fechaDesembolso>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:fechaDesembolso"/>
            </tns:fechaDesembolso>
            <xsl:if test="/ns0:generarContratoRequest/tns:datosContrato/tns:fechaPrimerCobro">
               <tns:fechaPrimerCobro>
                  <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:fechaPrimerCobro"/>
               </tns:fechaPrimerCobro>
            </xsl:if>
            <xsl:if test="/ns0:generarContratoRequest/tns:datosContrato/tns:multiploMoratorio">
               <tns:multiploMoratorio>
                  <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:multiploMoratorio"/>
               </tns:multiploMoratorio>
            </xsl:if>
            <tns:origen>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:origen"/>
            </tns:origen>
            <tns:sucursal>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:sucursal"/>
            </tns:sucursal>
            <tns:promotor>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:promotor"/>
            </tns:promotor>
            <tns:destino>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:destino"/>
            </tns:destino>
            <tns:tipoPago>
               <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:tipoPago"/>
            </tns:tipoPago>
            <xsl:if test="/ns0:generarContratoRequest/tns:datosContrato/tns:porcentajeAmortizacion">
               <tns:porcentajeAmortizacion>
                  <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:porcentajeAmortizacion"/>
               </tns:porcentajeAmortizacion>
            </xsl:if>
            <xsl:if test="/ns0:generarContratoRequest/tns:datosContrato/tns:diasGracia">
               <tns:diasGracia>
                  <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:diasGracia"/>
               </tns:diasGracia>
            </xsl:if>
            <xsl:if test="/ns0:generarContratoRequest/tns:datosContrato/tns:folioConsultaBuro">
               <tns:folioConsultaBuro>
                  <xsl:value-of select="/ns0:generarContratoRequest/tns:datosContrato/tns:folioConsultaBuro"/>
               </tns:folioConsultaBuro>
            </xsl:if>
         </tns:datosContrato>
           <xsl:if test="/ns0:generarContratoRequest/tns:garantia">
            <tns:garantia>
            <xsl:for-each select="/ns0:generarContratoRequest/tns:garantia/tns:numeroGarantia">
               <tns:numeroGarantia>
                  <xsl:value-of select="."/>
               </tns:numeroGarantia>
            </xsl:for-each>
         </tns:garantia>
</xsl:if>
         
      </tns:generarContratoRequest>
   </xsl:template>
</xsl:stylesheet>