<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:NMPIniciaASR="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:doc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:ct="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCommonTypes" xmlns:ava="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../SolicitudesVSR/Resources/Schemas/NMPSolicitudesVSRXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarSolicitudResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../../../SolicitudesVSR/Resources/Schemas/NMPSolicitudesVSRXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="actualizarSolicitudRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON AUG 14 13:42:41 CDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="numeroGarantia"/>
   <xsl:template match="/">
      <ns0:actualizarSolicitudRequest>
         <ns0:NmpSolicitudesClientesInfo>
            <ns0:numCliente>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:numCliente"/>
            </ns0:numCliente>
            <ns0:folioTramite>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:folioTramite"/>
            </ns0:folioTramite>
            <ns0:numeroGarantia>
               <xsl:value-of select="$numeroGarantia"/>
            </ns0:numeroGarantia>
         </ns0:NmpSolicitudesClientesInfo>
      </ns0:actualizarSolicitudRequest>
   </xsl:template>
</xsl:stylesheet>