<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi ns0 xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction ns0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:NMPDoc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:NMPPers="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPersona" xmlns:NMPCred="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:adt="http://servicios.montedepiedad.com.mx/NMP/Schema/AdminDoctosTipos">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPVehiculosSinResguardoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="generarSolicitudRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../Utileria/AdminDocumentos/Resources/Schemas/NMPAdministraDocumentosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="crearPlantillaResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc"/>
            <oracle-xsl-mapper:param name="crearPlantillaResponse"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPFlujoVehiculosSinResguardoSvcXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="iniciarFlujoVehiculoSinResguardoRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE MAR 07 14:17:59 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="newFolio"/>
   <xsl:param name="crearPlantillaResponse"/>
   <xsl:template match="/">
      <tns:iniciarFlujoVehiculoSinResguardoRequest>
         <tns:folio>
            <xsl:value-of select="$newFolio"/>
         </tns:folio>
         <tns:estadoSolicitud>1</tns:estadoSolicitud>
         <tns:estadoFlujoBpm>1</tns:estadoFlujoBpm>
         <tns:idProducto>
            <xsl:value-of select="/ns0:generarSolicitudRequest/tns:idProducto"/>
         </tns:idProducto>
         <tns:nombreProducto>
            <xsl:value-of select="/ns0:generarSolicitudRequest/tns:nombreProducto"/>
         </tns:nombreProducto>
         <tns:idSubProducto>
            <xsl:value-of select="/ns0:generarSolicitudRequest/tns:idSubProducto"/>
         </tns:idSubProducto>
         <tns:cliente>
            <tns:numeroCliente>
               <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cliente/tns:numeroCliente"/>
            </tns:numeroCliente>
         </tns:cliente>
         <tns:vehiculo>
            <veh:tipoVehiculo>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:tipoVehiculo"/>
            </veh:tipoVehiculo>
            <veh:vin>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:vin"/>
            </veh:vin>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:serieMotor">
               <veh:serieMotor>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:serieMotor"/>
               </veh:serieMotor>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:placas">
               <veh:placas>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:placas"/>
               </veh:placas>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:engomado">
               <veh:engomado>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:engomado/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:engomado/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:engomado"/>
               </veh:engomado>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca">
               <veh:marca>
                  <veh:idMarca>
                     <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca"/>
                  </veh:idMarca>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:descripcion">
                     <veh:descripcion>
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:descripcion"/>
                     </veh:descripcion>
                  </xsl:if>
               </veh:marca>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca">
               <veh:submarca>
                  <veh:idSubMarca>
                     <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca"/>
                  </veh:idSubMarca>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:descripcion">
                     <veh:descripcion>
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:descripcion"/>
                     </veh:descripcion>
                  </xsl:if>
               </veh:submarca>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo">
               <veh:modelo>
                  <veh:idModelo>
                     <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo"/>
                  </veh:idModelo>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:descripcion">
                     <veh:descripcion>
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:descripcion"/>
                     </veh:descripcion>
                  </xsl:if>
               </veh:modelo>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version">
               <veh:version>
                  <veh:idVersion>
                     <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion"/>
                  </veh:idVersion>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:descripcion">
                     <veh:descripcion>
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:descripcion"/>
                     </veh:descripcion>
                  </xsl:if>
               </veh:version>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje">
               <veh:kilometraje>
                  <veh:idKilometraje>
                     <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje"/>
                  </veh:idKilometraje>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:descripcion">
                     <veh:descripcion>
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:descripcion"/>
                     </veh:descripcion>
                  </xsl:if>
               </veh:kilometraje>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:complementos">
               <veh:complementos>
                  <xsl:for-each select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:complementos/veh:complemento">
                     <veh:complemento>
                        <xsl:if test="@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <veh:idComplemento>
                           <xsl:if test="veh:idComplemento/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="veh:idComplemento/@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <xsl:value-of select="veh:idComplemento"/>
                        </veh:idComplemento>
                        <xsl:if test="veh:descripcion">
                           <veh:descripcion>
                              <xsl:value-of select="veh:descripcion"/>
                           </veh:descripcion>
                        </xsl:if>
                     </veh:complemento>
                  </xsl:for-each>
               </veh:complementos>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:color">
               <veh:color>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:color"/>
               </veh:color>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:serieChasis">
               <veh:serieChasis>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:serieChasis"/>
               </veh:serieChasis>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:numeroTarjetaCirculacion">
               <veh:numeroTarjetaCirculacion>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:numeroTarjetaCirculacion"/>
               </veh:numeroTarjetaCirculacion>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:numeroFactura">
               <veh:numeroFactura>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:numeroFactura"/>
               </veh:numeroFactura>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:rfcEmisor">
               <veh:rfcEmisor>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:rfcEmisor"/>
               </veh:rfcEmisor>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:agenciaOrigen">
               <veh:agenciaOrigen>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:agenciaOrigen"/>
               </veh:agenciaOrigen>
            </xsl:if>
            <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:comentarios">
               <veh:comentarios>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:comentarios"/>
               </veh:comentarios>
            </xsl:if>
         </tns:vehiculo>
         <xsl:if test="/ns0:generarSolicitudRequest/tns:cotizacion">
            <tns:cotizacion>
               <cot:montoAvaluo>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoAvaluo"/>
               </cot:montoAvaluo>
               <cot:montoMinimoPrestamo>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoMinimoPrestamo"/>
               </cot:montoMinimoPrestamo>
               <cot:montoMaximoPrestamo>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoMaximoPrestamo"/>
               </cot:montoMaximoPrestamo>
               <cot:montoPrestamoSolicitado>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoPrestamoSolicitado"/>
               </cot:montoPrestamoSolicitado>
               <xsl:if test="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoCastigo">
                  <cot:montoCastigo>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoCastigo"/>
                  </cot:montoCastigo>
               </xsl:if>
            </tns:cotizacion>
         </xsl:if>
         <tns:listaDocumentos>
            <NMPDoc:documentos>
                  <NMPDoc:nombreDocumento>
                     <xsl:value-of select="$crearPlantillaResponse/NMPDoc:plantilla/NMPDoc:nombre"/>
                  </NMPDoc:nombreDocumento>
                  <NMPDoc:documentoURL>
                     <xsl:value-of select="$crearPlantillaResponse/NMPDoc:plantilla/NMPDoc:objetoURL"/>
                  </NMPDoc:documentoURL>
                  <NMPDoc:documentoID>
                     <xsl:value-of select="$crearPlantillaResponse/NMPDoc:plantilla/NMPDoc:objetoID"/>
                  </NMPDoc:documentoID>
                  <NMPDoc:fechaCreacion>
                     <xsl:value-of select="$crearPlantillaResponse/NMPDoc:plantilla/NMPDoc:fechaCreacion"/>
                  </NMPDoc:fechaCreacion>
                  <NMPDoc:tipoDocumento>CARPETA</NMPDoc:tipoDocumento>
                  <NMPDoc:estado>
                     <xsl:value-of select="$crearPlantillaResponse/NMPDoc:plantilla/NMPDoc:estado"/>
                  </NMPDoc:estado>
                  <NMPDoc:descripcion>
                     <xsl:value-of select="$crearPlantillaResponse/NMPDoc:plantilla/NMPDoc:descripcion"/>
                  </NMPDoc:descripcion>
            </NMPDoc:documentos>
         </tns:listaDocumentos>
      </tns:iniciarFlujoVehiculoSinResguardoRequest>
   </xsl:template>
</xsl:stylesheet>