<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPGarantias" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:NMPIniciaASR="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:doc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:ct="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCommonTypes" xmlns:ava="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../SolicitudesVSR/Resources/Schemas/NMPSolicitudesVSRXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="consultarSolicitudResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../Garantias/Resources/Schemas/NMPGarantiasSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="crearGarantiaRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPGarantias"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON AUG 14 12:09:05 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="aNombreDe"/>
  <xsl:template match="/">
    <tns:crearGarantiaRequest>
      <tns:InformacionGarantia>
        <tns:numeroGarantia/>
        <tns:descripcionVehiculo>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:comentarios"/>
        </tns:descripcionVehiculo>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:montoFactura/text() != &quot;&quot;">
          <tns:montoFactura>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:montoFactura"/>
          </tns:montoFactura>
        </xsl:if>
        <tns:serieChasis>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieChasis"/>
        </tns:serieChasis>
        <tns:numeroFactura>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroFactura"/>
        </tns:numeroFactura>
        <tns:serieMotor>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieMotor"/>
        </tns:serieMotor>
        <tns:aNombreDe>
          <xsl:value-of select="substring($aNombreDe, 0, 80)"/>
        </tns:aNombreDe>
        <tns:descripcionMarca>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionMarca, 0, 40)"/>
        </tns:descripcionMarca>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:anio/text() != &quot;&quot;">
          <tns:anio>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:anio"/>
          </tns:anio>
        </xsl:if>
        <tns:color>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:color"/>
        </tns:color>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:capacidad/text() != &quot;&quot;">
          <tns:capacidad>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:capacidad"/>
          </tns:capacidad>
        </xsl:if>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numPuertas/text() != &quot;&quot;">
          <tns:numPuertas>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numPuertas"/>
          </tns:numPuertas>
        </xsl:if>
        <tns:uso>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:uso, 0, 80)"/>
        </tns:uso>
        <tns:complemento>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:nmpGrupoComplementosCollection/veh:NmpGrupoComplementos/veh:descripcion"/>
        </tns:complemento>
        <tns:placas>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:placas"/>
        </tns:placas>
        <tns:agenciaOrigen>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:agenciaOrigen"/>
        </tns:agenciaOrigen>
        <tns:descripcionModelo>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionModelo, 0, 40)"/>
        </tns:descripcionModelo>
        <tns:transmision>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:transmision, 0, 40)"/>
        </tns:transmision>
        <tns:combustible>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:combustible, 0, 40)"/>
        </tns:combustible>
        <tns:lugarEmisionFactura>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:lugarEmisionFactura"/>
        </tns:lugarEmisionFactura>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:usado">
          <xsl:choose>
            <xsl:when test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:usado = true ( )">
              <tns:esUsado>
                <xsl:value-of select="true ( )"/>
              </tns:esUsado>
            </xsl:when>
            <xsl:when test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:usado = false ( )">
            <tns:esUsado>
                <xsl:value-of select="false ( )"/>
              </tns:esUsado>
            </xsl:when>
            <xsl:otherwise/>
          </xsl:choose>
        </xsl:if>
        <tns:vin>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:vin"/>
        </tns:vin>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:prelacionCobro/text() != &quot;&quot;">
          <tns:prelacionCobro>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:prelacionCobro"/>
          </tns:prelacionCobro>
        </xsl:if>
        <tns:descripcionSubmarca>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionSubMarca, 0, 40)"/>
        </tns:descripcionSubmarca>
        <tns:descripcionVersion>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionVersion, 0, 40)"/>
        </tns:descripcionVersion>
        <tns:rfcEmisor>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:rfcEmisor"/>
        </tns:rfcEmisor>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:fechaEmisionFactura/text() != &quot;&quot;">
          <tns:fechaEmisionFactura>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:fechaEmisionFactura"/>
          </tns:fechaEmisionFactura>
        </xsl:if>
        <tns:ubicacionAgencia>
          <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:lugarEmisionFactura, 0, 100)"/>
        </tns:ubicacionAgencia>
        <tns:numeroTarjetaCirculacion>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroTarjetaCirculacion"/>
        </tns:numeroTarjetaCirculacion>
        <tns:engomado>
          <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:engomado"/>
        </tns:engomado>
      </tns:InformacionGarantia>
      <tns:ValorGarantia>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:fechaActualizacion/text() != &quot;&quot;">
          <tns:fechaActualizacion>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:fechaActualizacion"/>
          </tns:fechaActualizacion>
        </xsl:if>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoPrestamo/text() != &quot;&quot;">
          <tns:montoPrestamo>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoPrestamo"/>
          </tns:montoPrestamo>
        </xsl:if>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluo/text() != &quot;&quot; and /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador/text() != &quot;&quot;">
          <tns:montoGarantizado>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluo - /ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador"/>
          </tns:montoGarantizado>
        </xsl:if>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador/text() != &quot;&quot;">
          <tns:montoAvaluoDictaminador>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador"/>
          </tns:montoAvaluoDictaminador>
        </xsl:if>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionKilometraje/text() != &quot;&quot;">
          <tns:descripcionKilometraje>
            <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionKilometraje, 0, 40)"/>
          </tns:descripcionKilometraje>
        </xsl:if>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nombreDictaminador/text() != &quot;&quot;">
          <tns:nombreDictaminador>
            <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nombreDictaminador, 0, 120)"/>
          </tns:nombreDictaminador>
        </xsl:if>
        <xsl:if test="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:folioTramite/text() != &quot;&quot;">
          <tns:folioTramite>
            <xsl:value-of select="substring(/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:folioTramite, 0, 20)"/>
          </tns:folioTramite>
        </xsl:if>
      </tns:ValorGarantia>
    </tns:crearGarantiaRequest>
  </xsl:template>
</xsl:stylesheet>