<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:tns="http://xmlns.oracle.com/bpmn/bpmnProcess/GestionCreditoVSR" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:NMPCot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:NMPDoc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:NMPVeh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:NMPComun="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPsm="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/FlujoBPM" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessageBPM" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns6="http://xmlns.oracle.com/bpm/bpmobject/Data/CotizacionBO" xmlns:ns10="http://xmlns.oracle.com/bpm/bpmobject/Data/EstadoSolicitudBO" xmlns:ns12="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculoBPM" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns13="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/ComunBPM" xmlns:ns14="http://xmlns.oracle.com/bpm/bpmobject/Data/VehiculoBO" xmlns:ns3="http://xmlns.oracle.com/bpm/bpmobject/Data/FolioBO" xmlns:ns4="http://xmlns.oracle.com/bpm/bpmobject/Data/EquipoAdicionalBO" xmlns:ns5="http://xmlns.oracle.com/bpm/bpmobject/Data/DocumentosBO" xmlns:ns7="http://xmlns.oracle.com/bpm/bpmobject/Data/EstadoFlujoBPMBO" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns8="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvcBPM" xmlns:ns9="http://servicios.montedepiedad.com.mx/NMP/Schema/CotizadorBPM" xmlns:tns6="http://xmlns.oracle.com/bpm/bpmobject/Data/IniciarGestionBO" xmlns:ns11="http://xmlns.oracle.com/bpm/bpmobject/Data/ClienteBO">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPFlujoVehiculosSinResguardoSvcXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="iniciarFlujoVehiculoSinResguardoRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GestionCreditoVSR.wsdl"/>
            <oracle-xsl-mapper:rootElement name="start" namespace="http://xmlns.oracle.com/bpmn/bpmnProcess/GestionCreditoVSR"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED MAR 15 16:50:05 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:start>
         <tns6:IniciarGestionBO>
            <tns6:folio>
               <ns3:folio>
                  <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:folio"/>
               </ns3:folio>
            </tns6:folio>
            <tns6:cliente>
               <ns1:cliente>
                  <ns1:idCliente>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:cliente/ns0:idCliente"/>
                  </ns1:idCliente>
                  <ns1:numeroCredencial>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:cliente/ns0:numeroCredencial"/>
                  </ns1:numeroCredencial>
               </ns1:cliente>
            </tns6:cliente>
            <tns6:estadoFlujoBPM>
               <ns1:estadoFlujoBpm>
                  <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:estadoFlujoBpm"/>
               </ns1:estadoFlujoBpm>
            </tns6:estadoFlujoBPM>
            <tns6:estadoSolicitud>
               <ns1:estadoSolicitud>
                  <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:estadoSolicitud"/>
               </ns1:estadoSolicitud>
            </tns6:estadoSolicitud>
            <tns6:cotizacion>
               <ns1:cotizacion>
                  <ns9:montoAvaluo>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:cotizacion/NMPCot:montoAvaluo"/>
                  </ns9:montoAvaluo>
                  <ns9:montoMaximoPrestamo>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:cotizacion/NMPCot:montoMaximoPrestamo"/>
                  </ns9:montoMaximoPrestamo>
                  <ns9:montoPrestamoSolicitado>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:cotizacion/NMPCot:montoPrestamoSolicitado"/>
                  </ns9:montoPrestamoSolicitado>
                  <ns1:montoCastigo>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:cotizacion/NMPCot:montoCastigo"/>
                  </ns1:montoCastigo>
               </ns1:cotizacion>
            </tns6:cotizacion>
            <tns6:vehiculo>
               <ns14:datosVehiculo>
                  <ns12:tipoVehiculo>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:tipoVehiculo"/>
                  </ns12:tipoVehiculo>
                  <ns12:vin>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:vin"/>
                  </ns12:vin>
                  <ns12:serieMotor>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:serieMotor"/>
                  </ns12:serieMotor>
                  <ns12:placas>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:placas"/>
                  </ns12:placas>
                  <ns12:marca>
                     <ns12:idMarca>
                        <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:marca/NMPVeh:idMarca/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:marca/NMPVeh:idMarca/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:marca/NMPVeh:idMarca"/>
                     </ns12:idMarca>
                     <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:marca/NMPVeh:descripcion">
                        <ns12:descripcion>
                           <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:marca/NMPVeh:descripcion"/>
                        </ns12:descripcion>
                     </xsl:if>
                  </ns12:marca>
                  <ns12:submarca>
                     <ns12:idSubMarca>
                        <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:submarca/NMPVeh:idSubMarca/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:submarca/NMPVeh:idSubMarca/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:submarca/NMPVeh:idSubMarca"/>
                     </ns12:idSubMarca>
                     <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:submarca/NMPVeh:descripcion">
                        <ns12:descripcion>
                           <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:submarca/NMPVeh:descripcion"/>
                        </ns12:descripcion>
                     </xsl:if>
                  </ns12:submarca>
                  <ns12:modelo>
                     <ns12:idModelo>
                        <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:modelo/NMPVeh:idModelo/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:modelo/NMPVeh:idModelo/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:modelo/NMPVeh:idModelo"/>
                     </ns12:idModelo>
                     <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:modelo/NMPVeh:descripcion">
                        <ns12:descripcion>
                           <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:modelo/NMPVeh:descripcion"/>
                        </ns12:descripcion>
                     </xsl:if>
                  </ns12:modelo>
                  <ns12:version>
                     <ns12:idVersion>
                        <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:version/NMPVeh:idVersion/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:version/NMPVeh:idVersion/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:version/NMPVeh:idVersion"/>
                     </ns12:idVersion>
                     <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:version/NMPVeh:descripcion">
                        <ns12:descripcion>
                           <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:version/NMPVeh:descripcion"/>
                        </ns12:descripcion>
                     </xsl:if>
                  </ns12:version>
                  <ns12:kilometraje>
                     <ns12:idKilometraje>
                        <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:kilometraje/NMPVeh:idKilometraje/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:kilometraje/NMPVeh:idKilometraje/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:kilometraje/NMPVeh:idKilometraje"/>
                     </ns12:idKilometraje>
                     <xsl:if test="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:kilometraje/NMPVeh:descripcion">
                        <ns12:descripcion>
                           <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:kilometraje/NMPVeh:descripcion"/>
                        </ns12:descripcion>
                     </xsl:if>
                  </ns12:kilometraje>
                  <ns12:complementos>
                     <xsl:for-each select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:complementos/NMPVeh:complemento">
                        <ns12:complemento>
                           <xsl:if test="@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                 <xsl:value-of select="@xsi:nil"/>
                              </xsl:attribute>
                           </xsl:if>
                           <ns12:idComplemento>
                              <xsl:if test="NMPVeh:idComplemento/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="NMPVeh:idComplemento/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:value-of select="NMPVeh:idComplemento"/>
                           </ns12:idComplemento>
                           <xsl:if test="NMPVeh:descripcion">
                              <ns12:descripcion>
                                 <xsl:value-of select="NMPVeh:descripcion"/>
                              </ns12:descripcion>
                           </xsl:if>
                        </ns12:complemento>
                     </xsl:for-each>
                  </ns12:complementos>
                  <ns12:color>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:color"/>
                  </ns12:color>
                  <ns12:serieChasis>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:serieChasis"/>
                  </ns12:serieChasis>
                  <ns12:numeroTarjetaCirculacion>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:numeroTarjetaCirculacion"/>
                  </ns12:numeroTarjetaCirculacion>
                  <ns12:numeroFactura>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:numeroFactura"/>
                  </ns12:numeroFactura>
                  <ns12:rfcEmisor>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:rfcEmisor"/>
                  </ns12:rfcEmisor>
                  <ns12:agenciaOrigen>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:agenciaOrigen"/>
                  </ns12:agenciaOrigen>
                  <ns12:comentarios>
                     <xsl:value-of select="/ns0:iniciarFlujoVehiculoSinResguardoRequest/ns0:vehiculo/NMPVeh:comentarios"/>
                  </ns12:comentarios>
               </ns14:datosVehiculo>
            </tns6:vehiculo>
         </tns6:IniciarGestionBO>
      </tns:start>
   </xsl:template>
</xsl:stylesheet>