<wsdl:definitions
     name="CuentaContableDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BusApplication/CuentaContable/CuentaContableDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BusApplication/CuentaContable/CuentaContableDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CuentaContableDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="CuentaContableDB_plt" >
    <plt:role name="CuentaContableDB_role" >
      <plt:portType name="tns:CuentaContableDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CuentaContableDB" schemaLocation="CuentaContableDB.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CuentaContableDBInput_msg">
        <wsdl:part name="CuentaContableDBInput_msg" element="db:CuentaContableDBInput"/>
    </wsdl:message>
    <wsdl:message name="CuentaContableDBOutputCollection_msg">
        <wsdl:part name="CuentaContableDBOutputCollection" element="db:CuentaContableDBOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="CuentaContableDB_ptt">
        <wsdl:operation name="CuentaContableDB">
            <wsdl:input message="tns:CuentaContableDBInput_msg"/>
            <wsdl:output message="tns:CuentaContableDBOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
