<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:ns0="http://xmlns.oracle.com/xdb/GATEWAYS" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Services/Clientes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPsm="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:NMPsh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Campania">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/GATEWAYS_NMP_ACTUALIZA_CLIENTES_TYPE.xsd"/>
        <oracle-xsl-mapper:rootElement name="NMP_ACTUALIZA_CLIENTES_TYPE" namespace="http://xmlns.oracle.com/xdb/GATEWAYS"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../../Clientes/Resources/WSDL/NMPClientesWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="updateClienteRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI JUN 23 12:08:58 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:updateClienteRequest>
      <tns:idCliente>
        <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/ID_CLIENTE_CRM"/>
      </tns:idCliente>
      <tns:aplicacionMovil>1</tns:aplicacionMovil>
      <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/EMAIL)>0">
        <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDTIPOEMAIL)>0">
          <tns:CorreosElectronicos>
            <tns:CorreoElectronico>
              
                  <tns:email>
                    <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/EMAIL"/>
                  </tns:email>
                
              <xsl:if test="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDTIPOEMAIL = 3">
                <tns:tipoEmail>
                  <xsl:value-of select="'Personal'"/>
                </tns:tipoEmail>
              </xsl:if>
            </tns:CorreoElectronico>
          </tns:CorreosElectronicos>
        </xsl:if>
      </xsl:if>
      <tns:Contacto>
        <tns:ListaTelefonos>
          <tns:Telefono>
            <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/LADA)>0 ">
              <tns:codigoArea>
                <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/LADA"/>
              </tns:codigoArea>
            </xsl:if>
            <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/NUMERO)>0">
              <tns:numeroTelefonico>
                <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/NUMERO"/>
              </tns:numeroTelefonico>
            </xsl:if>
            <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/EXTENSION)>0">
              <tns:extension>
                <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/EXTENSION"/>
              </tns:extension>
            </xsl:if>
            <xsl:if test="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDTIPOTELEFONO = 1">
              <tns:tipoTelefono>
                <xsl:value-of select="'1'"/>
              </tns:tipoTelefono>
            </xsl:if>
            <xsl:if test="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDTIPOTELEFONO = 2">
              <tns:tipoTelefono>
                <xsl:value-of select="'2'"/>
              </tns:tipoTelefono>
            </xsl:if>
            <xsl:if test="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDTIPOTELEFONO = 3">
              <tns:tipoTelefono>
                <xsl:value-of select="'3'"/>
              </tns:tipoTelefono>
            </xsl:if>
            <xsl:if test="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDTIPOTELEFONO = 0">
              <tns:tipoTelefono>
                <xsl:value-of select="'4'"/>
              </tns:tipoTelefono>
            </xsl:if>
          </tns:Telefono>
        </tns:ListaTelefonos>
        
          <tns:ListaDirecciones>
            <tns:Direccion>
              <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/CALLE)>0">
                <tns:nombreDelaCalle>
                  <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/CALLE"/>
                </tns:nombreDelaCalle>
              </xsl:if>
              <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/NUMEROEXTERIOR)>0">
                <tns:numeroExterior>
                  <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/NUMEROEXTERIOR"/>
                </tns:numeroExterior>
              </xsl:if>
              <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/NUMEROINTERIOR)>0">
                <tns:numeroInterior>
                  <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/NUMEROINTERIOR"/>
                </tns:numeroInterior>
              </xsl:if>
              <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDESTADO)>0">
                <tns:idEstado>
                  <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDESTADO"/>
                </tns:idEstado>
              </xsl:if>
              <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDMUNICIPIO)>0">
                <tns:idDelegacionMunicipio>
                  <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDMUNICIPIO"/>
                </tns:idDelegacionMunicipio>
              </xsl:if>
              <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDCODIGOPOSTAL)>0">
                <tns:codigoPostal>
                  <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/IDCODIGOPOSTAL"/>
                </tns:codigoPostal>
              </xsl:if>
              <xsl:if test="string-length  (/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/RS_TIPOVIVIENDAID)>0">
                <tns:tipoDomicilio>
                  <xsl:value-of select="/ns0:NMP_ACTUALIZA_CLIENTES_TYPE/RS_TIPOVIVIENDAID"/>
                </tns:tipoDomicilio>
              </xsl:if>
            </tns:Direccion>
          </tns:ListaDirecciones>

      </tns:Contacto>
    </tns:updateClienteRequest>
  </xsl:template>
</xsl:stylesheet>