<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectoBusDB/ProyectosFacade/ProyectosDBFacade" name="ProyectosDBFacade_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="ProyectosDBFacade.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectoBusDB/ProyectosFacade/ProyectosDBFacade"/>
    <wsdl:binding name="ProyectosDBFacade_ptt-binding" type="proy:ProyectosDBFacade_ptt" xmlns:proy="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectoBusDB/ProyectosFacade/ProyectosDBFacade">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="selectByPrimaryKey">
            <soap:operation soapAction="selectByPrimaryKey"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>