<wsdl:definitions targetNamespace="http://xmlns.oracle.com/BDUAplication/GestionClientes/BDActualizaRegistrosClientes-concreteWSDL" name="BDActualizaRegistrosClientes-concreteWSDL" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="BDActualizaRegistrosClientesDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/GestionClientes/BDActualizaRegistrosClientesDB"/>
  <wsdl:binding name="BDActualizaRegistrosClientesDB_ptt-binding" type="dbup:BDActualizaRegistrosClientesDB_ptt" xmlns:dbup="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/GestionClientes/BDActualizaRegistrosClientesDB">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="BDActualizaRegistrosClientesDB">
      <soap:operation soapAction="BDActualizaRegistrosClientesDB"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>