<wsdl:definitions name="BDActualizaRegistrosClientesDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/GestionClientes/BDActualizaRegistrosClientesDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/GestionClientes/BDActualizaRegistrosClientesDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/BDActualizaRegistrosClientesDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="BDActualizaRegistrosClientesDB_plt">
    <plt:role name="BDActualizaRegistrosClientesDB_role">
      <plt:portType name="tns:BDActualizaRegistrosClientesDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
     <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BDActualizaRegistrosClientesDB" schemaLocation="../Schemas/BDActualizaRegistrosClientesDB.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="BDActualizaRegistrosClientesDBInput_msg">
    <wsdl:part name="BDActualizaRegistrosClientesDBInput_msg" element="db:BDActualizaRegistrosClientesDBInput"/>
  </wsdl:message>
  <wsdl:portType name="BDActualizaRegistrosClientesDB_ptt">
    <wsdl:operation name="BDActualizaRegistrosClientesDB">
      <wsdl:input message="tns:BDActualizaRegistrosClientesDBInput_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>