<wsdl:definitions targetNamespace="http://xmlns.oracle.com/BDUBDU/GestionClientes/OSBBDUClientesConcrete" name="OSBBDUClientesConcrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
     <wsdl:import location="OSBBDUClientesAQ.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/aq/BDUBDU/GestionClientes/OSBBDUClientesAQ"/>
     <wsdl:binding name="Dequeue_pttSOAP11Binding" type="ren:Dequeue_ptt" xmlns:ren="http://xmlns.oracle.com/pcbpel/adapter/aq/BDUBDU/GestionClientes/OSBBDUClientesAQ">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="Dequeue">
      <soap:operation soapAction="Dequeue"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>