<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Servicios/Schema/Elementos/AppMonte" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPNotificacionesSMS" xmlns:NMPAppMonte="http://servicios.montedepiedad.com.mx/NMP/Servicios/Schema/Tipos/AppMonte">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPAppMonteSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="registrarClienteAppRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Servicios/Schema/Elementos/AppMonte"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Utileria/NotificacionesSMS/Resources/Schemas/NMPNotificacionesSMSXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="validarCodigoSMSRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPNotificacionesSMS"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI FEB 24 14:15:33 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns1:validarCodigoSMSRequest>
      <ns1:codigo>
        <xsl:value-of select="/ns0:registrarClienteAppRequest/NMPAppMonte:codigoVerificacion"/>
      </ns1:codigo>
      <ns1:credencialNmp>
        <xsl:value-of select="/ns0:registrarClienteAppRequest/NMPAppMonte:noCredencial"/>
      </ns1:credencialNmp>
      <ns1:Fuente>1</ns1:Fuente>
      <ns1:idCliente>
        <xsl:value-of select="/ns0:registrarClienteAppRequest/NMPAppMonte:idCliente"/>
      </ns1:idCliente>
      <ns1:NumTelefono>
        <xsl:value-of select="/ns0:registrarClienteAppRequest/NMPAppMonte:noTelefono"/>
      </ns1:NumTelefono>
    </ns1:validarCodigoSMSRequest>
  </xsl:template>
</xsl:stylesheet>