<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nmp="http://servicios.montedepiedad.com.mx/NMP/Service/NMPUsuariosExternos" xmlns:nmpm="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:ctx="http://www.bea.com/wli/sb/context" xmlns:ctx1="http://www.bea.com/wli/sb/stages/transform/config">
    <xsl:include href="../../../../Common/XSLT/TemplateFaultsMontePiedadV2.xsl"/>
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source/>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets/>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE AUG 29 17:53:24 CDT 2017].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:param name="operacionServicio"/>
    <xsl:template match="/">
        <Fault>
            <xsl:variable name="fault" select="ctx:fault"/>
            <xsl:variable name="beaCode" select="ctx:fault/ctx:errorCode"/>
            <Code>
                <Value>soap:Receiver</Value>
                <Subcode>
                    <Value>nmp:adminCuentasExternasFault</Value>
                </Subcode>
            </Code>
            <Reason>
                <Text xml:lang="es">
                    <xsl:choose>
                        <xsl:when test="starts-with ($beaCode, &quot;USER_OSB-&quot; )">
                            <xsl:call-template name="faultstring">
                                <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'USER_OSB-'))"/>
                                <xsl:with-param name="serviceName" select="$operacionServicio"/>
                            </xsl:call-template>
                        </xsl:when>
                        <xsl:otherwise>
                            <xsl:call-template name="faultstring">
                                <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'OSB-'))"/>
                                <xsl:with-param name="serviceName" select="$operacionServicio"/>
                            </xsl:call-template>
                        </xsl:otherwise>
                    </xsl:choose>
                </Text>
            </Reason>
            <Detail>
                <messageError>
                    <codigoError>
                        <xsl:choose>
                            <xsl:when test="starts-with ($beaCode, &quot;USER_OSB-&quot; )">
                                <xsl:call-template name="codigoError">
                                    <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'USER_OSB-'))"/>
                                </xsl:call-template>
                            </xsl:when>
                            <xsl:otherwise>
                                <xsl:call-template name="codigoError">
                                    <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'OSB-'))"/>
                                </xsl:call-template>
                            </xsl:otherwise>
                        </xsl:choose>
                    </codigoError>
                    <descripcionError>
                        <xsl:choose>
                            <xsl:when test="starts-with ($beaCode, &quot;USER_OSB-&quot; )">
                                <xsl:value-of select="$fault/ctx:reason"/>
                            </xsl:when>
                            <xsl:otherwise>
                                <xsl:choose>
                                    <xsl:when test="$fault//ctx1:ReceivedFaultDetail/ctx1:detail/nmpm:messageError/nmpm:descripcionError">
                                        <xsl:value-of select="$fault//ctx1:ReceivedFaultDetail/ctx1:detail/nmpm:messageError/nmpm:descripcionError"/>
                                    </xsl:when>
                                    <xsl:otherwise>
                                        <xsl:call-template name="descripcionError">
                                            <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'OSB-'))"/>
                                            <xsl:with-param name="serviceName" select="$operacionServicio"/>
                                            <xsl:with-param name="fault" select="$fault"/>
                                        </xsl:call-template>
                                    </xsl:otherwise>
                                </xsl:choose>
                            </xsl:otherwise>
                        </xsl:choose>
                    </descripcionError>
                    <tipoError>
                        <xsl:choose>
                            <xsl:when test="starts-with ($beaCode, &quot;USER_OSB-&quot; )">
                                <xsl:call-template name="tipoError">
                                    <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'USER_OSB-'))"/>
                                </xsl:call-template>
                            </xsl:when>
                            <xsl:otherwise>
                                <xsl:call-template name="tipoError">
                                    <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'OSB-'))"/>
                                </xsl:call-template>
                            </xsl:otherwise>
                        </xsl:choose>
                    </tipoError>
                    <severidad>
                        <xsl:choose>
                            <xsl:when test="starts-with ($beaCode, &quot;USER_OSB-&quot; )">
                                <xsl:call-template name="severidad">
                                    <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'USER_OSB-'))"/>
                                </xsl:call-template>
                            </xsl:when>
                            <xsl:otherwise>
                                <xsl:call-template name="severidad">
                                    <xsl:with-param name="errorCode" select="number(substring-after ($beaCode, 'OSB-'))"/>
                                </xsl:call-template>
                            </xsl:otherwise>
                        </xsl:choose>
                    </severidad>
                </messageError>
            </Detail>
        </Fault>
    </xsl:template>
</xsl:stylesheet>