<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultarObservaciones" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPM-QUALITAS-PAGOS_ADMINISTRATIVOS/BpmPagosAdministrativos/ConsultarObservaciones" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BPM-QUALITAS-PAGOS_ADMINISTRATIVOS/BpmPagosAdministrativos/ConsultarObservaciones" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarObservaciones" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="ConsultarObservaciones_plt">
      <plt:role name="ConsultarObservaciones_role">
         <plt:portType name="tns:ConsultarObservaciones_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarObservaciones" schemaLocation="../Schemas/ConsultarObservaciones.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ConsultarObservacionesInput_msg">
      <wsdl:part name="ConsultarObservacionesInput_msg" element="db:ConsultarObservacionesInput"/>
   </wsdl:message>
   <wsdl:message name="ConsultarObservacionesOutputCollection_msg">
      <wsdl:part name="ConsultarObservacionesOutputCollection" element="db:ConsultarObservacionesOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="ConsultarObservaciones_ptt">
      <wsdl:operation name="ConsultarObservaciones">
         <wsdl:input message="tns:ConsultarObservacionesInput_msg"/>
         <wsdl:output message="tns:ConsultarObservacionesOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
