<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultaMotivoRechazo" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BPM-QUALITAS-PAGOS_ADMINISTRATIVOS/BpmPagosAdministrativos/ConsultaMotivoRechazo" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/BPM-QUALITAS-PAGOS_ADMINISTRATIVOS/BpmPagosAdministrativos/ConsultaMotivoRechazo" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaMotivoRechazo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="ConsultaMotivoRechazo_plt">
      <plt:role name="ConsultaMotivoRechazo_role">
         <plt:portType name="tns:ConsultaMotivoRechazo_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultaMotivoRechazo" schemaLocation="../Schemas/ConsultaMotivoRechazo.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ConsultaMotivoRechazoInput_msg">
      <wsdl:part name="ConsultaMotivoRechazoInput_msg" element="db:ConsultaMotivoRechazoInput"/>
   </wsdl:message>
   <wsdl:message name="ConsultaMotivoRechazoOutputCollection_msg">
      <wsdl:part name="ConsultaMotivoRechazoOutputCollection" element="db:ConsultaMotivoRechazoOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="ConsultaMotivoRechazo_ptt">
      <wsdl:operation name="ConsultaMotivoRechazo">
         <wsdl:input message="tns:ConsultaMotivoRechazoInput_msg"/>
         <wsdl:output message="tns:ConsultaMotivoRechazoOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
