<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="urn:sap-com:document:sap:rfc:functions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Persona" xmlns:OrdT="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/OrdenesTrabajo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Cliente" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPSvcOrdenesTrabajoElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="actualizarGestionOrdenRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsMovilidadCapturaWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZLM_RFC_CAPTURA" namespace="urn:sap-com:document:sap:rfc:functions"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU JUL 28 17:20:48 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ZLM_RFC_CAPTURA>
      <BP>
        <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:idCliente"/>
      </BP>
      <CONSULTADEBURODECREDITO>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:primerNombre">
          <NOMBRE1>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:primerNombre"/>
          </NOMBRE1>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:segundoNombre">
          <NOMBRE2>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:segundoNombre"/>
          </NOMBRE2>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoPaterno">
          <APELLIDO_PATERNO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoPaterno"/>
          </APELLIDO_PATERNO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoMaterno">
          <APELLIDO_MATERNO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoMaterno"/>
          </APELLIDO_MATERNO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ocupacion">
          <OCUPACION>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ocupacion"/>
          </OCUPACION>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:sector">
          <SECTORCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:sector"/>
          </SECTORCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:actividadEconomica">
          <ACTECONOMICACB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:actividadEconomica"/>
          </ACTECONOMICACB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:genero">
          <GENEROCB>
             <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:genero"/>           
          </GENEROCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento">
          <!--Ejemplo Entrada: 1991-09-28-->
          <!--Ejemplo Salida: 28/09/1991-->
          <FNACIMIENTOCB>
            <xsl:value-of select="concat(substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento,9,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento,6,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento,1,4))"/>
          </FNACIMIENTOCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:rfc">
          <RFCCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:rfc"/>
          </RFCCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:nombreDeLaCalle">
          <CALLECB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:nombreDeLaCalle"/>
          </CALLECB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroExterior">
          <NOEXTCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroExterior"/>
          </NOEXTCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroInterior">
          <NOINTCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroInterior"/>
          </NOINTCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:manzana">
          <MANZANACB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:manzana"/>
          </MANZANACB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:lote">
          <LOTECB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:lote"/>
          </LOTECB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:estado">
          <ESTADOCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:estado"/>
          </ESTADOCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:delegacionMunicipio">
          <DELEGACIONCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:delegacionMunicipio"/>
          </DELEGACIONCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:codigoPostal">
          <CPCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:codigoPostal"/>
          </CPCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:colonia">
          <COLONIACB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:colonia"/>
          </COLONIACB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:localidad">
          <LOCALIDADCB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:localidad"/>
          </LOCALIDADCB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle1">
          <ENTRECALLE1CB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle1"/>
          </ENTRECALLE1CB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle2">
          <ENTRECALLE2CB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle2"/>
          </ENTRECALLE2CB>
        </xsl:if>
      </CONSULTADEBURODECREDITO>
      <DATOSBANCARIOS>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DatosBancarios/OrdT:banco">
          <BANCO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DatosBancarios/OrdT:banco"/>
          </BANCO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DatosBancarios/OrdT:numCuenta">
          <NUMCUENTA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DatosBancarios/OrdT:numCuenta"/>
          </NUMCUENTA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DatosBancarios/OrdT:tipoCuenta">
          <TIPOCUENTA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DatosBancarios/OrdT:tipoCuenta"/>
          </TIPOCUENTA>
        </xsl:if>
      </DATOSBANCARIOS>
      <DATOSDELCLIENTE>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:primerNombre">
          <PRIMERNOMBRESOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:primerNombre"/>
          </PRIMERNOMBRESOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:segundoNombre">
          <SEGUNDONOMBRESOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:segundoNombre"/>
          </SEGUNDONOMBRESOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoPaterno">
          <APPATERNOSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoPaterno"/>
          </APPATERNOSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoMaterno">
          <APMATERNOSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:apellidoMaterno"/>
          </APMATERNOSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ocupacion">
          <ACTIVIDADSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ocupacion"/>
          </ACTIVIDADSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:actividadEconomica">
          <ACTECONOMICASOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:actividadEconomica"/>
          </ACTECONOMICASOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:genero">
          <GENEROSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:genero"/>
          </GENEROSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento">
          <FECHA_NACIMIENTO>
           <!--Ejemplo Entrada: 1991-09-28-->
          <!--Ejemplo Salida: 28/09/1991-->
            <xsl:value-of select="concat(substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento,9,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento,6,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:fechaDeNacimiento,1,4))"/>
            </FECHA_NACIMIENTO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:edad">
          <EDADS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:edad"/>
          </EDADS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:rfc">
          <RFCSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:rfc"/>
          </RFCSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:curp">
          <CURPSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:curp"/>
          </CURPSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:estadoCivil">
          <ESTADO_CIVIL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:estadoCivil"/>
          </ESTADO_CIVIL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:primerNombreConyuge">
          <NOMBRECONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:primerNombreConyuge"/>
          </NOMBRECONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:segundoNombreConyuge">
          <NOMBRE2CONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:segundoNombreConyuge"/>
          </NOMBRE2CONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:apellidoPaternoConyuge">
          <APPATERNOCONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:apellidoPaternoConyuge"/>
          </APPATERNOCONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:apellidoMaternoConyuge">
          <APMATERNOCONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:apellidoMaternoConyuge"/>
          </APMATERNOCONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:TelefonosConyuge/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico">
          <TELDOMCONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:TelefonosConyuge/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico"/>
          </TELDOMCONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:TelefonosConyuge/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:numeroTelefonico">
          <TELTRABCONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:TelefonosConyuge/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:numeroTelefonico"/>
          </TELTRABCONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:TelefonosConyuge/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico">
          <TELCELCONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:TelefonosConyuge/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico"/>
          </TELCELCONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:mailConyuge">
          <MAILCONYSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:DatosConyuge/OrdT:mailConyuge"/>
          </MAILCONYSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:escolaridad">
          <ESCOLARIDAD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:escolaridad"/>
          </ESCOLARIDAD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:nacionalidad">
          <NACIONALIDAD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:nacionalidad"/>
          </NACIONALIDAD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:pais">
          <PAISNACSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:pais"/>
          </PAISNACSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:email">
          <EMAILSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:email"/>
          </EMAILSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:sector">
          <SECTORSOL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:sector"/>
          </SECTORSOL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:dependienteEconomico">
          <DEPENECONO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:dependienteEconomico"/>
          </DEPENECONO>
        </xsl:if>
      </DATOSDELCLIENTE>
      <DATOSDELCONTACTOYDOMICILIO>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:nombreDeLaCalle">
          <CALLE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:nombreDeLaCalle"/>
          </CALLE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroExterior">
          <NUMERO_EXTERIOR>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroExterior"/>
          </NUMERO_EXTERIOR>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroInterior">
          <NUMERO_INTERIOR>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroInterior"/>
          </NUMERO_INTERIOR>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:manzana">
          <MANZANADCD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:manzana"/>
          </MANZANADCD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:lote">
          <LOTEDCD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:lote"/>
          </LOTEDCD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:codigoPostal">
          <CODIGO_POSTAL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:codigoPostal"/>
          </CODIGO_POSTAL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:colonia">
          <COLONIA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:colonia"/>
          </COLONIA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:delegacionMunicipio">
          <MUNICIPIO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:delegacionMunicipio"/>
          </MUNICIPIO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:estado">
          <ESTADO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:estado"/>
          </ESTADO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:localidad">
          <LOCALIDADDCD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:localidad"/>
          </LOCALIDADDCD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle1">
          <ENTRECALLE1DCD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle1"/>
          </ENTRECALLE1DCD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle2">
          <ENTRECALLE2DCD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:entreCalle2"/>
          </ENTRECALLE2DCD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:codigoArea">
          <LADA_CASA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:codigoArea"/>
          </LADA_CASA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico">
          <TELEFONO_CASA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico"/>
          </TELEFONO_CASA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:codigoArea">
          <LADA_CELULAR>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:codigoArea"/>
          </LADA_CELULAR>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico">
          <TELEFONO_CELULAR>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico"/>
          </TELEFONO_CELULAR>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='3']/OrdT:codigoArea">
          <LADA_RECADOS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='3']/OrdT:codigoArea"/>
          </LADA_RECADOS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='3']/OrdT:numeroTelefonico">
          <TELEFONO_RECADOS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='3']/OrdT:numeroTelefonico"/>
          </TELEFONO_RECADOS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:email">
          <CORREODC>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:email"/>
          </CORREODC>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:fechaComienzoVivir">
          <FECHAVIVIRCDC>
           <!--Ejemplo Entrada: 1991-09-28-->
          <!--Ejemplo Salida: 28/09/1991-->
            <xsl:value-of select="concat(substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:fechaComienzoVivir,9,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:fechaComienzoVivir,6,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:fechaComienzoVivir,1,4))"/>
          </FECHAVIVIRCDC>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:tipoDomicilio">
          <TIPOVIVIENDA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:tipoDomicilio"/>
          </TIPOVIVIENDA>
        </xsl:if>
      </DATOSDELCONTACTOYDOMICILIO>
      <DATOS_BP_PRESOL>
        <ID_CLIENTE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Cliente/OrdT:idCliente"/>
        </ID_CLIENTE>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:primerNombre">
          <NOMBRE1>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:primerNombre"/>
          </NOMBRE1>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:segundoNombre">
          <NOMBRE2>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:segundoNombre"/>
          </NOMBRE2>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:apellidoPaterno">
          <APPAT>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:apellidoPaterno"/>
          </APPAT>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:apellidoMaterno">
          <APMAT>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:apellidoMaterno"/>
          </APMAT>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:codigoArea">
          <CASALADA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:codigoArea"/>
          </CASALADA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico">
          <CASATEL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico"/>
          </CASATEL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:codigoArea">
          <CELLADA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:codigoArea"/>
          </CELLADA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico">
          <CELTEL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico"/>
          </CELTEL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:codigoArea">
          <TRABLADA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:codigoArea"/>
          </TRABLADA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:numeroTelefonico">
          <TRABTEL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:numeroTelefonico"/>
          </TRABTEL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:extension">
          <TRABEXT>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:extension"/>
          </TRABEXT>
        </xsl:if>
        <!--Se truncan datos a 40 posiciones -->
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:nombreDeLaCalle">
          <CALLE>
            <xsl:value-of select="substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:nombreDeLaCalle,0,40)"/>
          </CALLE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroExterior">
          <NUMEXT>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroExterior"/>
          </NUMEXT>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroInterior">
          <NUMINT>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:numeroInterior"/>
          </NUMINT>
        </xsl:if>
        <!--Se truncan datos a 40 posiciones -->
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:colonia">
          <COLONIA>
            <xsl:value-of select="substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:colonia,0,40)"/>
          </COLONIA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:codigoPostal">
          <CODPOSTAL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:codigoPostal"/>
          </CODPOSTAL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:delegacionMunicipio">
          <DELMUNIP>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:delegacionMunicipio"/>
          </DELMUNIP>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:estado">
          <ESTADO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:ContactoDomicilio/OrdT:Direccion/OrdT:estado"/>
          </ESTADO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:estadoCivil">
          <EDOCIVIL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:estadoCivil"/>
          </EDOCIVIL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:escolaridad">
          <ESCOLARIDAD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:escolaridad"/>
          </ESCOLARIDAD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:fechaDeNacimiento">
          <FECNAC>
             <!--Ejemplo Entrada: 1991-09-28-->
             <!--Ejemplo Salida: 28/09/1991-->
            <xsl:value-of select="concat(substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:fechaDeNacimiento,9,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:fechaDeNacimiento,6,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:fechaDeNacimiento,1,4))"/>
          </FECNAC>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:nacionalidad">
          <NACIONALIDAD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:nacionalidad"/>
          </NACIONALIDAD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:siva">
          <SIVA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:siva"/>
          </SIVA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:probabilidadIncumplimiento">
          <PROBINCUMP>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:probabilidadIncumplimiento"/>
          </PROBINCUMP>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:capacidadPago">
          <CAPPAGO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:capacidadPago"/>
          </CAPPAGO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:montoPrestamo">
          <PRESTAMOS_NMP>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:montoPrestamo"/>
          </PRESTAMOS_NMP>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:montoPago">
          <PAGOS_NMP>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:montoPago"/>
          </PAGOS_NMP>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:montoPrestamoProm">
          <PRESTAMO_PROM>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:montoPrestamoProm"/>
          </PRESTAMO_PROM>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:prestamoPromocionVal">
          <PRESTA_PROM_VALU>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:prestamoPromocionVal"/>
          </PRESTA_PROM_VALU>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:numDesempenios">
          <DESEMPENIO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionPreSolicitud/OrdT:numDesempenios"/>
          </DESEMPENIO>
        </xsl:if>
      </DATOS_BP_PRESOL>
      <DOCUMENTACIONDELCLIENTE>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosSC/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTO',position(),'SC')"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCB/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTO',position(),'CB')"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosIdOficial/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTOID',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosIdOficial/OrdT:tipoIdOficial">
          <TIPOIDENTIFICACIONOFICIAL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosIdOficial/OrdT:tipoIdOficial"/>
          </TIPOIDENTIFICACIONOFICIAL>
        </xsl:if>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompDom/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTOCOMPDOM',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompDom/OrdT:tipoComprobanteDom">
          <TIPOCOMPROBANTEDOMICILIO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompDom/OrdT:tipoComprobanteDom"/>
          </TIPOCOMPROBANTEDOMICILIO>
        </xsl:if>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompViv/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTOCOMPVIV',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompViv/OrdT:tipoComprobanteViv">
          <TIPOCOMPROBANTEVIVIENDA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompViv/OrdT:tipoComprobanteViv"/>
          </TIPOCOMPROBANTEVIVIENDA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompIngEmp/OrdT:comprobanteIngresosAct">
          <COMPROBANTEINGRESOSACTIVIDAD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompIngEmp/OrdT:comprobanteIngresosAct"/>
          </COMPROBANTEINGRESOSACTIVIDAD>
        </xsl:if>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompIngEmp/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTOCOMPINGEMP',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompIngNeg/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTOCOMPINGNEG',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCompIngOtro/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTOCOMPOTROSING',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:DocumentacionCliente/OrdT:FotosCliente/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('FOTOCLIENTE',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
      </DOCUMENTACIONDELCLIENTE>
      <FORMIIKRESPONSESOURCE>
        <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:origenRespuesta"/>
      </FORMIIKRESPONSESOURCE>
      <GEOLOCALIZACIONCASANEGOCIO>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GeolocalizacionCasaNegocio/OrdT:gps">
          <GPS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GeolocalizacionCasaNegocio/OrdT:gps"/>
          </GPS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GeolocalizacionCasaNegocio/OrdT:gpsNegocioEmpleo">
          <GPSNEGOCIOEMPLEO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GeolocalizacionCasaNegocio/OrdT:gpsNegocioEmpleo"/>
          </GPSNEGOCIOEMPLEO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GeolocalizacionCasaNegocio/OrdT:cotejo">
          <COTEJO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GeolocalizacionCasaNegocio/OrdT:cotejo"/>
          </COTEJO>
        </xsl:if>
      </GEOLOCALIZACIONCASANEGOCIO>
      <INFORMACIONFINANCIERA>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:ventasMensuales">
          <VENTASMENSUALES>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:ventasMensuales"/>
          </VENTASMENSUALES>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:compras">
          <COMPRAS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:compras"/>
          </COMPRAS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:inventario">
          <INVENTARIO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:inventario"/>
          </INVENTARIO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:utilidadBruta">
          <UTILIDADBRUTA>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:utilidadBruta"/>
          </UTILIDADBRUTA>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:gastosOperativos">
          <GASTOSOPERATIVOS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:gastosOperativos"/>
          </GASTOSOPERATIVOS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:sueldos">
          <SUELDOS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:sueldos"/>
          </SUELDOS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:deudasNegocio">
          <DEUDASNEGOCIO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:deudasNegocio"/>
          </DEUDASNEGOCIO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:serviciosPublicosNegocio">
          <SERVICIOSPUBNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:serviciosPublicosNegocio"/>
          </SERVICIOSPUBNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:transporteNegocio">
          <TRANSPORTENEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:transporteNegocio"/>
          </TRANSPORTENEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:rentaNegocio">
          <RENTANEGOCIO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:rentaNegocio"/>
          </RENTANEGOCIO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:alimentacionNeg">
          <ALIMENTACIONNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:alimentacionNeg"/>
          </ALIMENTACIONNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosgastosNegocio">
          <OTROSGASTOSNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosgastosNegocio"/>
          </OTROSGASTOSNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:gastosFamiliares">
          <GASTOSFAMILIARES>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:gastosFamiliares"/>
          </GASTOSFAMILIARES>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:deudasBuroNegocio">
          <DEUDASBURONEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:deudasBuroNegocio"/>
          </DEUDASBURONEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:pagosRealNegocio">
          <PAGOSREALNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:pagosRealNegocio"/>
          </PAGOSREALNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:totalGastosNegocio">
          <TOTALGASTOSNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:totalGastosNegocio"/>
          </TOTALGASTOSNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosIngresosNegocio">
          <OTROSINGNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosIngresosNegocio"/>
          </OTROSINGNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngresosNegocio">
          <TIPOOTROSINGNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngresosNegocio"/>
          </TIPOOTROSINGNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:excedente">
          <EXCEDENTE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:excedente"/>
          </EXCEDENTE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:ingresoMensual">
          <INGRESOMENSUAL>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:ingresoMensual"/>
          </INGRESOMENSUAL>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:impuestosRetenidos">
          <IMPUESTOSRETEN>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:impuestosRetenidos"/>
          </IMPUESTOSRETEN>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosIngresosDiferidosNegocio">
          <OTROSINGRDIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosIngresosDiferidosNegocio"/>
          </OTROSINGRDIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngesosNegocio">
          <TIPOOTROSINGRNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngesosNegocio"/>
          </TIPOOTROSINGRNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:totalIngresosNegocio">
          <TOTALINGRESOSNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:totalIngresosNegocio"/>
          </TOTALINGRESOSNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:gastosFamDiferidosNegocio">
          <GASTOSFAMDIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:gastosFamDiferidosNegocio"/>
          </GASTOSFAMDIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:alimentacionDiferidoNegocio">
          <ALIMENTADIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:alimentacionDiferidoNegocio"/>
          </ALIMENTADIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:educacionDiferidaNegocio">
          <EDUCACIONDIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:educacionDiferidaNegocio"/>
          </EDUCACIONDIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:serviciosPublicosDiferidosNegocio">
          <SERVICIOPUBDIFN>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:serviciosPublicosDiferidosNegocio"/>
          </SERVICIOPUBDIFN>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:transporteDiferidoNegocio">
          <TRANSPORTEDIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:transporteDiferidoNegocio"/>
          </TRANSPORTEDIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:rentaDiferidoNegocio">
          <RENTADIFNEGOCIO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:rentaDiferidoNegocio"/>
          </RENTADIFNEGOCIO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:vestidoDiferidoNegocio">
          <VESTIDODIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:vestidoDiferidoNegocio"/>
          </VESTIDODIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosGastosDiferidosNegocio">
          <OTROSGASTOSDIFN>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:otrosGastosDiferidosNegocio"/>
          </OTROSGASTOSDIFN>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:deudasBuroDiferidoNegocio">
          <DEUDASBURODIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:deudasBuroDiferidoNegocio"/>
          </DEUDASBURODIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:pagosRealDiferidoNegocio">
          <PAGOSREALDIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:pagosRealDiferidoNegocio"/>
          </PAGOSREALDIFNEG>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:totalGastosDiferidosNegocio">
          <TOTALGASTOSDIFN>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:totalGastosDiferidosNegocio"/>
          </TOTALGASTOSDIFN>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:excedenteDiferidoNegocio">
          <EXCEDENTEDIFNEG>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionFinanciera/OrdT:excedenteDiferidoNegocio"/>
          </EXCEDENTEDIFNEG>
        </xsl:if>
      </INFORMACIONFINANCIERA>
      <INFO_SOLICITUD>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:montoSolicitado"/>
        <MONTO_SOLIC>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:montoSolicitado"/>
        </MONTO_SOLIC>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:periodicidad">
          <PERIODICIDAD>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:periodicidad"/>
          </PERIODICIDAD>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:plazo">
          <PLAZO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:plazo"/>
          </PLAZO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:promotorAsignado">
          <ID_FORMIIK>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:promotorAsignado"/>
          </ID_FORMIIK>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:desembolso">
          <F_DESEMBOLSO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:desembolso"/>
          </F_DESEMBOLSO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:primaCobrable">
          <FPRIMCOB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:primaCobrable"/>
          </FPRIMCOB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:tablaAmortizacion">
          <T_AMORT>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:tablaAmortizacion"/>
          </T_AMORT>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:checkSeguro">
          <CHECK_SEGURO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:checkSeguro"/>
          </CHECK_SEGURO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:checkComision">
          <CHECK_COMISION>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:InformacionSolicitud/OrdT:checkComision"/>
          </CHECK_COMISION>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GestionVisita/OrdT:resultadoVisita">
          <RESVISITAVTAS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GestionVisita/OrdT:resultadoVisita"/>
          </RESVISITAVTAS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GestionVisita/OrdT:gestion">
          <GESTIONVTAS>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:GestionVisita/OrdT:gestion"/>
          </GESTIONVTAS>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ConsultaBuroCredito/OrdT:estatus">
          <ESTATUS_BURO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ConsultaBuroCredito/OrdT:estatus"/>
          </ESTATUS_BURO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ConsultaBuroCredito/OrdT:categoria">
          <CATEGORIA2>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ConsultaBuroCredito/OrdT:categoria"/>
          </CATEGORIA2>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ConsultaBuroCredito/OrdT:estatus2">
          <ESTATUS2>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:ConsultaBuroCredito/OrdT:estatus2"/>
          </ESTATUS2>
        </xsl:if>
      </INFO_SOLICITUD>
      <OCUPACIONECONOMICA>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:nombreEmpleo">
          <NOMBREEMPLEO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:nombreEmpleo"/>
          </NOMBREEMPLEO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:fechaIngreso">
          <FECHAINGRESOEMP>
             <!--Ejemplo Entrada: 1991-09-28-->
             <!--Ejemplo Salida: 28/09/1991-->
            <xsl:value-of select="concat(substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:fechaIngreso,9,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:fechaIngreso,6,2),'/',substring(/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:fechaIngreso,1,4))"/>
          </FECHAINGRESOEMP>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:codigoArea">
          <LADA_TRABAJO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:codigoArea"/>
          </LADA_TRABAJO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:numeroTelefonico">
          <TELEFONO_TRABAJO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:numeroTelefonico"/>
          </TELEFONO_TRABAJO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:extension">
          <EXTENSION_TRAB>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='4']/OrdT:extension"/>
          </EXTENSION_TRAB>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:domicilioMismoEmpleo">
          <DOMICILIOMISMO>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:domicilioMismoEmpleo"/>
          </DOMICILIOMISMO>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:nombreDeLaCalle">
          <CALLEOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:nombreDeLaCalle"/>
          </CALLEOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:numeroExterior">
          <NOEXTOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:numeroExterior"/>
          </NOEXTOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:numeroInterior">
          <NOINTOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:numeroInterior"/>
          </NOINTOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:manzana">
          <MANZANAOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:manzana"/>
          </MANZANAOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:lote">
          <LOTEOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:lote"/>
          </LOTEOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:codigoPostal">
          <CPOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:codigoPostal"/>
          </CPOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:colonia">
          <COLONIAOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:colonia"/>
          </COLONIAOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:delegacionMunicipio">
          <DELEGACIONOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:delegacionMunicipio"/>
          </DELEGACIONOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:estado">
          <ESTADOOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:estado"/>
          </ESTADOOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:localidad">
          <LOCALIDADOE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:localidad"/>
          </LOCALIDADOE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:entreCalle1">
          <ENTRECALLE1OE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:entreCalle1"/>
          </ENTRECALLE1OE>
        </xsl:if>
        <xsl:if test="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:entreCalle2">
          <ENTRECALLE2OE>
            <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:OcupacionEconomica/OrdT:ContactoDomicilioEmpleo/OrdT:Direccion/OrdT:entreCalle2"/>
          </ENTRECALLE2OE>
        </xsl:if>
      </OCUPACIONECONOMICA>
      <REFERENCIAS>
        <xsl:for-each select="/ns0:actualizarGestionOrdenRequest/OrdT:ResultadoGestion/OrdT:Referencias/OrdT:Referencia">
          <xsl:if test="OrdT:primerNombre">
            <xsl:variable name="refElementName" select="concat('PRIMERNOMBREREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:primerNombre"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:segundoNombre">
            <xsl:variable name="refElementName" select="concat('NOMBRE2REF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:segundoNombre"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:apellidoPaterno">
            <xsl:variable name="refElementName" select="concat('APPATERNOREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:apellidoPaterno"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:apellidoMaterno">
            <xsl:variable name="refElementName" select="concat('APEMATERNOREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:apellidoMaterno"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:parentesco">
            <xsl:variable name="refElementName" select="concat('PARENTESCOREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:parentesco"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico">
            <xsl:variable name="refElementName" select="concat('TELDOMICILIOREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico">
            <xsl:variable name="refElementName" select="concat('TELCELULARREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:nombreDeLaCalle">
            <xsl:variable name="refElementName" select="concat('CALLEREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:nombreDeLaCalle"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroExterior">
            <xsl:variable name="refElementName" select="concat('NOEXTREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroExterior"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroInterior">
            <xsl:variable name="refElementName" select="concat('NOINTREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroInterior"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:manzana">
            <xsl:variable name="refElementName" select="concat('MANZANAREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:manzana"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:lote">
            <xsl:variable name="refElementName" select="concat('LOTEREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:lote"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:codigoPostal">
            <xsl:variable name="refElementName" select="concat('CPREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:codigoPostal"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:colonia">
            <xsl:variable name="refElementName" select="concat('COLONIAREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:colonia"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:delegacionMunicipio">
            <xsl:variable name="refElementName" select="concat('DELEGACIONREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:delegacionMunicipio"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:estado">
            <xsl:variable name="refElementName" select="concat('ESTADOREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:estado"/>
            </xsl:element>
          </xsl:if>
          <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:localidad">
            <xsl:variable name="refElementName" select="concat('LOCALIDADREF',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:localidad"/>
            </xsl:element>
          </xsl:if>
        </xsl:for-each>
      </REFERENCIAS>
      <RESPONSE_HEADER>
        <PRODUCTID>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:idProducto"/>
        </PRODUCTID>
        <EXTERNALID>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:idExterno"/>
        </EXTERNALID>
        <EXTERNALTYPE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:tipoOrdenTrabajo"/>
        </EXTERNALTYPE>
        <ASSIGNEDTO>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:promotorAsignado"/>
        </ASSIGNEDTO>
        <INITIALDATE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:fechaInicial"/>
        </INITIALDATE>
        <FINALDATE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:fechaFinal"/>
        </FINALDATE>
        <RESPONSEDATE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:fechaRespuesta"/>
        </RESPONSEDATE>
        <INITIALLATITUDE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:DatosGeoespaciales/OrdT:latitudInicial"/>
        </INITIALLATITUDE>
        <FINALLATITUDE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:DatosGeoespaciales/OrdT:latitudFinal"/>
        </FINALLATITUDE>
        <INITIALLONGITUDE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:DatosGeoespaciales/OrdT:longitudInicial"/>
        </INITIALLONGITUDE>
        <FINALLONGITUDE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:DatosGeoespaciales/OrdT:longitudFinal"/>
        </FINALLONGITUDE>
        <FORMIIKRESPONSE>
          <xsl:value-of select="/ns0:actualizarGestionOrdenRequest/OrdT:DatosTransaccion/OrdT:origenRespuesta"/>
        </FORMIIKRESPONSE>
      </RESPONSE_HEADER>
    </tns:ZLM_RFC_CAPTURA>
  </xsl:template>
</xsl:stylesheet>