<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Persona" xmlns:OrdT="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/OrdenesTrabajo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Cliente" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:n0="urn:sap-com:document:sap:rfc:functions" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPSvcOrdenesTrabajoElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="actualizarPendientesOrdenRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsReinsercionWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmReFm005" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI JUL 29 16:02:35 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ZlmReFm005>
      <ActivEco>
        <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:actividadEconomica"/>
      </ActivEco>
      <IDatosContYDom>
        <LadaCasa>
          <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:codigoArea"/>
        </LadaCasa>
        <TelCasa>
          <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico"/>
        </TelCasa>
        <LadaCel>
          <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:codigoArea"/>
        </LadaCel>
        <TelCel>
          <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico"/>
        </TelCel>
        <LadaRecados>
          <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='3']/OrdT:codigoArea"/>
        </LadaRecados>
        <TelRecados>
          <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:ContactoDomicilio/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='3']/OrdT:numeroTelefonico"/>
        </TelRecados>
      </IDatosContYDom>
      <IDocCliente>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosSC/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Foto',position(),'sc')"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCB/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Foto',position(),'cb')"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosIdOficial/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Fotoid',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosIdOficial/OrdT:tipoIdOficial">
          <Tipoidentificacionoficial>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosIdOficial/OrdT:tipoIdOficial"/>
          </Tipoidentificacionoficial>
        </xsl:if>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompDom/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Fotocompdom',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompDom/OrdT:tipoComprobanteDom">
          <Tipocomprobantedomicilio>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompDom/OrdT:tipoComprobanteDom"/>
          </Tipocomprobantedomicilio>
        </xsl:if>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompViv/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Fotocompviv',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompViv/OrdT:tipoComprobanteViv">
          <Tipocomprobantevivienda>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompViv/OrdT:tipoComprobanteViv"/>
          </Tipocomprobantevivienda>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompIngEmp/OrdT:comprobanteIngresosAct">
          <Comprobanteingresosactividad>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompIngEmp/OrdT:comprobanteIngresosAct"/>
          </Comprobanteingresosactividad>
        </xsl:if>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompIngEmp/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Fotocompingemp',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompIngNeg/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Fotocompingneg',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCompIngOtro/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Fotocompotrosing',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
        <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:DocumentacionCliente/OrdT:FotosCliente/OrdT:Fotos">
          <xsl:variable name="fotoElementName" select="concat('Fotocliente',position())"/>
          <xsl:variable name="valor" select="OrdT:foto"/>
          <xsl:element name="{$fotoElementName}">
            <xsl:value-of select="$valor"/>
          </xsl:element>
        </xsl:for-each>
      </IDocCliente>
      <IInfFinanciera>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:ventasMensuales">
          <Ventasmensuales>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:ventasMensuales"/>
          </Ventasmensuales>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:compras">
          <Compras>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:compras"/>
          </Compras>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:inventario">
          <Inventario>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:inventario"/>
          </Inventario>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:utilidadBruta">
          <Utilidadbruta>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:utilidadBruta"/>
          </Utilidadbruta>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:gastosOperativos">
          <Gastosoperativos>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:gastosOperativos"/>
          </Gastosoperativos>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:sueldos">
          <Sueldos>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:sueldos"/>
          </Sueldos>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:deudasNegocio">
          <Deudasnegocio>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:deudasNegocio"/>
          </Deudasnegocio>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:serviciosPublicosNegocio">
          <Serviciospubneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:serviciosPublicosNegocio"/>
          </Serviciospubneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:transporteNegocio">
          <Transporteneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:transporteNegocio"/>
          </Transporteneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:rentaNegocio">
          <Rentanegocio>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:rentaNegocio"/>
          </Rentanegocio>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:alimentacionNeg">
          <Alimentacionneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:alimentacionNeg"/>
          </Alimentacionneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosgastosNegocio">
          <Otrosgastosneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosgastosNegocio"/>
          </Otrosgastosneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:gastosFamiliares">
          <Gastosfamiliares>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:gastosFamiliares"/>
          </Gastosfamiliares>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:deudasBuroNegocio">
          <Deudasburoneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:deudasBuroNegocio"/>
          </Deudasburoneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:pagosRealNegocio">
          <Pagosrealneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:pagosRealNegocio"/>
          </Pagosrealneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:totalGastosNegocio">
          <Totalgastosneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:totalGastosNegocio"/>
          </Totalgastosneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosIngresosNegocio">
          <Otrosingneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosIngresosNegocio"/>
          </Otrosingneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngresosNegocio">
          <Tipootrosingneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngresosNegocio"/>
          </Tipootrosingneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:excedente">
          <Excedente>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:excedente"/>
          </Excedente>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:ingresoMensual">
          <Ingresomensual>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:ingresoMensual"/>
          </Ingresomensual>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:impuestosRetenidos">
          <Impuestosreten>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:impuestosRetenidos"/>
          </Impuestosreten>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosIngresosDiferidosNegocio">
          <Otrosingrdifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosIngresosDiferidosNegocio"/>
          </Otrosingrdifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngesosNegocio">
          <Tipootrosingrneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:tipoOtrosIngesosNegocio"/>
          </Tipootrosingrneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:totalIngresosNegocio">
          <Totalingresosneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:totalIngresosNegocio"/>
          </Totalingresosneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:gastosFamDiferidosNegocio">
          <Gastosfamdifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:gastosFamDiferidosNegocio"/>
          </Gastosfamdifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:alimentacionDiferidoNegocio">
          <Alimentadifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:alimentacionDiferidoNegocio"/>
          </Alimentadifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:educacionDiferidaNegocio">
          <Educaciondifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:educacionDiferidaNegocio"/>
          </Educaciondifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:serviciosPublicosDiferidosNegocio">
          <Serviciopubdifn>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:serviciosPublicosDiferidosNegocio"/>
          </Serviciopubdifn>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:transporteDiferidoNegocio">
          <Transportedifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:transporteDiferidoNegocio"/>
          </Transportedifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:rentaDiferidoNegocio">
          <Rentadifnegocio>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:rentaDiferidoNegocio"/>
          </Rentadifnegocio>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:vestidoDiferidoNegocio">
          <Vestidodifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:vestidoDiferidoNegocio"/>
          </Vestidodifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosGastosDiferidosNegocio">
          <Otrosgastosdifn>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:otrosGastosDiferidosNegocio"/>
          </Otrosgastosdifn>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:deudasBuroDiferidoNegocio">
          <Deudasburodifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:deudasBuroDiferidoNegocio"/>
          </Deudasburodifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:pagosRealDiferidoNegocio">
          <Pagosrealdifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:pagosRealDiferidoNegocio"/>
          </Pagosrealdifneg>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:totalGastosDiferidosNegocio">
          <Totalgastosdifn>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:totalGastosDiferidosNegocio"/>
          </Totalgastosdifn>
        </xsl:if>
        <xsl:if test="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:excedenteDiferidoNegocio">
          <Excedentedifneg>
            <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:InformacionFinanciera/OrdT:excedenteDiferidoNegocio"/>
          </Excedentedifneg>
        </xsl:if>
      </IInfFinanciera>
      
        <IReferencias>
          <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:Referencias/OrdT:Referencia">
            <xsl:if test="OrdT:primerNombre">
              <xsl:variable name="refElementName" select="concat('Primernombreref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:primerNombre"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:segundoNombre">
              <xsl:variable name="refElementName" select="concat('Nombre2ref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:segundoNombre"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:apellidoPaterno">
              <xsl:variable name="refElementName" select="concat('Appaternoref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:apellidoPaterno"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:apellidoMaterno">
              <xsl:variable name="refElementName" select="concat('Apematernoref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:apellidoMaterno"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:parentesco">
              <xsl:variable name="refElementName" select="concat('Parentescoref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:parentesco"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico">
              <xsl:variable name="refElementName" select="concat('Teldomicilioref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='1']/OrdT:numeroTelefonico"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico">
              <xsl:variable name="refElementName" select="concat('Telcelularref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Telefonos/OrdT:Telefono[OrdT:tipoTelefono='2']/OrdT:numeroTelefonico"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:nombreDeLaCalle">
              <xsl:variable name="refElementName" select="concat('Calleref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:nombreDeLaCalle"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroExterior">
              <xsl:variable name="refElementName" select="concat('Noextref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroExterior"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroInterior">
              <xsl:variable name="refElementName" select="concat('Nointref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:numeroInterior"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:manzana">
              <xsl:variable name="refElementName" select="concat('Manzanaref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:manzana"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:lote">
              <xsl:variable name="refElementName" select="concat('Loteref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:lote"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:codigoPostal">
              <xsl:variable name="refElementName" select="concat('Cpref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:codigoPostal"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:colonia">
              <xsl:variable name="refElementName" select="concat('Coloniaref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:colonia"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:delegacionMunicipio">
              <xsl:variable name="refElementName" select="concat('Delegacionref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:delegacionMunicipio"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:estado">
              <xsl:variable name="refElementName" select="concat('Estadoref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:estado"/>
              </xsl:element>
            </xsl:if>
            <xsl:if test="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:localidad">
              <xsl:variable name="refElementName" select="concat('Localidadref',position())"/>
              <xsl:element name="{$refElementName}">
                <xsl:value-of select="OrdT:ContactoDomicilioReferencia/OrdT:Direccion/OrdT:localidad"/>
              </xsl:element>
            </xsl:if>
          </xsl:for-each>
        </IReferencias>
        <IReferenciasBp>
          <xsl:for-each select="/ns0:actualizarPendientesOrdenRequest/OrdT:Pendiente/OrdT:ListaReferenciasPreSolicitud/OrdT:Referencia">
            <xsl:variable name="refElementName" select="concat('BpRef',position())"/>
            <xsl:element name="{$refElementName}">
              <xsl:value-of select="OrdT:referencia"/>
            </xsl:element>
          </xsl:for-each>
        </IReferenciasBp>
      <IdCorreccion>
        <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:DatosTransaccion/OrdT:idExterno"/>
      </IdCorreccion>
      <Promotor>
        <xsl:value-of select="/ns0:actualizarPendientesOrdenRequest/OrdT:DatosTransaccion/OrdT:promotorAsignado"/>
      </Promotor>
    </tns:ZlmReFm005>
  </xsl:template>
</xsl:stylesheet>