<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST" xmlns:GestionT="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilRESTTipos">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../../OperacionCreditos/Creditos/Resources/Schemas/NMPCreditoSvcElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="getInfoCreditoResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCredito"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/GestionMovilFormiikRestElementosXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="FlexibleUpdateWorkOrderResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU MAR 03 22:39:41 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:FlexibleUpdateWorkOrderResponse>
         <GestionT:UpdateFieldsValues>
            <GestionT:Resultado>Operación exitosa</GestionT:Resultado>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:estatus">
               <GestionT:Estatus>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:estatus"/>
               </GestionT:Estatus>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:motivoPendiente">
               <GestionT:Motivo_Pendiente>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:motivoPendiente"/>
               </GestionT:Motivo_Pendiente>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:desembolso">
               <GestionT:Monto_Desembolso>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:desembolso"/>
               </GestionT:Monto_Desembolso>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:subEstatus">
               <GestionT:Sub_Estatus>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:subEstatus"/>
               </GestionT:Sub_Estatus>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:estatusPago">
               <GestionT:Estatus_Pago>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:estatusPago"/>
               </GestionT:Estatus_Pago>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:fechaSolicitud">
               <GestionT:Fecha_Solicitud>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:fechaSolicitud"/>
               </GestionT:Fecha_Solicitud>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:fechaDesembolso">
               <GestionT:Fecha_Desembolso>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:fechaDesembolso"/>
               </GestionT:Fecha_Desembolso>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:horaCita">
               <GestionT:Hora_Cita>
                  <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:horaCita"/>
               </GestionT:Hora_Cita>
            </xsl:if>
            <xsl:if test="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:gerenteSucursal">
              <GestionT:Gerente_Sucursal>
                <xsl:value-of select="/ns0:getInfoCreditoResponse/ns0:Solicitud/ns0:gerenteSucursal"/>
              </GestionT:Gerente_Sucursal>
            </xsl:if>
         </GestionT:UpdateFieldsValues>
      </tns:FlexibleUpdateWorkOrderResponse>
   </xsl:template>
</xsl:stylesheet>