<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST" xmlns:GestionT="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilRESTTipos" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Persona" xmlns:OrdT="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/OrdenesTrabajo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Cliente">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/GestionMovilFormiikRestElementosXSD.xsd"/>
                <oracle-xsl-mapper:rootElement name="Response" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../Schemas/NMPSvcOrdenesTrabajoElementosXSD.xsd"/>
                <oracle-xsl-mapper:rootElement name="realizarPreregistroOrdenRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SUN JUL 31 11:54:17 CDT 2016].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <tns:realizarPreregistroOrdenRequest>
            <OrdT:Preregistro>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:Nombre">
                    <OrdT:primerNombre>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Nombre"/>
                    </OrdT:primerNombre>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:Nombre">
                    <OrdT:segundoNombre>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Nombre"/>
                    </OrdT:segundoNombre>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:ApellidoPaterno">
                    <OrdT:apellidoPaterno>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:ApellidoPaterno"/>
                    </OrdT:apellidoPaterno>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:ApellidoMaterno">
                    <OrdT:apellidoMaterno>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:ApellidoMaterno"/>
                    </OrdT:apellidoMaterno>
                </xsl:if>
                <OrdT:ContactoDomicilio>
                    <OrdT:Direccion>
                        <OrdT:nombreDeLaCalle>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Calle"/>
                        </OrdT:nombreDeLaCalle>
                        <OrdT:numeroExterior>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:NumeroExterior"/>
                        </OrdT:numeroExterior>
                        <OrdT:numeroInterior>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:NumeroInterior"/>
                        </OrdT:numeroInterior>
                        <OrdT:estado>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Estado"/>
                        </OrdT:estado>
                        <OrdT:delegacionMunicipio>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:DelegacionMunicipio"/>
                        </OrdT:delegacionMunicipio>
                        <OrdT:colonia>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Colonia"/>
                        </OrdT:colonia>
                        <OrdT:codigoPostal>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:CodigoPostal"/>
                        </OrdT:codigoPostal>
                        <OrdT:lote>
                            <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:LoteCB"/>
                        </OrdT:lote>
                    </OrdT:Direccion>
                    <OrdT:Telefonos>
                        <OrdT:Telefono>
                            <OrdT:codigoArea>
                                <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Lada"/>
                            </OrdT:codigoArea>
                            <OrdT:numeroTelefonico>
                                <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Telefono"/>
                            </OrdT:numeroTelefonico>
                            <OrdT:tipoTelefono>
                                <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:TipoTelefono"/>
                            </OrdT:tipoTelefono>
                        </OrdT:Telefono>
                    </OrdT:Telefonos>
                </OrdT:ContactoDomicilio>
                <OrdT:email>
                    <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Correo"/>
                </OrdT:email>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:Descripcion">
                    <OrdT:descripcion>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Descripcion"/>
                    </OrdT:descripcion>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:Evento">
                    <OrdT:evento>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Evento"/>
                    </OrdT:evento>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:FechaNacimiento">
                    <OrdT:fechaDeNacimiento>
                        <!--Ejemplo Salida: 1991-09-28-->
                        <!--Ejemplo Entrada: 09/04/1959-->
                        <xsl:value-of select="concat(substring(/ns0:Response//GestionT:PreRegistro/GestionT:FechaNacimiento,7,4), '-', substring(/ns0:Response//GestionT:PreRegistro/GestionT:FechaNacimiento,4,2), '-',substring(/ns0:Response//GestionT:PreRegistro/GestionT:FechaNacimiento,1,2))"/>
                    </OrdT:fechaDeNacimiento>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:Genero">
                    <OrdT:genero>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Genero"/>
                    </OrdT:genero>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:PreRegistro/GestionT:Origen">
                    <OrdT:idOrigen>
                        <xsl:value-of select="/ns0:Response//GestionT:PreRegistro/GestionT:Origen"/>
                    </OrdT:idOrigen>
                </xsl:if>
            </OrdT:Preregistro>
            <OrdT:DatosTransaccion>
                <OrdT:idProducto>
                    <xsl:value-of select="/ns0:Response/@ProductId"/>
                </OrdT:idProducto>
                <OrdT:idExterno>
                    <xsl:value-of select="/ns0:Response/@ExternalId"/>
                </OrdT:idExterno>
                <OrdT:tipoOrdenTrabajo>
                    <xsl:value-of select="/ns0:Response/@ExternalType"/>
                </OrdT:tipoOrdenTrabajo>
                <OrdT:promotorAsignado>
                    <xsl:value-of select="/ns0:Response/@AssignedTo"/>
                </OrdT:promotorAsignado>
                <OrdT:fechaInicial>
                    <!--Ejemplo Entrada: 20160715 17:10:19-->
                    <!--Ejemplo Salida: 1991-09-28T20:49:45-->
                    <xsl:value-of select="concat(substring(/ns0:Response/@InitialDate,1,4),'-',substring(/ns0:Response/@InitialDate,5,2),'-',substring(/ns0:Response/@InitialDate,7,2),'T',substring(/ns0:Response/@InitialDate,10))"/>
                </OrdT:fechaInicial>
                <OrdT:fechaFinal>
                    <!--Ejemplo Entrada: 20160715 17:10:19-->
                    <!--Ejemplo Salida: 1991-09-28T20:49:45-->
                    <xsl:value-of select="concat(substring(/ns0:Response/@FinalDate,1,4),'-',substring(/ns0:Response/@FinalDate,5,2),'-',substring(/ns0:Response/@FinalDate,7,2),'T',substring(/ns0:Response/@FinalDate,10))"/>
                </OrdT:fechaFinal>
                <OrdT:fechaRespuesta>
                    <!--Ejemplo Entrada: 20160715 17:10:19-->
                    <!--Ejemplo Salida: 1991-09-28T20:49:45-->
                    <xsl:value-of select="concat(substring(/ns0:Response/@ResponseDate,1,4),'-',substring(/ns0:Response/@ResponseDate,5,2),'-',substring(/ns0:Response/@ResponseDate,7,2),'T',substring(/ns0:Response/@ResponseDate,10))"/>
                </OrdT:fechaRespuesta>
                <OrdT:DatosGeoespaciales>
                    <OrdT:latitudInicial>
                        <xsl:value-of select="/ns0:Response/@InitialLatitude"/>
                    </OrdT:latitudInicial>
                    <OrdT:longitudInicial>
                        <xsl:value-of select="/ns0:Response/@InitialLongitude"/>
                    </OrdT:longitudInicial>
                    <OrdT:latitudFinal>
                        <xsl:value-of select="/ns0:Response/@FinalLatitude"/>
                    </OrdT:latitudFinal>
                    <OrdT:longitudFinal>
                        <xsl:value-of select="/ns0:Response/@FinalLongitude"/>
                    </OrdT:longitudFinal>
                </OrdT:DatosGeoespaciales>
                <OrdT:origenRespuesta>
                    <xsl:value-of select="/ns0:Response/@FormiikResponseSource"/>
                </OrdT:origenRespuesta>
            </OrdT:DatosTransaccion>
        </tns:realizarPreregistroOrdenRequest>
    </xsl:template>
</xsl:stylesheet>