<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST" xmlns:GestionT="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilRESTTipos" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Persona" xmlns:OrdT="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/OrdenesTrabajo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Cliente">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/GestionMovilFormiikRestElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="Response" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovilREST"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPSvcOrdenesTrabajoElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="actualizarGestionOrdenRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/OrdenesTrabajo"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI JUL 29 20:54:08 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:actualizarGestionOrdenRequest>
      <OrdT:ResultadoGestion>
        <OrdT:GestionVisita>
          <OrdT:resultadoVisita>
            <xsl:value-of select="/ns0:Response//GestionT:GestionVisita/GestionT:ResultadoVisitaVtas"/>
          </OrdT:resultadoVisita>
          <OrdT:gestion>
            <xsl:value-of select="/ns0:Response//GestionT:GestionVisita/GestionT:GestionVtas"/>
          </OrdT:gestion>
        </OrdT:GestionVisita>
        <OrdT:Cliente>
          <OrdT:idCliente>
            <xsl:value-of select="/ns0:Response//GestionT:GestionVisita/GestionT:Num_Cliente"/>
          </OrdT:idCliente>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:PrimerNombreSol">
              <OrdT:primerNombre>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:PrimerNombreSol"/>
              </OrdT:primerNombre>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Nombre1">
              <OrdT:primerNombre>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Nombre1"/>
              </OrdT:primerNombre>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:SegundoNombreSol">
              <OrdT:segundoNombre>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:SegundoNombreSol"/>
              </OrdT:segundoNombre>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Nombre2">
              <OrdT:segundoNombre>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Nombre2"/>
              </OrdT:segundoNombre>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:ApPaternoSol">
              <OrdT:apellidoPaterno>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:ApPaternoSol"/>
              </OrdT:apellidoPaterno>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Apellido_Paterno">
              <OrdT:apellidoPaterno>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Apellido_Paterno"/>
              </OrdT:apellidoPaterno>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:ApMaternoSol">
              <OrdT:apellidoMaterno>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:ApMaternoSol"/>
              </OrdT:apellidoMaterno>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Apellido_Materno">
              <OrdT:apellidoMaterno>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Apellido_Materno"/>
              </OrdT:apellidoMaterno>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:GeneroSol">
              <OrdT:genero>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:GeneroSol"/>
              </OrdT:genero>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:GeneroCB">
              <OrdT:genero>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:GeneroCB"/>
              </OrdT:genero>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento">
              <OrdT:fechaDeNacimiento>
                <!--Ejemplo Salida: 1991-09-28-->
                <!--Ejemplo Entrada: 09/04/1959-->
                <xsl:value-of select="concat(substring(/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento,7,4), '-', substring(/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento,4,2), '-',substring(/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento,1,2))"/>
              </OrdT:fechaDeNacimiento>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:FechadeNacimientoCB">
              <OrdT:fechaDeNacimiento>
                <!--Ejemplo Salida: 1991-09-28-->
                <!--Ejemplo Entrada: 09/04/1959-->
                <xsl:value-of select="concat(substring(/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:FechadeNacimientoCB,7,4), '-', substring(/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:FechadeNacimientoCB,4,2), '-',substring(/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:FechadeNacimientoCB,1,2))"/>
              </OrdT:fechaDeNacimiento>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:RFCSol">
              <OrdT:rfc>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:RFCSol"/>
              </OrdT:rfc>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:RFCCB">
              <OrdT:rfc>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:RFCCB"/>
              </OrdT:rfc>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:CURPSol">
              <OrdT:curp>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:CURPSol"/>
              </OrdT:curp>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:Estado_Civil">
              <OrdT:estadoCivil>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:Estado_Civil"/>
              </OrdT:estadoCivil>
            </xsl:when>
          </xsl:choose>
          <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:PrimerNombreConyugueSol">
            <OrdT:DatosConyuge>
              <OrdT:primerNombreConyuge>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:PrimerNombreConyugueSol"/>
              </OrdT:primerNombreConyuge>
              <OrdT:segundoNombreConyuge>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:SegundoNombreConyugueSol"/>
              </OrdT:segundoNombreConyuge>
              <OrdT:apellidoPaternoConyuge>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:ApPaternoConyugueSol"/>
              </OrdT:apellidoPaternoConyuge>
              <OrdT:apellidoMaternoConyuge>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:ApMaternoConyugueSol"/>
              </OrdT:apellidoMaternoConyuge>
              <OrdT:TelefonosConyuge>
                <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:TelefonoDomicilioConyugueSol">
                  <OrdT:Telefono>
                    <OrdT:numeroTelefonico>
                      <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:TelefonoDomicilioConyugueSol"/>
                    </OrdT:numeroTelefonico>
                    <OrdT:tipoTelefono>1</OrdT:tipoTelefono>
                  </OrdT:Telefono>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:TelefonoTrabajoConyugueSol">
                  <OrdT:Telefono>
                    <OrdT:numeroTelefonico>
                      <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:TelefonoTrabajoConyugueSol"/>
                    </OrdT:numeroTelefonico>
                    <OrdT:tipoTelefono>4</OrdT:tipoTelefono>
                  </OrdT:Telefono>
                </xsl:if>
                <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:TelefonoCelularConyugueSol">
                  <OrdT:Telefono>
                    <OrdT:numeroTelefonico>
                      <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:TelefonoCelularConyugueSol"/>
                    </OrdT:numeroTelefonico>
                    <OrdT:tipoTelefono>2</OrdT:tipoTelefono>
                  </OrdT:Telefono>
                </xsl:if>
              </OrdT:TelefonosConyuge>
              <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:MailConyugueSol">
                <OrdT:mailConyuge>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:MailConyugueSol"/>
                </OrdT:mailConyuge>
              </xsl:if>
            </OrdT:DatosConyuge>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:Escolaridad">
            <OrdT:escolaridad>
              <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:Escolaridad"/>
            </OrdT:escolaridad>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:Nacionalidad">
            <OrdT:nacionalidad>
              <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:Nacionalidad"/>
            </OrdT:nacionalidad>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:PaisNacimientoSol">
            <OrdT:pais>
              <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:PaisNacimientoSol"/>
            </OrdT:pais>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:EmailSol">
            <OrdT:email>
              <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:EmailSol"/>
            </OrdT:email>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:DatosDelCliente/GestionT:dependientes_economicos">
            <OrdT:dependienteEconomico>
              <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:dependientes_economicos"/>
            </OrdT:dependienteEconomico>
          </xsl:if>
        </OrdT:Cliente>
        <OrdT:ContactoDomicilio>
          <OrdT:Direccion>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:CalleDCD">
                <OrdT:nombreDeLaCalle>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:CalleDCD"/>
                </OrdT:nombreDeLaCalle>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:CalleCB">
                <OrdT:nombreDeLaCalle>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:CalleCB"/>
                </OrdT:nombreDeLaCalle>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Numero_Exterior">
                <OrdT:numeroExterior>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Numero_Exterior"/>
                </OrdT:numeroExterior>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:NoExtCB">
                <OrdT:numeroExterior>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:NoExtCB"/>
                </OrdT:numeroExterior>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Numero_Interior">
                <OrdT:numeroInterior>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Numero_Interior"/>
                </OrdT:numeroInterior>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:NoIntCB">
                <OrdT:numeroInterior>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:NoIntCB"/>
                </OrdT:numeroInterior>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:EntreCalle1DCD">
                <OrdT:entreCalle1>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:EntreCalle1DCD"/>
                </OrdT:entreCalle1>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:EntreCalle1CB">
                <OrdT:entreCalle1>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:EntreCalle1CB"/>
                </OrdT:entreCalle1>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:EntreCalle2DCD">
                <OrdT:entreCalle2>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:EntreCalle2DCD"/>
                </OrdT:entreCalle2>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:EntreCalle2CB">
                <OrdT:entreCalle2>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:EntreCalle2CB"/>
                </OrdT:entreCalle2>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:EstadoDCD">
                <OrdT:estado>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:EstadoDCD"/>
                </OrdT:estado>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:EstadoCB">
                <OrdT:estado>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:EstadoCB"/>
                </OrdT:estado>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Delegacion_o_Municipio">
                <OrdT:delegacionMunicipio>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Delegacion_o_Municipio"/>
                </OrdT:delegacionMunicipio>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:DelegacionCB">
                <OrdT:delegacionMunicipio>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:DelegacionCB"/>
                </OrdT:delegacionMunicipio>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:ColoniaDCD">
                <OrdT:colonia>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:ColoniaDCD"/>
                </OrdT:colonia>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:ColoniaCB">
                <OrdT:colonia>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:ColoniaCB"/>
                </OrdT:colonia>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:CPDCD">
                <OrdT:codigoPostal>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:CPDCD"/>
                </OrdT:codigoPostal>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:CPCB">
                <OrdT:codigoPostal>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:CPCB"/>
                </OrdT:codigoPostal>
              </xsl:when>
            </xsl:choose>
            <xsl:if test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:TipoVivienda">
              <OrdT:tipoDomicilio>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:TipoVivienda"/>
              </OrdT:tipoDomicilio>
            </xsl:if>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:ManzanaDCD">
                <OrdT:manzana>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:ManzanaDCD"/>
                </OrdT:manzana>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:ManzanaCB">
                <OrdT:manzana>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:ManzanaCB"/>
                </OrdT:manzana>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:LoteDCD">
                <OrdT:lote>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:LoteDCD"/>
                </OrdT:lote>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:LoteCB">
                <OrdT:lote>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:LoteCB"/>
                </OrdT:lote>
              </xsl:when>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:LocalidadDCD">
                <OrdT:localidad>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:LocalidadDCD"/>
                </OrdT:localidad>
              </xsl:when>
              <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:LocalidadCB">
                <OrdT:localidad>
                  <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:LocalidadCB"/>
                </OrdT:localidad>
              </xsl:when>
            </xsl:choose>
          </OrdT:Direccion>
          <OrdT:Telefonos>
            <xsl:if test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Telefono_Casa">
              <OrdT:Telefono>
                <OrdT:codigoArea>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Lada_Casa"/>
                </OrdT:codigoArea>
                <OrdT:numeroTelefonico>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Telefono_Casa"/>
                </OrdT:numeroTelefonico>
                <OrdT:tipoTelefono>1</OrdT:tipoTelefono>
              </OrdT:Telefono>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Telefono_Celular">
              <OrdT:Telefono>
                <OrdT:codigoArea>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Lada_Celular"/>
                </OrdT:codigoArea>
                <OrdT:numeroTelefonico>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Telefono_Celular"/>
                </OrdT:numeroTelefonico>
                <OrdT:tipoTelefono>2</OrdT:tipoTelefono>
              </OrdT:Telefono>
            </xsl:if>
            <xsl:if test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Telefono_Recados">
              <OrdT:Telefono>
                <OrdT:codigoArea>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Lada_Recados"/>
                </OrdT:codigoArea>
                <OrdT:numeroTelefonico>
                  <xsl:value-of select="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:Telefono_Recados"/>
                </OrdT:numeroTelefonico>
                <OrdT:tipoTelefono>3</OrdT:tipoTelefono>
              </OrdT:Telefono>
            </xsl:if>
          </OrdT:Telefonos>
          <xsl:if test="/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:FechaComienzoVivirCDC">
            <OrdT:fechaComienzoVivir>
              <!--Ejemplo Salida: 1991-09-28-->
              <!--Ejemplo Entrada: 09/04/1959-->
              <xsl:value-of select="concat(substring(/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:FechaComienzoVivirCDC,7,4), '-', substring(/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:FechaComienzoVivirCDC,4,2), '-',substring(/ns0:Response//GestionT:DatosDelContactoYDomicilio/GestionT:FechaComienzoVivirCDC,1,2))"/>
            </OrdT:fechaComienzoVivir>
          </xsl:if>
        </OrdT:ContactoDomicilio>
        <OrdT:InformacionPreSolicitud>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NOMBRE1">
            <OrdT:primerNombre>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NOMBRE1"/>
            </OrdT:primerNombre>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NOMBRE2">
            <OrdT:segundoNombre>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NOMBRE2"/>
            </OrdT:segundoNombre>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_APPAT">
            <OrdT:apellidoPaterno>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_APPAT"/>
            </OrdT:apellidoPaterno>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_APMAT">
            <OrdT:apellidoMaterno>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_APMAT"/>
            </OrdT:apellidoMaterno>
          </xsl:if>
          <OrdT:ContactoDomicilio>
            <OrdT:Direccion>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CALLE">
                <OrdT:nombreDeLaCalle>
                  <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CALLE"/>
                </OrdT:nombreDeLaCalle>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NUMEXT">
                <OrdT:numeroExterior>
                  <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NUMEXT"/>
                </OrdT:numeroExterior>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NUMINT">
                <OrdT:numeroInterior>
                  <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NUMINT"/>
                </OrdT:numeroInterior>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_ESTADO">
                <OrdT:estado>
                  <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_ESTADO"/>
                </OrdT:estado>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_DELMUN">
                <OrdT:delegacionMunicipio>
                  <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_DELMUN"/>
                </OrdT:delegacionMunicipio>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_COLONIA">
                <OrdT:colonia>
                  <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_COLONIA"/>
                </OrdT:colonia>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CODPOSTAL">
                <OrdT:codigoPostal>
                  <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CODPOSTAL"/>
                </OrdT:codigoPostal>
              </xsl:if>
            </OrdT:Direccion>
            <OrdT:Telefonos>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CASATEL">
                <OrdT:Telefono>
                  <OrdT:codigoArea>
                    <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CASALADA"/>
                  </OrdT:codigoArea>
                  <OrdT:numeroTelefonico>
                    <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CASATEL"/>
                  </OrdT:numeroTelefonico>
                  <OrdT:tipoTelefono>1</OrdT:tipoTelefono>
                </OrdT:Telefono>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CELTEL">
                <OrdT:Telefono>
                  <OrdT:codigoArea>
                    <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CELLADA"/>
                  </OrdT:codigoArea>
                  <OrdT:numeroTelefonico>
                    <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CELTEL"/>
                  </OrdT:numeroTelefonico>
                  <OrdT:tipoTelefono>2</OrdT:tipoTelefono>
                </OrdT:Telefono>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_TRABTEL">
                <OrdT:Telefono>
                  <OrdT:codigoArea>
                    <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_TRABLADA"/>
                  </OrdT:codigoArea>
                  <OrdT:numeroTelefonico>
                    <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_TRABTEL"/>
                  </OrdT:numeroTelefonico>
                  <OrdT:extension>
                    <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_TRABEXT"/>
                  </OrdT:extension>
                  <OrdT:tipoTelefono>4</OrdT:tipoTelefono>
                </OrdT:Telefono>
              </xsl:if>
            </OrdT:Telefonos>
          </OrdT:ContactoDomicilio>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_EDOCIVIL">
            <OrdT:estadoCivil>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_EDOCIVIL"/>
            </OrdT:estadoCivil>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_ESCOLARIDAD">
            <OrdT:escolaridad>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_ESCOLARIDAD"/>
            </OrdT:escolaridad>
          </xsl:if>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_FECNAC">
              <OrdT:fechaDeNacimiento>
                <!--Ejemplo Salida: 1991-09-28-->
                <!--Ejemplo Entrada: 09/04/1959-->
                <xsl:value-of select="concat(substring(/ns0:Response//GestionT:BP_Seccion/GestionT:BP_FECNAC,7,4), '-', substring(/ns0:Response//GestionT:BP_Seccion/GestionT:BP_FECNAC,4,2), '-',substring(/ns0:Response//GestionT:BP_Seccion/GestionT:BP_FECNAC,1,2))"/>
              </OrdT:fechaDeNacimiento>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento">
              <OrdT:fechaDeNacimiento>
                <!--Ejemplo Salida: 1991-09-28-->
                <!--Ejemplo Entrada: 09/04/1959-->
                <xsl:value-of select="concat(substring(/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento,7,4), '-', substring(/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento,4,2), '-',substring(/ns0:Response//GestionT:DatosDelCliente/GestionT:Fecha_de_Nacimiento,1,2))"/>
              </OrdT:fechaDeNacimiento>
            </xsl:when>
          </xsl:choose>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NACIONALIDAD">
            <OrdT:nacionalidad>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NACIONALIDAD"/>
            </OrdT:nacionalidad>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_SIVA">
            <OrdT:siva>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_SIVA"/>
            </OrdT:siva>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_PROBINCUMPL">
            <OrdT:probabilidadIncumplimiento>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_PROBINCUMPL"/>
            </OrdT:probabilidadIncumplimiento>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CAPPAGO">
            <OrdT:capacidadPago>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_CAPPAGO"/>
            </OrdT:capacidadPago>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PRESTAMOPROM">
            <OrdT:montoPrestamo>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PRESTAMOSNMP"/>
            </OrdT:montoPrestamo>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PAGOSNMP">
            <OrdT:montoPago>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PAGOSNMP"/>
            </OrdT:montoPago>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PRESTAMOPROM">
            <OrdT:montoPrestamoProm>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PRESTAMOPROM"/>
            </OrdT:montoPrestamoProm>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PRESTAMOPROMVALUACION">
            <OrdT:prestamoPromocionVal>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_IMP_PRESTAMOPROMVALUACION"/>
            </OrdT:prestamoPromocionVal>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NUM_DESEMPENIO">
            <OrdT:numDesempenios>
              <xsl:value-of select="/ns0:Response//GestionT:BP_Seccion/GestionT:BP_NUM_DESEMPENIO"/>
            </OrdT:numDesempenios>
          </xsl:if>
        </OrdT:InformacionPreSolicitud>
        <OrdT:DocumentacionCliente>
          <OrdT:FotosCompDom>
            <xsl:for-each select="/ns0:Response//GestionT:DocumentaciondelCliente/*[contains(local-name(), 'FotoCompDom')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
            <OrdT:tipoComprobanteDom>
              <xsl:value-of select="/ns0:Response//GestionT:DocumentaciondelCliente/GestionT:TipoComprobanteDomicilio"/>
            </OrdT:tipoComprobanteDom>
          </OrdT:FotosCompDom>
          <OrdT:FotosIdOficial>
            <xsl:for-each select="/ns0:Response//GestionT:ConsultadeBurodeCredito/*[contains(local-name(), 'FotoID')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
            <OrdT:tipoIdOficial>
              <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:TipoIdentificacionOficial"/>
            </OrdT:tipoIdOficial>
          </OrdT:FotosIdOficial>
          <OrdT:FotosCompViv>
            <xsl:for-each select="/ns0:Response//GestionT:DocumentaciondelCliente/*[contains(local-name(), 'FotoCompViv')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
            <OrdT:tipoComprobanteViv>
              <xsl:value-of select="/ns0:Response//GestionT:DocumentaciondelCliente/GestionT:TipoComprobanteVivienda"/>
            </OrdT:tipoComprobanteViv>
          </OrdT:FotosCompViv>
          <OrdT:FotosCompIngEmp>
            <xsl:for-each select="/ns0:Response//GestionT:DocumentaciondelCliente/*[contains(local-name(), 'FotoCompIngEmp')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
            <OrdT:comprobanteIngresosAct>
              <xsl:value-of select="/ns0:Response//GestionT:DocumentaciondelCliente/GestionT:ComprobanteIngresosActividad"/>
            </OrdT:comprobanteIngresosAct>
            <OrdT:tipoComprobanteIngEmp>
              <xsl:value-of select="/ns0:Response//GestionT:DocumentaciondelCliente/GestionT:TipoComprobanteIngresosEmpleado"/>
            </OrdT:tipoComprobanteIngEmp>
          </OrdT:FotosCompIngEmp>
          <OrdT:FotosCompIngNeg>
            <xsl:for-each select="/ns0:Response//GestionT:DocumentaciondelCliente/*[contains(local-name(), 'FotoCompIngNeg')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
            <OrdT:comprobanteIngresosAct>
              <xsl:value-of select="/ns0:Response//GestionT:DocumentaciondelCliente/GestionT:TipoComprobanteIngresosNegocio"/>
            </OrdT:comprobanteIngresosAct>
          </OrdT:FotosCompIngNeg>
          <OrdT:FotosCompIngOtro>
            <xsl:for-each select="/ns0:Response//GestionT:DocumentaciondelCliente/*[contains(local-name(), 'FotoCompOtrosIng')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
          </OrdT:FotosCompIngOtro>
          <OrdT:FotosCliente>
            <xsl:for-each select="/ns0:Response//GestionT:DocumentaciondelCliente/*[contains(local-name(), 'FotoCliente')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
          </OrdT:FotosCliente>
          <OrdT:FotosSC>
            <xsl:for-each select="/ns0:Response//GestionT:ConsultadeBurodeCredito/*[starts-with(local-name(), 'Foto') and ends-with(local-name(),'SC')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
          </OrdT:FotosSC>
          <OrdT:FotosCB>
            <xsl:for-each select="/ns0:Response//GestionT:ConsultadeBurodeCredito/*[starts-with(local-name(), 'Foto') and ends-with(local-name(),'CB')]">
              <OrdT:Fotos>
                <OrdT:foto>
                  <xsl:value-of select="."/>
                </OrdT:foto>
              </OrdT:Fotos>
            </xsl:for-each>
          </OrdT:FotosCB>
        </OrdT:DocumentacionCliente>
        <OrdT:GeolocalizacionCasaNegocio>
          <xsl:if test="/ns0:Response//GestionT:GeolocalizacionCasaNegocio/GestionT:GPSDomicilio">
            <OrdT:gps>
              <xsl:value-of select="/ns0:Response//GestionT:GeolocalizacionCasaNegocio/GestionT:GPSDomicilio"/>
            </OrdT:gps>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:GeolocalizacionCasaNegocio/GestionT:GPSNegocioEmpleo">
            <OrdT:gpsNegocioEmpleo>
              <xsl:value-of select="/ns0:Response//GestionT:GeolocalizacionCasaNegocio/GestionT:GPSNegocioEmpleo"/>
            </OrdT:gpsNegocioEmpleo>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:GeolocalizacionCasaNegocio/GestionT:Cotejo">
            <OrdT:cotejo>
              <xsl:value-of select="/ns0:Response//GestionT:GeolocalizacionCasaNegocio/GestionT:Cotejo"/>
            </OrdT:cotejo>
          </xsl:if>
        </OrdT:GeolocalizacionCasaNegocio>
        <OrdT:OcupacionEconomica>
          <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:NombreEmpleo">
            <OrdT:nombreEmpleo>
              <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:NombreEmpleo"/>
            </OrdT:nombreEmpleo>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:FechaIngresoEmpleo">
            <OrdT:fechaIngreso>
              <!--Ejemplo Salida: 1991-09-28-->
              <!--Ejemplo Entrada: 09/04/1959-->
              <xsl:value-of select="concat(substring(/ns0:Response//GestionT:OcupacionEconomica/GestionT:FechaIngresoEmpleo,7,4), '-', substring(/ns0:Response//GestionT:OcupacionEconomica/GestionT:FechaIngresoEmpleo,4,2), '-',substring(/ns0:Response//GestionT:OcupacionEconomica/GestionT:FechaIngresoEmpleo,1,2))"/>
            </OrdT:fechaIngreso>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:DomicilioMismoEmpleo">
            <OrdT:domicilioMismoEmpleo>
              <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:DomicilioMismoEmpleo"/>
            </OrdT:domicilioMismoEmpleo>
          </xsl:if>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:ActividadSol">
              <OrdT:ocupacion>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:ActividadSol"/>
              </OrdT:ocupacion>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Ocupacion">
              <OrdT:ocupacion>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Ocupacion"/>
              </OrdT:ocupacion>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:ActividadEconomicaSol">
              <OrdT:actividadEconomica>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:ActividadEconomicaSol"/>
              </OrdT:actividadEconomica>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:ActividadEconomicaCB">
              <OrdT:actividadEconomica>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:ActividadEconomicaCB"/>
              </OrdT:actividadEconomica>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:DatosDelCliente/GestionT:SectorSol">
              <OrdT:sector>
                <xsl:value-of select="/ns0:Response//GestionT:DatosDelCliente/GestionT:SectorSol"/>
              </OrdT:sector>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:SectorCB">
              <OrdT:sector>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:SectorCB"/>
              </OrdT:sector>
            </xsl:when>
          </xsl:choose>
          <OrdT:ContactoDomicilioEmpleo>
            <OrdT:Direccion>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:CalleOE">
                <OrdT:nombreDeLaCalle>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:CalleOE"/>
                </OrdT:nombreDeLaCalle>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:NoExtOE">
                <OrdT:numeroExterior>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:NoExtOE"/>
                </OrdT:numeroExterior>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:NoIntOE">
                <OrdT:numeroInterior>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:NoIntOE"/>
                </OrdT:numeroInterior>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:EntreCalle1OE">
                <OrdT:entreCalle1>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:EntreCalle1OE"/>
                </OrdT:entreCalle1>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:EntreCalle2OE">
                <OrdT:entreCalle2>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:EntreCalle2OE"/>
                </OrdT:entreCalle2>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:EstadoOE">
                <OrdT:estado>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:EstadoOE"/>
                </OrdT:estado>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:DelegacionOE">
                <OrdT:delegacionMunicipio>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:DelegacionOE"/>
                </OrdT:delegacionMunicipio>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:ColoniaOE">
                <OrdT:colonia>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:ColoniaOE"/>
                </OrdT:colonia>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:CPOE">
                <OrdT:codigoPostal>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:CPOE"/>
                </OrdT:codigoPostal>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:ManzanaOE">
                <OrdT:manzana>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:ManzanaOE"/>
                </OrdT:manzana>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:LoteOE">
                <OrdT:lote>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:LoteOE"/>
                </OrdT:lote>
              </xsl:if>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:LocalidadOE">
                <OrdT:localidad>
                  <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:LocalidadOE"/>
                </OrdT:localidad>
              </xsl:if>
            </OrdT:Direccion>
            <OrdT:Telefonos>
              <xsl:if test="/ns0:Response//GestionT:OcupacionEconomica/GestionT:Telefono_Trabajo">
                <OrdT:Telefono>
                  <OrdT:codigoArea>
                    <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:Lada_Trabajo"/>
                  </OrdT:codigoArea>
                  <OrdT:numeroTelefonico>
                    <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:Telefono_Trabajo"/>
                  </OrdT:numeroTelefonico>
                  <OrdT:extension>
                    <xsl:value-of select="/ns0:Response//GestionT:OcupacionEconomica/GestionT:Extension_Trabajo"/>
                  </OrdT:extension>
                  <OrdT:tipoTelefono>4</OrdT:tipoTelefono>
                </OrdT:Telefono>
              </xsl:if>
            </OrdT:Telefonos>
          </OrdT:ContactoDomicilioEmpleo>
        </OrdT:OcupacionEconomica>
        <OrdT:Referencias>
          <xsl:for-each select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), 'PrimerNombreRef')]">
            <OrdT:Referencia>
              <OrdT:primerNombre>
                <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('PrimerNombreRef',position()))]"/>
              </OrdT:primerNombre>
              <OrdT:segundoNombre>
                <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('SegundoNombreRef',position()))]"/>
              </OrdT:segundoNombre>
              <OrdT:apellidoPaterno>
                <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('ApPaternoRef',position()))]"/>
              </OrdT:apellidoPaterno>
              <OrdT:apellidoMaterno>
                <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('ApMaternoRef',position()))]"/>
              </OrdT:apellidoMaterno>
              <OrdT:parentesco>
                <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('ParentescoRef',position()))]"/>
              </OrdT:parentesco>
              <OrdT:ContactoDomicilioReferencia>
                <OrdT:Direccion>
                  <xsl:variable name="CalleRef" select="concat('CalleRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $CalleRef )]">
                    <OrdT:nombreDeLaCalle>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('CalleRef',position()))]"/>
                    </OrdT:nombreDeLaCalle>
                  </xsl:if>
                  <xsl:variable name="NoExtRef" select="concat('NoExtRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $NoExtRef )]">
                    <OrdT:numeroExterior>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('NoExtRef',position()))]"/>
                    </OrdT:numeroExterior>
                  </xsl:if>
                  <xsl:variable name="NoIntRef" select="concat('NoIntRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $NoIntRef )]">
                    <OrdT:numeroInterior>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('NoIntRef',position()))]"/>
                    </OrdT:numeroInterior>
                  </xsl:if>
                  <xsl:variable name="EstadoRef" select="concat('EstadoRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $EstadoRef)]">
                    <OrdT:estado>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('EstadoRef',position()))]"/>
                    </OrdT:estado>
                  </xsl:if>
                  <xsl:variable name="DelegacionRef" select="concat('DelegacionRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $DelegacionRef) ]">
                    <OrdT:delegacionMunicipio>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('DelegacionRef',position()))]"/>
                    </OrdT:delegacionMunicipio>
                  </xsl:if>
                  <xsl:variable name="ColoniaRef" select="concat('ColoniaRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $ColoniaRef)]">
                    <OrdT:colonia>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('ColoniaRef',position()))]"/>
                    </OrdT:colonia>
                  </xsl:if>
                  <xsl:variable name="CPRef" select="concat('CPRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $CPRef)]">
                    <OrdT:codigoPostal>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('CPRef',position()))]"/>
                    </OrdT:codigoPostal>
                  </xsl:if>
                  <xsl:variable name="ManzanaRef" select="concat('ManzanaRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $ManzanaRef)]">
                    <OrdT:manzana>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('ManzanaRef',position()))]"/>
                    </OrdT:manzana>
                  </xsl:if>
                  <xsl:variable name="LoteRef" select="concat('LoteRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $LoteRef)]">
                    <OrdT:lote>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('LoteRef',position()))]"/>
                    </OrdT:lote>
                  </xsl:if>
                  <xsl:variable name="LocalidadRef" select="concat('LocalidadRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $LocalidadRef)]">
                    <OrdT:localidad>
                      <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('LocalidadRef',position()))]"/>
                    </OrdT:localidad>
                  </xsl:if>
                </OrdT:Direccion>
                <OrdT:Telefonos>
                  <xsl:variable name="TelCelularRef" select=" concat('TelCelularRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $TelCelularRef)]">
                    <OrdT:Telefono>
                      <OrdT:numeroTelefonico>
                        <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('TelCelularRef',position()))]"/>
                      </OrdT:numeroTelefonico>
                      <OrdT:tipoTelefono>2</OrdT:tipoTelefono>
                    </OrdT:Telefono>
                  </xsl:if>
                  <xsl:variable name="TelDomicilioRef" select="concat('TelDomicilioRef',position())"/>
                  <xsl:if test="/ns0:Response//GestionT:Referencias/*[contains(local-name(), $TelDomicilioRef)]">
                    <OrdT:Telefono>
                      <OrdT:numeroTelefonico>
                        <xsl:value-of select="/ns0:Response//GestionT:Referencias/*[contains(local-name(), concat('TelDomicilioRef',position()))]"/>
                      </OrdT:numeroTelefonico>
                      <OrdT:tipoTelefono>1</OrdT:tipoTelefono>
                    </OrdT:Telefono>
                  </xsl:if>
                </OrdT:Telefonos>
              </OrdT:ContactoDomicilioReferencia>
            </OrdT:Referencia>
          </xsl:for-each>
        </OrdT:Referencias>
        <OrdT:DatosBancarios>
          <xsl:if test="/ns0:Response//GestionT:DatosBancarios/GestionT:Banco">
            <OrdT:banco>
              <xsl:value-of select="/ns0:Response//GestionT:DatosBancarios/GestionT:Banco"/>
            </OrdT:banco>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:DatosBancarios/GestionT:NumCuenta">
            <OrdT:numCuenta>
              <xsl:value-of select="/ns0:Response//GestionT:DatosBancarios/GestionT:NumCuenta"/>
            </OrdT:numCuenta>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:DatosBancarios/GestionT:TipoCuenta">
            <OrdT:tipoCuenta>
              <xsl:value-of select="/ns0:Response//GestionT:DatosBancarios/GestionT:TipoCuenta"/>
            </OrdT:tipoCuenta>
          </xsl:if>
        </OrdT:DatosBancarios>
        <OrdT:InformacionFinanciera>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ActividadIF">
            <OrdT:actividadEconomica>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ActividadIF"/>
            </OrdT:actividadEconomica>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VentasMensuales">
            <OrdT:ventasMensuales>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VentasMensuales"/>
            </OrdT:ventasMensuales>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Compras">
            <OrdT:compras>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Compras"/>
            </OrdT:compras>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Inventario">
            <OrdT:inventario>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Inventario"/>
            </OrdT:inventario>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:UtilidadBruta">
            <OrdT:utilidadBruta>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:UtilidadBruta"/>
            </OrdT:utilidadBruta>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosOperativos">
            <OrdT:gastosOperativos>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosOperativos"/>
            </OrdT:gastosOperativos>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Sueldos">
            <OrdT:sueldos>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Sueldos"/>
            </OrdT:sueldos>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasNegocio">
            <OrdT:deudasNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasNegocio"/>
            </OrdT:deudasNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosNegocio">
            <OrdT:serviciosPublicosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosNegocio"/>
            </OrdT:serviciosPublicosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteNegocio">
            <OrdT:transporteNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteNegocio"/>
            </OrdT:transporteNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaNegocio">
            <OrdT:rentaNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaNegocio"/>
            </OrdT:rentaNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionNegocio">
            <OrdT:alimentacionNeg>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionNegocio"/>
            </OrdT:alimentacionNeg>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosNegocio">
            <OrdT:otrosgastosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosNegocio"/>
            </OrdT:otrosgastosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliares">
            <OrdT:gastosFamiliares>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliares"/>
            </OrdT:gastosFamiliares>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroNegocio">
            <OrdT:deudasBuroNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroNegocio"/>
            </OrdT:deudasBuroNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosNegocio">
            <OrdT:pagosRealNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosNegocio"/>
            </OrdT:pagosRealNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosNegocio">
            <OrdT:totalGastosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosNegocio"/>
            </OrdT:totalGastosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosNegocio">
            <OrdT:otrosIngresosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosNegocio"/>
            </OrdT:otrosIngresosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosNegocio">
            <OrdT:tipoOtrosIngresosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosNegocio"/>
            </OrdT:tipoOtrosIngresosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Excedente">
            <OrdT:excedente>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:Excedente"/>
            </OrdT:excedente>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:IngresosMensuales">
            <OrdT:ingresoMensual>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:IngresosMensuales"/>
            </OrdT:ingresoMensual>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ImpuestosRetenciones">
            <OrdT:impuestosRetenidos>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ImpuestosRetenciones"/>
            </OrdT:impuestosRetenidos>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosDifNegocio">
            <OrdT:otrosIngresosDiferidosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosIngresosDifNegocio"/>
            </OrdT:otrosIngresosDiferidosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosDifNegocio">
            <OrdT:tipoOtrosIngesosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TipoOtrosIngresosDifNegocio"/>
            </OrdT:tipoOtrosIngesosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalIngresosDifNegocio">
            <OrdT:totalIngresosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalIngresosDifNegocio"/>
            </OrdT:totalIngresosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliaresDifNegocio">
            <OrdT:gastosFamDiferidosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:GastosFamiliaresDifNegocio"/>
            </OrdT:gastosFamDiferidosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionDifNegocio">
            <OrdT:alimentacionDiferidoNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:AlimentacionDifNegocio"/>
            </OrdT:alimentacionDiferidoNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:EducacionDifNegocio">
            <OrdT:educacionDiferidaNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:EducacionDifNegocio"/>
            </OrdT:educacionDiferidaNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosDifNegocio">
            <OrdT:serviciosPublicosDiferidosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ServiciosPublicosDifNegocio"/>
            </OrdT:serviciosPublicosDiferidosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteDifNegocio">
            <OrdT:transporteDiferidoNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TransporteDifNegocio"/>
            </OrdT:transporteDiferidoNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaDifNegocio">
            <OrdT:rentaDiferidoNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:RentaDifNegocio"/>
            </OrdT:rentaDiferidoNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VestidoDifNegocio">
            <OrdT:vestidoDiferidoNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:VestidoDifNegocio"/>
            </OrdT:vestidoDiferidoNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosDifNegocio">
            <OrdT:otrosGastosDiferidosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:OtrosGastosDifNegocio"/>
            </OrdT:otrosGastosDiferidosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroDifNegocio">
            <OrdT:deudasBuroDiferidoNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:DeudasBuroDifNegocio"/>
            </OrdT:deudasBuroDiferidoNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosDifNegocio">
            <OrdT:pagosRealDiferidoNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:PagosRealizadosDifNegocio"/>
            </OrdT:pagosRealDiferidoNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosDifNegocio">
            <OrdT:totalGastosDiferidosNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:TotalGastosDifNegocio"/>
            </OrdT:totalGastosDiferidosNegocio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ExcedenteDifNegocio">
            <OrdT:excedenteDiferidoNegocio>
              <xsl:value-of select="/ns0:Response//GestionT:InformacionFinanciera/GestionT:ExcedenteDifNegocio"/>
            </OrdT:excedenteDiferidoNegocio>
          </xsl:if>
        </OrdT:InformacionFinanciera>
        <OrdT:ConsultaBuroCredito>
          <xsl:if test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Folio">
            <OrdT:folio>
              <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Folio"/>
            </OrdT:folio>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Frecuencia">
            <OrdT:frecuencia>
              <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Frecuencia"/>
            </OrdT:frecuencia>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Estatus">
            <OrdT:estatus>
              <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Estatus"/>
            </OrdT:estatus>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Categoria2">
            <OrdT:categoria>
              <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Categoria2"/>
            </OrdT:categoria>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:MensajeBuro">
            <OrdT:mensajeBuro>
              <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:MensajeBuro"/>
            </OrdT:mensajeBuro>
          </xsl:if>
          <xsl:if test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Estatus2">
            <OrdT:estatus2>
              <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Estatus2"/>
            </OrdT:estatus2>
          </xsl:if>
        </OrdT:ConsultaBuroCredito>
        <OrdT:InformacionSolicitud>
          <xsl:if test="/ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Monto_Solic')]">
            <xsl:if test="number(/ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Monto_Solic')]) = /ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Monto_Solic')]">
              <OrdT:montoSolicitado>
                <xsl:value-of select="/ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Monto_Solic')]"/>
              </OrdT:montoSolicitado>
            </xsl:if>
          </xsl:if>
          <xsl:choose>
            <xsl:when test="/ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Periodicidad')]">
              <OrdT:periodicidad>
                <xsl:value-of select="/ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Periodicidad')]"/>
              </OrdT:periodicidad>
            </xsl:when>
            <xsl:when test="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Frecuencia">
              <OrdT:periodicidad>
                <xsl:value-of select="/ns0:Response//GestionT:ConsultadeBurodeCredito/GestionT:Frecuencia"/>
              </OrdT:periodicidad>
            </xsl:when>
          </xsl:choose>
          <xsl:if test="/ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Plazo')]">
            <OrdT:plazo>
              <xsl:value-of select="/ns0:Response//GestionT:Info_Solicitud/*[contains(local-name(), 'Plazo')]"/>
            </OrdT:plazo>
          </xsl:if>
        </OrdT:InformacionSolicitud>
      </OrdT:ResultadoGestion>
      <OrdT:DatosTransaccion>
        <OrdT:idProducto>
          <xsl:value-of select="/ns0:Response/@ProductId"/>
        </OrdT:idProducto>
        <OrdT:idExterno>
          <xsl:value-of select="/ns0:Response/@ExternalId"/>
        </OrdT:idExterno>
        <OrdT:tipoOrdenTrabajo>
          <xsl:value-of select="/ns0:Response/@ExternalType"/>
        </OrdT:tipoOrdenTrabajo>
        <OrdT:promotorAsignado>
          <xsl:value-of select="/ns0:Response/@AssignedTo"/>
        </OrdT:promotorAsignado>
        <OrdT:fechaInicial>
          <!--Ejemplo Entrada: 20160715 17:10:19-->
          <!--Ejemplo Salida: 1991-09-28T20:49:45-->
          <xsl:value-of select="concat(substring(/ns0:Response/@InitialDate,1,4),'-',substring(/ns0:Response/@InitialDate,5,2),'-',substring(/ns0:Response/@InitialDate,7,2),'T',substring(/ns0:Response/@InitialDate,10))"/>
        </OrdT:fechaInicial>
        <OrdT:fechaFinal>
          <!--Ejemplo Entrada: 20160715 17:10:19-->
          <!--Ejemplo Salida: 1991-09-28T20:49:45-->
          <xsl:value-of select="concat(substring(/ns0:Response/@FinalDate,1,4),'-',substring(/ns0:Response/@FinalDate,5,2),'-',substring(/ns0:Response/@FinalDate,7,2),'T',substring(/ns0:Response/@FinalDate,10))"/>
        </OrdT:fechaFinal>
        <OrdT:fechaRespuesta>
          <!--Ejemplo Entrada: 20160715 17:10:19-->
          <!--Ejemplo Salida: 1991-09-28T20:49:45-->
          <xsl:value-of select="concat(substring(/ns0:Response/@ResponseDate,1,4),'-',substring(/ns0:Response/@ResponseDate,5,2),'-',substring(/ns0:Response/@ResponseDate,7,2),'T',substring(/ns0:Response/@ResponseDate,10))"/>
        </OrdT:fechaRespuesta>
        <OrdT:DatosGeoespaciales>
          <OrdT:latitudInicial>
            <xsl:value-of select="/ns0:Response/@InitialLatitude"/>
          </OrdT:latitudInicial>
          <OrdT:longitudInicial>
            <xsl:value-of select="/ns0:Response/@InitialLongitude"/>
          </OrdT:longitudInicial>
          <OrdT:latitudFinal>
            <xsl:value-of select="/ns0:Response/@FinalLatitude"/>
          </OrdT:latitudFinal>
          <OrdT:longitudFinal>
            <xsl:value-of select="/ns0:Response/@FinalLongitude"/>
          </OrdT:longitudFinal>
        </OrdT:DatosGeoespaciales>
        <OrdT:origenRespuesta>
          <xsl:value-of select="/ns0:Response/@FormiikResponseSource"/>
        </OrdT:origenRespuesta>
      </OrdT:DatosTransaccion>
    </tns:actualizarGestionOrdenRequest>
  </xsl:template>
</xsl:stylesheet>