<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Identidades/Midas/Sucursal" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="urn:mx.com.nmp.midas" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Services/Identidades/Midas/Sucursal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://nmpusuario.schema.nmp.servicios.montedepiedad.com.mx" xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns5="http://nmpusuario.services.nmp.servicios.montedepiedad.com.mx" xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding" xmlns:ns3="http://nmpstandardmessage.schema.nmp.servicios.montedepiedad.com.mx" xmlns:ns4="http://nmpempleado.schema.nmp.servicios.montedepiedad.com.mx" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDL/MidasProvisioningServiceWSDL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="getAllPerfilesOperativosResponse" namespace="urn:mx.com.nmp.midas"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../XSD/MidasProvisioningNewXSD_Elements.xsd"/>
            <oracle-xsl-mapper:rootElement name="getAllPerfilesOperativosResponse" namespace="urn:mx.com.nmp.midas"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON JAN 25 18:12:48 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:getAllPerfilesOperativosResponse>
         <ns2:listaSucursalPerfiles>
            <xsl:if test="/tns:getAllPerfilesOperativosResponse/tns:listaSucursalPerfiles/ns2:sucursalPerfiles">
               <ns2:sucursalPerfiles>
                  <xsl:if test="/tns:getAllPerfilesOperativosResponse/tns:listaSucursalPerfiles/ns2:sucursalPerfiles/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/tns:getAllPerfilesOperativosResponse/tns:listaSucursalPerfiles/ns2:sucursalPerfiles/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:for-each select="/tns:getAllPerfilesOperativosResponse/tns:listaSucursalPerfiles/ns2:sucursalPerfiles/ns2:SucursalPerfiles">
                     <ns2:SucursalPerfiles>
                        <xsl:if test="@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="ns2:perfiles">
                           <ns2:perfiles>
                              <xsl:if test="ns2:perfiles/@xsi:nil">
                                 <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                    <xsl:value-of select="ns2:perfiles/@xsi:nil"/>
                                 </xsl:attribute>
                              </xsl:if>
                              <xsl:if test="ns2:perfiles/ns2:perfil">
                                 <ns2:perfil>
                                    <xsl:if test="ns2:perfiles/ns2:perfil/@xsi:nil">
                                       <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                          <xsl:value-of select="ns2:perfiles/ns2:perfil/@xsi:nil"/>
                                       </xsl:attribute>
                                    </xsl:if>
                                    <xsl:for-each select="ns2:perfiles/ns2:perfil/ns2:PerfilType">
                                       <ns2:PerfilType>
                                          <xsl:if test="@xsi:nil">
                                             <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                <xsl:value-of select="@xsi:nil"/>
                                             </xsl:attribute>
                                          </xsl:if>
                                          <xsl:if test="ns2:id">
                                             <ns2:id>
                                                <xsl:if test="ns2:id/@xsi:nil">
                                                   <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                      <xsl:value-of select="ns2:id/@xsi:nil"/>
                                                   </xsl:attribute>
                                                </xsl:if>
                                                <xsl:value-of select="ns2:id"/>
                                             </ns2:id>
                                          </xsl:if>
                                          <xsl:if test="ns2:nombre">
                                             <ns2:nombre>
                                                <xsl:if test="ns2:nombre/@xsi:nil">
                                                   <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                      <xsl:value-of select="ns2:nombre/@xsi:nil"/>
                                                   </xsl:attribute>
                                                </xsl:if>
                                                <xsl:value-of select="ns2:nombre"/>
                                             </ns2:nombre>
                                          </xsl:if>
                                          <xsl:if test="ns2:tipo">
                                             <ns2:tipo>
                                                <xsl:if test="ns2:tipo/@xsi:nil">
                                                   <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                      <xsl:value-of select="ns2:tipo/@xsi:nil"/>
                                                   </xsl:attribute>
                                                </xsl:if>
                                                <xsl:value-of select="ns2:tipo"/>
                                             </ns2:tipo>
                                          </xsl:if>
                                          <xsl:if test="/tns:getAllPerfilesOperativosResponse/tns:listaSucursalPerfiles/ns2:sucursalPerfiles/ns2:SucursalPerfiles/ns2:sucursal">
                                             <ns2:sucursal>
                                                <xsl:value-of select="/tns:getAllPerfilesOperativosResponse/tns:listaSucursalPerfiles/ns2:sucursalPerfiles/ns2:SucursalPerfiles/ns2:sucursal"/>
                                             </ns2:sucursal>
                                          </xsl:if>
                                       </ns2:PerfilType>
                                    </xsl:for-each>
                                 </ns2:perfil>
                              </xsl:if>
                           </ns2:perfiles>
                        </xsl:if>
                     </ns2:SucursalPerfiles>
                  </xsl:for-each>
               </ns2:sucursalPerfiles>
            </xsl:if>
         </ns2:listaSucursalPerfiles>
      </tns:getAllPerfilesOperativosResponse>
   </xsl:template>
</xsl:stylesheet>