<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ActualizarProyectoBPEL" targetNamespace="http://xmlns.oracle.com/ActualizaProyecto/ActualizaProyectoPrj/ActualizarProyectoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ActualizaProyecto/ActualizaProyectoPrj/ActualizarProyectoBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Servicio/ActualizarProyecto/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comun/Servicio/ActualizarProyecto/v1/" schemaLocation="../Schemas/ActualizarProyecto.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ActualizarProyectoBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:ActualizarProyectoRequest"/>
   </wsdl:message>
   <wsdl:message name="ActualizarProyectoBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:ActualizarProyectoResponse"/>
   </wsdl:message>
   <wsdl:portType name="ActualizarProyectoBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ActualizarProyectoBPELRequestMessage"/>
         <wsdl:output message="client:ActualizarProyectoBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ActualizarProyectoBPEL">
      <plnk:role name="ActualizarProyectoBPELProvider" portType="client:ActualizarProyectoBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
