<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="SelProyectoUpdDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaProyecto/ActualizaProyectoPrj/SelProyectoUpdDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaProyecto/ActualizaProyectoPrj/SelProyectoUpdDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelProyectoUpdDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="SelProyectoUpdDB_plt">
      <plt:role name="SelProyectoUpdDB_role">
         <plt:portType name="tns:SelProyectoUpdDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SelProyectoUpdDB" schemaLocation="../Schemas/SelProyectoUpdDB_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="SelProyectoUpdDBSelect_inputParameters">
      <wsdl:part name="SelProyectoUpdDBSelect_inputParameters" element="top:SelProyectoUpdDBSelect_idSolicitudInputParameters"/>
   </wsdl:message>
   <wsdl:message name="Gpa013ProyectoCollection_msg">
      <wsdl:part name="Gpa013ProyectoCollection" element="top:Gpa013ProyectoCollection"/>
   </wsdl:message>
   <wsdl:portType name="SelProyectoUpdDB_ptt">
      <wsdl:operation name="SelProyectoUpdDBSelect">
         <wsdl:input message="tns:SelProyectoUpdDBSelect_inputParameters"/>
         <wsdl:output message="tns:Gpa013ProyectoCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
