<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl ns0 a xsd NMPConsultaC bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPSucursal" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:NMPConsultaC="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:a="http://servicios.montedepiedad.com.mx/NMP/Schema/CanonicalModel" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:NMPCampania="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Campania" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns2="http://schemas.microsoft.com/2003/10/Serialization/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/CRMClienteSvcAltaDisElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="GetClienteByNMPCredentialResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPSucursal"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPClientesSvcElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="getClientesByNumCredencialResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCliente"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI DEC 11 15:25:22 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <NMPConsultaC:getClientesByNumCredencialResponse>
      <NMPConsultaC:Cliente>
        <NMPConsultaC:idCliente>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:IdCliente"/>
        </NMPConsultaC:idCliente>
        <xsl:choose>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Genero = 1.0">
            <NMPConsultaC:genero>
              <xsl:text disable-output-escaping="no">H</xsl:text>
            </NMPConsultaC:genero>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Genero = 2.0">
            <NMPConsultaC:genero>
              <xsl:text disable-output-escaping="no">M</xsl:text>
            </NMPConsultaC:genero>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Genero = 3.0">
            <NMPConsultaC:genero>
              <xsl:text disable-output-escaping="no">N</xsl:text>
            </NMPConsultaC:genero>
          </xsl:when>
        </xsl:choose>
        <NMPConsultaC:nombre>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Nombre"/>
        </NMPConsultaC:nombre>
        <NMPConsultaC:apellidoPaterno>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:ApellidoPaterno"/>
        </NMPConsultaC:apellidoPaterno>
        <NMPConsultaC:apellidoMaterno>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:ApellidoMaterno"/>
        </NMPConsultaC:apellidoMaterno>
        <NMPConsultaC:fechaDeNacimiento>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:FechaNacimiento"/>
        </NMPConsultaC:fechaDeNacimiento>
        <xsl:choose>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Trabaja = 1.0">
            <NMPConsultaC:trabaja>
              <xsl:text disable-output-escaping="no">S</xsl:text>
            </NMPConsultaC:trabaja>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Trabaja = 0.0">
            <NMPConsultaC:trabaja>
              <xsl:text disable-output-escaping="no">N</xsl:text>
            </NMPConsultaC:trabaja>
          </xsl:when>
        </xsl:choose>
        <NMPConsultaC:banderaDeBoletinacion>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Boletinado"/>
        </NMPConsultaC:banderaDeBoletinacion>
        <NMPConsultaC:numeroDeCredencial>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CredencialNMP"/>
        </NMPConsultaC:numeroDeCredencial>
        <NMPConsultaC:Cotitular>
          <NMPConsultaC:nombre>
            <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Cotitulares/a:Cotitular/a:Nombre"/>
          </NMPConsultaC:nombre>
          <NMPConsultaC:apellidoPaterno>
            <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Cotitulares/a:Cotitular/a:ApellidoPaterno"/>
          </NMPConsultaC:apellidoPaterno>
          <NMPConsultaC:apellidoMaterno>
            <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Cotitulares/a:Cotitular/a:ApellidoMaterno"/>
          </NMPConsultaC:apellidoMaterno>
        </NMPConsultaC:Cotitular>
        <!--<NMPConsultaC:Cotitulares>
          <xsl:for-each select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Cotitulares/a:Cotitular">
            <NMPConsultaC:Cotitular>
              <NMPConsultaC:nombre>
                <xsl:value-of select="a:Nombre"/>
              </NMPConsultaC:nombre>
              <NMPConsultaC:apellidoPaterno>
                <xsl:value-of select="a:ApellidoPaterno"/>
              </NMPConsultaC:apellidoPaterno>
              <NMPConsultaC:apellidoMaterno>
                <xsl:value-of select="a:ApellidoMaterno"/>
              </NMPConsultaC:apellidoMaterno>
              <NMPConsultaC:ListaTelefonos>
                <xsl:for-each select="a:Telefonos/a:Telefono">
                  <NMPConsultaC:Telefono>
                    <NMPConsultaC:numeroTelefonico>
                      <xsl:value-of select="a:NumeroTelefonico"/>
                    </NMPConsultaC:numeroTelefonico>
                    <NMPConsultaC:extension>
                      <xsl:value-of select="a:Extension"/>
                    </NMPConsultaC:extension>
                    <NMPConsultaC:tipoTelefono>
                      <xsl:value-of select="a:TipoTelefono"/>
                    </NMPConsultaC:tipoTelefono>
                  </NMPConsultaC:Telefono>
                </xsl:for-each>
              </NMPConsultaC:ListaTelefonos>
            </NMPConsultaC:Cotitular>
          </xsl:for-each>
        </NMPConsultaC:Cotitulares>-->
        <!-- Validacion23-12-2016 -->
        <xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Beneficiarios/a:Beneficiario[1]">
        <NMPConsultaC:Beneficiarios>
          <xsl:for-each select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Beneficiarios/a:Beneficiario">
            <NMPConsultaC:Beneficiario>
              <NMPConsultaC:nombre>
                <xsl:value-of select="a:Nombre"/>
              </NMPConsultaC:nombre>
              <NMPConsultaC:apellidoPaterno>
                <xsl:value-of select="a:ApellidoPaterno"/>
              </NMPConsultaC:apellidoPaterno>
              <NMPConsultaC:apellidoMaterno>
                <xsl:value-of select="a:ApellidoMaterno"/>
              </NMPConsultaC:apellidoMaterno>
            </NMPConsultaC:Beneficiario>
          </xsl:for-each>
        </NMPConsultaC:Beneficiarios>
        </xsl:if>
        <!-- Validacion23-12-2016 -->
        <xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Email != ''">
        <NMPConsultaC:email>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Email"/>
        </NMPConsultaC:email>
        </xsl:if>
        <!--NMPConsultaC:CorreosElectronicos>
          <NMPConsultaC:CorreoElectronico>
              <NMPConsultaC:email>email@email.com</NMPConsultaC:email>
          </NMPConsultaC:CorreoElectronico>
        </NMPConsultaC:CorreosElectronicos-->
        <xsl:choose>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:SobreAforoAjustado != &quot;&quot;">
            <NMPConsultaC:sobreAforo>
              <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:SobreAforoAjustado"/>
            </NMPConsultaC:sobreAforo>
          </xsl:when>
          <xsl:otherwise>
            <NMPConsultaC:sobreAforo>
              <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:SobreAforoSIVA2"/>
            </NMPConsultaC:sobreAforo>
          </xsl:otherwise>
        </xsl:choose>
        
        <!-- Validacion23-12-2016 -->
        <xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CalificacionSIVA2 != ''">
        <NMPConsultaC:calificacionReal>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CalificacionSIVA2"/>
        </NMPConsultaC:calificacionReal>
        </xsl:if>
        
        <xsl:choose>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CalificacionAjustada != &quot;&quot;">
            <NMPConsultaC:calificacionMidas>
              <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CalificacionAjustada"/>
            </NMPConsultaC:calificacionMidas>
          </xsl:when>
          <xsl:otherwise>
            <NMPConsultaC:calificacionMidas>
              <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CalificacionSIVA2"/>
            </NMPConsultaC:calificacionMidas>
          </xsl:otherwise>
        </xsl:choose>
        
        <!-- Validacion23-12-2016 -->
        <xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CapacidadPago != ''">
        <NMPConsultaC:capacidadDePago>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:CapacidadPago"/>
        </NMPConsultaC:capacidadDePago>
        </xsl:if>
        <!-- Validacion23-12-2016 -->
        <xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:ProbabilidadIncumplimiento != ''">
        <NMPConsultaC:probabilidadIncumplimiento>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:ProbabilidadIncumplimiento"/>
        </NMPConsultaC:probabilidadIncumplimiento>
        </xsl:if>
        <!-- Validacion23-12-2016 -->
        <xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:IndiceRecuperacion != ''">
        <NMPConsultaC:indiceRecuperacion>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:IndiceRecuperacion"/>
        </NMPConsultaC:indiceRecuperacion>
        </xsl:if>
        <!-- Validacion23-12-2016 -->
        <xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:GradoConfianza != ''">
        <NMPConsultaC:gradoDeConfianza>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:GradoConfianza"/>
        </NMPConsultaC:gradoDeConfianza>
        </xsl:if>
        <NMPConsultaC:tipoIdentificacion>
          <xsl:value-of select="DVMFunctions:lookupValue ('GestionCatalogos/Comun/Resources/DVMs/TipoIdentificacion', 'CRM', /ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion, 'NMP', '' )"/>
        </NMPConsultaC:tipoIdentificacion>
        <!--xsl:choose>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 1.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">CREDENCIAL PARA VOTAR</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 2.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">PASAPORTE</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 3.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">DOCUMENTACIÓN EXPEDIDA POR EL INSTITUTO NACIONAL DE MIGRACIÓN</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 4.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">CÉDULA PROFESIONAL</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 5.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">CARTILLA DE SERVICIO MILITAR</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 6.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">CERTIFICADO DE MATRÍCULA CONSULAR</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 7.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">TARJETA ÚNICA DE IDENTIFICACIÓN MILITAR</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 8.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">TARJETA DE AFILIACIÓN AL INSTITUTO NACIONAL DE LAS PERSONAS ADULTAS M</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 9.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">CREDENCIALES Y CARNETS EXPEDIDOS POR EL INSTITUTO MEXICANO DEL SEGURO</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 10.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">LICENCIA PARA CONDUCIR</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 11.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">OTRA CREDENCIAL EMITIDA POR AUTORIDADES FEDERALES</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 12.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">OTRA CREDENCIAL EMITIDA POR AUTORIDADES ESTATALES</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 13.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">OTRA CREDENCIAL EMITIDA POR AUTORIDADES MUNICIPALES</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 14.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">FORMA MIGRATORIA</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
          <xsl:when test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoIdentificacion = 16.0">
            <NMPConsultaC:tipoIdentificacion>
              <xsl:text disable-output-escaping="no">ACTA CONSITUTIVA</xsl:text>
            </NMPConsultaC:tipoIdentificacion>
          </xsl:when>
        </xsl:choose-->
        <NMPConsultaC:numeroIdentificacion>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:NoIdentificacion"/>
        </NMPConsultaC:numeroIdentificacion>
        <NMPConsultaC:existCamp>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Clienteencampana"/>
        </NMPConsultaC:existCamp>
        <NMPConsultaC:deseaSerContactado>
          <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:DeseaserContactado"/>
        </NMPConsultaC:deseaSerContactado>
        <NMPConsultaC:alertaMIDAS>false</NMPConsultaC:alertaMIDAS>
        <NMPConsultaC:Contacto>
          <NMPConsultaC:ListaTelefonos>
            <xsl:for-each select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Telefonos/a:Telefono">
              <NMPConsultaC:Telefono>
                <NMPConsultaC:codigoArea>
                  <xsl:value-of select="a:Lada"/>
                </NMPConsultaC:codigoArea>
                <NMPConsultaC:numeroTelefonico>
                  <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Telefonos/a:Telefono/a:NumeroTelefonico"/>
                </NMPConsultaC:numeroTelefonico>
                <NMPConsultaC:extension>
                  <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Telefonos/a:Telefono/a:Extension"/>
                </NMPConsultaC:extension>
                <!--xsl:choose>
                  <xsl:when test="a:TipoTelefono = 1.0"-->
                    <NMPConsultaC:tipoTelefono>
                    <xsl:value-of select="DVMFunctions:lookupValue ('GestionCatalogos/Comun/Resources/DVMs/TipoTelefono', 'CRM', a:TipoTelefono, 'OTROS', 'No valido' )"/>
                      <!--xsl:text disable-output-escaping="no">casa</xsl:text-->
                    </NMPConsultaC:tipoTelefono>
                  <!--/xsl:when>
                  <xsl:when test="a:TipoTelefono = 2.0">
                    <NMPConsultaC:tipoTelefono>
                      <xsl:text disable-output-escaping="no">oficina</xsl:text>
                    </NMPConsultaC:tipoTelefono>
                  </xsl:when>
                  <xsl:when test="a:TipoTelefono = 3.0">
                    <NMPConsultaC:tipoTelefono>
                      <xsl:text disable-output-escaping="no">celular</xsl:text>
                    </NMPConsultaC:tipoTelefono>
                  </xsl:when>
                </xsl:choose-->
              </NMPConsultaC:Telefono>
            </xsl:for-each>
          </NMPConsultaC:ListaTelefonos>
          <NMPConsultaC:ListaDirecciones>
            <xsl:for-each select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Direcciones/a:Direccion">
              <NMPConsultaC:Direccion>
                <NMPConsultaC:nombreDelaCalle>
                  <xsl:value-of select="a:Calle"/>
                </NMPConsultaC:nombreDelaCalle>
                <NMPConsultaC:numeroExterior>
                  <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Direcciones/a:Direccion/a:NumeroExterior"/>
                </NMPConsultaC:numeroExterior>
                <NMPConsultaC:numeroInterior>
                  <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Direcciones/a:Direccion/a:NumeroInterior"/>
                </NMPConsultaC:numeroInterior>
                <NMPConsultaC:estado>
                  <xsl:value-of select="a:EstadoOtro"/>
                </NMPConsultaC:estado>
                <NMPConsultaC:idEstado>
                  <xsl:value-of select="a:Estado"/>
                </NMPConsultaC:idEstado>
                <NMPConsultaC:delegacionMunicipio>
                  <xsl:value-of select="a:DelegacionMunicipioOtro"/>
                </NMPConsultaC:delegacionMunicipio>
                <NMPConsultaC:colonia>
                  <xsl:value-of select="a:ColoniaOtro"/>
                </NMPConsultaC:colonia>
                <NMPConsultaC:codigoPostal>
                  <xsl:value-of select="a:CP"/>
                </NMPConsultaC:codigoPostal>
                <NMPConsultaC:tipoDomicilio>
                  <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Direcciones/a:Direccion/a:TipoDomicilio"/>
                </NMPConsultaC:tipoDomicilio>
              </NMPConsultaC:Direccion>
            </xsl:for-each>
          </NMPConsultaC:ListaDirecciones>
        </NMPConsultaC:Contacto>
        <NMPConsultaC:tipoCliente>
              <xsl:value-of select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:TipoCliente"/>
        </NMPConsultaC:tipoCliente>
		<xsl:if test="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Alertas/a:Alerta[1]">
          <NMPConsultaC:listaAlertas>
            <xsl:for-each select="/ns0:GetClienteByNMPCredentialResponse/ns0:GetClienteByNMPCredentialResult/a:Alertas/a:Alerta">
              <NMPConsultaC:alerta>
                <NMPConsultaC:nombreAlerta>
                  <xsl:value-of select="a:NombreAlerta"/>
                </NMPConsultaC:nombreAlerta>
                <NMPConsultaC:descripcion>
                  <xsl:value-of select="a:Descripcion"/>
                </NMPConsultaC:descripcion>
              </NMPConsultaC:alerta>
            </xsl:for-each>
          </NMPConsultaC:listaAlertas>
        </xsl:if>
      </NMPConsultaC:Cliente>
    </NMPConsultaC:getClientesByNumCredencialResponse>
  </xsl:template>
</xsl:stylesheet>