<wsdl:definitions
     name="EstadisticasProyectoDataSvc"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EstadisticaProyecto/EstadisticasProyectoDataSvc"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EstadisticaProyecto/EstadisticasProyectoDataSvc"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/EstadisticasProyectoDataSvc"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="EstadisticasProyectoDataSvc_plt" >
    <plt:role name="EstadisticasProyectoDataSvc_role" >
      <plt:portType name="tns:EstadisticasProyectoDataSvc_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/EstadisticasProyectoDataSvc" schemaLocation="EstadisticasProyectoDataSvc.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EstadisticasProyectoDataSvcInput_msg">
        <wsdl:part name="EstadisticasProyectoDataSvcInput_msg" element="db:EstadisticasProyectoDataSvcInput"/>
    </wsdl:message>
    <wsdl:message name="EstadisticasProyectoDataSvcOutputCollection_msg">
        <wsdl:part name="EstadisticasProyectoDataSvcOutputCollection" element="db:EstadisticasProyectoDataSvcOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="EstadisticasProyectoDataSvc_ptt">
        <wsdl:operation name="EstadisticasProyectoDataSvc">
            <wsdl:input message="tns:EstadisticasProyectoDataSvcInput_msg"/>
            <wsdl:output message="tns:EstadisticasProyectoDataSvcOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
