<wsdl:definitions name="ActualizarProyectoBPEL" targetNamespace="http://xmlns.oracle.com/ActualizaProyecto/ActualizaProyectoPrj/ActualizarProyectoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ActualizaProyecto/ActualizaProyectoPrj/ActualizarProyectoBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Servicio/ActualizarProyecto/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.22:7007/soa-infra/services/GPADomain/ActualizaProyectoPrj!1.0/WSDLs/ActualizarProyectoBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ActualizarProyectoBPEL">
        <plnk:role name="ActualizarProyectoBPELProvider" portType="client:ActualizarProyectoBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/Comun/Servicio/ActualizarProyecto/v1/" schemaLocation="XMLSchema_-1622032020.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ActualizarProyectoBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:ActualizarProyectoRequest"/>
    </wsdl:message>
    <wsdl:message name="ActualizarProyectoBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:ActualizarProyectoResponse"/>
    </wsdl:message>
    <wsdl:portType name="ActualizarProyectoBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ActualizarProyectoBPELRequestMessage"/>
            <wsdl:output message="client:ActualizarProyectoBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ActualizarProyectoBPELBinding" type="client:ActualizarProyectoBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ActualizarProyectoService_ep">
        <wsdl:port name="ActualizarProyectoBPEL_pt" binding="client:ActualizarProyectoBPELBinding">
            <soap:address location="http://11.50.0.22:7007/soa-infra/services/GPADomain/ActualizaProyectoPrj/ActualizarProyectoService_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>