<?xml version='1.0' encoding='UTF-8'?>
<WL5G3N0:definitions name="ProrrateoSvc" targetNamespace="http://ws.gpa.qualitas.mx/" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://www.w3.org/2001/XMLSchema" xmlns:WL5G3N2="http://ws.gpa.qualitas.mx/" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/">
   <WL5G3N0:types>
      <WL5G3N1:schema xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.gpa.qualitas.mx/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <WL5G3N1:import namespace="http://ws.gpa.qualitas.mx/" schemaLocation="../Schemas/ProrrateoParsingSchema_1.xsd"/>
      </WL5G3N1:schema>
   </WL5G3N0:types>
   <WL5G3N0:message name="parse">
      <WL5G3N0:part name="data" type="WL5G3N1:base64Binary"/>
   </WL5G3N0:message>
   <WL5G3N0:message name="parseResponse">
      <WL5G3N0:part name="Prorrateo" type="WL5G3N2:prorrateoResponse"/>
   </WL5G3N0:message>
   <WL5G3N0:portType name="ProrrateoSvc">
      <WL5G3N0:operation name="parse">
         <WL5G3N0:input message="WL5G3N2:parse"/>
         <WL5G3N0:output message="WL5G3N2:parseResponse"/>
      </WL5G3N0:operation>
   </WL5G3N0:portType>
   <WL5G3N0:binding name="ProrrateoSvcPortBinding" type="WL5G3N2:ProrrateoSvc">
      <WL5G3N3:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
      <WL5G3N0:operation name="parse">
         <WL5G3N3:operation/>
         <WL5G3N0:input>
            <WL5G3N3:body use="literal" namespace="http://ws.gpa.qualitas.mx/"/>
         </WL5G3N0:input>
         <WL5G3N0:output>
            <WL5G3N3:body use="literal" namespace="http://ws.gpa.qualitas.mx/"/>
         </WL5G3N0:output>
      </WL5G3N0:operation>
   </WL5G3N0:binding>
   <WL5G3N0:service name="ProrrateoSvcPortBindingQSService">
      <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
      <WL5G3N0:port name="ProrrateoSvcPortBindingQSPort" binding="WL5G3N2:ProrrateoSvcPortBinding">
         <WL5G3N3:address location="http://11.50.0.20:7006/Finance/AP/GPA/Commons/ProxySvc/ProrrateoParsingPxy"/>
      </WL5G3N0:port>
   </WL5G3N0:service>
</WL5G3N0:definitions>
