<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://qualitas.com.mx/Comun/Oficina/validarOficinas/v1/" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:client="http://xmlns.oracle.com/ValidarCentroDeCostosApp/ValidarOficinasPrj/ValidarOficinasBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ValidarOficinasBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="validarOficinasRequest" namespace="http://qualitas.com.mx/Comun/Oficina/validarOficinas/v1/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ValidarOficinasBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="validarOficinasResponse" namespace="http://qualitas.com.mx/Comun/Oficina/validarOficinas/v1/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON DEC 19 20:39:17 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:validarOficinasResponse>
         <xsl:for-each select="/ns0:validarOficinasRequest/ns0:Input/ns0:claveOficina">
            <ns0:OperationResponse>
               <xsl:for-each select=".">
                  <xsl:choose>
                     <xsl:when test="self::node() = 12345">
                        <ns1:codigoRespuesta>
                           <xsl:value-of select="1"/>
                        </ns1:codigoRespuesta>
                     </xsl:when>
                     <xsl:otherwise>
                        <ns1:codigoRespuesta>
                           <xsl:value-of select="0"/>
                        </ns1:codigoRespuesta>
                     </xsl:otherwise>
                  </xsl:choose>
               </xsl:for-each>
               <xsl:for-each select=".">
                  <xsl:choose>
                     <xsl:when test="self::node() = 12345">
                        <ns1:descripcionRespuesta>NO ENCONTRARON OFICINAS</ns1:descripcionRespuesta>
                     </xsl:when>
                     <xsl:otherwise>
                        <ns1:descripcionRespuesta>SE ENCONTRARON OFICINAS</ns1:descripcionRespuesta>
                     </xsl:otherwise>
                  </xsl:choose>
               </xsl:for-each>
            </ns0:OperationResponse>
         </xsl:for-each>
      </ns0:validarOficinasResponse>
   </xsl:template>
</xsl:stylesheet>