<wsdl:definitions name="AsignarCuentasContables" targetNamespace="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/" xmlns:tns1="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.22:7007/soa-infra/services/GPADomain/AsignarContablesPrj!1.0/WSDLs/AsignarCuentasContables.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="AsignarCuentasContables">
        <plnk:role name="AsignarCuentasContablesProvider" portType="client:AsignarCuentasContables"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/v1/" schemaLocation="XMLSchema_-1738338818.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="AsignarCuentasContablesRequestMessage">
        <wsdl:part name="payload" element="tns1:GuardarSolicitudRequest"/>
    </wsdl:message>
    <wsdl:message name="AsignarCuentasContablesResponseMessage">
        <wsdl:part name="payload" element="tns1:GuardarSolicitudResponse"/>
    </wsdl:message>
    <wsdl:portType name="AsignarCuentasContables">
        <wsdl:operation name="process">
            <wsdl:input message="client:AsignarCuentasContablesRequestMessage"/>
            <wsdl:output message="client:AsignarCuentasContablesResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AsignarCuentasContablesBinding" type="client:AsignarCuentasContables">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="asignarcuentascontables_client_ep">
        <wsdl:port name="AsignarCuentasContables_pt" binding="client:AsignarCuentasContablesBinding">
            <soap:address location="http://11.50.0.22:7007/soa-infra/services/GPADomain/AsignarContablesPrj/asignarcuentascontables_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>