<wsdl:definitions name="ActualizaEstadoSolicitudBPEL" targetNamespace="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.20:7007/soa-infra/services/GPADomain/ActualizarEstadoSolicitudPrj!1.0/WSDLs/ActualizaEstadoSolicitudBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ActualizaEstadoSolicitudBPEL">
        <plnk:role name="ActualizaEstadoSolicitudBPELProvider" portType="client:ActualizaEstadoSolicitudBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/ActualizarEstadoSolicitudApp/ActualizarEstadoSolicitudPrj/ActualizaEstadoSolicitudBPEL" schemaLocation="XMLSchema_-790113000.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ActualizaEstadoSolicitudBPELRequestMessage">
        <wsdl:part name="payload" element="client:estadoSolicitudRequest"/>
    </wsdl:message>
    <wsdl:message name="ActualizaEstadoSolicitudBPELResponseMessage">
        <wsdl:part name="payload" element="client:estadoSolicitudResponse"/>
    </wsdl:message>
    <wsdl:portType name="ActualizaEstadoSolicitudBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ActualizaEstadoSolicitudBPELRequestMessage"/>
            <wsdl:output message="client:ActualizaEstadoSolicitudBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ActualizaEstadoSolicitudBPELBinding" type="client:ActualizaEstadoSolicitudBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="actualizaestadosolicitudbpel_client_ep">
        <wsdl:port name="ActualizaEstadoSolicitudBPEL_pt" binding="client:ActualizaEstadoSolicitudBPELBinding">
            <soap:address location="http://11.50.0.20:7007/soa-infra/services/GPADomain/ActualizarEstadoSolicitudPrj/actualizaestadosolicitudbpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>