<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:doc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ct="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPCommonTypes" xmlns:ava="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:NMPIniciaASR="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:NMPPers="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPersona">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../../../SolicitudesVSR/Resources/Schemas/NMPSolicitudesVSRXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarSolicitudResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/SolicitudesVSR"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPVehiculosSinResguardoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="consultarSolicitudResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON MAR 06 20:31:22 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:consultarSolicitudResponse>
         <NMPIniciaASR:folio>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:folioTramite"/>
         </NMPIniciaASR:folio>
         <NMPIniciaASR:estadoSolicitud>
            <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:estadoSolicitud"/>
         </NMPIniciaASR:estadoSolicitud>
         <NMPIniciaASR:cliente>
            <NMPIniciaASR:numeroCredencial>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:numCredencial"/>
            </NMPIniciaASR:numeroCredencial>
         </NMPIniciaASR:cliente>
         <tns:vehiculo>
            <veh:tipoVehiculo>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:tipoVehiculo"/>
            </veh:tipoVehiculo>
            <veh:vin>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:vin"/>
            </veh:vin>
            <veh:serieMotor>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieMotor"/>
            </veh:serieMotor>
            <veh:placas>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:placas"/>
            </veh:placas>
            <veh:marca>
               <veh:idMarca>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idMarca"/>
               </veh:idMarca>
               <veh:descripcion>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionMarca"/>
               </veh:descripcion>
            </veh:marca>
            <veh:submarca>
               <veh:idSubMarca>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idSubMarca"/>
               </veh:idSubMarca>
               <veh:descripcion>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionSubMarca"/>
               </veh:descripcion>
            </veh:submarca>
            <veh:modelo>
               <veh:idModelo>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idModelo"/>
               </veh:idModelo>
               <veh:descripcion>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionModelo"/>
               </veh:descripcion>
            </veh:modelo>
            <veh:version>
               <veh:idVersion>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idVersion"/>
               </veh:idVersion>
               <veh:descripcion>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionVersion"/>
               </veh:descripcion>
            </veh:version>
            <veh:kilometraje>
               <veh:idKilometraje>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:idKilometraje"/>
               </veh:idKilometraje>
               <veh:descripcion>
                  <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:descripcionKilometraje"/>
               </veh:descripcion>
            </veh:kilometraje>
            <veh:complementos>
               <xsl:for-each select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:nmpGrupoComplementosCollection/veh:complemento">
                  <veh:complemento>
                     <veh:idComplemento>
                        <xsl:value-of select="veh:idComplemento"/>
                     </veh:idComplemento>
                     <veh:descripcion>
                        <xsl:value-of select="veh:descripcion"/>
                     </veh:descripcion>
                  </veh:complemento>
               </xsl:for-each>
            </veh:complementos>
            <veh:color>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:color"/>
            </veh:color>
            <veh:serieChasis>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:serieChasis"/>
            </veh:serieChasis>
            <veh:numeroTarjetaCirculacion>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroTarjetaCirculacion"/>
            </veh:numeroTarjetaCirculacion>
            <veh:numeroFactura>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:numeroFactura"/>
            </veh:numeroFactura>
            <veh:rfcEmisor>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:rfcEmisor"/>
            </veh:rfcEmisor>
            <veh:agenciaOrigen>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:agenciaOrigen"/>
            </veh:agenciaOrigen>
            <veh:comentarios>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpVehiculoInfoCollection/ns0:NmpVehiculoInfo/veh:comentarios"/>
            </veh:comentarios>
         </tns:vehiculo>
         <tns:cotizacion>
            <cot:montoAvaluo>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluo"/>
            </cot:montoAvaluo>
            <cot:montoMaximoPrestamo>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoPrestamo"/>
            </cot:montoMaximoPrestamo>
            <cot:montoPrestamoSolicitado>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:prestamoSolicitado"/>
            </cot:montoPrestamoSolicitado>
            <cot:montoCastigo>
               <xsl:value-of select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:montoAvaluoDictaminador"/>
            </cot:montoCastigo>
         </tns:cotizacion>
         <tns:documentos>
            <xsl:for-each select="/ns0:consultarSolicitudResponse/ns0:NmpSolicitudesClientesInfo/ns0:nmpDocumentosSolicitudInfoCollection/ns0:NmpDocumentosSolicitudInfo">
               <doc:documentos>
                  <doc:nombreDocumento>
                     <xsl:value-of select="doc:nombreDocumento"/>
                  </doc:nombreDocumento>
                  <doc:documentoURL>
                     <xsl:value-of select="doc:url"/>
                  </doc:documentoURL>
                  <doc:fechaCreacion>
                     <xsl:value-of select="doc:fechaCreacion"/>
                  </doc:fechaCreacion>
                  <doc:tipoDocumento>
                     <xsl:value-of select="doc:tipoDocumento"/>
                  </doc:tipoDocumento>
                  <doc:descripcion>
                     <xsl:value-of select="concat (doc:creadoPor, '-', doc:fechaActualizacion )"/>
                  </doc:descripcion>
               </doc:documentos>
            </xsl:for-each>
         </tns:documentos>
      </tns:consultarSolicitudResponse>
   </xsl:template>
</xsl:stylesheet>