<wsdl:definitions name="ObtenerEmpleadoBPEL" targetNamespace="http://xmlns.oracle.com/ObtenerEmpleadoApp/ObtenerEmpleadoPrj/ObtenerEmpleadoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ObtenerEmpleadoApp/ObtenerEmpleadoPrj/ObtenerEmpleadoBPEL" xmlns:ns1="http://qualitas.com.mx/Personas/Empleado/obtenerEmpleadoPorNumero/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.22:7007/soa-infra/services/GPADomain/ObtenerEmpleadoPrj!1.0/WSDLs/ObtenerEmpleadoBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ObtenerEmpleadoBPEL">
        <plnk:role name="ObtenerEmpleadoBPELProvider" portType="client:ObtenerEmpleadoBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/Personas/Empleado/obtenerEmpleadoPorNumero/v1/" schemaLocation="XMLSchema_516097970.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerEmpleadoBPELRequestMessage">
        <wsdl:part name="payload" element="ns1:ObtenerEmpleadoRequest"/>
    </wsdl:message>
    <wsdl:message name="ObtenerEmpleadoBPELResponseMessage">
        <wsdl:part name="payload" element="ns1:ObtenerEmpleadoResponse"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerEmpleadoBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ObtenerEmpleadoBPELRequestMessage"/>
            <wsdl:output message="client:ObtenerEmpleadoBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ObtenerEmpleadoBPELBinding" type="client:ObtenerEmpleadoBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="obtenerempleadobpel_client_ep">
        <wsdl:port name="ObtenerEmpleadoBPEL_pt" binding="client:ObtenerEmpleadoBPELBinding">
            <soap:address location="http://11.50.0.22:7007/soa-infra/services/GPADomain/ObtenerEmpleadoPrj/obtenerempleadobpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>