<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/SolicitudDataSvc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/SolicitudesBDQry/SolicitudDataSvc" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator">
  <oracle-xsl-mapper:schema xml:id="id_2">
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources xml:id="id_3">
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
        <oracle-xsl-mapper:schema location="http://11.50.0.20:7006/Finance/AP/GPA/Data/ProxySvc/SolicitudDataSvcPxy?WSDL%2FFinance%2FAP%2FGPA%2FData%2FResources%2FSolicitudDataSvc" xml:id="id_5"/>
        <oracle-xsl-mapper:rootElement name="Gpa001SolicitudCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SolicitudDataSvc" xml:id="id_6"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets xml:id="id_7">
      <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
        <oracle-xsl-mapper:schema location="http://11.50.0.20:7006/Finance/AP/GPA/Data/ProxySvc/SolicitudDataSvcPxy?WSDL%2FFinance%2FAP%2FGPA%2FData%2FResources%2FSolicitudDataSvc" xml:id="id_9"/>
        <oracle-xsl-mapper:rootElement name="Gpa001SolicitudCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SolicitudDataSvc" xml:id="id_10"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI JUN 09 16:35:45 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/" xml:id="id_11">
    <ns0:Gpa001SolicitudCollection xml:id="id_797">
      <xsl:for-each select="/ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud" xml:id="id_798">
        <ns0:Gpa001Solicitud xml:id="id_799">
          <ns0:idSolicitud xml:id="id_800">
            <xsl:value-of select="ns0:idSolicitud" xml:id="id_801"/>
          </ns0:idSolicitud>
          <xsl:if test="ns0:idTpSolicitud" xml:id="id_802">
            <ns0:idTpSolicitud xml:id="id_803">
              <xsl:value-of select="ns0:idTpSolicitud" xml:id="id_804"/>
            </ns0:idTpSolicitud>
          </xsl:if>
          <xsl:if test="ns0:nuEmpleado" xml:id="id_805">
            <ns0:nuEmpleado xml:id="id_806">
              <xsl:value-of select="ns0:nuEmpleado" xml:id="id_807"/>
            </ns0:nuEmpleado>
          </xsl:if>
          <xsl:if test="ns0:nombreEmpleado" xml:id="id_808">
            <ns0:nombreEmpleado xml:id="id_809">
              <xsl:value-of select="ns0:nombreEmpleado" xml:id="id_810"/>
            </ns0:nombreEmpleado>
          </xsl:if>
          <xsl:if test="ns0:fhActualizacion" xml:id="id_811">
            <ns0:fhActualizacion xml:id="id_812">
              <xsl:value-of select="ns0:fhActualizacion" xml:id="id_816"/>
            </ns0:fhActualizacion>
          </xsl:if>
          <xsl:if test="ns0:idUsuario" xml:id="id_817">
            <ns0:idUsuario xml:id="id_818">
              <xsl:value-of select="ns0:idUsuario" xml:id="id_822"/>
            </ns0:idUsuario>
          </xsl:if>
          <xsl:if test="ns0:totalPagar" xml:id="id_823">
            <ns0:totalPagar xml:id="id_824">
              <xsl:value-of select="ns0:totalPagar" xml:id="id_828"/>
            </ns0:totalPagar>
          </xsl:if>
          <xsl:if test="ns0:fhCreacion" xml:id="id_829">
            <ns0:fhCreacion xml:id="id_830">
              <xsl:value-of select="ns0:fhCreacion" xml:id="id_834"/>
            </ns0:fhCreacion>
          </xsl:if>
          <xsl:if test="ns0:nuOrden" xml:id="id_835">
            <ns0:nuOrden xml:id="id_836">
              <xsl:value-of select="ns0:nuOrden" xml:id="id_840"/>
            </ns0:nuOrden>
          </xsl:if>
          <xsl:if test="ns0:fhFinProceso" xml:id="id_841">
            <ns0:fhFinProceso xml:id="id_842">
              <xsl:value-of select="ns0:fhFinProceso" xml:id="id_846"/>
            </ns0:fhFinProceso>
          </xsl:if>
          <xsl:if test="ns0:procesable" xml:id="id_847">
            <ns0:procesable xml:id="id_848">
              <xsl:value-of select="ns0:procesable" xml:id="id_852"/>
            </ns0:procesable>
          </xsl:if>
          <xsl:if test="ns0:idSubtpSolic" xml:id="id_853">
            <ns0:idSubtpSolic xml:id="id_854">
              <xsl:value-of select="ns0:idSubtpSolic" xml:id="id_858"/>
            </ns0:idSubtpSolic>
          </xsl:if>
          <xsl:if test="ns0:impCContablesCollection/ns0:Gpa020ImpCcontables" xml:id="id_859">
            <ns0:impCContablesCollection xml:id="id_860">
              <xsl:for-each select="ns0:impCContablesCollection/ns0:Gpa020ImpCcontables" xml:id="id_861">
                <ns0:Gpa020ImpCcontables xml:id="id_862">
                  <ns0:idImpCc xml:id="id_863">
                    <xsl:value-of select="ns0:idImpCc" xml:id="id_864"/>
                  </ns0:idImpCc>
                  <xsl:if test="ns0:idDescIva" xml:id="id_865">
                    <ns0:idDescIva xml:id="id_866">
                      <xsl:value-of select="ns0:idDescIva" xml:id="id_867"/>
                    </ns0:idDescIva>
                  </xsl:if>
                  <xsl:if test="ns0:idUsuario" xml:id="id_868">
                    <ns0:idUsuario xml:id="id_869">
                      <xsl:value-of select="ns0:idUsuario" xml:id="id_873"/>
                    </ns0:idUsuario>
                  </xsl:if>
                  <xsl:if test="ns0:descPago" xml:id="id_874">
                    <ns0:descPago xml:id="id_875">
                      <xsl:value-of select="ns0:descPago" xml:id="id_879"/>
                    </ns0:descPago>
                  </xsl:if>
                  <xsl:if test="ns0:ccSubtotal" xml:id="id_880">
                    <ns0:ccSubtotal xml:id="id_881">
                      <xsl:value-of select="ns0:ccSubtotal" xml:id="id_885"/>
                    </ns0:ccSubtotal>
                  </xsl:if>
                  <xsl:if test="ns0:ccIva" xml:id="id_886">
                    <ns0:ccIva xml:id="id_887">
                      <xsl:value-of select="ns0:ccIva" xml:id="id_891"/>
                    </ns0:ccIva>
                  </xsl:if>
                  <xsl:if test="ns0:ccRetencionIva" xml:id="id_892">
                    <ns0:ccRetencionIva xml:id="id_893">
                       <xsl:value-of select="ns0:ccRetencionIva" xml:id="id_897"/>
                    </ns0:ccRetencionIva>
                  </xsl:if>
                  <xsl:if test="ns0:ccRetencionIsr" xml:id="id_898">
                    <ns0:ccRetencionIsr xml:id="id_899">
                      <xsl:value-of select="ns0:ccRetencionIsr" xml:id="id_903"/>
                    </ns0:ccRetencionIsr>
                  </xsl:if>
                  <xsl:if test="ns0:ccOtrosImpuestos" xml:id="id_904">
                    <ns0:ccOtrosImpuestos xml:id="id_905">
                      <xsl:value-of select="ns0:ccOtrosImpuestos" xml:id="id_909"/>
                    </ns0:ccOtrosImpuestos>
                  </xsl:if>
                </ns0:Gpa020ImpCcontables>
              </xsl:for-each>
            </ns0:impCContablesCollection>
          </xsl:if>
          <xsl:if test="ns0:proyecto" xml:id="id_910">
            <ns0:proyecto xml:id="id_911">
              <ns0:idProyecto xml:id="id_915">
                <xsl:value-of select="ns0:proyecto/ns0:idProyecto" xml:id="id_916"/>
              </ns0:idProyecto>
              <xsl:if test="ns0:proyecto/ns0:descProyecto" xml:id="id_917">
                <ns0:descProyecto xml:id="id_918">
                  <xsl:value-of select="ns0:proyecto/ns0:descProyecto" xml:id="id_922"/>
                </ns0:descProyecto>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:stProyecto" xml:id="id_923">
                <ns0:stProyecto xml:id="id_924">
                  <xsl:value-of select="ns0:proyecto/ns0:stProyecto" xml:id="id_928"/>
                </ns0:stProyecto>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:presupuestoAprobado" xml:id="id_929">
                <ns0:presupuestoAprobado xml:id="id_930">
                  <xsl:value-of select="ns0:proyecto/ns0:presupuestoAprobado" xml:id="id_934"/>
                </ns0:presupuestoAprobado>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:parcialidades" xml:id="id_935">
                <ns0:parcialidades xml:id="id_936">
                  <xsl:value-of select="ns0:proyecto/ns0:parcialidades" xml:id="id_940"/>
                </ns0:parcialidades>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:fhCreacionProy" xml:id="id_941">
                <ns0:fhCreacionProy xml:id="id_942">
                  <xsl:value-of select="ns0:proyecto/ns0:fhCreacionProy" xml:id="id_946"/>
                </ns0:fhCreacionProy>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:idCondicionesPago" xml:id="id_947">
                <ns0:idCondicionesPago xml:id="id_948">
                  <xsl:value-of select="ns0:proyecto/ns0:idCondicionesPago" xml:id="id_952"/>
                </ns0:idCondicionesPago>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:idSolicitud" xml:id="id_953">
                <ns0:idSolicitud xml:id="id_954">
                  <xsl:value-of select="ns0:proyecto/ns0:idSolicitud" xml:id="id_958"/>
                </ns0:idSolicitud>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:idPrestador" xml:id="id_959">
                <ns0:idPrestador xml:id="id_960">
                  <xsl:value-of select="ns0:proyecto/ns0:idPrestador" xml:id="id_964"/>
                </ns0:idPrestador>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:centroCosto" xml:id="id_965">
                <ns0:centroCosto xml:id="id_966">
                  <xsl:value-of select="ns0:proyecto/ns0:centroCosto" xml:id="id_970"/>
                </ns0:centroCosto>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:descOficina" xml:id="id_971">
                <ns0:descOficina xml:id="id_972">
                  <xsl:value-of select="ns0:proyecto/ns0:descOficina" xml:id="id_976"/>
                </ns0:descOficina>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:descArea" xml:id="id_977">
                <ns0:descArea xml:id="id_978">
                  <xsl:value-of select="ns0:proyecto/ns0:descArea" xml:id="id_982"/>
                </ns0:descArea>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:responsableArea" xml:id="id_983">
                <ns0:responsableArea xml:id="id_984">
                  <xsl:value-of select="ns0:proyecto/ns0:responsableArea" xml:id="id_988"/>
                </ns0:responsableArea>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:nombreProyecto" xml:id="id_989">
                <ns0:nombreProyecto xml:id="id_990">
                  <xsl:value-of select="ns0:proyecto/ns0:nombreProyecto" xml:id="id_994"/>
                </ns0:nombreProyecto>
              </xsl:if>
              <xsl:if test="*:proyecto/ns0:cveOficina" xml:id="id_995">
                <ns0:cveOficina xml:id="id_996">
                  <xsl:value-of select="ns0:proyecto/ns0:cveOficina" xml:id="id_1000"/>
                </ns0:cveOficina>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:procesable" xml:id="id_1001">
                <ns0:procesable xml:id="id_1002">
                  <xsl:value-of select="ns0:proyecto/ns0:procesable" xml:id="id_1006"/>
                </ns0:procesable>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:presupuestoDisponible" xml:id="id_1007">
                <ns0:presupuestoDisponible xml:id="id_1008">
                  <xsl:value-of select="ns0:proyecto/ns0:presupuestoDisponible" xml:id="id_1012"/>
                </ns0:presupuestoDisponible>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:pagosProceso" xml:id="id_1013">
                <ns0:pagosProceso xml:id="id_1014">
                  <xsl:value-of select="ns0:proyecto/ns0:pagosProceso" xml:id="id_1018"/>
                </ns0:pagosProceso>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:idProyectomarco" xml:id="id_1019">
                <ns0:idProyectomarco xml:id="id_1020">
                  <xsl:value-of select="ns0:proyecto/ns0:idProyectomarco" xml:id="id_1024"/>
                </ns0:idProyectomarco>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:parcialidadActual" xml:id="id_1025">
                <ns0:parcialidadActual xml:id="id_1026">
                  <xsl:value-of select="ns0:proyecto/ns0:parcialidadActual" xml:id="id_1030"/>
                </ns0:parcialidadActual>
              </xsl:if>
              <xsl:if test="ns0:proyecto/ns0:tipoMoneda" xml:id="id_1031">
                <ns0:tipoMoneda xml:id="id_1032">
                  <xsl:value-of select="ns0:proyecto/ns0:tipoMoneda" xml:id="id_1036"/>
                </ns0:tipoMoneda>
              </xsl:if>
            </ns0:proyecto>
          </xsl:if>
          <xsl:if test="ns0:pagosCollection" xml:id="id_1037">
            <ns0:pagosCollection xml:id="id_1038">
              <xsl:for-each select="ns0:pagosCollection/ns0:Gpa019Pagos" xml:id="id_1039">
                <ns0:Gpa019Pagos xml:id="id_1040">
                  <ns0:idPagos xml:id="id_1041">
                    <xsl:value-of select="ns0:idPagos" xml:id="id_1042"/>
                  </ns0:idPagos>
                  <xsl:if test="ns0:numOrden" xml:id="id_1043">
                    <ns0:numOrden xml:id="id_1044">
                      <xsl:value-of select="ns0:numOrden" xml:id="id_1048"/>
                    </ns0:numOrden>
                  </xsl:if>
                  <xsl:if test="ns0:numCaratula" xml:id="id_1049">
                    <ns0:numCaratula xml:id="id_1050">
                      <xsl:value-of select="ns0:numCaratula" xml:id="id_1054"/>
                    </ns0:numCaratula>
                  </xsl:if>
                  <xsl:if test="ns0:estadoPago" xml:id="id_1055">
                    <ns0:estadoPago xml:id="id_1056">
                      <xsl:value-of select="ns0:estadoPago" xml:id="id_1060"/>
                    </ns0:estadoPago>
                  </xsl:if>
                  <xsl:if test="ns0:fhCreacion" xml:id="id_1061">
                    <ns0:fhCreacion xml:id="id_1062">
                      <xsl:value-of select="ns0:fhCreacion" xml:id="id_1066"/>
                    </ns0:fhCreacion>
                  </xsl:if>
                  <xsl:if test="ns0:fhActualizacion" xml:id="id_1067">
                    <ns0:fhActualizacion xml:id="id_1068">
                      <xsl:value-of select="ns0:fhActualizacion" xml:id="id_1072"/>
                    </ns0:fhActualizacion>
                  </xsl:if>
                  <xsl:if test="ns0:procesable" xml:id="id_1073">
                    <ns0:procesable xml:id="id_1074">
                      <xsl:value-of select="ns0:procesable" xml:id="id_1078"/>
                    </ns0:procesable>
                  </xsl:if>
                </ns0:Gpa019Pagos>
              </xsl:for-each>
            </ns0:pagosCollection>
          </xsl:if>
          <xsl:if test="ns0:estado" xml:id="id_1079">
            <ns0:estado xml:id="id_1080">
              <ns0:idEstado xml:id="id_1084">
                <xsl:value-of select="ns0:estado/ns0:idEstado" xml:id="id_1085"/>
              </ns0:idEstado>
              <xsl:if test="ns0:estado/ns0:descripcion" xml:id="id_1086">
                <ns0:descripcion xml:id="id_1087">
                  <xsl:value-of select="ns0:estado/ns0:descripcion" xml:id="id_1088"/>
                </ns0:descripcion>
              </xsl:if>
              <xsl:if test="ns0:estado/ns0:stRegistro" xml:id="id_1089">
                <ns0:stRegistro xml:id="id_1090">
                  <xsl:value-of select="ns0:estado/ns0:stRegistro" xml:id="id_1091"/>
                </ns0:stRegistro>
              </xsl:if>
              <xsl:if test="ns0:estado/ns0:clasificacion" xml:id="id_1092">
                <ns0:clasificacion xml:id="id_1093">
                  <xsl:value-of select="ns0:estado/ns0:clasificacion" xml:id="id_1097"/>
                </ns0:clasificacion>
              </xsl:if>
            </ns0:estado>
          </xsl:if>
          <xsl:if test="ns0:importesCollection" xml:id="id_1098">
            <ns0:importesCollection xml:id="id_1099">
              <xsl:for-each select="ns0:importesCollection/ns0:Gpa002Importes" xml:id="id_1100">
                <ns0:Gpa002Importes xml:id="id_1101">
                  <ns0:idImportes xml:id="id_1102">
                    <xsl:value-of select="ns0:idImportes" xml:id="id_1103"/>
                  </ns0:idImportes>
                  <xsl:if test="ns0:montoIva" xml:id="id_1104">
                    <ns0:montoIva xml:id="id_1105">
                      <xsl:value-of select="ns0:montoIva" xml:id="id_1109"/>
                    </ns0:montoIva>
                  </xsl:if>
                  <xsl:if test="ns0:tasaIva" xml:id="id_1110">
                    <ns0:tasaIva xml:id="id_1111">
                      <xsl:value-of select="ns0:tasaIva" xml:id="id_1115"/>
                    </ns0:tasaIva>
                  </xsl:if>
                  <xsl:if test="ns0:observaciones" xml:id="id_1116">
                    <ns0:observaciones xml:id="id_1117">
                      <xsl:value-of select="ns0:observaciones" xml:id="id_1121"/>
                    </ns0:observaciones>
                  </xsl:if>
                  <xsl:if test="ns0:folioFiscal" xml:id="id_1122">
                    <ns0:folioFiscal xml:id="id_1123">
                      <xsl:value-of select="ns0:folioFiscal" xml:id="id_1127"/>
                    </ns0:folioFiscal>
                  </xsl:if>
                  <xsl:if test="ns0:nombreDocumento" xml:id="id_1128">
                    <ns0:nombreDocumento xml:id="id_1129">
                      <xsl:value-of select="ns0:nombreDocumento" xml:id="id_1133"/>
                    </ns0:nombreDocumento>
                  </xsl:if>
                  <xsl:if test="ns0:xmlFactura" xml:id="id_1134">
                    <ns0:xmlFactura xml:id="id_1135">
                      <xsl:value-of select="ns0:xmlFactura" xml:id="id_1139"/>
                    </ns0:xmlFactura>
                  </xsl:if>
                  <xsl:if test="ns0:tpMoneda" xml:id="id_1140">
                    <ns0:tpMoneda xml:id="id_1141">
                      <xsl:value-of select="ns0:tpMoneda" xml:id="id_1145"/>
                    </ns0:tpMoneda>
                  </xsl:if>
                  <xsl:if test="ns0:montoRetencionIsr" xml:id="id_1146">
                    <ns0:montoRetencionIsr xml:id="id_1147">
                      <xsl:value-of select="ns0:montoRetencionIsr" xml:id="id_1151"/>
                    </ns0:montoRetencionIsr>
                  </xsl:if>
                  <xsl:if test="ns0:montoRetencionIva" xml:id="id_1152">
                    <ns0:montoRetencionIva xml:id="id_1153">
                      <xsl:value-of select="ns0:montoRetencionIva" xml:id="id_1157"/>
                    </ns0:montoRetencionIva>
                  </xsl:if>
                  <xsl:if test="ns0:otrosImpuestos" xml:id="id_1158">
                    <ns0:otrosImpuestos xml:id="id_1159">
                      <xsl:value-of select="ns0:otrosImpuestos" xml:id="id_1163"/>
                    </ns0:otrosImpuestos>
                  </xsl:if>
                  <xsl:if test="ns0:subtotal" xml:id="id_1164">
                    <ns0:subtotal xml:id="id_1165">
                      <xsl:value-of select="ns0:subtotal" xml:id="id_1169"/>
                    </ns0:subtotal>
                  </xsl:if>
                  <xsl:if test="ns0:total" xml:id="id_1170">
                    <ns0:total xml:id="id_1171">
                      <xsl:value-of select="ns0:total" xml:id="id_1175"/>
                    </ns0:total>
                  </xsl:if>
                  <xsl:if test="ns0:tipoImpuesto" xml:id="id_1176">
                    <ns0:tipoImpuesto xml:id="id_1177">
                      <xsl:value-of select="ns0:tipoImpuesto" xml:id="id_1181"/>
                    </ns0:tipoImpuesto>
                  </xsl:if>
                </ns0:Gpa002Importes>
              </xsl:for-each>
            </ns0:importesCollection>
          </xsl:if>
          <xsl:if test="ns0:seguimientos" xml:id="id_1182">
            <ns0:seguimientos xml:id="id_1183">
              <xsl:for-each select="ns0:seguimientos/ns0:Gpa005Seguimiento" xml:id="id_1184">
                <ns0:Gpa005Seguimiento xml:id="id_1185">
                  <ns0:idSeguimiento xml:id="id_1186">
                    <xsl:value-of select="ns0:idSeguimiento" xml:id="id_1187"/>
                  </ns0:idSeguimiento>
                  <xsl:if test="ns0:actividad" xml:id="id_1188">
                    <ns0:actividad xml:id="id_1189">
                      <xsl:value-of select="ns0:actividad" xml:id="id_1193"/>
                    </ns0:actividad>
                  </xsl:if>
                  <xsl:if test="ns0:fhCreacion" xml:id="id_1194">
                    <ns0:fhCreacion xml:id="id_1195">
                      <xsl:value-of select="ns0:fhCreacion" xml:id="id_1199"/>
                    </ns0:fhCreacion>
                  </xsl:if>
                  <xsl:if test="ns0:usuario" xml:id="id_1200">
                    <ns0:usuario xml:id="id_1201">
                      <xsl:value-of select="ns0:usuario" xml:id="id_1205"/>
                    </ns0:usuario>
                  </xsl:if>
                  <xsl:if test="ns0:fhActualizacion" xml:id="id_1206">
                    <ns0:fhActualizacion xml:id="id_1207">
                      <xsl:value-of select="ns0:fhActualizacion" xml:id="id_1211"/>
                    </ns0:fhActualizacion>
                  </xsl:if>
                  <xsl:if test="ns0:nuIteracion" xml:id="id_1212">
                    <ns0:nuIteracion xml:id="id_1213">
                      <xsl:value-of select="ns0:nuIteracion" xml:id="id_1217"/>
                    </ns0:nuIteracion>
                  </xsl:if>
                  <xsl:if test="ns0:idEstado" xml:id="id_1218">
                    <ns0:idEstado xml:id="id_1219">
                      <xsl:value-of select="ns0:idEstado" xml:id="id_1223"/>
                    </ns0:idEstado>
                  </xsl:if>
                  <xsl:if test="ns0:observaciones" xml:id="id_1224">
                    <ns0:observaciones xml:id="id_1225">
                      <xsl:for-each select="ns0:observaciones/ns0:Gpa007Observaciones" xml:id="id_1226">
                        <ns0:Gpa007Observaciones xml:id="id_1227">
                          <ns0:idObservaciones xml:id="id_1228">
                            <xsl:value-of select="ns0:idObservaciones" xml:id="id_1229"/>
                          </ns0:idObservaciones>
                          <xsl:if test="ns0:txComentario" xml:id="id_1230">
                            <ns0:txComentario xml:id="id_1231">
                              <xsl:value-of select="ns0:txComentario" xml:id="id_1235"/>
                            </ns0:txComentario>
                          </xsl:if>
                          <xsl:if test="ns0:idTpObservaciones" xml:id="id_1236">
                            <ns0:idTpObservaciones xml:id="id_1237">
                              <xsl:value-of select="ns0:idTpObservaciones" xml:id="id_1241"/>
                            </ns0:idTpObservaciones>
                          </xsl:if>
                        </ns0:Gpa007Observaciones>
                      </xsl:for-each>
                    </ns0:observaciones>
                  </xsl:if>
                </ns0:Gpa005Seguimiento>
              </xsl:for-each>
            </ns0:seguimientos>
          </xsl:if>
          <xsl:if test="ns0:documentos" xml:id="id_1242">
            <ns0:documentos xml:id="id_1243">
              <xsl:for-each select="ns0:documentos/ns0:Gpa009Documento" xml:id="id_1244">
                <ns0:Gpa009Documento xml:id="id_1245">
                  <ns0:idDocumento xml:id="id_1246">
                    <xsl:value-of select="ns0:idDocumento" xml:id="id_1247"/>
                  </ns0:idDocumento>
                  <xsl:if test="ns0:nombreDocumento" xml:id="id_1248">
                    <ns0:nombreDocumento xml:id="id_1249">
                      <xsl:value-of select="ns0:nombreDocumento" xml:id="id_1253"/>
                    </ns0:nombreDocumento>
                  </xsl:if>
                </ns0:Gpa009Documento>
              </xsl:for-each>
            </ns0:documentos>
          </xsl:if>
          <!--xsl:comment>VA A ENTRAR A SERICIO</xsl:comment-->
          <!--xsl:if test="*:servicio" xml:id="id_1254"-->
            <ns0:servicio xml:id="id_1255">            
              <!--xsl:comment>ENTRO A SERICIO</xsl:comment-->
              <!--xsl:comment>antes de descServicio</xsl:comment-->
              <xsl:if test="*:servicio/*:descServicio" xml:id="id_1259">                
                <ns0:descServicio xml:id="id_1260">
                <!--xsl:comment>despues de descServicio</xsl:comment-->
                  <xsl:value-of select="*:servicio/*:descServicio" xml:id="id_1264"/>
                </ns0:descServicio>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:idTpServicio" xml:id="id_1265">
                <ns0:idTpServicio xml:id="id_1266">
                  <xsl:value-of select="ns0:servicio/ns0:idTpServicio" xml:id="id_1270"/>
                </ns0:idTpServicio>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:centroCosto" xml:id="id_1271">
                <ns0:centroCosto xml:id="id_1272">
                  <xsl:value-of select="ns0:servicio/ns0:centroCosto" xml:id="id_1276"/>
                </ns0:centroCosto>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:idSolicitud" xml:id="id_1277">
                <ns0:idSolicitud xml:id="id_1278">
                  <xsl:value-of select="ns0:servicio/ns0:idSolicitud" xml:id="id_1282"/>
                </ns0:idSolicitud>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:idPrestador" xml:id="id_1283">
                <ns0:idPrestador xml:id="id_1284">
                  <xsl:value-of select="ns0:servicio/ns0:idPrestador" xml:id="id_1288"/>
                </ns0:idPrestador>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:fhRegistro" xml:id="id_1289">
                <ns0:fhRegistro xml:id="id_1290">
                  <xsl:value-of select="ns0:servicio/ns0:fhRegistro" xml:id="id_1294"/>
                </ns0:fhRegistro>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:descOficina" xml:id="id_1295">
                <ns0:descOficina xml:id="id_1296">
                  <xsl:value-of select="ns0:servicio/ns0:descOficina" xml:id="id_1300"/>
                </ns0:descOficina>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:descArea" xml:id="id_1301">
                <ns0:descArea xml:id="id_1302">
                  <xsl:value-of select="ns0:servicio/ns0:descArea" xml:id="id_1306"/>
                </ns0:descArea>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:responsableArea" xml:id="id_1307">
                <ns0:responsableArea xml:id="id_1308">
                  <xsl:value-of select="ns0:servicio/ns0:responsableArea" xml:id="id_1312"/>
                </ns0:responsableArea>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:cveOficina" xml:id="id_1313">
                <ns0:cveOficina xml:id="id_1314">
                  <xsl:value-of select="ns0:servicio/ns0:cveOficina" xml:id="id_1318"/>
                </ns0:cveOficina>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:procesable" xml:id="id_1319">
                <ns0:procesable xml:id="id_1320">
                  <xsl:value-of select="ns0:servicio/ns0:procesable" xml:id="id_1324"/>
                </ns0:procesable>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:tipoPrestador" xml:id="id_1325">
                <ns0:tipoPrestador xml:id="id_1326">
                  <xsl:value-of select="ns0:servicio/ns0:tipoPrestador" xml:id="id_1330"/>
                </ns0:tipoPrestador>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:beneficiario" xml:id="id_1331">
                <ns0:beneficiario xml:id="id_1332">
                  <xsl:value-of select="ns0:servicio/ns0:beneficiario" xml:id="id_1336"/>
                </ns0:beneficiario>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:idFormaPago" xml:id="id_1337">
                <ns0:idFormaPago xml:id="id_1338">
                  <xsl:value-of select="ns0:servicio/ns0:idFormaPago" xml:id="id_1342"/>
                </ns0:idFormaPago>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:idConceptoGasto" xml:id="id_1343">
                <ns0:idConceptoGasto xml:id="id_1344">
                  <xsl:value-of select="ns0:servicio/ns0:idConceptoGasto" xml:id="id_1348"/>
                </ns0:idConceptoGasto>
              </xsl:if>
              <xsl:if test="ns0:servicio/ns0:chequeCertificado" xml:id="id_1349">
                <ns0:chequeCertificado xml:id="id_1350">
                  <xsl:value-of select="ns0:servicio/ns0:chequeCertificado" xml:id="id_1354"/>
                </ns0:chequeCertificado>
              </xsl:if>
              <ns0:viatico xml:id="id_1355">
                <ns0:idViatico xml:id="id_1356">
                  <xsl:value-of select="*:servicio/*:viatico/*:idViatico" xml:id="id_1357"/>
                </ns0:idViatico>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:fhInicioViaje" xml:id="id_1358">
                  <ns0:fhInicioViaje xml:id="id_1359">
                    <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:fhInicioViaje" xml:id="id_1363"/>
                  </ns0:fhInicioViaje>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:fhFinViaje" xml:id="id_1364">
                  <ns0:fhFinViaje xml:id="id_1365">
                    <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:fhFinViaje" xml:id="id_1369"/>
                  </ns0:fhFinViaje>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:justificacion" xml:id="id_1370">
                  <ns0:justificacion xml:id="id_1371">
                    <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:justificacion" xml:id="id_1372"/>
                  </ns0:justificacion>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:loginAutorizador" xml:id="id_1373">
                  <ns0:loginAutorizador xml:id="id_1374">
                    <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:loginAutorizador" xml:id="id_1378"/>
                  </ns0:loginAutorizador>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:nroDiasViaje" xml:id="id_1379">
                  <ns0:nroDiasViaje xml:id="id_1380">
                    <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:nroDiasViaje" xml:id="id_1384"/>
                  </ns0:nroDiasViaje>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:nroKms" xml:id="id_1385">
                  <ns0:nroKms xml:id="id_1386">                    
                    <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:nroKms" xml:id="id_1390"/>
                  </ns0:nroKms>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:valorAnticipo" xml:id="id_1391">
                  <ns0:valorAnticipo xml:id="id_1392">                   
                    <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:valorAnticipo" xml:id="id_1396"/>
                  </ns0:valorAnticipo>
                </xsl:if>
                <!--xsl:comment>ANTES DE ESTADO SERV</xsl:comment-->
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:idEstado" xml:id="id_1397">
                  <ns0:idEstado xml:id="id_1398">
                  <!--xsl:comment>DESPUES DE ESTADO SERV</xsl:comment-->                   
                    <xsl:value-of select="*:servicio/*:viatico/*:idEstado" xml:id="id_1402"/>
                  </ns0:idEstado>
                </xsl:if>
                <xsl:if test="*:servicio/*:viatico/*:ctadeudora" xml:id="id_1403">
                  <ns0:ctadeudora xml:id="id_1404">
                    <ns0:idCedudoras xml:id="id_1408">
                      <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:idCedudoras" xml:id="id_1409"/>
                    </ns0:idCedudoras>
                    <xsl:if test="*:servicio/ns0:viatico/ns0:ctadeudora/ns0:nuCdeudoras" xml:id="id_1410">
                      <ns0:nuCdeudoras xml:id="id_1411">
                        <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:nuCdeudoras" xml:id="id_1412"/>
                      </ns0:nuCdeudoras>
                    </xsl:if>
                    <xsl:if test="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:descDeudoras" xml:id="id_1413">
                      <ns0:descDeudoras xml:id="id_1414">
                        <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:descDeudoras" xml:id="id_1415"/>
                      </ns0:descDeudoras>
                    </xsl:if>
                    <xsl:if test="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:stRegistro" xml:id="id_1416">
                      <ns0:stRegistro xml:id="id_1417">
                        <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:stRegistro" xml:id="id_1418"/>
                      </ns0:stRegistro>
                    </xsl:if>
                    <xsl:if test="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:userLogin" xml:id="id_1419">
                      <ns0:userLogin xml:id="id_1420">
                        
                        <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:ctadeudora/ns0:userLogin" xml:id="id_1424"/>
                      </ns0:userLogin>
                    </xsl:if>
                  </ns0:ctadeudora>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:categorias" xml:id="id_1425">
                  <ns0:categorias xml:id="id_1426">
                    <xsl:for-each select="ns0:servicio/ns0:viatico/ns0:categorias/ns0:Gpa023CatViaticos" xml:id="id_1427">
                      <ns0:Gpa023CatViaticos xml:id="id_1428">
                        <ns0:codigoTarifa xml:id="id_1429">
                          <xsl:value-of select="ns0:codigoTarifa" xml:id="id_1430"/>
                        </ns0:codigoTarifa>
                        <xsl:if test="ns0:valorTarifa" xml:id="id_1431">
                          <ns0:valorTarifa xml:id="id_1432">
                            <xsl:value-of select="ns0:valorTarifa" xml:id="id_1433"/>
                          </ns0:valorTarifa>
                        </xsl:if>
                        <xsl:if test="ns0:valorAnticipo" xml:id="id_1434">
                          <ns0:valorAnticipo xml:id="id_1435">
                            <xsl:value-of select="ns0:valorAnticipo" xml:id="id_1436"/>
                          </ns0:valorAnticipo>
                        </xsl:if>
                      </ns0:Gpa023CatViaticos>
                    </xsl:for-each>
                  </ns0:categorias>
                </xsl:if>
                
                  <ns0:complementos xml:id="id_1438">
                    <!--xsl:comment>Entro a complemento</xsl:comment-->
                    <xsl:for-each select="//*:complementos/*:Gpa022Viaticos" xml:id="id_1439">
                                  <!--xsl:comment>Entro a foreach  <xsl:value-of select="ns0:idViatico"/></xsl:comment-->
                    <xsl:if xml:id="id_783" test="ns0:idEstado = &quot;16&quot;">
                      <ns0:Gpa022Viaticos xml:id="id_1440">
                        <ns0:idViatico xml:id="id_1441">
                          <xsl:value-of select="ns0:idViatico" xml:id="id_1442"/>
                        </ns0:idViatico>
                        <xsl:if test="ns0:fhInicioViaje" xml:id="id_1443">
                          <ns0:fhInicioViaje xml:id="id_1444">
                           
                            <xsl:value-of select="ns0:fhInicioViaje" xml:id="id_1448"/>
                          </ns0:fhInicioViaje>
                        </xsl:if>
                        <xsl:if test="ns0:fhFinViaje" xml:id="id_1449">
                          <ns0:fhFinViaje xml:id="id_1450">
                            
                            <xsl:value-of select="ns0:fhFinViaje" xml:id="id_1454"/>
                          </ns0:fhFinViaje>
                        </xsl:if>
                        <xsl:if test="ns0:justificacion" xml:id="id_1455">
                          <ns0:justificacion xml:id="id_1456">
                            <xsl:value-of select="ns0:justificacion" xml:id="id_1457"/>
                          </ns0:justificacion>
                        </xsl:if>
                        <xsl:if test="ns0:loginAutorizador" xml:id="id_1458">
                          <ns0:loginAutorizador xml:id="id_1459">                           
                            <xsl:value-of select="ns0:loginAutorizador" xml:id="id_1463"/>
                          </ns0:loginAutorizador>
                        </xsl:if>
                        <xsl:if test="ns0:nroDiasViaje" xml:id="id_1464">
                          <ns0:nroDiasViaje xml:id="id_1465">                            
                            <xsl:value-of select="ns0:nroDiasViaje" xml:id="id_1469"/>
                          </ns0:nroDiasViaje>
                        </xsl:if>
                        <xsl:if test="ns0:nroKms" xml:id="id_1470">
                          <ns0:nroKms xml:id="id_1471">                            
                            <xsl:value-of select="ns0:nroKms" xml:id="id_1475"/>
                          </ns0:nroKms>
                        </xsl:if>
                        <xsl:if test="ns0:valorAnticipo" xml:id="id_1476">
                          <ns0:valorAnticipo xml:id="id_1477">
                            <xsl:value-of select="ns0:valorAnticipo" xml:id="id_1481"/>
                          </ns0:valorAnticipo>
                        </xsl:if>
                        <xsl:if test="ns0:idEstado" xml:id="id_1482">
                          <ns0:idEstado xml:id="id_1483">
                            <xsl:value-of select="ns0:idEstado" xml:id="id_1487"/>
                          </ns0:idEstado>
                        </xsl:if>
                        <xsl:if test="ns0:ctadeudora" xml:id="id_1488">
                          <ns0:ctadeudora xml:id="id_1489">
                            <ns0:idCedudoras xml:id="id_1493">
                              <xsl:value-of select="ns0:ctadeudora/ns0:idCedudoras" xml:id="id_1494"/>
                            </ns0:idCedudoras>
                            <xsl:if test="ns0:ctadeudora/ns0:nuCdeudoras" xml:id="id_1495">
                              <ns0:nuCdeudoras xml:id="id_1496">
                                <xsl:value-of select="ns0:ctadeudora/ns0:nuCdeudoras" xml:id="id_1497"/>
                              </ns0:nuCdeudoras>
                            </xsl:if>
                            <xsl:if test="ns0:ctadeudora/ns0:descDeudoras" xml:id="id_1498">
                              <ns0:descDeudoras xml:id="id_1499">
                                <xsl:value-of select="ns0:ctadeudora/ns0:descDeudoras" xml:id="id_1500"/>
                              </ns0:descDeudoras>
                            </xsl:if>
                            <xsl:if test="ns0:ctadeudora/ns0:stRegistro" xml:id="id_1501">
                              <ns0:stRegistro xml:id="id_1502">
                                <xsl:value-of select="ns0:ctadeudora/ns0:stRegistro" xml:id="id_1503"/>
                              </ns0:stRegistro>
                            </xsl:if>
                            <xsl:if test="ns0:ctadeudora/ns0:userLogin" xml:id="id_1504">
                              <ns0:userLogin xml:id="id_1505">
                                <xsl:value-of select="ns0:ctadeudora/ns0:userLogin" xml:id="id_1509"/>
                              </ns0:userLogin>
                            </xsl:if>
                          </ns0:ctadeudora>
                        </xsl:if>
                        <xsl:if test="ns0:categorias" xml:id="id_1510">
                          <ns0:categorias xml:id="id_1511">
                            <xsl:for-each select="ns0:categorias/ns0:Gpa023CatViaticos" xml:id="id_1512">
                              <ns0:Gpa023CatViaticos xml:id="id_1513">
                                <ns0:codigoTarifa xml:id="id_1514">
                                  <xsl:value-of select="ns0:codigoTarifa" xml:id="id_1515"/>
                                </ns0:codigoTarifa>
                                <xsl:if test="ns0:valorTarifa" xml:id="id_1516">
                                  <ns0:valorTarifa xml:id="id_1517">
                                    <xsl:value-of select="ns0:valorTarifa" xml:id="id_1518"/>
                                  </ns0:valorTarifa>
                                </xsl:if>
                                <xsl:if test="ns0:valorAnticipo" xml:id="id_1519">
                                  <ns0:valorAnticipo xml:id="id_1520">
                                    <xsl:value-of select="ns0:valorAnticipo" xml:id="id_1521"/>
                                  </ns0:valorAnticipo>
                                </xsl:if>
                              </ns0:Gpa023CatViaticos>
                            </xsl:for-each>
                          </ns0:categorias>
                        </xsl:if>
                        <xsl:if test="*:oficina" xml:id="id_1522">
                          <ns0:oficina xml:id="id_1523">
                            <ns0:cvOficina xml:id="id_1527">
                              <xsl:value-of select="ns0:oficina/ns0:cvOficina" xml:id="id_1528"/>
                            </ns0:cvOficina>
                            <xsl:if test="ns0:oficina/ns0:descOficina" xml:id="id_1529">
                              <ns0:descOficina xml:id="id_1530">
                                <xsl:value-of select="ns0:oficina/ns0:descOficina" xml:id="id_1534"/>
                              </ns0:descOficina>
                            </xsl:if>
                            <xsl:if test="ns0:oficina/ns0:stRegistro" xml:id="id_1535">
                              <ns0:stRegistro xml:id="id_1536">
                                <xsl:value-of select="ns0:oficina/ns0:stRegistro" xml:id="id_1540"/>
                              </ns0:stRegistro>
                            </xsl:if>
                          </ns0:oficina>
                        </xsl:if>
                      </ns0:Gpa022Viaticos>
                      </xsl:if>
                    </xsl:for-each>
                  </ns0:complementos>
               
                <xsl:if test="ns0:servicio/ns0:viatico/ns0:oficina" xml:id="id_1541">
                  <ns0:oficina xml:id="id_1542">
                    <ns0:cvOficina xml:id="id_1546">
                      <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:oficina/ns0:cvOficina" xml:id="id_1547"/>
                    </ns0:cvOficina>
                    <xsl:if test="ns0:servicio/ns0:viatico/ns0:oficina/ns0:descOficina" xml:id="id_1548">
                      <ns0:descOficina xml:id="id_1549">
                        <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:oficina/ns0:descOficina" xml:id="id_1553"/>
                      </ns0:descOficina>
                    </xsl:if>
                    <xsl:if test="ns0:servicio/ns0:viatico/ns0:oficina/ns0:stRegistro" xml:id="id_1554">
                      <ns0:stRegistro xml:id="id_1555">
                        <xsl:value-of select="ns0:servicio/ns0:viatico/ns0:oficina/ns0:stRegistro" xml:id="id_1559"/>
                      </ns0:stRegistro>
                    </xsl:if>
                  </ns0:oficina>
                </xsl:if>
              </ns0:viatico>
            </ns0:servicio>
          <!--/xsl:if-->
          <xsl:if test="ns0:oficina" xml:id="id_1560">
            <ns0:oficina xml:id="id_1561">
              <ns0:cvOficina xml:id="id_1565">
                <xsl:value-of select="ns0:oficina/ns0:cvOficina" xml:id="id_1566"/>
              </ns0:cvOficina>
              <xsl:if test="ns0:oficina/ns0:descOficina" xml:id="id_1567">
                <ns0:descOficina xml:id="id_1568">
                  <xsl:value-of select="ns0:oficina/ns0:descOficina" xml:id="id_1572"/>
                </ns0:descOficina>
              </xsl:if>
              <xsl:if test="ns0:oficina/ns0:stRegistro" xml:id="id_1573">
                <ns0:stRegistro xml:id="id_1574">
                  <xsl:value-of select="ns0:oficina/ns0:stRegistro" xml:id="id_1578"/>
                </ns0:stRegistro>
              </xsl:if>
            </ns0:oficina>
          </xsl:if>
        </ns0:Gpa001Solicitud>
      </xsl:for-each>
    </ns0:Gpa001SolicitudCollection>
  </xsl:template>
</xsl:stylesheet>