<?binding.jca CabeceraPadronDBAdapter_db.jca?><wsdl:definitions name="CabeceraPadronDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/CabeceraPadronDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CabeceraPadronDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/CabeceraPadronDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <plt:partnerLinkType name="CabeceraPadronDBAdapter_plt">
    <plt:role name="CabeceraPadronDBAdapter_role">
      <plt:portType name="tns:CabeceraPadronDBAdapter_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CabeceraPadronDBAdapter" schemaLocation="../Schemas/DBBeneficiariosCabeceraTiposXSD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="CabeceraPadronDBAdapterInput_msg">
    <wsdl:part name="CabeceraPadronDBAdapterInput_msg" element="db:CabeceraPadronDBAdapterInput"/>
  </wsdl:message>
  <wsdl:message name="CabeceraPadronDBAdapterOutputCollection_msg">
    <wsdl:part name="CabeceraPadronDBAdapterOutputCollection" element="db:CabeceraPadronDBAdapterOutputCollection"/>
  </wsdl:message>
  <wsdl:portType name="CabeceraPadronDBAdapter_ptt">
    <wsdl:operation name="CabeceraPadronDBAdapter">
      <wsdl:input message="tns:CabeceraPadronDBAdapterInput_msg"/>
      <wsdl:output message="tns:CabeceraPadronDBAdapterOutputCollection_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>