<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/CabeceraPadronDBAdapter" name="CabeceraPadronDBAdapter-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/CabeceraPadronDBAdapter" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/CabeceraPadronDBAdapter" location="DBCabeceraBeneficiarioDbWSDL.wsdl"/>
  <binding name="CabeceraPadronDBAdapter_ptt-binding" type="tns:CabeceraPadronDBAdapter_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="CabeceraPadronDBAdapter">
      <soap:operation soapAction="CabeceraPadronDBAdapter"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CabeceraPadronDBAdapter-service">
    <port name="CabeceraPadronDBAdapter-port" binding="tns:CabeceraPadronDBAdapter_ptt-binding">
      <soap:address location="jca://eis/DB/PeopleSoftAdapter"/>
    </port>
  </service>
</definitions>