<?binding.jca TotalesPadronDBAdapter_db.jca?><wsdl:definitions name="TotalesPadronDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/TotalesPadronDBAdapter" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/TotalesPadronDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/TotalesPadronDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <plt:partnerLinkType name="TotalesPadronDBAdapter_plt">
    <plt:role name="TotalesPadronDBAdapter_role">
      <plt:portType name="tns:TotalesPadronDBAdapter_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TotalesPadronDBAdapter" schemaLocation="../Schemas/DBBeneficiariosTotalesElementosXSD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="TotalesPadronDBAdapterInput_msg">
    <wsdl:part name="TotalesPadronDBAdapterInput_msg" element="db:TotalesPadronDBAdapterInput"/>
  </wsdl:message>
  <wsdl:message name="TotalesPadronDBAdapterOutputCollection_msg">
    <wsdl:part name="TotalesPadronDBAdapterOutputCollection" element="db:TotalesPadronDBAdapterOutputCollection"/>
  </wsdl:message>
  <wsdl:portType name="TotalesPadronDBAdapter_ptt">
    <wsdl:operation name="TotalesPadronDBAdapter">
      <wsdl:input message="tns:TotalesPadronDBAdapterInput_msg"/>
      <wsdl:output message="tns:TotalesPadronDBAdapterOutputCollection_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>