<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo" xmlns:ve="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPAvaluoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="obtenerAvaluoAuto" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Avaluo"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SAPCatalogoAutosWSDL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ZlmfmConsultaAutm" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE MAY 23 17:23:41 EDT 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:ZlmfmConsultaAutm>
         <IdComplemento>
            <xsl:for-each select="/ns0:obtenerAvaluoAuto/ve:complementos/ve:complemento">
               <item>
                  <Id>
                     <xsl:value-of select="ve:idComplemento"/>
                  </Id>
                  <Descripcion>
                     <xsl:value-of select="ve:descripcion"/>
                  </Descripcion>
               </item>
            </xsl:for-each>
         </IdComplemento>
         <IdKilometraje>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:kilometraje/ve:idKilometraje"/>
         </IdKilometraje>
         <IdMarca>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:marca/ve:idMarca"/>
         </IdMarca>
         <IdModelo>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:modelo/ve:idModelo"/>
         </IdModelo>
         <IdSubmarca>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:submarca/ve:idSubMarca"/>
         </IdSubmarca>
         <IdVersion>
            <xsl:value-of select="/ns0:obtenerAvaluoAuto/ve:version/ve:idVersion"/>
         </IdVersion>
      </tns:ZlmfmConsultaAutm>
   </xsl:template>
</xsl:stylesheet>