<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi xsl soap12 soapenc nmp soap mime xsd http wsdl client plnk bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:nmp="http://xmlns.montepiedad.com.mx/nmp/cenmp" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:client="http://xmlns.oracle.com/nmpApp/WSCancelarInscripcion/CancelarInscripcionBPELProcess" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:bpmn="http://schemas.oracle.com/bpm/xpath" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/NmpProxy.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CancelarInscripcionRequest" namespace="http://xmlns.montepiedad.com.mx/nmp/cenmp"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../wsdl/WSCancelarInscripcion.wsdl"/>
        <oracle-xsl-mapper:rootElement name="process" namespace="http://xmlns.oracle.com/nmpApp/WSCancelarInscripcion/CancelarInscripcionBPELProcess"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE JAN 05 23:43:56 CST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <client:process>
      <client:Usuario>
        <xsl:value-of select="/nmp:CancelarInscripcionRequest/nmp:Usuario"/>
      </client:Usuario>
      <client:idCurso>
        <xsl:value-of select="/nmp:CancelarInscripcionRequest/nmp:idCurso"/>
      </client:idCurso>
      <client:idGrupo>
        <xsl:value-of select="/nmp:CancelarInscripcionRequest/nmp:idGrupo"/>
      </client:idGrupo>
      
         <client:idCentro>
        <xsl:value-of select="/nmp:CancelarInscripcionRequest/nmp:idCentro"/>
      </client:idCentro>
      
         <client:nombreCentro>
        <xsl:value-of select="/nmp:CancelarInscripcionRequest/nmp:nombreCentro"/>
      </client:nombreCentro>
      
      
    </client:process>
    
  
  </xsl:template>
</xsl:stylesheet>