<wsdl:definitions name="TipoCambiarioEndpointService" targetNamespace="http://ws.api.cambiario.sivad.ms.nmp.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.api.cambiario.sivad.ms.nmp.com.mx/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://nmp.com.mx/ms/sivad/cambiario/ws/diamantes/">
<wsdl:import location="TipoCambiarioBlueMixWSDL.wsdl" namespace="http://nmp.com.mx/ms/sivad/cambiario/ws/diamantes/"/>
<wsdl:binding name="TipoCambiarioEndpointServiceSoapBinding" type="ns1:TipoCambiarioService">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="actualizar">
<soap:operation soapAction="http://nmp.com.mx/ms/cambiario/ws/diamantes/actualizar" style="document"/>
<wsdl:input name="actualizar">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="actualizarResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="TipoCambiarioEndpointService">
<wsdl:port binding="tns:TipoCambiarioEndpointServiceSoapBinding" name="TipoCambiarioEndpointPort">
<soap:address location="https://dev1775-sivad-tipo-cambiario.mybluemix.net/soap-api/TipoCambiario"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>