<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPServiciosPrestadorDB" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/SPServiciosPrestadorDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/comunes/objetosComunes/v1/">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/SPServiciosPrestadorDB.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPServiciosPrestadorDB" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../WSDLs/ObtenerServiciosPorPrestadorBPEL.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="serviciosPrestadorResponse" namespace="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED DEC 07 20:06:40 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <tns:serviciosPrestadorResponse xml:id="id_12">
         <xsl:for-each xml:id="id_13" select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row">
            <tns:servicioPrestadorOEN xml:id="id_14">
               <tns:idProyecto xml:id="id_18">
                  <xsl:value-of select="ns0:ID_PROYECTO" xml:id="id_19"/>
               </tns:idProyecto>
               <tns:nombreProyecto xml:id="id_43">
                  <xsl:value-of select="ns0:NOMBRE_PROYECTO" xml:id="id_44"/>
               </tns:nombreProyecto>
               <tns:descProyecto xml:id="id_20">
                  <xsl:value-of select="ns0:DESC_PROYECTO" xml:id="id_21"/>
               </tns:descProyecto>
               <tns:estatus xml:id="id_22">
                  <xsl:value-of select="ns0:ST_PROYECTO" xml:id="id_23"/>
               </tns:estatus>
               <tns:presupuestoAprob xml:id="id_24">
                  <xsl:value-of select="ns0:PRESUPUESTO_APROBADO" xml:id="id_25"/>
               </tns:presupuestoAprob>
               <tns:parcialidades xml:id="id_26">
                  <xsl:value-of select="ns0:PARCIALIDADES" xml:id="id_27"/>
               </tns:parcialidades>
               <tns:condicionPago xml:id="id_28">
                  <xsl:value-of select="ns0:ID_CONDICIONES_PAGO" xml:id="id_29"/>
               </tns:condicionPago>
               <tns:idsolicitud xml:id="id_30">
                  <xsl:value-of select="ns0:ID_SOLICITUD" xml:id="id_31"/>
               </tns:idsolicitud>
               <tns:idPrestador xml:id="id_32">
                  <xsl:value-of select="ns0:ID_PRESTADOR" xml:id="id_33"/>
               </tns:idPrestador>
               <tns:centroCosto xml:id="id_34">
                  <xsl:value-of select="ns0:CENTRO_COSTO" xml:id="id_35"/>
               </tns:centroCosto>
               <tns:claveOficina xml:id="id_45">
                  <xsl:value-of select="ns0:CVE_OFICINA" xml:id="id_46"/>
               </tns:claveOficina>
               <tns:descOficina xml:id="id_47">
                  <xsl:value-of select="ns0:DESC_OFICINA" xml:id="id_48"/>
               </tns:descOficina>
               <tns:descArea xml:id="id_49">
                  <xsl:value-of select="ns0:DESC_AREA" xml:id="id_50"/>
               </tns:descArea>
               <tns:responsableArea xml:id="id_51">
                  <xsl:value-of select="ns0:RESPONSABLE_AREA" xml:id="id_52"/>
               </tns:responsableArea>
               <tns:numEmpleado xml:id="id_36">
                  <xsl:value-of select="ns0:NU_EMPLEADO" xml:id="id_37"/>
               </tns:numEmpleado>
            </tns:servicioPrestadorOEN>
         </xsl:for-each>
         <tns:OperationResponse xml:id="id_38">
            <xsl:choose xml:id="id_56">
               <xsl:when xml:id="id_57" test="string-length (/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PROYECTO ) > 0">
                  <ns2:codigoRespuesta xml:id="id_39">
                     <xsl:value-of select="/ns0:OutputParameters/ns0:P_OUTCVE" xml:id="id_40"/>
                  </ns2:codigoRespuesta>
               </xsl:when>
            <xsl:otherwise>
            <ns2:codigoRespuesta xml:id="id_39">
                     <xsl:value-of xml:id="id_58" select="1"/>
                  </ns2:codigoRespuesta>
                  </xsl:otherwise>
            </xsl:choose>
            <xsl:choose xml:id="id_54">
               <xsl:when xml:id="id_55" test="string-length (/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PROYECTO ) > 0">
                  <ns2:descripcionRespuesta xml:id="id_41">
                     <xsl:value-of select="string ('EJECUCION EXISTOSA' )" xml:id="id_42"/>
                  </ns2:descripcionRespuesta>
               </xsl:when>
               <xsl:otherwise>
                <ns2:descripcionRespuesta xml:id="id_41">NO SE ENCONTRARON SERVICIOS</ns2:descripcionRespuesta>
               </xsl:otherwise>
            </xsl:choose>
            <ns2:fecha xml:id="id_59"/>
         </tns:OperationResponse>
      </tns:serviciosPrestadorResponse>
   </xsl:template>
</xsl:stylesheet>