<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerServPrestador" xmlns:tns="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/SPObtenerServPrestador" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/comunes/objetosComunes/v1/">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../WSDLs/SPObtenerServPrestador.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerServPrestador" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../WSDLs/ObtenerServiciosPorPrestadorBPEL.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="serviciosPrestadorResponse" namespace="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON DEC 26 15:20:36 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <tns:serviciosPrestadorResponse xml:id="id_12">
         <xsl:for-each xml:id="id_13" select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row">
            <tns:servicioPrestadorOEN xml:id="id_14">
               <tns:idProyecto xml:id="id_15">
                  <xsl:value-of select="ns0:ID_PROYECTO" xml:id="id_16"/>
               </tns:idProyecto>
               <tns:nombreProyecto xml:id="id_17">
                  <xsl:value-of select="ns0:NOMBRE_PROYECTO" xml:id="id_18"/>
               </tns:nombreProyecto>
               <tns:descProyecto xml:id="id_19">
                  <xsl:value-of select="ns0:DESC_PROYECTO" xml:id="id_20"/>
               </tns:descProyecto>
               <tns:estatus xml:id="id_60">
                  <xsl:value-of select="ns0:ST_PROYECTO" xml:id="id_64"/>
               </tns:estatus>
               <tns:presupuestoAprob xml:id="id_23">
                  <xsl:value-of select="ns0:PRESUPUESTO_APROBADO" xml:id="id_24"/>
               </tns:presupuestoAprob>
               <tns:totalParcialidades xml:id="id_52">
                  <xsl:value-of select="ns0:PARCIALIDADES" xml:id="id_53"/>
               </tns:totalParcialidades>
               <tns:numeroParcialidad xml:id="id_54">
                  <xsl:value-of xml:id="id_55" select="oraext:query-database (concat (&quot;SELECT MAX(NU_PARCIALIDAD) AS NU_PARCIALIDAD FROM  GPA014_SEGU_PROYECTO WHERE ID_PROYECTO =&quot;, ns0:ID_PROYECTO ), false ( ), false ( ), &quot;jdbc/GPAConnDB&quot; )"/>
               </tns:numeroParcialidad>
               <tns:condicionPago xml:id="id_62">
                  <xsl:value-of select="ns0:ID_CONDICIONES_PAGO" xml:id="id_63"/>
               </tns:condicionPago>
               <tns:idsolicitud xml:id="id_29">
                  <xsl:value-of select="ns0:ID_SOLICITUD" xml:id="id_30"/>
               </tns:idsolicitud>
               <tns:idPrestador xml:id="id_31">
                  <xsl:value-of select="ns0:ID_PRESTADOR" xml:id="id_32"/>
               </tns:idPrestador>
               <tns:centroCosto xml:id="id_33">
                  <xsl:value-of select="ns0:CENTRO_COSTO" xml:id="id_34"/>
               </tns:centroCosto>
               <tns:claveOficina xml:id="id_35">
                  <xsl:value-of select="ns0:CVE_OFICINA" xml:id="id_36"/>
               </tns:claveOficina>
               <tns:descOficina xml:id="id_39">
                  <xsl:value-of select="ns0:DESC_OFICINA" xml:id="id_40"/>
               </tns:descOficina>
               <tns:descArea xml:id="id_41">
                  <xsl:value-of select="ns0:DESC_AREA" xml:id="id_42"/>
               </tns:descArea>
               <tns:responsableArea xml:id="id_43">
                  <xsl:value-of select="ns0:RESPONSABLE_AREA" xml:id="id_44"/>
               </tns:responsableArea>
               <tns:numEmpleado xml:id="id_37">
                  <xsl:value-of select="ns0:NU_EMPLEADO" xml:id="id_38"/>
               </tns:numEmpleado>
               <tns:tipoMoneda xml:id="id_77">
                  <xsl:value-of select="ns0:TP_MONEDA" xml:id="id_78"/>
               </tns:tipoMoneda>
            </tns:servicioPrestadorOEN>
         </xsl:for-each>
         <tns:OperationResponse xml:id="id_45">
            <xsl:choose xml:id="id_72">
               <xsl:when xml:id="id_73" test="/ns0:OutputParameters/ns0:P_OUTCVE = 2">
                  <ns2:codigoRespuesta xml:id="id_74">0</ns2:codigoRespuesta>
               </xsl:when>
               <xsl:when xml:id="id_75" test="/ns0:OutputParameters/ns0:P_OUTCVE = 0">
                  <ns2:codigoRespuesta xml:id="id_76">0</ns2:codigoRespuesta>
               </xsl:when>
            </xsl:choose>
            <xsl:if xml:id="id_67" test="/ns0:OutputParameters/ns0:P_OUTCVE = 2">
               <ns2:descripcionRespuesta xml:id="id_48">NO SE ENCONTRARON DATOS</ns2:descripcionRespuesta>
            </xsl:if>
            <xsl:if xml:id="id_70" test="/ns0:OutputParameters/ns0:P_OUTCVE = 0">
               <ns2:descripcionRespuesta xml:id="id_71">EJECUCION EXITOSA</ns2:descripcionRespuesta>
            </xsl:if>
            <ns2:tiempoRespuesta xml:id="id_50"/>
            <ns2:fecha xml:id="id_56">
               <xsl:value-of select="xp20:current-dateTime ( )" xml:id="id_57"/>
            </ns2:fecha>
         </tns:OperationResponse>
      </tns:serviciosPrestadorResponse>
   </xsl:template>
</xsl:stylesheet>