<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://qualitas.com.mx/Comun/CentroCostos/validarCentroCostos/v1/" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://qualitas.com.mx/ValidarCentroDeCostosApp/ValidarCentrosDeCostosPrj/ValidarCentroDeCostosBPEL" xmlns:ns1="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/GPADomain/ValidarCentrosDeCostosPrj!1.0/WSDLs/ValidarCentroDeCostosBPEL.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="ValidarCentroCostosResponse" namespace="http://qualitas.com.mx/Comun/CentroCostos/validarCentroCostos/v1/" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../WSDLs/ObtenerServiciosPorPrestadorBPEL.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="serviciosPrestadorResponse" namespace="http://xmlns.oracle.com/ObtenerServicioPorPrestadorApp/ObtenerServicioPorPretstadorPrj/ObtenerServiciosPorPrestadorBPEL" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON DEC 19 16:05:56 CST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/" xml:id="id_11">
      <tns:serviciosPrestadorResponse xml:id="id_12">
         <xsl:for-each xml:id="id_13" select="/ns0:ValidarCentroCostosResponse">
            <tns:servicioPrestadorOEN xml:id="id_14">
               <xsl:if test="ns0:centroCostos" xml:id="id_21">
                  <tns:centroCosto xml:id="id_22">
                     <xsl:value-of select="ns0:centroCostos" xml:id="id_23"/>
                  </tns:centroCosto>
               </xsl:if>
               <xsl:if test="ns0:claveOficina" xml:id="id_24">
                  <tns:claveOficina xml:id="id_25">
                     <xsl:value-of select="ns0:claveOficina" xml:id="id_26"/>
                  </tns:claveOficina>
               </xsl:if>
               <xsl:if test="ns0:descOficina" xml:id="id_15">
                  <tns:descOficina xml:id="id_16">
                     <xsl:value-of select="ns0:descOficina" xml:id="id_17"/>
                  </tns:descOficina>
               </xsl:if>
               <xsl:if test="ns0:descArea" xml:id="id_18">
                  <tns:descArea xml:id="id_19">
                     <xsl:value-of select="ns0:descArea" xml:id="id_20"/>
                  </tns:descArea>
               </xsl:if>
               <xsl:if test="ns0:responsableArea" xml:id="id_27">
                  <tns:responsableArea xml:id="id_28">
                     <xsl:value-of select="ns0:responsableArea" xml:id="id_29"/>
                  </tns:responsableArea>
               </xsl:if>
            </tns:servicioPrestadorOEN>
         </xsl:for-each>
      </tns:serviciosPrestadorResponse>
   </xsl:template>
</xsl:stylesheet>