<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ProrrateoSvc" targetNamespace="http://ws.gpa.qualitas.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:WL5G3N2="http://ws.gpa.qualitas.mx/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="ParsingDocService">
      <plnk:role name="ProrrateoSvc" portType="WL5G3N2:ProrrateoSvc"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://ws.gpa.qualitas.mx/" location="ProrrateoParsingPxy_2.wsdl"/>
</wsdl:definitions>
