<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="selectNumOrdenDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GestionOrdenPagoApp/OrdenesPagoPrj/selectNumOrdenDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GestionOrdenPagoApp/OrdenesPagoPrj/selectNumOrdenDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/selectNumOrdenDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plt:partnerLinkType name="selectNumOrdenDB_plt">
      <plt:role name="selectNumOrdenDB_role">
         <plt:portType name="tns:selectNumOrdenDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <plt:partnerLinkType name="selectNumOrdenDB_plt">
      <plt:role name="selectNumOrdenDB_role">
         <plt:portType name="tns:selectNumOrdenDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selectNumOrdenDB" schemaLocation="../Schemas/selectNumOrdenDB.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selectNumOrdenDB" schemaLocation="../Schemas/selectNumOrdenDB.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="selectNumOrdenDBInput_msg">
      <wsdl:part name="selectNumOrdenDBInput_msg" element="db:selectNumOrdenDBInput"/>
   </wsdl:message>
   <wsdl:message name="selectNumOrdenDBOutputCollection_msg">
      <wsdl:part name="selectNumOrdenDBOutputCollection" element="db:selectNumOrdenDBOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="selectNumOrdenDB_ptt">
      <wsdl:operation name="selectNumOrdenDB">
         <wsdl:input message="tns:selectNumOrdenDBInput_msg"/>
         <wsdl:output message="tns:selectNumOrdenDBOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
