<wsdl:definitions name="SetOfertas" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://tempuri.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import schemaLocation="../Schemas/CRMCreaOfertasElementosXSD.xsd" namespace="http://tempuri.org/"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ICreaOfertas_Guarda_InputMessage">
    <wsdl:part name="parameters" element="tns:Guarda"/>
  </wsdl:message>
  <wsdl:message name="ICreaOfertas_Guarda_OutputMessage">
    <wsdl:part name="parameters" element="tns:GuardaResponse"/>
  </wsdl:message>
  <wsdl:portType name="ICreaOfertas">
    <wsdl:operation name="Guarda">
      <wsdl:input wsaw:Action="http://tempuri.org/ICreaOfertas/Guarda" message="tns:ICreaOfertas_Guarda_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/ICreaOfertas/GuardaResponse" message="tns:ICreaOfertas_Guarda_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_ICreaOfertas" type="tns:ICreaOfertas">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Guarda">
      <soap:operation soapAction="http://tempuri.org/ICreaOfertas/Guarda" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SetOfertas">
    <wsdl:port name="BasicHttpBinding_ICreaOfertas" binding="tns:BasicHttpBinding_ICreaOfertas">
      <soap:address location="http://10.30.3.49/Ofertas/CreaOfertas.svc"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>