<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BusApplication/GPA/CtaContableDB" name="CtaContableDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CtaContableDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BusApplication/GPA/CtaContableDB"/>
    <wsdl:binding name="CtaContableDB_ptt-binding" type="ctac:CtaContableDB_ptt" xmlns:ctac="http://xmlns.oracle.com/pcbpel/adapter/db/BusApplication/GPA/CtaContableDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CtaContableDB">
            <soap:operation soapAction="CtaContableDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>