<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi ns0 xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction ns0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cot="http://servicios.montedepiedad.com.mx/NMP/Schema/Cotizador" xmlns:veh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPVehiculo" xmlns:NMPDoc="http://servicios.montedepiedad.com.mx/NMP/Schema/OpenTextSvc" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns1="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage" xmlns:NMPPers="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPersona">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPVehiculosSinResguardoXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="generarSolicitudRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculosSinResguardo"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/NMPFlujoVehiculosSinResguardoSvcXSD.xsd"/>
            <oracle-xsl-mapper:rootElement name="iniciarFlujoVehiculoSinResguardoRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/VehiculoSinResguardo/Flujo"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE MAR 07 14:17:59 EST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="newFolio"/>
   <xsl:template match="/">
      <tns:iniciarFlujoVehiculoSinResguardoRequest>
         <tns:folio>
            <xsl:value-of select="$newFolio"/>
         </tns:folio>
         <tns:estadoSolicitud>1</tns:estadoSolicitud>
         <tns:estadoFlujoBpm>1</tns:estadoFlujoBpm>
         <tns:cliente>
            <tns:idCliente>
               <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cliente/tns:idCliente"/>
            </tns:idCliente>
            <tns:numeroCredencial>
               <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cliente/tns:numeroCredencial"/>
            </tns:numeroCredencial>
         </tns:cliente>
         <tns:vehiculo>
            <veh:tipoVehiculo>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:tipoVehiculo"/>
            </veh:tipoVehiculo>
            <veh:vin>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:vin"/>
            </veh:vin>
            <veh:serieMotor>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:serieMotor"/>
            </veh:serieMotor>
            <veh:placas>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:placas"/>
            </veh:placas>
            <veh:marca>
               <veh:idMarca>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:idMarca"/>
               </veh:idMarca>
               <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:descripcion">
                  <veh:descripcion>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:marca/veh:descripcion"/>
                  </veh:descripcion>
               </xsl:if>
            </veh:marca>
            <veh:submarca>
               <veh:idSubMarca>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:idSubMarca"/>
               </veh:idSubMarca>
               <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:descripcion">
                  <veh:descripcion>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:submarca/veh:descripcion"/>
                  </veh:descripcion>
               </xsl:if>
            </veh:submarca>
            <veh:modelo>
               <veh:idModelo>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:idModelo"/>
               </veh:idModelo>
               <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:descripcion">
                  <veh:descripcion>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:modelo/veh:descripcion"/>
                  </veh:descripcion>
               </xsl:if>
            </veh:modelo>
            <veh:version>
               <veh:idVersion>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:idVersion"/>
               </veh:idVersion>
               <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:descripcion">
                  <veh:descripcion>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:version/veh:descripcion"/>
                  </veh:descripcion>
               </xsl:if>
            </veh:version>
            <veh:kilometraje>
               <veh:idKilometraje>
                  <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje/@xsi:nil">
                     <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje/@xsi:nil"/>
                     </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:idKilometraje"/>
               </veh:idKilometraje>
               <xsl:if test="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:descripcion">
                  <veh:descripcion>
                     <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:kilometraje/veh:descripcion"/>
                  </veh:descripcion>
               </xsl:if>
            </veh:kilometraje>
            <veh:complementos>
               <xsl:for-each select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:complementos/veh:complemento">
                  <veh:complemento>
                     <xsl:if test="@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <veh:idComplemento>
                        <xsl:if test="veh:idComplemento/@xsi:nil">
                           <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                              <xsl:value-of select="veh:idComplemento/@xsi:nil"/>
                           </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="veh:idComplemento"/>
                     </veh:idComplemento>
                     <xsl:if test="veh:descripcion">
                        <veh:descripcion>
                           <xsl:value-of select="veh:descripcion"/>
                        </veh:descripcion>
                     </xsl:if>
                  </veh:complemento>
               </xsl:for-each>
            </veh:complementos>
            <veh:color>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:color"/>
            </veh:color>
            <veh:serieChasis>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:serieChasis"/>
            </veh:serieChasis>
            <veh:numeroTarjetaCirculacion>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:numeroTarjetaCirculacion"/>
            </veh:numeroTarjetaCirculacion>
            <veh:numeroFactura>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:numeroFactura"/>
            </veh:numeroFactura>
            <veh:rfcEmisor>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:rfcEmisor"/>
            </veh:rfcEmisor>
            <veh:agenciaOrigen>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:agenciaOrigen"/>
            </veh:agenciaOrigen>
            <veh:comentarios>
               <xsl:value-of select="/ns0:generarSolicitudRequest/ns0:vehiculo/veh:comentarios"/>
            </veh:comentarios>
         </tns:vehiculo>
         <tns:cotizacion>
            <cot:montoAvaluo>
               <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoAvaluo"/>
            </cot:montoAvaluo>
            <cot:montoMaximoPrestamo>
               <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoMaximoPrestamo"/>
            </cot:montoMaximoPrestamo>
            <cot:montoPrestamoSolicitado>
               <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoPrestamoSolicitado"/>
            </cot:montoPrestamoSolicitado>
            <cot:montoCastigo>
               <xsl:value-of select="/ns0:generarSolicitudRequest/tns:cotizacion/cot:montoCastigo"/>
            </cot:montoCastigo>
         </tns:cotizacion>
      </tns:iniciarFlujoVehiculoSinResguardoRequest>
   </xsl:template>
</xsl:stylesheet>