<xsl:stylesheet version="1.0" exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Schema/GestionMovil" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:sap-com:document:sap:soap:functions:mc-style" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:n1="urn:sap-com:document:sap:rfc:functions" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:CbzE="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/CobranzaConsultas" xmlns:CbzT="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/CobranzaConsultas">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SAPZlmWsCobranzaClienteWSDL.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ZlmRfcCobranzaClienteResponse" namespace="urn:sap-com:document:sap:soap:functions:mc-style"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPSvcCobranzaConsultasElementosXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="consultarCobranzaClienteResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Elementos/CobranzaConsultas"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN DEC 06 20:02:26 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <CbzE:consultarCobranzaClienteResponse>
      <xsl:for-each select="/ns0:ZlmRfcCobranzaClienteResponse/CobranzaCliente/item">
        <CbzT:CobranzaCliente>
          <CbzT:nombreCliente>
            <xsl:value-of select="NombreCliente"/>
          </CbzT:nombreCliente>
          <CbzT:idCliente>
            <xsl:value-of select="Cliente"/>
          </CbzT:idCliente>
          <CbzT:contrato>
            <xsl:value-of select="Contrato"/>
          </CbzT:contrato>
          <CbzT:montoExigible>
            <xsl:value-of select="MontoExigible"/>
          </CbzT:montoExigible>
          <CbzT:diasAtraso>
            <xsl:value-of select="DiasAtraso"/>
          </CbzT:diasAtraso>
        </CbzT:CobranzaCliente>
      </xsl:for-each>
    </CbzE:consultarCobranzaClienteResponse>
  </xsl:template>
</xsl:stylesheet>