<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns1="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:client="http://xmlns.oracle.com/SOA_INT/ordenPagoProrrateoBPEL/OrdenPagoProrrateoBPEL" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OrdenPagoProrrateoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ordenPagProrrateoRequest" namespace="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/GPADomain/GestionOrdenPago!1.0/WSDLs/GestionOrdenPagoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="guardarOrdenPagoRequest" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/"/>
            <oracle-xsl-mapper:param name="InvGuardarOrd_InputVariable.guardarArchivoReq"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/GPADomain/GestionOrdenPago!1.0/WSDLs/GestionOrdenPagoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="guardarOrdenPagoRequest" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [THU JAN 19 01:17:10 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InvGuardarOrd_InputVariable.guardarArchivoReq"/>
   <xsl:template match="/">
      <ns1:guardarOrdenPagoRequest>
         <ns1:Input>
            <ns1:id_solicitud>
               <xsl:value-of select="$InvGuardarOrd_InputVariable.guardarArchivoReq/ns1:guardarOrdenPagoRequest/ns1:Input/ns1:id_solicitud"/>
            </ns1:id_solicitud>
         </ns1:Input>
      </ns1:guardarOrdenPagoRequest>
   </xsl:template>
</xsl:stylesheet>