<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="GenerarSolicitudBPEL" targetNamespace="http://xmlns.oracle.com/GenerarSolicitudApp/GenerarSolicitudPrj/GenerarSolicitudBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/GenerarSolicitudApp/GenerarSolicitudPrj/GenerarSolicitudBPEL" xmlns:ns1="http://qualitas.com.mx/Solicitud/GenerarSolicitud/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Solicitud/GenerarSolicitud/v1/" schemaLocation="../Schemas/generarSolicitud.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="GenerarSolicitudBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:GenerarSolicitudRequest"/>
   </wsdl:message>
   <wsdl:message name="GenerarSolicitudBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:GenerarSolicitudResponse"/>
   </wsdl:message>
   <wsdl:portType name="GenerarSolicitudBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:GenerarSolicitudBPELRequestMessage"/>
         <wsdl:output message="client:GenerarSolicitudBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="GenerarSolicitudBPEL">
      <plnk:role name="GenerarSolicitudBPELProvider" portType="client:GenerarSolicitudBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
