<wsdl:definitions name="CancelarInscripcionBPELProcess" targetNamespace="http://xmlns.oracle.com/nmpApp/WSCancelarInscripcion/CancelarInscripcionBPELProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/nmpApp/WSCancelarInscripcion/CancelarInscripcionBPELProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://nmpsoaserver:8001/soa-infra/services/cenmp/WSCancelarInscripcion!1.0/CancelarInscripcionBPELProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="CancelarInscripcionBPELProcess">
        <plnk:role name="CancelarInscripcionBPELProcessProvider" portType="client:CancelarInscripcionBPELProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/nmpApp/WSCancelarInscripcion/CancelarInscripcionBPELProcess" schemaLocation="../xsd/WSCancelarInscripcion.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CancelarInscripcionBPELProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="CancelarInscripcionBPELProcessResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="CancelarInscripcionBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:CancelarInscripcionBPELProcessRequestMessage"/>
            <wsdl:output message="client:CancelarInscripcionBPELProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CancelarInscripcionBPELProcessBinding" type="client:CancelarInscripcionBPELProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="cancelarinscripcionbpelprocess_client_ep">
        <wsdl:port name="CancelarInscripcionBPELProcess_pt" binding="client:CancelarInscripcionBPELProcessBinding">
            <soap:address location="http://nmpsoaserver:8001/soa-infra/services/cenmp/WSCancelarInscripcion/cancelarinscripcionbpelprocess_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>