<wsdl:definitions name="ObtenerCursosSocioTecBPELProcess" targetNamespace="http://xmlns.oracle.com/nmpApp/WSObtenerCursosSocioTec/ObtenerCursosSocioTecBPELProcess" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/nmpApp/WSObtenerCursosSocioTec/ObtenerCursosSocioTecBPELProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://nmpsoaserver:8001/soa-infra/services/cenmp/WSObtenerCursosSocioTec!1.0/ObtenerCursosSocioTecBPELProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ObtenerCursosSocioTecBPELProcess">
        <plnk:role name="ObtenerCursosSocioTecBPELProcessProvider" portType="client:ObtenerCursosSocioTecBPELProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/nmpApp/WSObtenerCursosSocioTec/ObtenerCursosSocioTecBPELProcess" schemaLocation="../xsd/XMLSchema_1135539966.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerCursosSocioTecBPELProcessRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="ObtenerCursosSocioTecBPELProcessResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerCursosSocioTecBPELProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:ObtenerCursosSocioTecBPELProcessRequestMessage"/>
            <wsdl:output message="client:ObtenerCursosSocioTecBPELProcessResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ObtenerCursosSocioTecBPELProcessBinding" type="client:ObtenerCursosSocioTecBPELProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="obtenercursossociotecbpelprocess_client_ep">
        <wsdl:port name="ObtenerCursosSocioTecBPELProcess_pt" binding="client:ObtenerCursosSocioTecBPELProcessBinding">
            <soap:address location="http://nmpsoaserver:8001/soa-infra/services/cenmp/WSObtenerCursosSocioTec/obtenercursossociotecbpelprocess_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>