<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/Servicio/DocumentoDonataria/v1" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:ns2="http://servicios.montedepiedad.com.mx/NMP/Schema/Entidad/Donataria/RepresentanteLegal/v1" xmlns:ns1="http://www.example.org" xmlns:ns4="http://servicios.montedepiedad.com.mx/NMP/Schema/Entidad/Donataria/InformacionGeneral/v1" xmlns:ns5="http://servicios.montedepiedad.com.mx/NMP/Schema/Entidad/Donataria/DatosContacto/v1" xmlns:NMPDocumento="http://servicios.montedepiedad.com.mx/NMP/Schema/Entidad/Documento/v1" xmlns:ns7="http://servicios.montedepiedad.com.mx/NMP/Schema/Tipos/Comun" xmlns:ns3="http://servicios.montedepiedad.com.mx/NMP/Schema/Entidad/Donataria/ActaConstitutiva/v1" xmlns:ns6="http://servicios.montedepiedad.com.mx/NMP/Schema/Entidad/Donataria/Consejero/v1" xmlns:NMPDonataria="http://servicios.montedepiedad.com.mx/NMP/Schema/Entidad/Donataria/v1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPDocumentoDonatariaSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="ObtenerURLDocumentoRequest" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Servicio/DocumentoDonataria/v1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/NMPDocumentoDonatariaSvcXSD.xsd"/>
        <oracle-xsl-mapper:rootElement name="ObtenerURLDocumentoResponse" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/Servicio/DocumentoDonataria/v1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON SEP 04 12:09:37 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:ObtenerURLDocumentoResponse>
      <NMPDocumento:url>https://dl.dropboxusercontent.com/apitl/1/AAADe9smRmJAxsyqPThgCQDAdARK7Ss3BT5m9NGfD9sUHV_u0AU8qN1yxPSNuLf6oLF6issJV-3siorFtpYNui24EmuTaO29XBvAXTzcMgEILesCiDVzZbKGwIQ3shIhhT1YyZb73DQ06eFBuJzHYNYEAhGhCkjReopIRrWVW0ZZoy0U3gOPuH4z-JHS2BUVLSOyUNI08nJH9X7rAyCCj9kGP55n7BtVyObvfsv9Fj8aepS6OOek7jxPcqfwXX4lEyKkTu-ZOx78VYHpTM4ln9s6GaJEU73to5Fqv9cZ5t_AgxwaLfRf7WeI6RiNy_hWd20</NMPDocumento:url>
    </ns0:ObtenerURLDocumentoResponse>
  </xsl:template>
</xsl:stylesheet>