<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:tns="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/spObtenerDatosOrden" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/GestionOrdenPagoApp/OrdenesPagoPrj/spObtenerDatosOrden" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns2="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xml:id="id_1" oraxsl:ignorexmlids="true">
    <oracle-xsl-mapper:schema xml:id="id_2">
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources xml:id="id_3">
            <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
                <oracle-xsl-mapper:schema location="../WSDLs/spObtenerDatosOrden.wsdl" xml:id="id_5"/>
                <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/spObtenerDatosOrden" xml:id="id_6"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets xml:id="id_7">
            <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
                <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/GPADomain/GestionOrdenPago!1.0/WSDLs/GestionOrdenPagoBPEL.wsdl" xml:id="id_9"/>
                <oracle-xsl-mapper:rootElement name="guardarOrdenPagoRequest" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xml:id="id_10"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED JAN 11 02:24:14 CST 2017].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/" xml:id="id_11">
        <tns:guardarOrdenPagoRequest xml:id="id_12">
         <!-- CONCATENACION DE FOLOS FICALES-->
                    <xsl:variable name="concatenacion" xml:id="id_97">
                    <!-- CUENTA EL NUMERo DE FACTURAS -->
                    <xsl:variable name="totalFac" select="count( /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row )" xml:id="id_96"/>
                    <!--tns:totalFacturas>
                        <xsl:value-of select='$tatalFac'/>
                    </tns:totalFacturas-->
                        <xsl:for-each select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row" xml:id="id_98">
                            <xsl:choose xml:id="id_99">
                                <xsl:when test="position() = $totalFac " xml:id="id_100">
                                        <xsl:value-of select="ns0:FOLIO_FISCAL" xml:id="id_101"/>
                                </xsl:when>
                                <xsl:otherwise xml:id="id_102">
                                      <xsl:value-of select="concat(ns0:FOLIO_FISCAL,&quot;/&quot;)" xml:id="id_103"/>
                                </xsl:otherwise>
                            </xsl:choose>
                        </xsl:for-each>
                </xsl:variable>
                <tns:Input xml:id="id_13">
                    <!-- SUBTOTAL -->
                    <xsl:if test="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:SUBTOTAL > 0" xml:id="id_14">
                        <tns:ctaPagos xml:id="id_15">
                            <tns:ctaPago xml:id="id_16">
                                <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CC_SUBTOTAL" xml:id="id_17"/>
                            </tns:ctaPago>
                            <tns:cveOficinaMov xml:id="id_18">
                                <!--xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CVE_OFICINA" xml:id="id_19"/-->
                                <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO" xml:id="id_19"/>
                            </tns:cveOficinaMov>
                            <tns:descMov xml:id="id_20">
                                <!--xsl:value-of select='concat("F-",/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:FOLIO_FISCAL," ",/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PAGO," OF-", /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO)'
                                              xml:id="id_21"/-->
                                <xsl:value-of select="concat(&quot;F-&quot;,$concatenacion,&quot; &quot;,/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PAGO,&quot; OF-&quot;, /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO)" xml:id="id_21"/>
                                              
                            </tns:descMov>
                            <!-- SUMATORIA DEL SUBTOTAL -->
                            <tns:importe xml:id="id_22">
                                <xsl:value-of select="sum(/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:SUBTOTAL)" xml:id="id_110"/>
                            </tns:importe>
                            <tns:tipMov xml:id="id_24">D</tns:tipMov>
                            <tns:varCta xml:id="id_25">
                                <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CENTRO_COSTO" xml:id="id_26"/>
                            </tns:varCta>
                        </tns:ctaPagos>
                </xsl:if>
                    <!-- OTROS IMPUESTOS-->
                    <xsl:if test="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OTROS_IMPUESTOS > 0" xml:id="id_27">
                            <tns:ctaPagos xml:id="id_28">
                                <tns:ctaPago xml:id="id_29">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CC_OTROS_IMPUESTOS" xml:id="id_30"/>
                                </tns:ctaPago>
                                <!--tns:cveOficinaMov xml:id="id_31">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CVE_OFICINA" xml:id="id_32"/>
                                </tns:cveOficinaMov-->
                                <tns:cveOficinaMov xml:id="id_31">010</tns:cveOficinaMov>
                                
                                <tns:descMov xml:id="id_33">
                                    <xsl:value-of select="concat(&quot;F-&quot;,/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:FOLIO_FISCAL,&quot; &quot;,/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PAGO,&quot; OF-&quot;, /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO)" xml:id="id_34"/>
                                </tns:descMov>
                                <tns:importe xml:id="id_35">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OTROS_IMPUESTOS" xml:id="id_36"/>
                                </tns:importe>
                                <!-- GALTRA LA VALIDACION DEL IMPUESTO CEDULAR U OTROS-->
                                <tns:tipMov xml:id="id_37">D</tns:tipMov>
                                <tns:varCta xml:id="id_38">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CENTRO_COSTO" xml:id="id_39"/>
                                </tns:varCta>
                            </tns:ctaPagos>
                    </xsl:if>
                    <!-- MONTO IVA -->
                    <xsl:if test="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:MONTO_IVA > 0" xml:id="id_40">
                            <tns:ctaPagos xml:id="id_41">
                                <tns:ctaPago xml:id="id_42">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CC_IVA" xml:id="id_43"/>
                                </tns:ctaPago>
                                <!--tns:cveOficinaMov xml:id="id_44">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CVE_OFICINA" xml:id="id_45"/>
                                </tns:cveOficinaMov-->
                                <tns:cveOficinaMov xml:id="id_44">010</tns:cveOficinaMov>
                                <tns:descMov xml:id="id_46">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CONCEPTO_ABV_IVA" xml:id="id_47"/>
                                </tns:descMov>
                                <!-- SUMA MONTO IVA -->
                                <tns:importe xml:id="id_48">
                                    <xsl:value-of select="sum(/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:MONTO_IVA)" xml:id="id_49"/>
                                </tns:importe>
                                <tns:tipMov xml:id="id_50">D</tns:tipMov>
                                <tns:varCta xml:id="id_51">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CENTRO_COSTO" xml:id="id_52"/>
                                </tns:varCta>
                            </tns:ctaPagos>
                    </xsl:if>
                     
                    <xsl:if test="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:MONTO_RETENCION_ISR > 0" xml:id="id_53">
                            <tns:ctaPagos xml:id="id_54">
                                <tns:ctaPago xml:id="id_55">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CC_RETENCION_ISR" xml:id="id_56"/>
                                </tns:ctaPago>
                                <!--tns:cveOficinaMov xml:id="id_57">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CVE_OFICINA" xml:id="id_58"/>
                                </tns:cveOficinaMov-->
                                <tns:cveOficinaMov xml:id="id_57">010</tns:cveOficinaMov>
                                <tns:descMov xml:id="id_59">
                                    <xsl:value-of select="concat(&quot;F-&quot;,/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:FOLIO_FISCAL,&quot; &quot;,/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PAGO,&quot; OF-&quot;, /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO)" xml:id="id_60"/>
                                </tns:descMov>
                                <tns:importe xml:id="id_61">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:MONTO_RETENCION_ISR" xml:id="id_62"/>
                                </tns:importe>
                                <tns:tipMov xml:id="id_63">C</tns:tipMov>
                                <tns:varCta xml:id="id_64">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CENTRO_COSTO" xml:id="id_65"/>
                                </tns:varCta>
                            </tns:ctaPagos>
                    </xsl:if>
                    <!-- RETENCION IVA -->
                    <xsl:if test="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:MONTO_RETENCION_IVA  > 0" xml:id="id_66">
                            <tns:ctaPagos xml:id="id_67">
                                <tns:ctaPago xml:id="id_68">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CC_RETENCION_IVA" xml:id="id_69"/>
                                </tns:ctaPago>
                                <!--tns:cveOficinaMov xml:id="id_70">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CVE_OFICINA" xml:id="id_71"/>
                                </tns:cveOficinaMov-->
                                <tns:cveOficinaMov xml:id="id_70">010</tns:cveOficinaMov>
                                <tns:descMov xml:id="id_72">
                                    <xsl:value-of select="concat(&quot;F-&quot;,/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:FOLIO_FISCAL,&quot; &quot;,/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PAGO,&quot; OF-&quot;, /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO)" xml:id="id_73"/>
                                </tns:descMov>
                                <tns:importe xml:id="id_74">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:MONTO_RETENCION_IVA" xml:id="id_75"/>
                                </tns:importe>
                                <tns:tipMov xml:id="id_76">C</tns:tipMov>
                                <tns:varCta xml:id="id_77">
                                    <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:CENTRO_COSTO" xml:id="id_78"/>
                                </tns:varCta>
                            </tns:ctaPagos>
                    </xsl:if>
                    <tns:cveBen xml:id="id_79">
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:ID_PRESTADOR" xml:id="id_80"/>
                    </tns:cveBen>
                    <xsl:choose xml:id="id_81">
                        <xsl:when test="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:TP_MONEDA = 1" xml:id="id_82">
                            <tns:monePag xml:id="id_83">
                                <xsl:value-of select="concat (0, 0 )" xml:id="id_84"/>
                            </tns:monePag>
                        </xsl:when>
                        <xsl:otherwise xml:id="id_85">
                            <tns:monePag xml:id="id_86">
                                <xsl:value-of select="concat (0, 1 )" xml:id="id_87"/>
                            </tns:monePag>
                        </xsl:otherwise>
                    </xsl:choose>
                    <!--CONCATENACION INICIAL 1 -->
                    <!--tns:observ>
                      <xsl:value-of select="concat(/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:FOLIO_FISCAL, &quot;&quot;, &quot;-&quot;, &quot;&quot;, /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PAGO, &quot;&quot;, &quot;-&quot;, &quot;&quot;,  /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO )"/>
                        </tns:observ-->
                    <tns:observ xml:id="id_104">
                        <xsl:value-of select="normalize-space ( concat (&quot;F-&quot;,$concatenacion,&quot; &quot;, /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:DESC_PAGO, &quot; OF-&quot;, /ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO ) )" xml:id="id_105"/>
                    </tns:observ>
                    <tns:ofnaPag xml:id="id_90">
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:OFICINA_DESTINO" xml:id="id_91"/>
                    </tns:ofnaPag>
                    <tns:tipBen xml:id="id_92">T</tns:tipBen>
                    <tns:usuario xml:id="id_93">LZARCO</tns:usuario>
                    <tns:id_solicitud xml:id="id_94">
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:ID_SOLICITUD" xml:id="id_95"/>
                    </tns:id_solicitud>
                </tns:Input>
        
        </tns:guardarOrdenPagoRequest>
        <xsl:copy-of select="" xml:id="id_111"/>
    </xsl:template>
</xsl:stylesheet>