<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://qualitas.com.mx/Comunes/OrdenesPago/v1/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://oracle.com/sca/soapservice/GestionOrdenPagoApp/OrdenesPagoPrj/OrdenesPagoService" xml:id="id_1" oraxsl:ignorexmlids="true" xmlns:ns3="http://qualitas.com.mx/Comunes/Prorrateo/ordenPagoProrrateo/v1/">
  <oracle-xsl-mapper:schema xml:id="id_2">
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources xml:id="id_3">
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
        <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/default/GestionOrdenPago!1.0/WSDLs/GestionOrdenPagoBPEL.wsdl" xml:id="id_5"/>
        <oracle-xsl-mapper:rootElement name="consultarOrdenPagoResponse" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xml:id="id_6"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets xml:id="id_7">
      <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
        <oracle-xsl-mapper:schema location="../WSDLs/OrdenesPagoService.wsdl" xml:id="id_9"/>
        <oracle-xsl-mapper:rootElement name="consultarOrdenPagoResponse" namespace="http://qualitas.com.mx/Comunes/OrdenesPago/v1/" xml:id="id_10"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [TUE JAN 10 21:35:26 CST 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/" xml:id="id_11">
    <tns:consultarOrdenPagoResponse xml:id="id_12">
      <tns:OperationResponse xml:id="id_13">
        <ns1:codigoRespuesta xml:id="id_14">
          <xsl:value-of select="/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:codigoRespuesta" xml:id="id_15"/>
        </ns1:codigoRespuesta>
        <ns1:descripcionRespuesta xml:id="id_16">
          <xsl:value-of select="/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta" xml:id="id_17"/>
        </ns1:descripcionRespuesta>
      </tns:OperationResponse>
      <tns:Output xml:id="id_18">
        <tns:numOrden xml:id="id_19">
          <xsl:value-of select="/ns0:consultarOrdenPagoResponse/ns0:Output/ns0:numOrden" xml:id="id_20"/>
        </tns:numOrden>
        <tns:numCaratula xml:id="id_21">
          <xsl:value-of select="/ns0:consultarOrdenPagoResponse/ns0:Output/ns0:numCaratula" xml:id="id_22"/>
        </tns:numCaratula>
        <tns:estadoPago xml:id="id_23">
          <xsl:value-of select="/ns0:consultarOrdenPagoResponse/ns0:Output/ns0:estadoPago" xml:id="id_24"/>
        </tns:estadoPago>
      </tns:Output>
    </tns:consultarOrdenPagoResponse>
  </xsl:template>
</xsl:stylesheet>