<wsdl:definitions name="BitacoraContabilidadDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AutomatizacionContable/SIGOTiempoReal/BitacoraContabilidadDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AutomatizacionContable/SIGOTiempoReal/BitacoraContabilidadDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/BitacoraContabilidadDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="BitacoraContabilidadDB_plt">
    <plt:role name="BitacoraContabilidadDB_role">
      <plt:portType name="tns:BitacoraContabilidadDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/BitacoraContabilidadDB" schemaLocation="../Schemas/OSBBitacoraContabilidadDbXSD.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="BitOsbContabilidadCollection_msg">
        <wsdl:part name="BitOsbContabilidadCollection" element="top:BitOsbContabilidadCollection"/>
    </wsdl:message>
    <wsdl:portType name="BitacoraContabilidadDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:BitOsbContabilidadCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>