<wsdl:definitions name="ScoreBitacoraDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Adaptadores/Score/ScoreBitacoraDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Adaptadores/Score/ScoreBitacoraDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ScoreBitacoraDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="ScoreBitacoraDB_plt">
    <plt:role name="ScoreBitacoraDB_role">
      <plt:portType name="tns:ScoreBitacoraDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ScoreBitacoraDB" schemaLocation="../Schemas/OSBBitacoraScoreXSD.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="BitOsbScoreCollection_msg">
        <wsdl:part name="BitOsbScoreCollection" element="top:BitOsbScoreCollection"/>
    </wsdl:message>
    <wsdl:portType name="ScoreBitacoraDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:BitOsbScoreCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>