<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Adaptadores/Score/ScoreBitacoraDB" name="ScoreBitacoraBS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="OSBBitacoraScoreDbWSDL.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Adaptadores/Score/ScoreBitacoraDB"/>
    <wsdl:binding name="ScoreBitacoraDB_ptt-binding" type="scor:ScoreBitacoraDB_ptt" xmlns:scor="http://xmlns.oracle.com/pcbpel/adapter/db/Adaptadores/Score/ScoreBitacoraDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>