<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ObtenerOficinaBPEL" targetNamespace="http://qualitas.com.mx/ObtenerOficinaApp/ObtenerOficinaPrj/ObtenerOficinaBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ObtenerOficinaApp/ObtenerOficinaPrj/ObtenerOficinaBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Oficina/obtenerOficinaPorClave/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comun/Oficina/obtenerOficinaPorClave/v1/" schemaLocation="../Schemas/obtenerOficinaPorClave.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ObtenerOficinaBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:obtenerOficinaPorClaveRequest"/>
   </wsdl:message>
   <wsdl:message name="ObtenerOficinaBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:obtenerOficinaPorClaveResponse"/>
   </wsdl:message>
   <wsdl:portType name="ObtenerOficinaBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ObtenerOficinaBPELRequestMessage"/>
         <wsdl:output message="client:ObtenerOficinaBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ObtenerOficinaBPEL">
      <plnk:role name="ObtenerOficinaBPELProvider" portType="client:ObtenerOficinaBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
