<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="GuardarArchivoProrrateo" targetNamespace="http://qualitas.com.mx/Comunes/Prorrateo/guardarArchivoProrrateo/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/Comunes/Prorrateo/guardarArchivoProrrateo/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:qcmcpgv="http://qualitas.com.mx/Comunes/Prorrateo/guardarArchivoProrrateo/v1/">
   <wsdl:types>
      <xsd:schema>
         <xsd:import schemaLocation="../Schemas/GuardarArchivoProrrateo.xsd" namespace="http://qualitas.com.mx/Comunes/Prorrateo/guardarArchivoProrrateo/v1/"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="GuardarArchivoProrrateoRequestMessage">
      <wsdl:part name="payload" element="qcmcpgv:processRequest"/>
   </wsdl:message>
   <wsdl:message name="GuardarArchivoProrrateoResponseMessage">
      <wsdl:part name="payload" element="qcmcpgv:processResponse"/>
   </wsdl:message>
   <wsdl:portType name="GuardarArchivoProrrateo">
      <wsdl:operation name="process">
         <wsdl:input message="client:GuardarArchivoProrrateoRequestMessage"/>
         <wsdl:output message="client:GuardarArchivoProrrateoResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="GuardarArchivoProrrateo">
      <plnk:role name="GuardarArchivoProrrateoProvider" portType="client:GuardarArchivoProrrateo"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
