<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertOrdenPago" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/GestionOrdenPago/DB_InsertOrdenPago" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GestionOrdenPagoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="consultarOrdenPagoResponse" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DB_InsertOrdenPago.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Gpa019PagosCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_InsertOrdenPago"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI JAN 06 20:40:29 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Gpa019PagosCollection>
         <tns:Gpa019Pagos>
            <xsl:choose>
               <xsl:when test="/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;PENDIENTE&quot; or /ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;CANCELADO&quot;">
                  <tns:numCaratula>
                     <xsl:value-of select="&quot;&quot;"/>
                  </tns:numCaratula>
               </xsl:when>
               <xsl:otherwise>
               <tns:numCaratula>
                     <xsl:value-of select="/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta"/>
                  </tns:numCaratula>
               </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
               <xsl:when test="/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;PENDIENTE&quot; or /ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;CANCELADO&quot;">
                  <tns:estadoPago>
                     <xsl:value-of select="/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta"/>
                  </tns:estadoPago>
               </xsl:when>
               <xsl:otherwise>
                <tns:estadoPago>PAGADO</tns:estadoPago>
               </xsl:otherwise>
            </xsl:choose>
         </tns:Gpa019Pagos>
      </tns:Gpa019PagosCollection>
   </xsl:template>
</xsl:stylesheet>