<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:tns="http://service.pagos.qualitas.com.mx/" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GestionOrdenPagoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="guardarOrdenPagoRequest" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://11.50.0.73:9010/pagos-web/servicios/pagosService?wsdl"/>
            <oracle-xsl-mapper:rootElement name="generaOrden" namespace="http://service.pagos.qualitas.com.mx/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI JAN 06 17:29:56 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:generaOrden>
         <OrdenPago>
            <cheqCert>
               <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cheqCert"/>
            </cheqCert>
            <ctaPagos>
               <xsl:for-each select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:ctaPagos">
                  <ctaPago>
                     <ctaPag>
                        <xsl:value-of select="ns0:ctaPago"/>
                     </ctaPag>
                     <cveOficinaMov>
                        <xsl:value-of select="ns0:cveOficinaMov"/>
                     </cveOficinaMov>
                     <descMov>
                        <xsl:value-of select="ns0:descMov"/>
                     </descMov>
                     <importe>
                        <xsl:value-of select="ns0:importe"/>
                     </importe>
                     <tipMov>
                        <xsl:value-of select="ns0:tipMov"/>
                     </tipMov>
                     <varCta>
                        <xsl:value-of select="ns0:varCta"/>
                     </varCta>
                  </ctaPago>
               </xsl:for-each>
            </ctaPagos>
              <xsl:choose>
                     <xsl:when test="string-length(string(/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())) = 4">
                          <cveBen>
                               <xsl:value-of select="concat('0',/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())"/>
                          </cveBen>
                     </xsl:when>
                     <xsl:when test="string-length(string(/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())) = 3">
                          <cveBen>
                               <xsl:value-of select="concat('00',/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())"/>
                          </cveBen>
                     </xsl:when>
                     <xsl:when test="string-length(string(/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())) = 2">
                          <cveBen>
                               <xsl:value-of select="concat('000',/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())"/>
                          </cveBen>
                     </xsl:when>
                     <xsl:when test="string-length(string(/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())) = 1">
                          <cveBen>
                               <xsl:value-of select="concat('0000',/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen/text())"/>
                          </cveBen>
                     </xsl:when>
                     <xsl:otherwise>
                          <cveBen>
                              <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen"/>
                          </cveBen>
                     </xsl:otherwise>
               </xsl:choose>
               
               
               <!--cveBen>
                  <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:cveBen"/>
               </cveBen-->
           
            <monePag>
               <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:monePag"/>
            </monePag>
            <observ>
               <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:observ"/>
            </observ>
            <ofnaPag>
               <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:ofnaPag"/>
            </ofnaPag>
            <tipBen>
               <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:tipBen"/>
            </tipBen>
            <usuario>
               <xsl:value-of select="/ns0:guardarOrdenPagoRequest/ns0:Input/ns0:usuario"/>
            </usuario>
         </OrdenPago>
      </tns:generaOrden>
   </xsl:template>
</xsl:stylesheet>