<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="GuardarSolicitudBPEL" targetNamespace="http://qualitas.com.mx/GuardarSolicitudApp/GuardarSolicitudPrj/GuardarSolicitudBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/GuardarSolicitudApp/GuardarSolicitudPrj/GuardarSolicitudBPEL" xmlns:ns1="http://qualitas.com.mx/Solicitud/GuardarSolicitud/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Solicitud/GuardarSolicitud/v1/" schemaLocation="../Schemas/GuardarSolicitud.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="GuardarSolicitudBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:GuardarSolicitudRequest"/>
   </wsdl:message>
   <wsdl:message name="GuardarSolicitudBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:GuardarSolicitudResponse"/>
   </wsdl:message>
   <wsdl:portType name="GuardarSolicitudBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:GuardarSolicitudBPELRequestMessage"/>
         <wsdl:output message="client:GuardarSolicitudBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="GuardarSolicitudBPEL">
      <plnk:role name="GuardarSolicitudBPELProvider" portType="client:GuardarSolicitudBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
