<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/HistoricoViaticosEmpleadoDB" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Data/BusinessSvc/HistorialViaticosEmpleado/Resources/HistoricoViaticosEmpleadoDB_table.xsd"/>
        <oracle-xsl-mapper:rootElement name="Gpa001SolicitudCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/HistoricoViaticosEmpleadoDB"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../Data/BusinessSvc/HistorialViaticosEmpleado/Resources/HistoricoViaticosEmpleadoDB_table.xsd"/>
        <oracle-xsl-mapper:rootElement name="Gpa001SolicitudCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/HistoricoViaticosEmpleadoDB"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI MAY 05 14:24:19 CDT 2017].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <!--xsl:variable name="activos" select="0">
      < CUENTA EL NUMERO Complementos Activos  >
      <xsl:for-each select="/ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud/ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos/ns0:complementos">
        <xsl:choose>
          <xsl:when test="/ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud/ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos/ns0:complementos/ns0:idEstado != 2
                            or /ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud/ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos/ns0:complementos/ns0:idEstado != 4
                            or /ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud/ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos/ns0:complementos/ns0:idEstado != 7">
          <xsl:when test="/ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud/ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos/ns0:complementos/ns0:idEstado = 12">
            <xsl:value-of select="count(/ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud/ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos/ns0:complementos)"/>
            <otros>
              <xsl:value-of select="$activos+1"/>
            </otros>
          </xsl:when>
        </xsl:choose>
      </xsl:for-each-->
    <ns0:Gpa001SolicitudCollection>
      <xsl:for-each select="/ns0:Gpa001SolicitudCollection/ns0:Gpa001Solicitud">
        <xsl:if test="position() = 1">
          <ns0:Gpa001Solicitud>
            <ns0:idSolicitud>
              <xsl:value-of select="ns0:idSolicitud"/>
            </ns0:idSolicitud>
            <xsl:if test="ns0:idTpSolicitud/text()">
              <ns0:idTpSolicitud>
                <xsl:value-of select="ns0:idTpSolicitud"/>
              </ns0:idTpSolicitud>
            </xsl:if>
            <xsl:if test="ns0:nuEmpleado/text()">
              <ns0:nuEmpleado>
                <xsl:value-of select="ns0:nuEmpleado"/>
              </ns0:nuEmpleado>
            </xsl:if>
            <xsl:if test="ns0:nombreEmpleado/text()">
              <ns0:nombreEmpleado>
                <xsl:value-of select="ns0:nombreEmpleado"/>
              </ns0:nombreEmpleado>
            </xsl:if>
            <xsl:if test="ns0:fhActualizacion/text()">
              <ns0:fhActualizacion>
                <xsl:if test="ns0:fhActualizacion/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:fhActualizacion/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:fhActualizacion"/>
              </ns0:fhActualizacion>
            </xsl:if>
            <xsl:if test="ns0:idUsuario/text()">
              <ns0:idUsuario>
                <xsl:if test="ns0:idUsuario/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:idUsuario/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:idUsuario"/>
              </ns0:idUsuario>
            </xsl:if>
            <xsl:if test="ns0:totalPagar/text()">
              <ns0:totalPagar>
                <xsl:if test="ns0:totalPagar/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:totalPagar/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:totalPagar"/>
              </ns0:totalPagar>
            </xsl:if>
            <xsl:if test="ns0:fhCreacion/text()">
              <ns0:fhCreacion>
                <xsl:if test="ns0:fhCreacion/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:fhCreacion/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:fhCreacion"/>
              </ns0:fhCreacion>
            </xsl:if>
            <xsl:if test="ns0:nuOrden/text()">
              <ns0:nuOrden>
                <xsl:if test="ns0:nuOrden/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:nuOrden/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:nuOrden"/>
              </ns0:nuOrden>
            </xsl:if>
            <xsl:if test="ns0:fhFinProceso/text()">
              <ns0:fhFinProceso>
                <xsl:if test="ns0:fhFinProceso/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:fhFinProceso/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:fhFinProceso"/>
              </ns0:fhFinProceso>
            </xsl:if>
            <xsl:if test="ns0:idEstadoSolicitud/text()">
              <ns0:idEstadoSolicitud>
                <xsl:if test="ns0:idEstadoSolicitud/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:idEstadoSolicitud/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:idEstadoSolicitud"/>
              </ns0:idEstadoSolicitud>
            </xsl:if>
            <xsl:if test="ns0:oficinaDestino/text()">
              <ns0:oficinaDestino>
                <xsl:if test="ns0:oficinaDestino/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:oficinaDestino/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:oficinaDestino"/>
              </ns0:oficinaDestino>
            </xsl:if>
            <xsl:if test="ns0:procesable/text()">
              <ns0:procesable>
                <xsl:if test="ns0:procesable/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:procesable/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:procesable"/>
              </ns0:procesable>
            </xsl:if>
            <xsl:if test="ns0:auxIdproyecto/text()">
              <ns0:auxIdproyecto>
                <xsl:if test="ns0:auxIdproyecto/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:auxIdproyecto/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:auxIdproyecto"/>
              </ns0:auxIdproyecto>
            </xsl:if>
            <xsl:if test="ns0:idSubtpSolic/text()">
              <ns0:idSubtpSolic>
                <xsl:if test="ns0:idSubtpSolic/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:idSubtpSolic/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:idSubtpSolic"/>
              </ns0:idSubtpSolic>
            </xsl:if>
            <!--xsl:if test="ns0:servicio/text()"-->
            <xsl:if test="ns0:servicio/ns0:idServicio/text()">
              <ns0:servicio>
                <xsl:if test="ns0:servicio/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:servicio/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <ns0:idServicio>
                  <xsl:value-of select="ns0:servicio/ns0:idServicio"/>
                </ns0:idServicio>
                <xsl:if test="ns0:servicio/ns0:descServicio/text()">
                  <ns0:descServicio>
                    <xsl:if test="ns0:servicio/ns0:descServicio/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:descServicio/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:descServicio"/>
                  </ns0:descServicio>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:idTpServicio/text()">
                  <ns0:idTpServicio>
                    <xsl:if test="ns0:servicio/ns0:idTpServicio/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:idTpServicio/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:idTpServicio"/>
                  </ns0:idTpServicio>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:centroCosto/text()">
                  <ns0:centroCosto>
                    <xsl:if test="ns0:servicio/ns0:centroCosto/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:centroCosto/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:centroCosto"/>
                  </ns0:centroCosto>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:idSolicitud/text()">
                  <ns0:idSolicitud>
                    <xsl:if test="ns0:servicio/ns0:idSolicitud/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:idSolicitud/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:idSolicitud"/>
                  </ns0:idSolicitud>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:idPrestador/text()">
                  <ns0:idPrestador>
                    <xsl:if test="ns0:servicio/ns0:idPrestador/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:idPrestador/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:idPrestador"/>
                  </ns0:idPrestador>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:fhRegistro/text()">
                  <ns0:fhRegistro>
                    <xsl:if test="ns0:servicio/ns0:fhRegistro/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:fhRegistro/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:fhRegistro"/>
                  </ns0:fhRegistro>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:descOficina/text()">
                  <ns0:descOficina>
                    <xsl:if test="ns0:servicio/ns0:descOficina/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:descOficina/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:descOficina"/>
                  </ns0:descOficina>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:descArea/text()">
                  <ns0:descArea>
                    <xsl:if test="ns0:servicio/ns0:descArea/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:descArea/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:descArea"/>
                  </ns0:descArea>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:responsableArea/text()">
                  <ns0:responsableArea>
                    <xsl:if test="ns0:servicio/ns0:responsableArea/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:responsableArea/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:responsableArea"/>
                  </ns0:responsableArea>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:cveOficina/text()">
                  <ns0:cveOficina>
                    <xsl:if test="ns0:servicio/ns0:cveOficina/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:cveOficina/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:cveOficina"/>
                  </ns0:cveOficina>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:procesable/text()">
                  <ns0:procesable>
                    <xsl:if test="ns0:servicio/ns0:procesable/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:servicio/ns0:procesable/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:servicio/ns0:procesable"/>
                  </ns0:procesable>
                </xsl:if>
                <xsl:if test="ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos">
                  <ns0:viaticos>
                    <xsl:for-each select="ns0:servicio/ns0:viaticos/ns0:Gpa022Viaticos">
                      <ns0:Gpa022Viaticos>
                        <xsl:if test="ns0:fhInicioViaje/text()">
                          <ns0:fhInicioViaje>
                            <xsl:if test="ns0:fhInicioViaje/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:fhInicioViaje/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:fhInicioViaje"/>
                          </ns0:fhInicioViaje>
                        </xsl:if>
                        <xsl:if test="ns0:fhFinViaje/text()">
                          <ns0:fhFinViaje>
                            <xsl:if test="ns0:fhFinViaje/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:fhFinViaje/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:fhFinViaje"/>
                          </ns0:fhFinViaje>
                        </xsl:if>
                        <xsl:if test="ns0:justificacion/text()">
                          <ns0:justificacion>
                            <xsl:value-of select="ns0:justificacion"/>
                          </ns0:justificacion>
                        </xsl:if>
                        <xsl:if test="ns0:loginAutorizador/text()">
                          <ns0:loginAutorizador>
                            <xsl:if test="ns0:loginAutorizador/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:loginAutorizador/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:loginAutorizador"/>
                          </ns0:loginAutorizador>
                        </xsl:if>
                        <xsl:if test="ns0:nroDiasViaje/text()">
                          <ns0:nroDiasViaje>
                            <xsl:if test="ns0:nroDiasViaje/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:nroDiasViaje/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:nroDiasViaje"/>
                          </ns0:nroDiasViaje>
                        </xsl:if>
                        <xsl:if test="ns0:nroKms/text()">
                          <ns0:nroKms>
                            <xsl:if test="ns0:nroKms/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:nroKms/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:nroKms"/>
                          </ns0:nroKms>
                        </xsl:if>
                        <xsl:if test="ns0:valorAnticipo/text()">
                          <ns0:valorAnticipo>
                            <xsl:if test="ns0:valorAnticipo/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:valorAnticipo/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:valorAnticipo"/>
                          </ns0:valorAnticipo>
                        </xsl:if>
                        <xsl:if test="ns0:cveOficinaDestino/text()">
                          <ns0:cveOficinaDestino>
                            <xsl:if test="ns0:cveOficinaDestino/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:cveOficinaDestino/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:cveOficinaDestino"/>
                          </ns0:cveOficinaDestino>
                        </xsl:if>
                        <xsl:if test="ns0:idEstado/text()">
                          <ns0:idEstado>
                            <xsl:if test="ns0:idEstado/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:idEstado/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:value-of select="ns0:idEstado"/>
                          </ns0:idEstado>
                        </xsl:if>
                        <xsl:if test="ns0:categorias/ns0:Gpa023CatViaticos">
                          <ns0:categorias>
                            <xsl:for-each select="ns0:categorias/ns0:Gpa023CatViaticos">
                              <ns0:Gpa023CatViaticos>
                                <ns0:codigoTarifa>
                                  <xsl:value-of select="ns0:codigoTarifa"/>
                                </ns0:codigoTarifa>
                                <xsl:if test="ns0:valorTarifa/text()">
                                  <ns0:valorTarifa>
                                    <xsl:value-of select="ns0:valorTarifa"/>
                                  </ns0:valorTarifa>
                                </xsl:if>
                                <xsl:if test="ns0:valorAnticipo/text()">
                                  <ns0:valorAnticipo>
                                    <xsl:value-of select="ns0:valorAnticipo"/>
                                  </ns0:valorAnticipo>
                                </xsl:if>
                              </ns0:Gpa023CatViaticos>
                            </xsl:for-each>
                          </ns0:categorias>
                        </xsl:if>
                        <xsl:if test="ns0:cdeudoras/ns0:idCedudoras/text()">
                          <ns0:cdeudoras>
                            <xsl:if test="ns0:cdeudoras/@xsi:nil">
                              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                <xsl:value-of select="ns0:cdeudoras/@xsi:nil"/>
                              </xsl:attribute>
                            </xsl:if>
                            <ns0:idCedudoras>
                              <xsl:value-of select="ns0:cdeudoras/ns0:idCedudoras"/>
                            </ns0:idCedudoras>
                            <xsl:if test="ns0:cdeudoras/ns0:nuCdeudoras/text()">
                              <ns0:nuCdeudoras>
                                <xsl:value-of select="ns0:cdeudoras/ns0:nuCdeudoras"/>
                              </ns0:nuCdeudoras>
                            </xsl:if>
                            <xsl:if test="ns0:cdeudoras/ns0:descDeudoras/text()">
                              <ns0:descDeudoras>
                                <xsl:value-of select="ns0:cdeudoras/ns0:descDeudoras"/>
                              </ns0:descDeudoras>
                            </xsl:if>
                            <xsl:if test="ns0:cdeudoras/ns0:stRegistro/text()">
                              <ns0:stRegistro>
                                <xsl:value-of select="ns0:cdeudoras/ns0:stRegistro"/>
                              </ns0:stRegistro>
                            </xsl:if>
                          </ns0:cdeudoras>
                        </xsl:if>
                        <xsl:if test="ns0:complementos/ns0:Gpa022Viaticos">
                          <ns0:complementos>
                            <xsl:for-each select="ns0:complementos/ns0:Gpa022Viaticos">
                              <!--xsl:if test="int(*:complementos/*:Gpa022Viaticos/*:idEstado/text()) = 16"-->
                              <xsl:if test="ns0:idEstado/text() != 2">
                                <xsl:if test="ns0:idEstado/text() != 4">
                                  <xsl:if test="ns0:idEstado/text() != 5">
                                    <xsl:if test="ns0:idEstado/text() != 7">
                                      <xsl:if test="ns0:idEstado/text() != 12">
                                        <xsl:if test="ns0:idEstado/text() != 17">
                                          <xsl:if test="ns0:idEstado/text() != 22">
                                            <xsl:if test="ns0:idEstado/text() != 23">
                                              <ns0:Gpa022Viaticos>
                                                <xsl:if test="ns0:fhInicioViaje/text()">
                                                  <ns0:fhInicioViaje>
                                                    <xsl:if test="ns0:fhInicioViaje/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:fhInicioViaje/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:fhInicioViaje"/>
                                                  </ns0:fhInicioViaje>
                                                </xsl:if>
                                                <xsl:if test="ns0:fhFinViaje/text()">
                                                  <ns0:fhFinViaje>
                                                    <xsl:if test="ns0:fhFinViaje/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:fhFinViaje/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:fhFinViaje"/>
                                                  </ns0:fhFinViaje>
                                                </xsl:if>
                                                <xsl:if test="ns0:justificacion/text()">
                                                  <ns0:justificacion>
                                                    <xsl:value-of select="ns0:justificacion"/>
                                                  </ns0:justificacion>
                                                </xsl:if>
                                                <xsl:if test="ns0:loginAutorizador/text()">
                                                  <ns0:loginAutorizador>
                                                    <xsl:if test="ns0:loginAutorizador/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:loginAutorizador/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:loginAutorizador"/>
                                                  </ns0:loginAutorizador>
                                                </xsl:if>
                                                <xsl:if test="ns0:nroDiasViaje/text()">
                                                  <ns0:nroDiasViaje>
                                                    <xsl:if test="ns0:nroDiasViaje/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:nroDiasViaje/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:nroDiasViaje"/>
                                                  </ns0:nroDiasViaje>
                                                </xsl:if>
                                                <xsl:if test="ns0:nroKms/text()">
                                                  <ns0:nroKms>
                                                    <xsl:if test="ns0:nroKms/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:nroKms/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:nroKms"/>
                                                  </ns0:nroKms>
                                                </xsl:if>
                                                <xsl:if test="ns0:valorAnticipo/text()">
                                                  <ns0:valorAnticipo>
                                                    <xsl:if test="ns0:valorAnticipo/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:valorAnticipo/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:valorAnticipo"/>
                                                  </ns0:valorAnticipo>
                                                </xsl:if>
                                                <xsl:if test="ns0:cveOficinaDestino/text()">
                                                  <ns0:cveOficinaDestino>
                                                    <xsl:if test="ns0:cveOficinaDestino/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:cveOficinaDestino/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:cveOficinaDestino"/>
                                                  </ns0:cveOficinaDestino>
                                                </xsl:if>
                                                <xsl:if test="ns0:idEstado/text()">
                                                  <ns0:idEstado>
                                                    <xsl:if test="ns0:idEstado/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:idEstado/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <xsl:value-of select="ns0:idEstado"/>
                                                  </ns0:idEstado>
                                                  <!--activo>1</activo-->
                                                </xsl:if>
                                                <xsl:if test="ns0:categorias/ns0:Gpa023CatViaticos">
                                                  <ns0:categorias>
                                                    <xsl:for-each select="ns0:categorias/ns0:Gpa023CatViaticos">
                                                      <ns0:Gpa023CatViaticos>
                                                        <ns0:codigoTarifa>
                                                          <xsl:value-of select="ns0:codigoTarifa"/>
                                                        </ns0:codigoTarifa>
                                                        <xsl:if test="ns0:valorTarifa/text()">
                                                          <ns0:valorTarifa>
                                                            <xsl:value-of select="ns0:valorTarifa"/>
                                                          </ns0:valorTarifa>
                                                        </xsl:if>
                                                        <xsl:if test="ns0:valorAnticipo/text()">
                                                          <ns0:valorAnticipo>
                                                            <xsl:value-of select="ns0:valorAnticipo"/>
                                                          </ns0:valorAnticipo>
                                                        </xsl:if>
                                                      </ns0:Gpa023CatViaticos>
                                                    </xsl:for-each>
                                                  </ns0:categorias>
                                                </xsl:if>
                                                <xsl:if test="ns0:cdeudoras/ns0:idCedudoras/text()">
                                                  <ns0:cdeudoras>
                                                    <xsl:if test="ns0:cdeudoras/@xsi:nil">
                                                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                                                        <xsl:value-of select="ns0:cdeudoras/@xsi:nil"/>
                                                      </xsl:attribute>
                                                    </xsl:if>
                                                    <ns0:idCedudoras>
                                                      <xsl:value-of select="ns0:cdeudoras/ns0:idCedudoras"/>
                                                    </ns0:idCedudoras>
                                                    <xsl:if test="ns0:cdeudoras/ns0:nuCdeudoras/text()">
                                                      <ns0:nuCdeudoras>
                                                        <xsl:value-of select="ns0:cdeudoras/ns0:nuCdeudoras"/>
                                                      </ns0:nuCdeudoras>
                                                    </xsl:if>
                                                    <xsl:if test="ns0:cdeudoras/ns0:descDeudoras/text()">
                                                      <ns0:descDeudoras>
                                                        <xsl:value-of select="ns0:cdeudoras/ns0:descDeudoras"/>
                                                      </ns0:descDeudoras>
                                                    </xsl:if>
                                                    <xsl:if test="ns0:cdeudoras/ns0:stRegistro/text()">
                                                      <ns0:stRegistro>
                                                        <xsl:value-of select="ns0:cdeudoras/ns0:stRegistro"/>
                                                      </ns0:stRegistro>
                                                    </xsl:if>
                                                  </ns0:cdeudoras>
                                                </xsl:if>
                                              </ns0:Gpa022Viaticos>
                                            </xsl:if>
                                          </xsl:if>
                                        </xsl:if>
                                      </xsl:if>
                                    </xsl:if>
                                  </xsl:if>
                                </xsl:if>
                              </xsl:if>
                            </xsl:for-each>
                          </ns0:complementos>
                        </xsl:if>
                      </ns0:Gpa022Viaticos>
                    </xsl:for-each>
                  </ns0:viaticos>
                </xsl:if>
              </ns0:servicio>
            </xsl:if>
          </ns0:Gpa001Solicitud>
        </xsl:if>
      </xsl:for-each>
    </ns0:Gpa001SolicitudCollection>
    <!--/xsl:variable-->
  </xsl:template>
</xsl:stylesheet>