<wsdl:definitions name="ObtenerPreciosRapaport" targetNamespace="http://xmlns.oracle.com/OperacionPrendaria/NMPObtenerPrecios/ObtenerPreciosRapaport" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/OperacionPrendaria/NMPObtenerPrecios/ObtenerPreciosRapaport" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://10.30.3.15:8001/soa-infra/services/OPP_PREN/NMPObtenerPrecios!1.0/WSDLs/ObtenerPreciosRapaport.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ObtenerPreciosRapaport">
        <plnk:role name="ObtenerPreciosRapaportProvider" portType="client:ObtenerPreciosRapaport"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/OperacionPrendaria/NMPObtenerPrecios/ObtenerPreciosRapaport" schemaLocation="../Schemas/NMPObtenerPreciosBpelXSD.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerPreciosRapaportRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerPreciosRapaport">
        <wsdl:operation name="process">
            <wsdl:input message="client:ObtenerPreciosRapaportRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ObtenerPreciosRapaportBinding" type="client:ObtenerPreciosRapaport">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="obtenerpreciosrapaport_client_ep">
        <wsdl:port name="ObtenerPreciosRapaport_pt" binding="client:ObtenerPreciosRapaportBinding">
            <soap:address location="http://10.30.3.15:8001/soa-infra/services/OPP_PREN/NMPObtenerPrecios/obtenerpreciosrapaport_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>