<wsdl:definitions targetNamespace="http://xmlns.oracle.com/PlataformaComercial_3/OperacionPrendaria/BDAArticulosAgilirionConcreteBD" name="BDAArticulosAgilirionConcreteBD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="BDAArticulosAgilirionBD.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/PlataformaComercial/OperacionPrendaria/BDAArticulosAgilirionBD"/>
  
  
   <wsdl:binding name="BDAArticulosAgilirionBD_ptt-binding" type="dbup:BDAArticulosAgilirionBD_ptt" xmlns:dbup="http://xmlns.oracle.com/pcbpel/adapter/db/PlataformaComercial/OperacionPrendaria/BDAArticulosAgilirionBD">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="BDAArticulosAgilirionBD">
      <soap:operation soapAction="BDAArticulosAgilirionBD"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>