<wsdl:definitions name="BDAArticulosAgilirionBD" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PlataformaComercial/OperacionPrendaria/BDAArticulosAgilirionBD" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PlataformaComercial/OperacionPrendaria/BDAArticulosAgilirionBD" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/BDAArticulosAgilirionBD" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="BDAArticulosAgilirionBD_plt">
    <plt:role name="BDAArticulosAgilirionBD_role">
      <plt:portType name="tns:BDAArticulosAgilirionBD_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BDAArticulosAgilirionBD" schemaLocation="../Schemas/BDAArticulosAgilirionBD.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="BDAArticulosAgilirionBDInput_msg">
        <wsdl:part name="BDAArticulosAgilirionBDInput_msg" element="db:BDAArticulosAgilirionBDInput"/>
    </wsdl:message>
    <wsdl:portType name="BDAArticulosAgilirionBD_ptt">
        <wsdl:operation name="BDAArticulosAgilirionBD">
            <wsdl:input message="tns:BDAArticulosAgilirionBDInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>