<definitions targetNamespace="http://servicios.montedepiedad.com.mx/NMP/Servicios/NMPPublicarArticulosQueue" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://servicios.montedepiedad.com.mx/NMP/Servicios/NMPPublicarArticulosQueue" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:NMPArticulos="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPlataformacomercial" xmlns:NMPsh="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import schemaLocation="../Schemas/NMPAgilirionProductoXSD.xsd" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPPlataformacomercial"/>
            <import schemaLocation="../../../../Common/XSD/NMPStandardHeader.xsd" namespace="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardHeader"/>
        </schema>
    </wsdl:types>
    <message name="NMPStandardHeader">
        <part name="requestHeader" element="NMPsh:headerMessage"/>
        <part name="traz" element="NMPArticulos:trazabilidad"/>
    </message>
    <wsdl:message name="publicarArticulosQueueRequest">
        <wsdl:part name="parameters" element="NMPArticulos:obteneArticuloAgilirionResponse"/>
    </wsdl:message>
    <portType name="ArticulosQueue_ptt">
        <operation name="publicarArticulosQueue">
            <input message="tns:publicarArticulosQueueRequest"/>
        </operation>
    </portType>
    <binding name="ArticulosQueueBinding" type="tns:ArticulosQueue_ptt">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="publicarArticulosQueue">
            <soap:operation style="document" soapAction="http://servicios.montedepiedad.com.mx/NMP/Servicios/NMPPlataformaComercial/publicarArticulosQueue"/>
            <input>
                <soap:body use="literal" parts="parameters"/>
                <soap:header message="tns:NMPStandardHeader" part="requestHeader" use="literal"/>
                <soap:header message="tns:NMPStandardHeader" part="traz" use="literal"/>
            </input>
        </operation>
    </binding>
    <service name="Articulos_ptt">
        <port name="Articulos_pttPort" binding="tns:ArticulosQueueBinding"/>
    </service>
</definitions>