<wsdl:definitions targetNamespace="http://xmlns.oracle.com/PlataformaComercial_3/OperacionPrendaria/OSBArticulosAgilirionConcrete2" name="OSBArticulosAgilirionConcrete2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<wsdl:import location="OSBArticulosAgilirionAQ.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/aq/PlataformaComercial_3/OperacionPrendaria/OSBArticulosAgilirionAQ"/>
       
       
                  
<wsdl:binding name="Dequeue_pttSOAP11Binding" type="ren:Dequeue_ptt" xmlns:ren="http://xmlns.oracle.com/pcbpel/adapter/aq/PlataformaComercial_3/OperacionPrendaria/OSBArticulosAgilirionAQ">

       <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="Dequeue">
      <soap:operation soapAction="Dequeue"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>