<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectoBusDB/ActualizarEstado/SeguimientoSolicitudSP" name="SeguimientoSolicitudSP-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SeguimientoSolicitudSP.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectoBusDB/ActualizarEstado/SeguimientoSolicitudSP"/>
    <wsdl:binding name="SeguimientoSolicitudSP_ptt-binding" type="seg:SeguimientoSolicitudSP_ptt" xmlns:seg="http://xmlns.oracle.com/pcbpel/adapter/db/ProyectoBusDB/ActualizarEstado/SeguimientoSolicitudSP">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SeguimientoSolicitudSP">
            <soap:operation soapAction="SeguimientoSolicitudSP"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>