<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/DetallePadronDBAdapter" name="DetallePadronDBAdapter-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/DetallePadronDBAdapter" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMP_Padr%C3%B3n_Compontes/NMP_Componentes/DetallePadronDBAdapter" location="DBDetalleBeneficiariosScvWSDL.wsdl"/>
  <binding name="DetallePadronDBAdapter_ptt-binding" type="tns:DetallePadronDBAdapter_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="DetallePadronDBAdapter">
      <soap:operation soapAction="DetallePadronDBAdapter"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="DetallePadronDBAdapter-service">
    <port name="DetallePadronDBAdapter-port" binding="tns:DetallePadronDBAdapter_ptt-binding">
      <soap:address location="jca://eis/DB/PeopleSoftAdapter"/>
    </port>
  </service>
</definitions>