<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/SelImportesCCDB" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerSolicitudDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://xmlns.oracle.com/ObtenerPrestadorApp/ObtenerPrestadorPrj/ObtenerPrestadorBPEL" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns2 ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns5="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleSolicitudApp/ConsultarDetalleSolicitudPrj/SelImportesCCDB" xmlns:ns4="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleSolicitudApp/ConsultarDetalleSolicitudPrj/SPObtenerSolicitudDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns7="http://qualitas.com.mx/comunes/" xmlns:ns9="http://qualitas.com.mx/Pagos/CuentasContables/v1/" xmlns:ns10="http://qualitas.com.mx/Comun/Servicio/ProyectoData/v1/" xmlns:ns6="http://qualitas.com.mx/Importes/v1/" xmlns:ns8="http://qualitas.com.mx/Comun/Servicio/v1/" xmlns:client="http://qualitas.com.mx/Solicitud/ConsultarDetalleSolicitud/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SPObtenerSolicitudDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerSolicitudDB"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/GPADomain/ObtenerPrestadorPrj!1.0/WSDLs/ObtenerPrestadorBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="processResponse" namespace="http://xmlns.oracle.com/ObtenerPrestadorApp/ObtenerPrestadorPrj/ObtenerPrestadorBPEL"/>
            <oracle-xsl-mapper:param name="ObtenerPrestadorInvoke_OutputVariable.payload"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SelImportesCCDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SelImportesCCDBOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelImportesCCDB"/>
            <oracle-xsl-mapper:param name="SelImportesCCInvoke_OutputVariable.SelImportesCCDBOutputCollection"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/consultarDetalleSolicitud.wsdl"/>
            <oracle-xsl-mapper:rootElement name="consultarDetalleSolicitudResponse" namespace="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI JAN 13 15:12:53 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ObtenerPrestadorInvoke_OutputVariable.payload"/>
   <xsl:param name="SelImportesCCInvoke_OutputVariable.SelImportesCCDBOutputCollection"/>
   <xsl:template match="/">
      <tns:consultarDetalleSolicitudResponse>
         <pagoServicios>
            <xsl:choose>
               <xsl:when test="/ns0:OutputParameters/ns0:P_TIPOSERVICIO = 1">
                  <servicio>
                     <ns8:idTpServicio>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDTPSERVICIO"/>
                     </ns8:idTpServicio>
                     <ns8:idPrestador>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDPRESTADOR"/>
                     </ns8:idPrestador>
                     <ns8:CentroDeCosto>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_CENTROCOSTO"/>
                     </ns8:CentroDeCosto>
                     <ns8:cveOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_CVEOFIC"/>
                     </ns8:cveOficina>
                     <ns8:descOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESOFIC"/>
                     </ns8:descOficina>
                     <ns8:descArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESAREA"/>
                     </ns8:descArea>
                     <ns8:respArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_RESPAREA"/>
                     </ns8:respArea>
                     <ns8:servicioData>
                        <ns8:idServicio>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDSERVICIO"/>
                        </ns8:idServicio>
                        <ns8:descripcion>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESSERVICIO"/>
                        </ns8:descripcion>
                        <ns8:tipoMoneda>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:TP_MONEDA"/>
                        </ns8:tipoMoneda>
                     </ns8:servicioData>
                  </servicio>
               </xsl:when>
               <xsl:when test="/ns0:OutputParameters/ns0:P_TIPOSERVICIO = 3">
                  <servicio>
                     <ns8:idTpServicio>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_TIPOSERVICIO"/>
                     </ns8:idTpServicio>
                     <ns8:idPrestador>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDPRESTADOR"/>
                     </ns8:idPrestador>
                     <ns8:CentroDeCosto>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_CENTROCOSTO"/>
                     </ns8:CentroDeCosto>
                     <ns8:cveOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_CVEOFIC"/>
                     </ns8:cveOficina>
                     <ns8:descOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESOFIC"/>
                     </ns8:descOficina>
                     <ns8:descArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESCAREA"/>
                     </ns8:descArea>
                     <ns8:respArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_RESPAREA"/>
                     </ns8:respArea>
                     <ns8:servicioData>
                        <ns8:idServicio/>
                        <ns8:descripcion/>
                        <ns8:tipoMoneda/>
                     </ns8:servicioData>
                     <ns8:proyecto>
                        <ns10:idProyecto>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDPROYECTO"/>
                        </ns10:idProyecto>
                        <ns10:descripcion>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESPROY"/>
                        </ns10:descripcion>
                        <ns10:nombre>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_NOMPROY"/>
                        </ns10:nombre>
                        <ns10:presupuestoAprob>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_PRESAPROB"/>
                        </ns10:presupuestoAprob>
                        <ns10:totalParcialidades>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_PARC"/>
                        </ns10:totalParcialidades>
                        <ns10:numParcialidad>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:C_NUPARC"/>
                        </ns10:numParcialidad>
                        <ns10:idcondicionPago>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDCONDPAGO"/>
                        </ns10:idcondicionPago>
                        <xsl:if test="/ns0:OutputParameters/ns0:B_IDCONDPAGO = 1">
                           <ns10:condicionPago>PAGO EN UNA SOLA EXHIBICION</ns10:condicionPago>
                        </xsl:if>
                        <xsl:if test="/ns0:OutputParameters/ns0:B_IDCONDPAGO = 1">
                           <ns10:condicionPago>PAGO EN PARCIALIDADES</ns10:condicionPago>
                        </xsl:if>
                        <ns10:tipoMoneda>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:TP_MONEDA"/>
                        </ns10:tipoMoneda>
                        <ns10:complemento>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:C_COMPLEMENTO"/>
                        </ns10:complemento>
                     </ns8:proyecto>
                  </servicio>
               </xsl:when>
            </xsl:choose>
            <xsl:for-each select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row">
               <Importes>
                  <ns6:idImportes>
                     <xsl:value-of select="ns0:ID_IMPORTES"/>
                  </ns6:idImportes>
                  <ns6:nombreDocumento>
                     <xsl:value-of select="ns0:NOMBRE_DOCUMENTO"/>
                  </ns6:nombreDocumento>
                  <ns6:subtotal>
                     <xsl:value-of select="ns0:SUBTOTAL"/>
                  </ns6:subtotal>
                  <ns6:montoIva>
                     <xsl:value-of select="ns0:MONTO_IVA"/>
                  </ns6:montoIva>
                  <ns6:tasaIva>
                     <xsl:value-of select="ns0:TASA_IVA"/>
                  </ns6:tasaIva>
                  <ns6:retencionIsr>
                     <xsl:value-of select="ns0:MONTO_RETENCION_ISR"/>
                  </ns6:retencionIsr>
                  <ns6:retencionIva>
                     <xsl:value-of select="ns0:MONTO_RETENCION_IVA"/>
                  </ns6:retencionIva>
                  <ns6:otrosImpuestos>
                     <xsl:value-of select="ns0:OTROS_IMPUESTOS"/>
                  </ns6:otrosImpuestos>
                  <ns6:observaciones>
                     <xsl:value-of select="ns0:OBSERVACIONES"/>
                  </ns6:observaciones>
                  <ns6:xmlFactura>
                     <xsl:value-of select="ns0:XML_FACTURA"/>
                  </ns6:xmlFactura>
                  <ns6:tipoMoneda>
                     <xsl:value-of select="ns0:TP_MONEDA"/>
                  </ns6:tipoMoneda>
                  <ns6:folioFiscal>
                     <xsl:value-of select="ns0:FOLIO_FISCAL"/>
                  </ns6:folioFiscal>
               </Importes>
            </xsl:for-each>
            <Prestador>
               <numeroPrestador>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:numeroPrestador"/>
               </numeroPrestador>
               <nombre>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:nombrePrestador"/>
               </nombre>
               <tipoPersona>
                  <codigo>
                     <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:cveTipoPersona"/>
                  </codigo>
                  <descripcion>
                     <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:tipoPersona"/>
                  </descripcion>
               </tipoPersona>
               <claveEntidad>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:cveEntidad"/>
               </claveEntidad>
               <entidad>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:entidad"/>
               </entidad>
               <nacionalidad>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:cveNacionalidad"/>
               </nacionalidad>
            </Prestador>
            <xsl:for-each select="$SelImportesCCInvoke_OutputVariable.SelImportesCCDBOutputCollection/ns2:SelImportesCCDBOutputCollection/ns2:SelImportesCCDBOutput">
               <ccontables>
                  <ns9:idCcontable>
                     <xsl:value-of select="ns2:ID_IMP_CC"/>
                  </ns9:idCcontable>
                  <ns9:idImportes>
                     <xsl:value-of select="ns2:ID_IMPORTES"/>
                  </ns9:idImportes>
                  <ns9:descPago>
                     <xsl:value-of select="ns2:DESC_PAGO"/>
                  </ns9:descPago>
                  <ns9:idDescIVA>
                     <xsl:value-of select="ns2:ID_DESC_IVA"/>
                  </ns9:idDescIVA>
                  <ns9:idUsuario>
                     <xsl:value-of select="ns2:ID_USUARIO"/>
                  </ns9:idUsuario>
                  <ns9:ccSubtotal>
                     <xsl:value-of select="ns2:CC_SUBTOTAL"/>
                  </ns9:ccSubtotal>
                  <ns9:ccIva>
                     <xsl:value-of select="ns2:CC_IVA"/>
                  </ns9:ccIva>
                  <ns9:ccRetencionISR>
                     <xsl:value-of select="ns2:CC_RETENCION_ISR"/>
                  </ns9:ccRetencionISR>
                  <ns9:ccRetencionIVA>
                     <xsl:value-of select="ns2:CC_RETENCION_IVA"/>
                  </ns9:ccRetencionIVA>
                  <ns9:ccOtrosImpuestos>
                     <xsl:value-of select="ns2:CC_OTROS_IMPUESTOS"/>
                  </ns9:ccOtrosImpuestos>
               </ccontables>
            </xsl:for-each>
            <Solicitud>
               <idSolicitud>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_IDSOL"/>
               </idSolicitud>
               <totalPagar>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_TOTALPAGAR"/>
               </totalPagar>
               <idUsuario>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_IDUSUARIO"/>
               </idUsuario>
               <numEmpleado>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_NUMPLEADO"/>
               </numEmpleado>
               <nomEmpleado>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_NOMEMPLEADO"/>
               </nomEmpleado>
               <cveOfiDestino>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_OFICDEST"/>
               </cveOfiDestino>
               <desOfDestino>
                  <xsl:value-of select="oraext:query-database (concat (&quot;SELECT DESC_OFICINA FROM GPA_CAT_OFICINA WHERE CV_OFICINA = '&quot;, ns0:OutputParameters/ns0:A_OFICDEST, &quot;'&quot; ), false(), false(), &quot;jdbc/GPAConnDB&quot; )"/>
               </desOfDestino>
            </Solicitud>
         </pagoServicios>
      </tns:consultarDetalleSolicitudResponse>
   </xsl:template>
</xsl:stylesheet>