<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerSolicitudDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://xmlns.oracle.com/ObtenerPrestadorApp/ObtenerPrestadorPrj/ObtenerPrestadorBPEL" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns3="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/ConsultarDetalleSolicitudApp/ConsultarDetalleSolicitudPrj/SPObtenerSolicitudDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns5="http://qualitas.com.mx/comunes/" xmlns:ns7="http://qualitas.com.mx/Comun/Servicio/ProyectoData/v1/" xmlns:ns4="http://qualitas.com.mx/Importes/v1/" xmlns:ns6="http://qualitas.com.mx/Comun/Servicio/v1/" xmlns:client="http://qualitas.com.mx/Solicitud/ConsultarDetalleSolicitud/" xmlns:ns8="http://qualitas.com.mx/Pagos/CuentasContables/v1/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SPObtenerSolicitudDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OutputParameters" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/SPObtenerSolicitudDB"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="http://11.50.0.22:7007/soa-infra/services/default/ObtenerPrestadorPrj!1.0/WSDLs/ObtenerPrestadorBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="processResponse" namespace="http://xmlns.oracle.com/ObtenerPrestadorApp/ObtenerPrestadorPrj/ObtenerPrestadorBPEL"/>
            <oracle-xsl-mapper:param name="ObtenerPrestadorInvoke_OutputVariable.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/consultarDetalleSolicitud.wsdl"/>
            <oracle-xsl-mapper:rootElement name="consultarDetalleSolicitudResponse" namespace="http://qualitas.com.mx/ConsultarDetalleSolicitud/v1/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [MON JAN 09 15:36:11 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ObtenerPrestadorInvoke_OutputVariable.payload"/>
   <xsl:variable name="tipoServicio"/>
   <xsl:template match="/">
      <tns:consultarDetalleSolicitudResponse>
         <reembolso>
            <Solicitud>
               <idSolicitud/>
               <totalPagar/>
               <idUsuario/>
               <numEmpleado/>
               <cveOfiDestino/>
            </Solicitud>
         </reembolso>
         <pagoServicios>
            <xsl:choose>
               <xsl:when test="/ns0:OutputParameters/ns0:P_TIPOSERVICIO = 1">
                  <servicio>
                     <ns6:idTpServicio>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDTPSERVICIO"/>
                     </ns6:idTpServicio>
                     <ns6:idPrestador>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDPRESTADOR"/>
                     </ns6:idPrestador>
                     <ns6:CentroDeCosto>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_CENTROCOSTO"/>
                     </ns6:CentroDeCosto>
                     <ns6:cveOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_CVEOFIC"/>
                     </ns6:cveOficina>
                     <ns6:descOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESOFIC"/>
                     </ns6:descOficina>
                     <ns6:descArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESAREA"/>
                     </ns6:descArea>
                     <ns6:respArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:S_RESPAREA"/>
                     </ns6:respArea>
                     <ns6:servicioData>
                        <ns6:idServicio>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:S_IDSERVICIO"/>
                        </ns6:idServicio>
                        <ns6:descripcion>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:S_DESSERVICIO"/>
                        </ns6:descripcion>
                        <ns6:tipoMoneda>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:TP_MONEDA"/>
                        </ns6:tipoMoneda>
                     </ns6:servicioData>
                  </servicio>
               </xsl:when>
               <xsl:when test="/ns0:OutputParameters/ns0:P_TIPOSERVICIO = 3">
                  <servicio>
                     <ns6:idTpServicio>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:P_TIPOSERVICIO"/>
                     </ns6:idTpServicio>
                     <ns6:idPrestador>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDPRESTADOR"/>
                     </ns6:idPrestador>
                     <ns6:CentroDeCosto>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_CENTROCOSTO"/>
                     </ns6:CentroDeCosto>
                     <ns6:cveOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_CVEOFIC"/>
                     </ns6:cveOficina>
                     <ns6:descOficina>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESOFIC"/>
                     </ns6:descOficina>
                     <ns6:descArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESCAREA"/>
                     </ns6:descArea>
                     <ns6:respArea>
                        <xsl:value-of select="/ns0:OutputParameters/ns0:B_RESPAREA"/>
                     </ns6:respArea>
                     <ns6:servicioData>
                        <ns6:idServicio/>
                        <ns6:descripcion/>
                        <ns6:tipoMoneda/>
                     </ns6:servicioData>
                     <ns6:proyecto>
                        <ns7:idProyecto>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDPROYECTO"/>
                        </ns7:idProyecto>
                        <ns7:descripcion>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_DESPROY"/>
                        </ns7:descripcion>
                        <ns7:nombre>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_NOMPROY"/>
                        </ns7:nombre>
                        <ns7:presupuestoAprob>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_PRESAPROB"/>
                        </ns7:presupuestoAprob>
                        <ns7:totalParcialidades>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_PARC"/>
                        </ns7:totalParcialidades>
                        <ns7:numParcialidad>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:C_NUPARC"/>
                        </ns7:numParcialidad>
                        <ns7:idcondicionPago>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:B_IDCONDPAGO"/>
                        </ns7:idcondicionPago>
                        <xsl:if test="/ns0:OutputParameters/ns0:B_IDCONDPAGO = 1">
                           <ns7:condicionPago>PAGO EN UNA SOLA EXHIBICION</ns7:condicionPago>
                        </xsl:if>
                        <xsl:if test="/ns0:OutputParameters/ns0:B_IDCONDPAGO = 2">
                           <ns7:condicionPago>PAGO EN PARCIALIDADES</ns7:condicionPago>
                        </xsl:if>
                        <ns7:tipoMoneda>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row/ns0:TP_MONEDA"/>
                        </ns7:tipoMoneda>
                        <ns7:complemento>
                           <xsl:value-of select="/ns0:OutputParameters/ns0:C_COMPLEMENTO"/>
                        </ns7:complemento>
                     </ns6:proyecto>
                  </servicio>
               </xsl:when>
            </xsl:choose>
            <xsl:for-each select="/ns0:OutputParameters/ns0:P_RECORDSET/ns0:P_RECORDSET_Row">
               <Importes>
                  <ns4:idImportes>
                     <xsl:value-of select="ns0:ID_IMPORTES"/>
                  </ns4:idImportes>
                  <ns4:nombreDocumento>
                     <xsl:value-of select="ns0:NOMBRE_DOCUMENTO"/>
                  </ns4:nombreDocumento>
                  <ns4:subtotal>
                     <xsl:value-of select="ns0:SUBTOTAL"/>
                  </ns4:subtotal>
                  <ns4:montoIva>
                     <xsl:value-of select="ns0:MONTO_IVA"/>
                  </ns4:montoIva>
                  <ns4:tasaIva>
                     <xsl:value-of select="ns0:TASA_IVA"/>
                  </ns4:tasaIva>
                  <ns4:retencionIsr>
                     <xsl:value-of select="ns0:MONTO_RETENCION_ISR"/>
                  </ns4:retencionIsr>
                  <ns4:retencionIva>
                     <xsl:value-of select="ns0:MONTO_RETENCION_IVA"/>
                  </ns4:retencionIva>
                  <ns4:otrosImpuestos>
                     <xsl:value-of select="ns0:OTROS_IMPUESTOS"/>
                  </ns4:otrosImpuestos>
                  <ns4:observaciones>
                     <xsl:value-of select="ns0:OBSERVACIONES"/>
                  </ns4:observaciones>
                  <ns4:xmlFactura>
                     <xsl:value-of select="ns0:XML_FACTURA"/>
                  </ns4:xmlFactura>
                  <ns4:tipoMoneda>
                     <xsl:value-of select="ns0:TP_MONEDA"/>
                  </ns4:tipoMoneda>
                  <ns4:folioFiscal>
                     <xsl:value-of select="ns0:FOLIO_FISCAL"/>
                  </ns4:folioFiscal>
               </Importes>
            </xsl:for-each>
            <Prestador>
               <numeroPrestador>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:numeroPrestador"/>
               </numeroPrestador>
               <nombre>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:nombrePrestador"/>
               </nombre>
               <tipoPersona>
                  <codigo>
                     <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:cveTipoPersona"/>
                  </codigo>
                  <descripcion>
                     <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:tipoPersona"/>
                  </descripcion>
               </tipoPersona>
               <claveEntidad>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:cveEntidad"/>
               </claveEntidad>
               <entidad>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:entidad"/>
               </entidad>
               <nacionalidad>
                  <xsl:value-of select="$ObtenerPrestadorInvoke_OutputVariable.payload/ns1:processResponse/ns1:cveNacionalidad"/>
               </nacionalidad>
            </Prestador>
            <Solicitud>
               <idSolicitud>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_IDSOL"/>
               </idSolicitud>
               <totalPagar>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_TOTALPAGAR"/>
               </totalPagar>
               <idUsuario>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_IDUSUARIO"/>
               </idUsuario>
               <numEmpleado>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_NUMPLEADO"/>
               </numEmpleado>
               <nomEmpleado>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_NOMEMPLEADO"/>
               </nomEmpleado>
               <cveOfiDestino>
                  <xsl:value-of select="/ns0:OutputParameters/ns0:A_OFICDEST"/>
               </cveOfiDestino>
               <desOfDestino>
                  <xsl:value-of select="oraext:query-database (concat (&quot;SELECT DESC_OFICINA FROM GPA_CAT_OFICINA WHERE CV_OFICINA = '&quot;, /ns0:OutputParameters/ns0:A_OFICDEST, &quot;'&quot; ), false(), false(), eis/DB/GPAConnDB )"/>
               </desOfDestino>
            </Solicitud>
         </pagoServicios>
      </tns:consultarDetalleSolicitudResponse>
   </xsl:template>
</xsl:stylesheet>