<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_UpdateOrdenPago" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ops="http://qualitas.com.mx/Comunes/gestionOrdenPagoBPEL/v1/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/Application1/GestionOrdenPago/DB_UpdateOrdenPago" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GestionOrdenPagoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="consultarOrdenPagoRequest" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GestionOrdenPagoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="consultarOrdenPagoResponse" namespace="http://qualitas.com.mx/Comunes/gestionOrdenPagoSchema/v1/"/>
            <oracle-xsl-mapper:param name="Reply_consultarOrdenPago_OutputVariable.consultarOrdenPagoRes"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DB_UpdateOrdenPago.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Gpa019PagosCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/DB_UpdateOrdenPago"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI JAN 06 21:29:03 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Reply_consultarOrdenPago_OutputVariable.consultarOrdenPagoRes"/>
   <xsl:template match="/">
      <tns:Gpa019PagosCollection>
         <tns:Gpa019Pagos>
            <tns:numOrden>
               <xsl:value-of select="/ns0:consultarOrdenPagoRequest/ns0:Input/ns0:numOrdenPago"/>
            </tns:numOrden>
            <xsl:choose>
               <xsl:when test="$Reply_consultarOrdenPago_OutputVariable.consultarOrdenPagoRes/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;PENDIENTE&quot; or $Reply_consultarOrdenPago_OutputVariable.consultarOrdenPagoRes/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;CANCELADA&quot;">
                  <tns:numCaratula>
                     <xsl:value-of select="&quot;&quot;"/>
                  </tns:numCaratula>
               </xsl:when>
               <xsl:otherwise>
               <tns:numCaratula>
                     <xsl:value-of select="number ($Reply_consultarOrdenPago_OutputVariable.consultarOrdenPagoRes/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta )"/>
                  </tns:numCaratula>
               </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
               <xsl:when test="$Reply_consultarOrdenPago_OutputVariable.consultarOrdenPagoRes/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;PENDIENTE&quot;">
              <tns:estadoPago>
               <xsl:value-of select="16"/>
                  </tns:estadoPago>
               </xsl:when>
               <xsl:when test="$Reply_consultarOrdenPago_OutputVariable.consultarOrdenPagoRes/ns0:consultarOrdenPagoResponse/ns0:OperationResponse/ns1:descripcionRespuesta = &quot;CANCELADA&quot;">
               
                  <tns:estadoPago>
               <xsl:value-of select="17"/>
                  </tns:estadoPago>
                  </xsl:when>
                  <xsl:otherwise>
               <tns:estadoPago>
                     <xsl:value-of select="18"/>
                  </tns:estadoPago>
               </xsl:otherwise>
            </xsl:choose>
         </tns:Gpa019Pagos>
      </tns:Gpa019PagosCollection>
   </xsl:template>
</xsl:stylesheet>