package model.capturacriterios.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 07 10:22:24 CST 2015
// ---------------------------------------------------------------------
public interface CapturaCriteriosAM extends ApplicationModule {


    void iniciarConcentradora();

    void iniciarCompraCumplido();
}

