<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ValidarCentrosDeCostosBPEL" targetNamespace="http://xmlns.oracle.com/ValidarCentrosDeCostosApp/ValidarCentrosDeCostosPrj/ValidarCentrosDeCostosBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ValidarCentrosDeCostosApp/ValidarCentrosDeCostosPrj/ValidarCentrosDeCostosBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/CentroCostos/validarCentrosDeCostos/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comun/CentroCostos/validarCentrosDeCostos/v1/" schemaLocation="../Schemas/validarCentrosDeCostos.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ValidarCentrosDeCostosBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:validarCentrosDeCostosRequest"/>
   </wsdl:message>
   <wsdl:message name="ValidarCentrosDeCostosBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:validarCentrosDeCostosResponse"/>
   </wsdl:message>
   <wsdl:portType name="ValidarCentrosDeCostosBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ValidarCentrosDeCostosBPELRequestMessage"/>
         <wsdl:output message="client:ValidarCentrosDeCostosBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ValidarCentrosDeCostosBPEL">
      <plnk:role name="ValidarCentrosDeCostosBPELProvider" portType="client:ValidarCentrosDeCostosBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
