<definitions targetNamespace="http://xmlns.oracle.com/MNPValidarCodigoVerificacion" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/MNPValidarCodigoVerificacion" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wtcgsrv="http://xmlns.oracle.com/MNPValidarCodigoVerificacion">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://xmlns.oracle.com/MNPValidarCodigoVerificacion" schemaLocation="../Schemas/ValidaCodigoXSD.xsd"/>
    </xsd:schema>
  </types>
  <xsd:types/>
  <portType name="resourceSpecification_port">
    <operation name="ValidarCodigoVerificacionRequest">
      <input message="tns:ValidarCodigoVerificacionRequest"/>
      <output message="tns:ValidarCodigoVerificacionResponse"/>
    </operation>
  </portType>
  <message name="ValidarCodigoVerificacionRequest">
    <part name="part" element="wtcgsrv:ValidarCodigoVerificacionRequest"/>
  </message>
  <message name="ValidarCodigoVerificacionResponse">
    <part name="part" element="wtcgsrv:ValidarCodigoVerificacionResponse"/>
  </message>
  <binding name="resourceSpecification_portSOAP11Binding" type="tns:resourceSpecification_port">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ValidarCodigoVerificacionRequest">
      <soap:operation style="document" soapAction="http://xmlns.oracle.com/MNPValidarCodigoVerificacion/ValidarCodigoVerificacionRequest"/>
      <input>
        <soap:body use="literal" parts="part"/>
      </input>
      <output>
        <soap:body use="literal" parts="part"/>
      </output>
    </operation>
  </binding>
  <service name="resourceSpecification_port">
    <port name="resourceSpecification_portPort" binding="tns:resourceSpecification_portSOAP11Binding">
      <soap:address location="http://www.example.com"/>
    </port>
  </service>
</definitions>