<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMPRenovacionTopUpSB/OsbRenovacionTopUp/DbUpdateRegistroRenovacion" name="DbUpdateRegistroRenovacion-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="DbUpdateRegistroRenovacionWSDL.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMPRenovacionTopUpSB/OsbRenovacionTopUp/DbUpdateRegistroRenovacion"/>
  <wsdl:binding name="DbUpdateRegistroRenovacion_ptt-binding" type="dbup:DbUpdateRegistroRenovacion_ptt" xmlns:dbup="http://xmlns.oracle.com/pcbpel/adapter/db/NMPRenovacionTopUpSB/OsbRenovacionTopUp/DbUpdateRegistroRenovacion">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="DbUpdateRegistroRenovacion">
      <soap:operation soapAction="DbUpdateRegistroRenovacion"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>