<wsdl:definitions name="RenovacionAQ" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/aq/NMPRenovacionTopUp/OSBRenovacionQueue/RenovacionAQ" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/aq/NMPRenovacionTopUp/OSBRenovacionQueue/RenovacionAQ" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:obj1="http://xmlns.oracle.com/xdb/CMSOA" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="Dequeue_plt">
    <plt:role name="Dequeue_role">
      <plt:portType name="tns:Dequeue_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/xdb/CMSOA" schemaLocation="../Schemas/OSBRenovacionTiposXSD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="RENOVACION_MESSAGE_TYPE_msg">
    <wsdl:part name="RENOVACION_MESSAGE_TYPE" element="obj1:RENOVACION_MESSAGE_TYPE"/>
  </wsdl:message>
  <wsdl:portType name="Dequeue_ptt">
    <wsdl:operation name="Dequeue">
      <wsdl:input message="tns:RENOVACION_MESSAGE_TYPE_msg"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Dequeue_pttSOAP11Binding" type="tns:Dequeue_ptt">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Dequeue">
      <soap:operation style="document" soapAction="http://xmlns.oracle.com/pcbpel/adapter/aq/NMPRenovacionTopUp/OSBRenovacionQueue/RenovacionAQ/Dequeue"/>
      <wsdl:input>
        <soap:body use="literal" parts="RENOVACION_MESSAGE_TYPE"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>