package model.capturacriterios.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 04 19:46:52 CDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConcentradoraVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ConcentradoraVOImpl() {
    }
}

