package model.capturacriterios.vo;

import model.capturacriterios.ent.ControlEtapasImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 14 12:04:31 CDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ControlEtapasViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_CONTROLETAPAS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdSolicitud,
        IdProyecto,
        IdEtapa,
        FechaCreacionEtapa,
        IdSubetapa,
        FechaCreacionSubetapa;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int IDSOLICITUD = AttributesEnum.IdSolicitud.index();
    public static final int IDPROYECTO = AttributesEnum.IdProyecto.index();
    public static final int IDETAPA = AttributesEnum.IdEtapa.index();
    public static final int FECHACREACIONETAPA = AttributesEnum.FechaCreacionEtapa.index();
    public static final int IDSUBETAPA = AttributesEnum.IdSubetapa.index();
    public static final int FECHACREACIONSUBETAPA = AttributesEnum.FechaCreacionSubetapa.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ControlEtapasViewRowImpl() {
    }

    /**
     * Gets ControlEtapas entity object.
     * @return the ControlEtapas
     */
    public ControlEtapasImpl getControlEtapas() {
        return (ControlEtapasImpl) getEntity(ENTITY_CONTROLETAPAS);
    }

    /**
     * Gets the attribute value for ID_SOLICITUD using the alias name IdSolicitud.
     * @return the ID_SOLICITUD
     */
    public Number getIdSolicitud() {
        return (Number) getAttributeInternal(IDSOLICITUD);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_SOLICITUD using the alias name IdSolicitud.
     * @param value value to set the ID_SOLICITUD
     */
    public void setIdSolicitud(Number value) {
        setAttributeInternal(IDSOLICITUD, value);
    }

    /**
     * Gets the attribute value for ID_PROYECTO using the alias name IdProyecto.
     * @return the ID_PROYECTO
     */
    public Number getIdProyecto() {
        return (Number) getAttributeInternal(IDPROYECTO);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_PROYECTO using the alias name IdProyecto.
     * @param value value to set the ID_PROYECTO
     */
    public void setIdProyecto(Number value) {
        setAttributeInternal(IDPROYECTO, value);
    }

    /**
     * Gets the attribute value for ID_ETAPA using the alias name IdEtapa.
     * @return the ID_ETAPA
     */
    public Number getIdEtapa() {
        return (Number) getAttributeInternal(IDETAPA);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_ETAPA using the alias name IdEtapa.
     * @param value value to set the ID_ETAPA
     */
    public void setIdEtapa(Number value) {
        setAttributeInternal(IDETAPA, value);
    }

    /**
     * Gets the attribute value for FECHA_CREACION_ETAPA using the alias name FechaCreacionEtapa.
     * @return the FECHA_CREACION_ETAPA
     */
    public String getFechaCreacionEtapa() {
        return (String) getAttributeInternal(FECHACREACIONETAPA);
    }

    /**
     * Sets <code>value</code> as attribute value for FECHA_CREACION_ETAPA using the alias name FechaCreacionEtapa.
     * @param value value to set the FECHA_CREACION_ETAPA
     */
    public void setFechaCreacionEtapa(String value) {
        setAttributeInternal(FECHACREACIONETAPA, value);
    }

    /**
     * Gets the attribute value for ID_SUBETAPA using the alias name IdSubetapa.
     * @return the ID_SUBETAPA
     */
    public Number getIdSubetapa() {
        return (Number) getAttributeInternal(IDSUBETAPA);
    }

    /**
     * Sets <code>value</code> as attribute value for ID_SUBETAPA using the alias name IdSubetapa.
     * @param value value to set the ID_SUBETAPA
     */
    public void setIdSubetapa(Number value) {
        setAttributeInternal(IDSUBETAPA, value);
    }

    /**
     * Gets the attribute value for FECHA_CREACION_SUBETAPA using the alias name FechaCreacionSubetapa.
     * @return the FECHA_CREACION_SUBETAPA
     */
    public String getFechaCreacionSubetapa() {
        return (String) getAttributeInternal(FECHACREACIONSUBETAPA);
    }

    /**
     * Sets <code>value</code> as attribute value for FECHA_CREACION_SUBETAPA using the alias name FechaCreacionSubetapa.
     * @param value value to set the FECHA_CREACION_SUBETAPA
     */
    public void setFechaCreacionSubetapa(String value) {
        setAttributeInternal(FECHACREACIONSUBETAPA, value);
    }
}

