package model.capturacriterios.vo;

import model.capturacriterios.vo.common.ListaFuenteVORow;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 07 21:13:04 CDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListaFuenteVORowImpl extends ViewRowImpl implements ListaFuenteVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ID_Fuente,
        Abreviatura,
        Descripcion;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID_FUENTE = AttributesEnum.ID_Fuente.index();
    public static final int ABREVIATURA = AttributesEnum.Abreviatura.index();
    public static final int DESCRIPCION = AttributesEnum.Descripcion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ListaFuenteVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ID_Fuente.
     * @return the ID_Fuente
     */
    public Integer getID_Fuente() {
        return (Integer) getAttributeInternal(ID_FUENTE);
    }

    /**
     * Gets the attribute value for the calculated attribute Abreviatura.
     * @return the Abreviatura
     */
    public String getAbreviatura() {
        return (String) getAttributeInternal(ABREVIATURA);
    }

    /**
     * Gets the attribute value for the calculated attribute Descripcion.
     * @return the Descripcion
     */
    public String getDescripcion() {
        return (String) getAttributeInternal(DESCRIPCION);
    }
}

