package model.capturacriterios.vo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 31 16:53:59 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TabNumPartDesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ID_tabNumPartDes,
        NumPartDes,
        Opcion;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID_TABNUMPARTDES = AttributesEnum.ID_tabNumPartDes.index();
    public static final int NUMPARTDES = AttributesEnum.NumPartDes.index();
    public static final int OPCION = AttributesEnum.Opcion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TabNumPartDesVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ID_tabNumPartDes.
     * @return the ID_tabNumPartDes
     */
    public Integer getID_tabNumPartDes() {
        return (Integer) getAttributeInternal(ID_TABNUMPARTDES);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ID_tabNumPartDes.
     * @param value value to set the  ID_tabNumPartDes
     */
    public void setID_tabNumPartDes(Integer value) {
        setAttributeInternal(ID_TABNUMPARTDES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NumPartDes.
     * @return the NumPartDes
     */
    public Integer getNumPartDes() {
        return (Integer) getAttributeInternal(NUMPARTDES);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NumPartDes.
     * @param value value to set the  NumPartDes
     */
    public void setNumPartDes(Integer value) {
        setAttributeInternal(NUMPARTDES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Opcion.
     * @return the Opcion
     */
    public String getOpcion() {
        return (String) getAttributeInternal(OPCION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Opcion.
     * @param value value to set the  Opcion
     */
    public void setOpcion(String value) {
        setAttributeInternal(OPCION, value);
    }
}

