package model.capturacriterios.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 09 10:51:00 CDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TabSucExpVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TabSucExpVOImpl() {
    }
}

