<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateProyectoDB" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://qualitas.com.mx/Comun/Servicio/ActualizarProyecto/v1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://qualitas.com.mx/comunes/objetosComunes/v1/" xmlns:ns2="http://qualitas.com.mx/Comun/Servicio/v1/" xmlns:client="http://xmlns.oracle.com/ActualizaProyecto/ActualizaProyectoPrj/ActualizarProyectoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns3="http://qualitas.com.mx/Comun/Servicio/ProyectoData/v1/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns4="http://xmlns.oracle.com/pcbpel/adapter/db/ActualizaProyecto/ActualizaProyectoPrj/updateProyectoDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ActualizarProyectoBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ActualizarProyectoRequest" namespace="http://qualitas.com.mx/Comun/Servicio/ActualizarProyecto/v1/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/updateProyectoDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Gpa013ProyectoCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateProyectoDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [FRI JAN 06 00:09:58 CST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:Gpa013ProyectoCollection>
         <tns:Gpa013Proyecto>
            <tns:descProyecto>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:descripcion"/>
            </tns:descProyecto>
            <xsl:choose>
               <xsl:when test="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:condicionPago = 1">
                  <tns:stProyecto>13</tns:stProyecto>
               </xsl:when>
               <xsl:when test="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:condicionPago = 2">
                  <tns:stProyecto>14</tns:stProyecto>
               </xsl:when>
            </xsl:choose>
            <tns:presupuestoAprobado>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:presupuestoAprob"/>
            </tns:presupuestoAprobado>
            <tns:parcialidades>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:numParcialidades"/>
            </tns:parcialidades>
            <tns:idCondicionesPago>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:condicionPago"/>
            </tns:idCondicionesPago>
            <tns:idSolicitud>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:idSolicitud"/>
            </tns:idSolicitud>
            <tns:centroCosto>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:centroCostos"/>
            </tns:centroCosto>
            <tns:descOficina>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:descOficina"/>
            </tns:descOficina>
            <tns:descArea>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:descArea"/>
            </tns:descArea>
            <tns:responsableArea>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:responsableArea"/>
            </tns:responsableArea>
            <tns:nombreProyecto>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:nombre"/>
            </tns:nombreProyecto>
            <tns:cveOficina>
               <xsl:value-of select="/ns0:ActualizarProyectoRequest/ns0:Input/ns0:servicio/ns2:proyecto/ns3:claveOficina"/>
            </tns:cveOficina>
         </tns:Gpa013Proyecto>
      </tns:Gpa013ProyectoCollection>
   </xsl:template>
</xsl:stylesheet>