<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ValidarOficinasBPEL" targetNamespace="http://xmlns.oracle.com/ValidarCentroDeCostosApp/ValidarOficinasPrj/ValidarOficinasBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ValidarCentroDeCostosApp/ValidarOficinasPrj/ValidarOficinasBPEL" xmlns:ns1="http://qualitas.com.mx/Comun/Oficina/validarOficinas/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Comun/Oficina/validarOficinas/v1/" schemaLocation="../Schemas/validarOficinas.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="ValidarOficinasBPELRequestMessage">
      <wsdl:part name="payload" element="ns1:validarOficinasRequest"/>
   </wsdl:message>
   <wsdl:message name="ValidarOficinasBPELResponseMessage">
      <wsdl:part name="payload" element="ns1:validarOficinasResponse"/>
   </wsdl:message>
   <wsdl:portType name="ValidarOficinasBPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:ValidarOficinasBPELRequestMessage"/>
         <wsdl:output message="client:ValidarOficinasBPELResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="ValidarOficinasBPEL">
      <plnk:role name="ValidarOficinasBPELProvider" portType="client:ValidarOficinasBPEL"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
