
package qualitas.ws.proxy.cs.deleteDoc;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DeleteFile", targetNamespace = "http://www.stellent.com/DeleteFile/",
                  wsdlLocation =
                  "http://11.50.0.2:16200/_dav/cs/idcplg/#%7Bhttp%3A%2F%2Fwww.stellent.com%2FDeleteFile%2F%7DDeleteFile?wsdl")
public class DeleteFile extends Service {

    private final static URL DELETEFILE_WSDL_LOCATION;
    private final static WebServiceException DELETEFILE_EXCEPTION;
    private final static QName DELETEFILE_QNAME = new QName("http://www.stellent.com/DeleteFile/", "DeleteFile");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://11.50.0.2:16200/_dav/cs/idcplg/#%7Bhttp%3A%2F%2Fwww.stellent.com%2FDeleteFile%2F%7DDeleteFile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELETEFILE_WSDL_LOCATION = url;
        DELETEFILE_EXCEPTION = e;
    }

    public DeleteFile() {
        super(__getWsdlLocation(), DELETEFILE_QNAME);
    }

    public DeleteFile(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELETEFILE_QNAME, features);
    }

    public DeleteFile(URL wsdlLocation) {
        super(wsdlLocation, DELETEFILE_QNAME);
    }

    public DeleteFile(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELETEFILE_QNAME, features);
    }

    public DeleteFile(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteFile(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DeleteFileSoap
     */
    @WebEndpoint(name = "DeleteFileSoap")
    public DeleteFileSoap getDeleteFileSoap() {
        return super.getPort(new QName("http://www.stellent.com/DeleteFile/", "DeleteFileSoap"), DeleteFileSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteFileSoap
     */
    @WebEndpoint(name = "DeleteFileSoap")
    public DeleteFileSoap getDeleteFileSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.stellent.com/DeleteFile/", "DeleteFileSoap"), DeleteFileSoap.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (DELETEFILE_EXCEPTION != null) {
            throw DELETEFILE_EXCEPTION;
        }
        return DELETEFILE_WSDL_LOCATION;
    }

}
