<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EstadisticaProyecto/EstadisticasProyectoDataSvc" name="EstadisticasProyectoDataSvc-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="EstadisticasProyectoDataSvc.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EstadisticaProyecto/EstadisticasProyectoDataSvc"/>
    <wsdl:binding name="EstadisticasProyectoDataSvc_ptt-binding" type="est:EstadisticasProyectoDataSvc_ptt" xmlns:est="http://xmlns.oracle.com/pcbpel/adapter/db/QualitasGPABus/EstadisticaProyecto/EstadisticasProyectoDataSvc">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="EstadisticasProyectoDataSvc">
            <soap:operation soapAction="EstadisticasProyectoDataSvc"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>