<wsdl:definitions name="CountProyectosSolicitudDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountProyectosSolicitudDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountProyectosSolicitudDB" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CountProyectosSolicitudDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="CountProyectosSolicitudDB_plt">
    <plt:role name="CountProyectosSolicitudDB_role">
      <plt:portType name="tns:CountProyectosSolicitudDB_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CountProyectosSolicitudDB" schemaLocation="CountProyectosSolicitudDB.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="CountProyectosSolicitudDBInput_msg">
        <wsdl:part name="CountProyectosSolicitudDBInput_msg" element="db:CountProyectosSolicitudDBInput"/>
    </wsdl:message>
    <wsdl:message name="CountProyectosSolicitudDBOutput_msg">
        <wsdl:part name="CountProyectosSolicitudDBOutput" element="db:CountProyectosSolicitudDBOutput"/>
    </wsdl:message>
    <wsdl:portType name="CountProyectosSolicitudDB_ptt">
        <wsdl:operation name="CountProyectosSolicitudDB">
            <wsdl:input message="tns:CountProyectosSolicitudDBInput_msg"/>
            <wsdl:output message="tns:CountProyectosSolicitudDBOutput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>