<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountProyectosSolicitudDB" name="CountProyectosSolicitudDB-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="CountProyectosSolicitudDB.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountProyectosSolicitudDB"/>
    <wsdl:binding name="CountProyectosSolicitudDB_ptt-binding" type="coun:CountProyectosSolicitudDB_ptt" xmlns:coun="http://xmlns.oracle.com/pcbpel/adapter/db/GPAIntegration/DBTemplate/CountProyectosSolicitudDB">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="CountProyectosSolicitudDB">
            <soap:operation soapAction="CountProyectosSolicitudDB"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>