<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nmp1="http://servicios.montepiedad.com.mx/NMP/Services/CatalogoAutos" xmlns:ctx="http://www.bea.com/wli/sb/context" xmlns:con1="http://www.bea.com/wli/sb/stages/transform/config" xmlns:ns0="http://servicios.montedepiedad.com.mx/NMP/Schema/NMPStandardMessage">
    <xsl:include href="../../../../Common/XSLT/TemplateFaultsMontePiedadV2.xsl"/>
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source/>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../../../../Common/XSD/NMPStandardFault.xsd.xsd"/>
                <oracle-xsl-mapper:rootElement name="Fault" namespace="http://schemas.xmlsoap.org/soap/envelope/"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.1.0(XSLT Build 160608.1900.0023) AT [WED AUG 17 12:47:18 CDT 2016].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:output encoding="UTF-8"/>
    <xsl:param name="AppError"/>
    <xsl:template match="/">
        <xsl:variable name="appCode" select="substring-before(ctx:fault/ctx:errorCode,'-')"/>
        <xsl:variable name="errorCode">
            <xsl:choose>
                <xsl:when test="$appCode != 'OSB'">
                    <xsl:value-of select="substring-after(ctx:fault/ctx:errorCode,'-')"/>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="number(substring-after(ctx:fault/ctx:errorCode,concat($appCode,'-')))"/>
                </xsl:otherwise>
            </xsl:choose>
        </xsl:variable>
        <xsl:variable name="faultstring">
            <xsl:call-template name="faultstring">
                <xsl:with-param name="errorCode" select="$errorCode"/>
                <xsl:with-param name="serviceName" select="$AppError"/>
            </xsl:call-template>
        </xsl:variable>
        <xsl:variable name="descripcionError">
            <xsl:choose>
                <xsl:when test="$appCode = 'NMP'">
                    <xsl:value-of select="substring(ctx:fault/ctx:reason,0,1500)"/>
                </xsl:when>
                <xsl:when test="$appCode = 'OSB'">
                    <xsl:call-template name="descripcionError">
                        <xsl:with-param name="errorCode" select="$errorCode"/>
                        <xsl:with-param name="fault" select="/ctx:fault"/>
                        <xsl:with-param name="serviceName" select="$AppError"/>
                    </xsl:call-template>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="substring(ctx:fault/ctx:details,0,1500)"/>
                </xsl:otherwise>
            </xsl:choose>
        </xsl:variable>
        <!--Generar Fault-->
        <soap:Fault>
            <faultcode>
                <xsl:value-of select="&quot;nmp1:Fault&quot;"/>
            </faultcode>
            <faultstring>
                <xsl:value-of select="$faultstring"/>
            </faultstring>
            <detail>
                <ns0:messageError>
                    <ns0:codigoError>
                        <xsl:call-template name="codigoError">
                            <xsl:with-param name="errorCode" select="$errorCode"/>
                            <xsl:with-param name="serviceName" select="$AppError"/>
                        </xsl:call-template>
                    </ns0:codigoError>
                    <ns0:descripcionError>
                        <xsl:value-of select="$descripcionError"/>
                    </ns0:descripcionError>
                    <ns0:tipoError>
                        <xsl:call-template name="tipoError">
                            <xsl:with-param name="errorCode" select="$errorCode"/>
                            <xsl:with-param name="serviceName" select="$AppError"/>
                        </xsl:call-template>
                    </ns0:tipoError>
                    <ns0:severidad>
                        <xsl:call-template name="severidad">
                            <xsl:with-param name="errorCode" select="$errorCode"/>
                            <xsl:with-param name="serviceName" select="$AppError"/>
                        </xsl:call-template>
                    </ns0:severidad>
                </ns0:messageError>
            </detail>
        </soap:Fault>
    </xsl:template>
</xsl:stylesheet>