<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="OfertaBase_DecisionService" targetNamespace="http://xmlns.oracle.com/OfertaBase/OfertaBase_DecisionService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://xmlns.oracle.com/OfertaBase/OfertaBase_DecisionService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="OfertaBase.OfertaBase_DecisionService">
      <plnk:role name="IDecisionService" portType="tns:IDecisionService"/>
   </plnk:partnerLinkType>
   <wsdl:import namespace="http://xmlns.oracle.com/OfertaBase/OfertaBase_DecisionService" location="OfertaBase_DecisionService.wsdl"/>
</wsdl:definitions>
