<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://110.10.0.98:8081/RecepcionPagosAdmon/services/recepcionCDFI" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://110.10.0.98:8081/RecepcionPagosAdmon/services/recepcionCDFI" xmlns:intf="http://110.10.0.98:8081/RecepcionPagosAdmon/services/recepcionCDFI" xmlns:tns1="http://ws.sagfe.mx.softwareag.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.2.1
Built on Jun 14, 2005 (09:15:57 EDT)-->
 <wsdl:types>
  <schema targetNamespace="http://ws.sagfe.mx.softwareag.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="recibeCFDs" type="xsd:anyType"/>
  </schema>
  <schema targetNamespace="http://110.10.0.98:8081/RecepcionPagosAdmon/services/recepcionCDFI" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="recibeCFDsReturn" type="xsd:anyType"/>
  </schema>
 </wsdl:types>

   <wsdl:message name="recibeCFDsResponse">

      <wsdl:part element="impl:recibeCFDsReturn" name="recibeCFDsReturn"/>

   </wsdl:message>

   <wsdl:message name="recibeCFDsRequest">

      <wsdl:part element="tns1:recibeCFDs" name="part"/>

   </wsdl:message>

   <wsdl:portType name="RecepcionCFDI">

      <wsdl:operation name="recibeCFDs">

         <wsdl:input message="impl:recibeCFDsRequest" name="recibeCFDsRequest"/>

         <wsdl:output message="impl:recibeCFDsResponse" name="recibeCFDsResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="recepcionCDFISoapBinding" type="impl:RecepcionCFDI">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="recibeCFDs">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="recibeCFDsRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="recibeCFDsResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="RecepcionCFDIService">

      <wsdl:port binding="impl:recepcionCDFISoapBinding" name="recepcionCDFI">

         <wsdlsoap:address location="http://110.10.0.98:8081/RecepcionPagosAdmon/services/recepcionCDFI"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>