<wsdl:definitions name="DbUpdateRegistroRenovacion" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NMPRenovacionTopUpSB/OsbRenovacionTopUp/DbUpdateRegistroRenovacion" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NMPRenovacionTopUpSB/OsbRenovacionTopUp/DbUpdateRegistroRenovacion" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DbUpdateRegistroRenovacion" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <plt:partnerLinkType name="DbUpdateRegistroRenovacion_plt">
    <plt:role name="DbUpdateRegistroRenovacion_role">
      <plt:portType name="tns:DbUpdateRegistroRenovacion_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DbUpdateRegistroRenovacion" schemaLocation="../Schemas/DBGOVUpdateRegistroRenovacionXSD.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="DbUpdateRegistroRenovacionInput_msg">
    <wsdl:part name="DbUpdateRegistroRenovacionInput_msg" element="db:DbUpdateRegistroRenovacionInput"/>
  </wsdl:message>
  <wsdl:portType name="DbUpdateRegistroRenovacion_ptt">
    <wsdl:operation name="DbUpdateRegistroRenovacion">
      <wsdl:input message="tns:DbUpdateRegistroRenovacionInput_msg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>