<wsdl:definitions name="ObtenerGenericoBPEL" targetNamespace="http://qualitas.com.mx/ObtenerGenericoApp/ObtenerGenericoPrj/ObtenerGenericoBPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/ObtenerGenericoApp/ObtenerGenericoPrj/ObtenerGenericoBPEL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:documentation>
        <abstractWSDL>http://11.50.0.20:7007/soa-infra/services/GPADomain/ObtenerGenericoPrj!1.0/WSDLs/ObtenerGenericoBPEL.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ObtenerGenericoBPEL">
        <plnk:role name="ObtenerGenericoBPELProvider" portType="client:ObtenerGenericoBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://qualitas.com.mx/ObtenerGenericoApp/ObtenerGenericoPrj/ObtenerGenericoBPEL" schemaLocation="XMLSchema_-620691209.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ObtenerGenericoBPELRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="ObtenerGenericoBPELResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="ObtenerGenericoBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ObtenerGenericoBPELRequestMessage"/>
            <wsdl:output message="client:ObtenerGenericoBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ObtenerGenericoBPELBinding" type="client:ObtenerGenericoBPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="obtenergenericobpel_client_ep">
        <wsdl:port name="ObtenerGenericoBPEL_pt" binding="client:ObtenerGenericoBPELBinding">
            <soap:address location="http://11.50.0.20:7007/soa-infra/services/GPADomain/ObtenerGenericoPrj/obtenergenericobpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>