<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="AsignarCuentasContables" targetNamespace="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/" xmlns:tns1="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/v1/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://qualitas.com.mx/Pagos/CuentasContables/AsignarCuentasContables/v1/" schemaLocation="../Schemas/AsignarCuentasContables.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="AsignarCuentasContablesRequestMessage">
      <wsdl:part name="payload" element="tns1:GuardarSolicitudRequest"/>
   </wsdl:message>
   <wsdl:message name="AsignarCuentasContablesResponseMessage">
      <wsdl:part name="payload" element="tns1:GuardarSolicitudResponse"/>
   </wsdl:message>
   <wsdl:portType name="AsignarCuentasContables">
      <wsdl:operation name="process">
         <wsdl:input message="client:AsignarCuentasContablesRequestMessage"/>
         <wsdl:output message="client:AsignarCuentasContablesResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="AsignarCuentasContables">
      <plnk:role name="AsignarCuentasContablesProvider" portType="client:AsignarCuentasContables"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
